### ISSUE TITLE
Page Up/down does not work in WSL (Ubuntu 18.04) when using  PowerShell 6.1.1

### ISSUE THREAD

**Issue by bergmeister** [PowerShell/PSReadLine#837] opened 2018-12-20 15:48 UTC
Environment data
----------------

```
PS version: 6.1.1
PSReadline version: 2.0.0-beta3
os: Linux DESKTOP-4P56TIT 4.4.0-17763-Microsoft #194-Microsoft Mon Dec 03 17:58:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
PS file version:
```

Steps to reproduce or exception report
--------------------------------------

Press Page up/down in WSL (Ubuntu 18.04) in PowerShell 6.1.1 on Windows 10 1809. Exception:

```
System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.ConsolePal.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ScrollDisplayUp(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

**Comment by SteveL-MSFT** [comment] 2019-06-18 21:59
Dupe of https://github.com/PowerShell/PSReadLine/issues/700

**Closed as completed by SteveL-MSFT** 2019-06-18 21:59 UTC
Labels: Resolution-Duplicate
