### ISSUE TITLE
CRLF is printing ^M

### ISSUE THREAD

**Issue by juneb** [PowerShell/PSReadLine#245] opened 2015-06-15 23:41 UTC
![untitled2](https://cloud.githubusercontent.com/assets/2954883/8173535/248cec54-138c-11e5-80d3-d08826ba7a41.jpg)
Windows standard line endings are CRLF. In our PowerShell host, we make sure each \n is converted to a \r\n to conform to the standard, but PSReadLine expects only \n. When we pass \r\n, it prints ^M. 

PSReadLine should conform to the Windows standard. Is it possible to make this change?

**Comment by lzybkr** [comment] 2015-06-16 22:54
How do I reproduce this issue?

**Comment by juneb** [comment] 2015-06-22 18:13
Jason, this is the PowerShell Studio console, but it should repro on any host that interprets \n as \r\n, per the Windows standard. 
To repro in PowerShell Studio: 
1. Download and install the 45-day trial: https://www.sapien.com/software/powershell_studio
2. If not 5.0, import PSReadline.
3. In PowerShell Studio, Ctrl+N (new file).
4. In the new file, type (any command), e.g. Get-Process
5. Select the command and click Run / Run Selection in Console (Ctrl+Shift+F8).

**Comment by lzybkr** [comment] 2015-06-22 19:27
I think PSReadline is doing the correct thing here, and the PowerShell Studio host is incorrectly sending \r as a keystroke.

For comparison, conhost does not send that key when pasting via right click.  Similarly, if you paste via Ctrl+v, PSReadline does the right thing here.

That said, it looks like PowerShell Studio is redirecting standard input.  That causes lots of problems because there is no terminal emulation support, so many key binding don't work.  When PSReadline sees redirected input, I think I'll be forced to deal with emulating what conhost does in terms of ignoring \r.

If I'm wrong about how PowerShell Studio is implemented, then I think PowerShell Studio needs to be changed because it would be acting more like conhost in that case.

**Comment by juneb** [comment] 2015-06-23 17:08
Thanks for the quick reply, Jason. I'll pass on the info.

**Comment by juneb** [comment] 2015-06-23 18:17
I just checked and we don't redirect anything. We use standard Microsoft APIs to attach a console to a Windows host (AttachConsole) and write to the console (WriteConsole). WriteConsole requires CRLF, so we use it. It seems to me that PSReadline should support this.

**Comment by lzybkr** [comment] 2017-11-11 03:58
Closing in favor of #579 which covers all of the known issues with right-click paste.

**Closed as completed by lzybkr** 2017-11-11 03:58 UTC
