### ISSUE TITLE
System.ArgumentOutOfRangeException Windows Terminal PSReadLine: 2.0.0-beta5

### ISSUE THREAD

**Issue by hbuckle** [PowerShell/PSReadLine#1101] opened 2019-10-16 14:16 UTC
Environment data
----------------
```
PS version: 7.0.0-preview.4
PSReadline version: 2.0.0-beta5
os: 10.0.18362.1 (WinBuild.160101.0800)
PS file version: 7.0.0.0
HostName: ConsoleHost (Windows Terminal)
BufferWidth: 201
BufferHeight: 54
```

Steps to reproduce or exception report
--------------------------------------

I'm still seeing this error when pasting text into the new Windows Terminal

```
& {
>>
>>     $hostName = $Host.Name                                                                                                                                                                            >>                                                                                                                                                                                                       >>     if ($hostName -eq "ConsoleHost" -and (Get-Command Get-CimIn                                                                                                                                       Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new
### Environment
PSReadLine: 2.0.0-beta5
PowerShell: 7.0.0-preview.4
OS: Microsoft Windows 10.0.18362
Last 200 Keys

 } Spacebar e l s e Spacebar { Spacebar " p o w e r s h e l l . e x e " Spacebar } ; Spacebar ( d i r Spacebar $ p s h o m e \ $ n a m e ) . V e r s i o n I n f o . F i l e V e r s i o n ) " Enter      Ctrl+Enter Spacebar Spacebar Spacebar Spacebar " H o s t N a m e : Spacebar $ h o s t N a m e " Enter
 Ctrl+Enter Spacebar Spacebar Spacebar Spacebar " B u f f e r W i d t h : Spacebar $ ( [ c o n s o l e ] : : B u f f e r W i d t h ) " Enter
 Ctrl+Enter Spacebar Spacebar Spacebar Spacebar " B u f f e r H e i g h t : Spacebar $ ( [ c o n s o l e ] : : B u f f e r H e i g h t ) ` n " Enter
 Ctrl+Enter }

### Exception

System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Actual value was 54.
   at System.ConsolePal.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.MoveCursor(Int32 newCursor)
   at Microsoft.PowerShell.PSConsoleReadLine.MoveToLine(Int32 lineOffset)
   at Microsoft.PowerShell.PSConsoleReadLine.PreviousLine(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InsertLineAbove(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)

```

**Comment by msftrncs** [comment] 2019-10-16 16:16
@hbuckle, this is an issue in Windows Terminal.  See #1081 for more details.

**Comment by daxian-dbw** [comment] 2019-10-16 19:01
Close as a duplicate of #1081

**Closed as completed by daxian-dbw** 2019-10-16 19:01 UTC
Labels: Resolution-Duplicate
