### ISSUE TITLE
Error running PowerShell as Administrator

### ISSUE THREAD

**Issue by OrangePlaner** [PowerShell/PSReadLine#318] opened 2015-12-14 23:00 UTC
This only happens when running PowerShell, not PowerShell ISE, I guess...
Suddenly, PowerShell run as Admin from right-click gives me a hung shell, no prompt.
As a test, I did a runas.exe /noprofile /user:administrator powershell.exe and got the following window, although it did run and I got a prompt.
Oops, something went wrong.  Please report this bug with the details below.
## Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new

Last 5 Keys:
 e x i t Enter

Exception:
System.UnauthorizedAccessException: Access to the path 'C:\Users\Default\AppData
\Roaming\Microsoft\Windows\PowerShell\PSReadline' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path,
Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean che
ckHost)
   at Microsoft.PowerShell.PSConsoleReadLine.WriteHistoryRange(Int32 start, Int3
2 end, Func`2 fileOpener)
   at Microsoft.PowerShell.PSConsoleReadLine.MaybeAddToHistory(String result, Li
st`1 edits, Int32 undoEditIndex, Boolean readingHistoryFile, Boolean fromDiffere
ntSession)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineI

**Comment by lzybkr** [comment] 2015-12-31 06:46
Dupe of #322.

**Closed as completed by lzybkr** 2015-12-31 06:46 UTC
Labels: Issue-Bug, Resolution-Duplicate
