### ISSUE TITLE
Issue of Powershell/Code in the Visual Studio Code

### ISSUE THREAD

**Issue by udayfrom-usd** [PowerShell/PSReadLine#2256] opened 2021-02-27 16:04 UTC
There was an error that occurred 

> every second time

 I made the code run in the Visual Studio Code.

That code was,
`#include<stdio.h>

int main(){
    // int a; b=a;
    int a = 3 ^ 3;
    printf("The value of v is: %d \n", a);
    printf(" the value of 3.0/8 - 2 is %f", 3.0/8 - 2 );
    return 0;
}`

[Error in vs code.txt](https://github.com/PowerShell/PSReadLine/files/6054873/Error.in.vs.code.txt)

**Comment by daxian-dbw** [comment] 2021-03-05 19:00
This is a duplicate of #1306, and was fixed. Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.

**Closed as completed by daxian-dbw** 2021-03-05 19:00 UTC
