### ISSUE TITLE
vmware powerclicore error on "boot" in Docker OS X

### ISSUE THREAD

**Issue by ischoll** [PowerShell/PSReadLine#518] opened 2017-03-16 01:41 UTC
Running Docker Community Edition 
Version 17.03.0-ce-mac2 (15654)
Channel: stable
1d7d97bbbd
Just re-downloaded the image:

```
Loading personal and system profiles took 3482ms.
nnPS /powershell> nn
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 0 Keys:
Exception:
System.DivideByZeroException: Attempted to divide by zero.
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

**Comment by lzybkr** [comment] 2017-03-16 06:13
Duplicate of #425.

**Closed as completed by lzybkr** 2017-03-16 06:13 UTC
Labels: Resolution-Duplicate
