### ISSUE TITLE
Getting an powershell-related error by spamming some keybinds while a command is executing

### ISSUE THREAD

**Issue by GEOEGII555** [PowerShell/PSReadLine#3264] opened 2022-04-08 19:33 UTC
### Prerequisites

- [x] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Произошла ошибка. Сообщите об этой ошибке, указав данные ниже.
Напишите в GitHub: https://github.com/PowerShell/PSReadLine/issues/new
### Среда
PSReadLine: 2.0.0
PowerShell: 5.1.22000.282
ОС: Microsoft Windows 10.0.22000
Последние 32 ключей

 p y t h o n Spacebar m a i n Ctrl+Backspace Ctrl+Backspace Ctrl+Backspace Ctrl+Backspace p y t h o n Spacebar m a i n . p y Enter
 UpArrow Enter
 UpArrow Enter
 Ctrl+Delete Ctrl+Insert

### Исключение
System.InvalidOperationException: Очередь пуста.
   в System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   в System.Collections.Generic.Queue`1.Dequeue()
   в Microsoft.PowerShell.PSConsoleReadLine.ReadKey()
   в Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   в Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

### Screenshot

![image](https://user-images.githubusercontent.com/57674559/162511339-cf208584-e766-492c-b336-1d68d6381e7f.png)

### Environment data

```console
PS Version: 5.1.22000.282
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.0.0
PSReadLine EditMode: Windows
OS: 10.0.22000.184 (WinBuild.160101.0800)
BufferWidth: 120
BufferHeight: 30
```

### Steps to reproduce

Type some commands. While last command is executing, start hitting CTRL+INSERT, CTRL+DELETE and CTRL+PAUSE
Powershell will enter debug mode
Continue hitting without stopping, and here we go! An error!
### Expected behavior

Switch command

### Actual behavior

With a small chance, throwing out an error "System.InvalidOperationException: Queue is blank"

**Comment by daxian-dbw** [comment] 2022-04-08 20:49
Thanks for the reporting. This is the second issue reported regarding "Queue is empty" exception, and both involves `Ctrl+Break`. Will look into it.

**Comment by daxian-dbw** [comment] 2022-04-12 22:36
Close as a duplicate of #3260

**Closed as completed by daxian-dbw** 2022-04-12 22:36 UTC
