### ISSUE TITLE
Powershell error after window resize

### ISSUE THREAD

**Issue by Disciplyne** [PowerShell/PSReadLine#427] opened 2016-08-21 23:40 UTC
Received the following error after resizing the PS window and getting a blank page. Hit the REturn key an this error came up. I was simply listing the mapped aliases prior to this action.  Running Win 10 Pro on AMD 940 BE CPU, Asus M4A79 Deluxe Motherboard, No OC.

---

PS C:>
Oops, something went wrong.  Please report this bug with the details below.
## Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new

Last 29 Keys:
 c d Spacebar . . Enter
 c d Spacebar . Enter
 c d Spacebar \ Enter
 g e t Spacebar Backspace - a l i a s Enter
 PageUp

Exception:
System.IO.IOException: The parameter is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ScrollDisplayUp(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by lzybkr** [comment] 2017-01-12 19:55
Most likely a dupe of #292, reopen with additional information if you disagree.

**Closed as completed by lzybkr** 2017-01-12 19:55 UTC
Labels: Resolution-Duplicate
