### ISSUE TITLE
Bug in when pressing winkey + arrowkeys

### ISSUE THREAD

**Issue by brannmar** [PowerShell/PSReadLine#521] opened 2017-03-22 09:32 UTC
I got this error when using the <Windows key> + arrowkeys to move the powershell window around on the screen.

> PS C:\windows\system32> as
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
> Last 200 Keys:
 e k Backspace l Tab Tab e t e d RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow Ri
ghtArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow Righ
tArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightA
rrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArr
ow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow
 RightArrow RightArrow Delete Delete Delete Delete Delete Delete Delete Delete Enter
 UpArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftA
rrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow
 LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow Lef
tArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArr
ow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow Backspace Backspace Backspace Backspace Backspace Backspace B
ackspace LeftArrow LeftArrow LeftArrow LeftArrow Backspace Backspace Backspace Backspace Backspace Backspace G e t Enter
 UpArrow Spacebar Ctrl+Alt+< Ctrl+Alt+Spacebar Backspace Backspace Spacebar - d e t a i l e d Spacebar Ctrl+Alt+< Ctrl+Alt+Spacebar f
l LeftArrow LeftArrow Spacebar Enter
 UpArrow UpArrow UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 LeftWindows LeftWindows LeftWindows LeftWindows a s

> Exception:
> System.IO.IOException: Felaktig parameter.

   > vid System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   vid System.Console.SetWindowPosition(Int32 left, Int32 top)
   vid Microsoft.PowerShell.PSConsoleReadLine.ReallyRender()
   vid Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   vid Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   vid Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction,
Object arg)
   vid Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   vid Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
> y

![image](https://cloud.githubusercontent.com/assets/7968452/24190904/4fdbed14-0eea-11e7-9b31-321b212a816a.png)

**Comment by lzybkr** [comment] 2017-04-11 19:11
Most likely a dupe of #292, reopen with additional information if you disagree.

**Closed as completed by lzybkr** 2017-04-11 19:11 UTC
Labels: Resolution-Duplicate
