### ISSUE TITLE
PSReadline constantly hangs Terminal with ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by schwinbp** [PowerShell/PSReadLine#2675] opened 2021-07-14 13:26 UTC
PSReadline is constantly hanging my terminal. There is no particular sequence of things that I can find to reproduce it, but It will always occur several times a day. The status bar powershell will be spinning along with my PC fan. The terminal hangs for around 10 minutes or so, meanwhile I cannot run any commands. Eventually it spews out the following before returning control back to me.

Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.md
Thank you!

### Environment
PSReadLine: 2.1.0
PowerShell: 2021.6.2
OS: Microsoft Windows 10.0.19042
BufferWidth: 291
BufferHeight: 24

Last 7 Keys
```
 Ctrl+s DownArrow c l s Enter
 DownArrow
```

### Exception
```
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Actual value was 25.
   at System.ConsolePal.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.CalculateWhereAndWhatToRender(Boolean cursorMovedToInitialPos, RenderData renderData, LineInfoForRendering& lineInfoForRendering)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Render()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadKey()
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

## Environment

```none
PS version: 7.1.2
PSReadline version: 2.1.0
os: 10.0.19041.1 (WinBuild.160101.0800)
PS file version: 7.1.2.0
HostName: Visual Studio Code Host
BufferWidth: 291
BufferHeight: 24
```

## Steps to reproduce

Run a script, a command ...any script will do. It will happen sometime if you keep doing it.

## Expected behavior

I expect to be able to run PS commands and not have to sit there waiting for control again. 

## Actual behavior

Terminal is hung and fan is whirring away while it is doing whatever it is doin.

**Comment by schwinbp** [comment] 2021-07-14 14:05
Here is another dump...

Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.md
Thank you!

### Environment
PSReadLine: 2.1.0
PowerShell: 2021.6.2
OS: Microsoft Windows 10.0.19042
BufferWidth: 291
BufferHeight: 24

Last 200 Keys
```
 Enter
 c l s Enter
 DownArrow $ k e y Enter
 Escape DownArrow UpArrow Escape c l s Enter
 g e t Backspace Backspace c Spacebar G Backspace * S E C C e Backspace Backspace S e c r e t * Enter
 UpArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow RightArrow e t - c o m m a n d Delete Enter
 G e t - c o m m a n d Spacebar U p d a t e - S e c r e t Enter
 UpArrow Ctrl+LeftArrow S E C Enter
 G e t - Backspace Backspace Backspace Backspace UpArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace H e l p Enter
 DownArrow Home DownArrow DownArrow DownArrow $ t o d a y Enter
 DownArrow Home $ e x p i r i n g K e y s Enter
 g e t - c o m m a n d Spacebar * I A M U s e r A c c e s s * Enter

```

### Exception
```
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Actual value was 25.
   at System.ConsolePal.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.CalculateWhereAndWhatToRender(Boolean cursorMovedToInitialPos, RenderData renderData, LineInfoForRendering& lineInfoForRendering)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadKey()
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)

**Comment by daxian-dbw** [comment] 2021-09-20 17:51
This is another duplicate of #2298, which happens in VSCode extension (PowerShell: 2021.6.2).

**Closed as completed by daxian-dbw** 2021-09-20 17:51 UTC
Labels: Resolution-Duplicate
