### ISSUE TITLE
Completion of duplicated cmdlets

### ISSUE THREAD

**Issue by ebugusey** [PowerShell/PSReadLine#430] opened 2016-08-22 20:35 UTC
Steps:
I'm trying to complete `Get-PSReadlineKeyHandler`. I set `Set-PSReadlineOption -EditMode Emacs`. I have entered `get-psread` and pressed `Tab`.

What I got:

``` powershell
PS C:\Users\User> get-psread
Get-PSReadlineKeyHandler  Get-PSReadlineOption      Get-PSReadlineKeyHandler  Get-PSReadlineOption
PS C:\Users\User> get-psread
```

As you can see all of them start with `Get-PSReadline`.

Expected:
It should complete my input to `Get-PSReadline` and then after I enter `K` and `Tab` it should complete to `Get-PSReadlineKeyHandler`.

**Comment by lzybkr** [comment] 2016-08-23 05:05
Sounds like a duplicate of #413.

**Comment by ebugusey** [comment] 2016-08-23 06:40
I don't have TabExpansionPlusPlus (if this information of any help at all).

**Comment by lzybkr** [comment] 2016-08-23 15:21
Yeah, helpful in understanding the scope. Do you have multiple versions of PSReadline installed?

**Comment by ebugusey** [comment] 2016-08-24 17:38
No, I don't think so.
Should I also post OS and PS versions and such?

**Comment by lzybkr** [comment] 2016-08-24 21:09
That shouldn't make a difference.  I've seen it, just need to debug it sometime :)

**Comment by ebugusey** [comment] 2016-08-29 08:46
There was problems with `Install-Module` in ps 5 and I have installed PsGet. There is now two `Install-Module` cmdlets. When I type `insta` and press `Ctrl-Space` I see something like this:

``` powershell
PS C:\Users\User> PsGet\Install-Module
Install-Dtc              Install-Module           Install-Package          Install-PackageProvider  Install-Script           >Install-Module
```

I marked selected entry with `>`.

**Comment by lzybkr** [comment] 2017-11-04 16:51
Closing as dupe of #413.

**Closed as completed by lzybkr** 2017-11-04 16:51 UTC
