### ISSUE TITLE
Can't search in history in vi mode

### ISSUE THREAD

**Issue by smuehlst** [PowerShell/PSReadLine#640] opened 2018-03-02 20:19 UTC
Environment data
----------------

```
PS version: 5.1.16299.248
PSReadline version: 1.2
os: 10.0.16299.15 (WinBuild.160101.0800)
PS file version: 10.0.16299.15 (WinBuild.160101.0800)
```

Steps to reproduce or exception report
--------------------------------------

I'm trying to search a command in the history in vi mode with `<ESC>/searchtext<RETURN>`. I get only a beep when typing a character after `<ESC>/`.

**Comment by srdubya** [comment] 2018-03-11 22:14
I cannot reproduce with PSReadline version 2.0 on the same version of PS.

**Comment by smuehlst** [comment] 2018-03-11 22:48
I see, my version is outdated. How can I upgrade to PSReadline version 2.0? I tried `Install-Module -Name PSReadLine -RequiredVersion 2.0.0` as Administrator according to the instructions from https://www.powershellgallery.com/packages/PSReadLine/2.0.0, but this had no effect.

**Comment by lzybkr** [comment] 2018-03-12 00:46
First, make sure you have PowerShellGet `1.6.0`, It looks like I installed it like this:

```
Install-Module PowerShellGet -AllowClobber -Scope CurrentUser -Force
```

Then in a new instance of PowerShell (or reload `PowerShellGet`), run

```
Install-Module -AllowPrerelease -SkipPublisherCheck -AllowClobber -Force -Scope CurrentUser PSReadLine
```

I know it's a silly number of arguments, and I hope I got them all.

**Comment by smuehlst** [comment] 2018-03-12 07:46
@lzybkr Thanks for the instructions to upgrade. The second command has a small error in it, `Current User`must not have a blank in it. This worked for me:

    Install-Module -AllowPrerelease -SkipPublisherCheck -AllowClobber -Force -Scope CurrentUser PSReadLine

After that I can verify that I have PSReadLine 2.0.0:

    > (Get-Module PSReadline).Version
    
    Major  Minor  Build  Revision
    -----  -----  -----  --------
    2      0      0      -1

And now I can indeed search in Vi editing mode with `<ESC>/`, which is great!

Unfortunately I have a much bigger problem now after the upgrade: I can no longer enter any characters in PowerShell that require the `<ALT>`  key on my German keyboard, e.g. `|`or `@`. I'm running Windows under VMware Fusion on an iMac if that matters, but it worked fine before and I also can enter these characters in a `cmd.exe`window. Do I have to fiddle with `Set-PSReadLineKeyHandler` to get back the `<ALT>` characters?

**Comment by lzybkr** [comment] 2018-03-12 17:03
Closing at it sounds like the issue is fixed.

The non-English keyboard problem is also fixed, but I haven't published a release for it yet. You'd have to grab a build from appveyor [here](https://ci.appveyor.com/project/lzybkr/PSReadLine/build/artifacts).

**Closed as completed by lzybkr** 2018-03-12 17:03 UTC
