### ISSUE TITLE
Command Completion[Ctr+Space] Not Revealing Folder Names Correctly When Prediction is turned on with List View

### ISSUE THREAD

**Issue by pragun-sharma** [PowerShell/PSReadLine#2282] opened 2021-03-09 17:16 UTC
Here is how to reproduce it.

- Turn on Prediction based on history (`Set-PSReadLineOption -PredictionSource History`)
- Press F2 so that you get into the List view mode of predictions.
As you can see in the screenshot, that pressing (CTR+Space) after writing (`cd .\`), it is displaying the _.metadata_ folder correctly, but all the other folders are not being revealed/displayed properly.
![image](https://user-images.githubusercontent.com/21987886/110509740-6fd77c00-8128-11eb-9677-b422fe2c6654.png)
 The moment I start to move around with keyboard direction keys over these folder names, they reveal their names correctly.
![image](https://user-images.githubusercontent.com/21987886/110510007-c2189d00-8128-11eb-85bb-8b27eec505c0.png)

(Note: When Prediction Mode is toggled to Inline(F2), it does not cause issue.)

**Comment by daxian-dbw** [comment] 2021-03-10 20:24
This is a duplicate of #1935 and was fixed in the latest 2.2.0-beta2 preview. Please upgrade to the 2.2.0-beta2 version of PSReadLine.

**Closed as completed by daxian-dbw** 2021-03-10 20:24 UTC
