### ISSUE TITLE
Exception reading history file at startup

### ISSUE THREAD

**Issue by KevinLoonen** [PowerShell/PSReadLine#302] opened 2015-11-11 14:38 UTC
![startupps](https://cloud.githubusercontent.com/assets/15801582/11093376/3548129e-888a-11e5-9648-7d6dde86cb54.jpg)

**Comment by lzybkr** [comment] 2015-12-02 21:03
Please paste text in the future, it's much easier to read and search.

**Comment by lzybkr** [comment] 2015-12-31 05:47
Closing as a dupe of #322.

**Closed as completed by lzybkr** 2015-12-31 05:47 UTC
Labels: Issue-Bug, Resolution-Duplicate
