### ISSUE TITLE
Screen Went Blank

### ISSUE THREAD

**Issue by ChrisUbben** [PowerShell/PSReadLine#423] opened 2016-08-16 23:36 UTC
Not sure what happened. Was just typing and then PS text disappeared and just showed empty blue console. When I pressed a key and pressed enter the below message appeared and everything was resolved.

Oops, something went wrong.  Please report this bug with the details below.
## Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new

Last 76 Keys:
 c d Spacebar F : / o p Tab Enter
 UpArrow UpArrow DownArrow Escape c d Spacebar M u Tab Enter
 c d Spacebar t Tab Enter
 UpArrow UpArrow UpArrow UpArrow Enter
 g e t - c o m Tab Spacebar s l s Enter
 UpArrow Backspace Backspace Backspace s e l Tab - s t Tab Enter
 g e t - h e Tab Spacebar s e l Tab - s t Tab Enter
 h

Exception:
System.IO.IOException: The parameter is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()

**Comment by lzybkr** [comment] 2016-08-17 18:26
This is likely a conhost bug that I think is fixed in Win10 Anniversary Update.  What OS are you seeing this on?

**Comment by lzybkr** [comment] 2017-01-12 20:59
Most likely a dupe of #292, reopen with additional information if you disagree.

**Closed as completed by lzybkr** 2017-01-12 20:59 UTC
Labels: Resolution-Duplicate
