### ISSUE TITLE
PSReadLine crashes on latest build of PowerShell

### ISSUE THREAD

**Issue by kborowinski** [PowerShell/PSReadLine#2482] opened 2021-05-21 22:59 UTC
## Environment

```none
PSReadLine: 2.2.0-beta2
PowerShell: 7.2.0-preview.5
OS: Microsoft Windows 10.0.19043
BufferWidth: 237
BufferHeight: 9001
```

## Exception report

```
System.TypeLoadException: Could not load type 'System.Management.Automation.Subsystem.PredictionResult' from assembly 'Microsoft.PowerShell.PSReadLine.Polyfiller, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionViewBase.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionInlineView.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Prediction.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

## Steps to reproduce

![psreadline](https://user-images.githubusercontent.com/16168755/119205178-cdc50000-ba97-11eb-9911-1fc56d7a0d55.jpg)

## Probable cause

[Are recent changes to prediction interface causing this?](https://github.com/PowerShell/PowerShell/commit/5febcad3db03ce15399a57a1c1fd8c7d50b2f0be)

## Workaround

Rollback *PSReadLine* module to version **2.1.0** or rollback PowerShell to version **7.2.0-preview.5-46-ge927e94aedb6c425ec98174ac28a1de9feecd72a**

**Comment by iSazonov** [comment] 2021-05-22 18:52
> Are recent changes to prediction interface causing this?

I think yes. The interface was updated but PSRL is still not. (I guess you could disable the feature in config.)

**Comment by kborowinski** [comment] 2021-05-22 20:58
@iSazonov I did disable the prediction with `Set-PSReadLineOption -PredictionSource None` but it does not help. I'll rollback the PowerShell to version *7.2.0-preview.5-46-ge927e94aedb6c425ec98174ac28a1de9feecd72a* and wait for the PSReadLine update.

**Comment by gwojan** [comment] 2021-05-24 14:51
I ran into the same issue with the latest daily build.

```powershell
### Environment
PSReadLine: 2.2.0-beta2
PowerShell: 7.2.0-daily20210521.1
OS: Microsoft Windows 10.0.19042
BufferWidth: 160
BufferHeight: 42
```

**Comment by daxian-dbw** [comment] 2021-05-28 20:52
Thanks for reporting and using the preview version of PowerShell!
This is a duplicate of #2495. The powershell-7.2.0-preview.6 contains a [release note](https://github.com/PowerShell/PowerShell/releases/tag/v7.2.0-preview.6) for this:

> PSReadLine 2.2.0-beta1 and 2.2.0-beta2 do not work with this preview of PowerShell due to breaking changes in the prediction interface. The upcoming PSReadLine 2.2.0-beta3 release will resolve this. Use PSReadLine 2.1.0 as the temporary workaround.

**Closed as completed by daxian-dbw** 2021-05-28 20:52 UTC
Labels: Resolution-Duplicate

**Comment by gwojan** [comment] 2021-06-01 17:51
@daxian-dbw I just grabbed the latest build of `PSReadLine` from AppVeyor and so far so good! ☺
