### ISSUE TITLE
The system cannot open the device or file specified. : 'PSReadLineHistoryFile_3505960416'

### ISSUE THREAD

**Issue by yaananth** [PowerShell/PSReadLine#1665] opened 2020-07-15 21:21 UTC
I believe something was stuck and I canceled the session, later when I try to start powershell.. I get 

### Environment
```
PSReadLine: 2.0.0
PowerShell: 7.0.2
OS: Darwin 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64
Last 0 Keys
```

### Exception

```
System.IO.IOException: The system cannot open the device or file specified. : 'PSReadLineHistoryFile_3505960416'
   at System.Threading.Mutex.CreateMutexCore(Boolean initiallyOwned, String name, Boolean& createdNew)
   at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name)
   at Microsoft.PowerShell.PSConsoleReadLine.DelayedOneTimeInitialize()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

Closing the terminal and reopening works.

**Comment by daxian-dbw** [comment] 2020-07-16 18:42
@yaananth Thanks for reporting the issue. This is a duplicate of #1464. It's likely a permission issue to `/private/tmp`. Please take a look at https://github.com/PowerShell/PSReadLine/issues/1464#issuecomment-631941511 to see if that fix your problem too.

**Closed as completed** 2020-07-16 18:43 UTC
Labels: Resolution-Duplicate
