### ISSUE TITLE
Ctrl+Space (MenuComplete) not working in Windows Terminal Preview with German keyboard layout

### ISSUE THREAD

**Issue by l-c-g** [PowerShell/PSReadLine#1415] opened 2020-03-21 07:45 UTC
## Environment

```none
PS version: 7.0.0
PSReadline version: 2.0.0
os: 10.0.18362.718 (WinBuild.160101.0800)
PS file version: 7.0.0.0
HostName: ConsoleHost (Windows Terminal)
BufferWidth: 99
BufferHeight: 29
```

## Exception report

None.

## Steps to reproduce

Enter a partial command line and then try to invoke MenuComplete via <kbd>Ctrl</kbd>+<kbd>Space</kbd>, e.g.
`Get-ChildItem -`<kbd>Ctrl</kbd>+<kbd>Space</kbd>

## Expected behavior

MenuComplete shows all possible completions (which it does in ConHost Powershell).

## Actual behavior

A quotation mark " appears at the cursor location in the buffer.

## Additional information

This may be related to #1380 (but I am already using PSReadLine 2.0) or #1086 (Windows Terminal and VS Code may share some code in this area, I don't know). It might also be related to microsoft/terminal#2865. From a comment in that issue, I understand that this is due to terminals handling <kbd>Ctrl</kbd>+<kbd>Space</kbd> as alias for <kbd>Ctrl</kbd>+<kbd>@</kbd>. Coincidentally, on a German keyboard you enter " as <kbd>Shift</kbd>+<kbd>2</kbd>, which is where the US layout has the @ glyph. This comment lead me to try and switch my keyboard layout to US; if I do, <kbd>Ctrl</kbd>+<kbd>Space</kbd> correctly invokes MenuComplete.

To me, it looks like a complex interaction between Windows Terminal, PSReadLine and the keyboard layout. I cannot say, however, whether the problem is in PSReadLine or Windows Terminal (in which case I would gladly open an issue with them).

**Comment by daxian-dbw** [comment] 2020-03-24 17:15
Thanks for reporting the issue. This is a duplicate of #1086. Quote from that issue:
> as my default language usually is set to german, I'm encountering problems while trying <kbd>Ctrl</kbd>+<kbd>Space</kbd> for calling MenuCompletion.
<kbd>Ctrl</kbd>+<kbd>Space</kbd> is then interpreted as <kbd>ctrl</kbd>+<kbd>"</kbd>. Even switching keyboard layout then to english with <kbd>Shift</kbd>+<kbd>Alt</kbd> makes no difference.

Given most of the conversation is happening in that issue, I will close this one as a duplicate.

**Closed as completed by daxian-dbw** 2020-03-24 17:15 UTC
Labels: Resolution-Duplicate, Issue-KeyboardLayout

**Comment by daxian-dbw** [comment] 2020-06-19 18:21
A bunch of key bindings used in PSReadLine get fixed in the most recent preview release of Windows Terminal (v1.1.1671.0), including <kbd>ctrl+space</kbd> (which doesn't need the <kbd>ctrl+@</kbd> workaround binding for `MenuComplete` anymore).
See https://github.com/microsoft/terminal/issues/879 for the issue, and https://github.com/microsoft/terminal/issues/879#issuecomment-646179386 for the release information.
@l-c-g Can you please install the preview version of Windows Terminal and see if `Ctrl+Space` works fine in the German keyboard as well?

**Comment by gwojan** [comment] 2020-06-19 19:17
@daxian-dbw one keybinding that no longer works for me with the latest Terminal Preview is <kbd>Ctrl+[</kbd> in `vi` mode as an alternate <kbd>Esc</kbd>. I've tested with all PowerShell 7 builds and Windows PowerShell 5.1.

Should I file a separate bug?

**Comment by daxian-dbw** [comment] 2020-06-19 20:42
@gwojan You already opened the issue https://github.com/PowerShell/PSReadLine/issues/906, so no new issue is needed.
The PR https://github.com/PowerShell/PSReadLine/pull/935 was submitted for that issue, but the fix was not accepted. I didn't spend time on it since then as it was not high priority at the time.
But it's in my radar and I will get back to it.

**Comment by gwojan** [comment] 2020-06-19 21:11
@daxian-dbw Thanks. I had totally forgotten about #906 because I started using Windows Terminal shortly after that and <kbd>Ctrl+[</kbd> worked as I expected. 😊

**Comment by daxian-dbw** [comment] 2020-06-19 21:17
Ah, yeah, it looks <kbd>Ctrl+[</kbd> was fixed in WT preview to generate the same `ConsoleKeyInfo` as in conhost:
```
KeyChar  Key Modifiers
--------  --- ---------
         Oem4   Control
```

**Comment by l-c-g** [comment] 2020-06-20 06:45
> @l-c-g Can you please install the preview version of Windows Terminal and see if `Ctrl+Space` works fine in the German keyboard as well?

Yes, after removing my workaround keybindings, <kbd>Ctrl</kbd>+<kbd>Space</kbd> successfully invokes PSReadline  MenuComplete in Windows Terminal Preview 1.1.1671.0.
