### ISSUE TITLE
Exception thrown in stout VS Code Integrated Console right arrow while looking at autocomplete on path

### ISSUE THREAD

**Issue by mavaddat** [PowerShell/PSReadLine#2932] opened 2021-10-25 05:17 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.        
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.md
Thank you!

### Environment
PSReadLine: 2.1.0
PowerShell: 2021.10.1
OS: Microsoft Windows 10.0.22483
BufferWidth: 117
BufferHeight: 12

Last 200 Keys

 LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow Enter
 UpArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow \ LeftArrow * Enter
 UpArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow \ LeftArrow * Enter
 UpArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete a p p Tab m s Tab RightArrow RightArrow RightArrow LeftArrow LeftArrow RightArrow Enter
 Ctrl+a Delete $ e n v : L O C A L A P P Tab \ Backspace Ctrl+a Ctrl+x $ e n v : L O C A L A P P D A T A \ E d Tab Backspace Backspace M i r Backspace c Tab E Tab Enter
 Backspace Spacebar Backspace Tab RightArrow Enter
 U s e r Tab Spacebar Backspace Tab Escape Backspace P r e Tab Backspace Backspace Backspace P r e Tab Delete ' LeftArrow Ctrl+w Tab UpArrow RightArrow DownArrow RightArrow LeftArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace t Backspace Tab RightArrow
```

### Exception
```
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.Menu.DrawMenu(Menu previousMenu, Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.MenuCompleteImpl(Menu menu, CommandCompletion completions)
   at Microsoft.PowerShell.PSConsoleReadLine.PossibleCompletionsImpl(CommandCompletion completions, Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.CompleteImpl(Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

### Screenshot

Screenshot of first exception:

![First exception](https://user-images.githubusercontent.com/5055400/138634882-56d91a3c-166e-425f-a64b-ff755f764150.png)

Screenshot of second exception:

![Second exception](https://user-images.githubusercontent.com/5055400/138634927-a80fe5fa-a432-4481-9660-ca2fe69e97c2.png)

![Animation of the exception generation](https://user-images.githubusercontent.com/5055400/138637880-a1638257-6a23-418a-917e-eaf2fda89c7b.gif)

### Environment data

```console
PS Version: 7.1.5
PS HostName: Visual Studio Code Host
PSReadLine Version: 2.1.0
PSReadLine EditMode: Windows
OS: 10.0.22483.1000 (WinBuild.160101.0800)
BufferWidth: 117
BufferHeight: 10
```

PowerShell Preview Extension version: 2021.10.1
VS Code version: Code - Insiders 1.62.0-insider (bcb9df5afa52c5b713f62e86dcac2c5050504b5f, 2021-10-22T05:15:25.330Z)
OS version: Windows_NT x64 10.0.22483
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3540M CPU @ 3.00GHz (4 x 2990)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (5.94GB free)|
|Process Argv|--crash-reporter-id 283c6689-32a9-4a0e-be89-cbd962d5dd31|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551cf:30291413
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805:30301674
pythonvspyt200:30323110
vsccppwt:30382699
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt2:30353727
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
pydsgst2:30361790
vsaa593cf:30376535
vscrecpromptt2:30387008

</details>

Contents of Directory `$env:LOCALAPPDATA\Microsoft\Edge Beta\User Data`:

| Name                         | Mode  |
|------------------------------|-------|
| Ad Blocking                  | d---- |
| Application Guard            | d---- |
| CertificateRevocation        | d---- |
| Crashpad                     | d---- |
| Default                      | d---- |
| Edge Shopping                | d---- |
| GrShaderCache                | d---- |
| hyphen-data                  | d---- |
| OriginTrials                 | d---- |
| RecoveryImproved             | d---- |
| Safe Browsing                | d---- |
| ShaderCache                  | d---- |
| SmartScreen                  | d---- |
| Speech Recognition           | d---- |
| Subresource Filter           | d---- |
| Trust Protection Lists       | d---- |
| Web Notifications Deny List  | d---- |
| WidevineCdm                  | d---- |
| ZxcvbnData                   | d---- |
| BrowserMetrics-spare.pma     | -a--- |
| CrashpadMetrics-active.pma   | -a--- |
| CrashpadMetrics.pma          | -a--- |
| First Run                    | -a--- |
| FirstLaunchAfterInstallation | -a--- |
| Functional Data              | -a--- |
| Functional Data-wal          | -a--- |
| Functional SAN Data          | -a--- |
| Functional SAN Data-wal      | -a--- |
| Last Browser                 | -a--- |
| Last Version                 | -a--- |
| Local State                  | -a--- |
| lockfile                     | -a--- |

Output of `Get-PSReadLineOption`:

| EditMode | ContinuationPrompt | ContinuationPromptColor | ExtraPromptLineCount | AddToHistoryHandler                           | CommandValidationHandler | CommandsToValidateScriptBlockArguments                 | HistoryNoDuplicates | MaximumHistoryCount | MaximumKillRingCount | HistorySearchCursorMovesToEnd | ShowToolTips | DingTone | CompletionQueryItems | WordDelimiters                | DingDuration | BellStyle | HistorySearchCaseSensitive | ViModeIndicator | ViModeChangeHandler | HistorySavePath                                                                                                     | HistorySaveStyle  | PredictionSource | AnsiEscapeTimeout | PromptText | DefaultTokenColor | CommentColor | KeywordColor | StringColor | OperatorColor | VariableColor | CommandColor | ParameterColor | TypeColor | NumberColor | MemberColor | EmphasisColor | ErrorColor | SelectionColor | InlinePredictionColor |
|----------|--------------------|-------------------------|----------------------|-----------------------------------------------|--------------------------|--------------------------------------------------------|---------------------|---------------------|----------------------|-------------------------------|--------------|----------|----------------------|-------------------------------|--------------|-----------|----------------------------|-----------------|---------------------|---------------------------------------------------------------------------------------------------------------------|-------------------|------------------|-------------------|------------|-------------------|--------------|--------------|-------------|---------------|---------------|--------------|----------------|-----------|-------------|-------------|---------------|------------|----------------|-----------------------|
| Windows  | \>\>               | \[37m                  | 0                    | System.Func\`2\[System.String,System.Object\] |                          | System.Collections.Generic.HashSet\`1\[System.String\] | True                | 10000               | 10                   | True                          | True         | 1221     | 100                  | ;:,.\[\]{}()/\\\|^&\*-=+'"–—― | 50           | Audible   | False                      | None            |                     | C:\\Users\\mavad\\AppData\\Roaming\\Microsoft\\Windows\\PowerShell\\PSReadLine\\Visual Studio Code Host_history.txt | SaveIncrementally | History          | 100               |            | \[37m            | \[32m       | \[92m       | \[36m      | \[90m        | \[92m        | \[93m       | \[90m         | \[37m    | \[97m      | \[97m      | \[96m        | \[91m     | \[30;47m      | \[38;5;238m          |

### Steps to reproduce

1. Open [VS Code](https://github.com/Microsoft/vscode) or [VS Code Insiders](https://code.visualstudio.com/insiders/) with [PowerShell Preview extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell-Preview). 
2. Stage the following string in the **PowerShell Integrated Console** terminal at the current prompt (it doesn't matter that the string is not `"` terminated):  
  
```pwsh 
& "$env:LOCALAPPDATA\Microsoft\Edge Beta\User Data\
```
3. Press `tab` to autocomplete the end of the line.
4. Press any of the directional arrows ←	↑→↓ on the keyboard to navigate to Autocomplete suggestions

### Expected behavior

- Able to use directional arrows ←	↑→↓ on the keyboard to navigate to Autocomplete suggestions.
- Able to navigate the autocomplete results with automatic scrolling down in the terminal if necessary.

### Actual behavior

After an indeterminate number of arrows traversing the results, there  is an exception thrown.

**Comment by daxian-dbw** [comment] 2021-11-04 21:34
@mavaddat I cannot reproduce the issue you reported. Some fixes to the menu completion was done in 2.2.0-beta2 (PR #1946), and it's likely the issue you ran into was already addressed.

Can you please update the PowerShell Preview VSCode extension to the latest version (updated on 11/3/2021)? The latest PowerShell Preview extension bundles the 2.2.0-beta4 version of PSReadLine. Please try that version and see it still reproduces for you. I will close this issue for now, and please open a new one if you ran into anything with the 2.2.0-beta4 PSReadLine.

Thanks again for the well-written issue report!

**Closed as completed by daxian-dbw** 2021-11-04 21:34 UTC
