### ISSUE TITLE
found bugs

### ISSUE THREAD

**Issue by okypratama** [PowerShell/PSReadLine#516] opened 2017-03-07 07:53 UTC
-----------------------------------------------------------------------
Last 145 Keys:
 c d \ Enter
 c d Spacebar l a r a g o n Enter
 c d Spacebar w w w Enter
 c d Spacebar w e Backspace Backspace Backspace Backspace Backspace Backspace d i r Enter
 c d Spacebar l a r a p i s Enter
 c d Spacebar l a r a p u s Enter
 d i r Enter
 c o m p o s e r Enter
 p h p Spacebar a r t i s a n Spacebar r o u t e : : Backspace l i s t Enter
 p h p Spacebar a r t i s a n Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace RightArrow RightArrow Ctrl+c

Exception:
System.ArgumentException: Destination array was not long enough. Check destIndex and length, and the array's lower bounds.
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Array destinationArray, Int32 length)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender()
   at Microsoft.PowerShell.PSConsoleReadLine.CancelLine(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.CopyOrCancelLine(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
------------------------------------------------------------C

**Comment by lzybkr** [comment] 2017-04-11 19:13
Different symptom, but most likely a dupe of #292, reopen with additional information if you disagree.

**Closed as completed by lzybkr** 2017-04-11 19:13 UTC
Labels: Resolution-Duplicate
