### ISSUE TITLE
Destination array was not long enough

### ISSUE THREAD

**Issue by pansitwattana** [PowerShell/PSReadLine#595] opened 2017-11-26 15:20 UTC
Environment data
----------------

Steps to reproduce or exception report
--------------------------------------

Last 26 Keys: UpArrow UpArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace

Exception:System.ArgumentException: Destination array was not long enough. Check destIndex and length, and the array's lower bounds.   
at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)   
at System.Array.Copy(Array sourceArray, Array destinationArray, Int32 length)
at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender()   
at Microsoft.PowerShell.PSConsoleReadLine.BackwardDeleteChar(Nullable`1 key, Object arg)   
at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)   
at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()   
at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by lzybkr** [comment] 2017-11-26 16:24
Dupe of many like #491.

**Closed as completed by lzybkr** 2017-11-26 16:24 UTC
Labels: Resolution-Duplicate
