### ISSUE TITLE
CancellationToken should cancel background thread running Console.ReadKey

### ISSUE THREAD

**Issue by TylerLeonhardt** [PowerShell/PSReadLine#1505] opened 2020-05-06 22:53 UTC
## Steps to reproduce

Run this:
```
& {
    [Microsoft.PowerShell.PSConsoleReadLine]::ReadLine($host.Runspace, $ExecutionContext, [System.Threading.CancellationTokenSource]::new(1000).Token)
    Read-Host "asdf"
}
```
Then when prompted, type `asdf`

## Expected behavior

`asdf` is printed.

## Actual behavior

`sdf` is printed (technically only `sdf` is read in to Read-Host even though I typed an `a` before it) and `a` shows up in the prompt after the fact.

![image](https://user-images.githubusercontent.com/2644648/81236361-e019ec00-8fb1-11ea-85d5-7d1901bb9259.png)

This is because there's a lingering call to `Console.ReadKey`

## Why?

PowerShell Editor Services overrides `Console.ReadKey` used in PSReadLine with some cancellation logic that says "if you cancel the token, return down arrow KeyInfo"

We'd, ideally, like to not have this override anymore and just use what PSReadLine uses by default...

In order to do this, the above code needs to work.

I know it's a tall ask, but I wanted to capture this here after our meeting, @daxian-dbw, @SydneyhSmith, @rjmholt, @SteveL-MSFT 

Ideally we could get a cancellable ReadKey like the ask here:
https://github.com/dotnet/runtime/issues/801

but I don't think the .NET Team wants to sign up for that work.

**Comment by daxian-dbw** [comment] 2020-05-10 23:39
This is because PSReadLine is able to cancel [PSConsoleReadLine.ReadKey()](https://github.com/PowerShell/PSReadLine/blob/master/PSReadLine/ReadLine.cs#L170), but not the calls to `Console.ReadKey(bool)` from [ReadOneOrMoreKeys()](https://github.com/PowerShell/PSReadLine/blob/master/PSReadLine/ReadLine.cs#L90) which runs on a different thread (named `"readkey thread"` in PSReadLine).

Aborting that thread is not an option, because it's likely leaving PSReadLine in an bad state, e.g. `Console.ReadKey` could be processing a key when the thread is aborted, and that key will be lost.
One option is to provide a view of the `_queuedKeys` when `ReadLine` is cancelled, so even if `Console.ReadKey` on the `readkey thread` reads in the next key that is supposed to be read by a different `Console.ReadKey` call as shown in the repro step, there is a way to get that key back. But this approach is still unreliable:
1. `_queueKeys` could contains some unprocessed keys that PSReadLine read in before the cancellation happens;
2. When two `Console.ReadKey()` are running on two different thread, there may be no guarantee on the order of the keys read by those 2 calls. For example, the above repro shows the 1st key was ready by the `readkey thread` and the next 3 keys were read by the pipeline thread, but it's possible the 1st key is read by the pipeline thread and the `readkey thread` gets the second key.

The current workaround used in PowerShell Editor Service works much more reliable than having a general solution for this in PSReadLine, because it's using the same method/buffer for both the pipeline thread read and the `readkey thread` read, so the race condition is more manageable and the order of the read-in keys is preserved.

Given the above, I'm inclined to close this issue as by design. @TylerLeonhardt thoughts?

**Comment by SeeminglyScience** [comment] 2020-05-11 02:08
> Ideally we could get a cancellable ReadKey like the ask here:
> [dotnet/runtime#801](https://github.com/dotnet/runtime/issues/801)
> 
> but I don't think the .NET Team wants to sign up for that work.

Problem is I don't really know how you would fix this *outside* of `dotnet/runtime`.  Even if you were going the extra mile and writing separate native implementations, you're still fighting for the same input as someone using `Console.ReadKey`.  Maybe you could write something that blocks until input is queued, but anything using `Console.ReadKey` is going to snatch it up before PSRL can.

Maybe an easier ask for the .NET team is a way to "unget" a key.

**Closed as completed** 2020-05-25 06:00 UTC
Labels: Needs-Author Feedback
