### ISSUE TITLE
Add configuration option to not save commands to history that returned an error

### ISSUE THREAD

**Issue by owenlamont** [PowerShell/PSReadLine#3886] opened 2023-11-28 01:25 UTC
### Prerequisites

- [X] Write a descriptive title.

### Description of the new feature/enhancement

I get frustrated with the predictive intellisense from history because my history inevitably contains many commands that were wrong due to typos or incorrect arguments or argument orders. PSReadLine will unhelpfully suggest auto-completing to these commands and quite often I don't even remember they were wrong or why they were wrong and attempt to run them again further persisting them to the history.

I know some users probably do want all history preserved but I would really like a configuration option (which can default to the current behaviour) to disable saving commands to history if they returned an error.

I'm not sure how to best detect a command returned an error... maybe from a numeric exit status or maybe because it wrote something to standard error... not sure how PSReadLine could hook into those. I know there's similar Linux shell history plugins (e.g. [mcfly](https://github.com/cantino/mcfly)) that do have this option to avoid saving commands that errored and I would love to have that same option in PSReadLine.

**Comment by StevenBucher98** [comment] 2023-11-28 20:59
Duplicate of https://github.com/PowerShell/PSReadLine/issues/3517, upvote this issue to show your interest in this!

**Closed as completed** 2023-11-29 14:09 UTC
Labels: Resolution-Duplicate, Issue-Enhancement
