### ISSUE TITLE
Error after installing powershell and installing WSMan on Mac

### ISSUE THREAD

**Issue by spaz87** [PowerShell/PSReadLine#3486] opened 2022-11-17 19:17 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
### Environment
PSReadLine: 2.2.6
PowerShell: 7.3.0
OS: Darwin 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
BufferWidth: 148
BufferHeight: 23

Last 0 Keys:



### Exception

System.IO.IOException: The system cannot open the device or file specified. : 'PSReadLineHistoryFile_1725057288'
   at System.Threading.Mutex.CreateMutexCore(Boolean initiallyOwned, String name, Boolean& createdNew)
   at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name)
   at Microsoft.PowerShell.PSConsoleReadLine.DelayedOneTimeInitialize()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken, Nullable`1 lastRunStatus)
```

### Screenshot

![Screenshot 2022-11-17 at 1 12 36 PM](https://user-images.githubusercontent.com/101998995/202537481-eb277031-b555-4237-abc0-94afff405e30.png)

### Environment data

```console
Unable as powershell stops working after getting the error
```

### Steps to reproduce

After installing PowerShell via Brew and then installing WSMan running pwsh to start powershell the error is output and the terminal freezes. 

### Expected behavior

No exception 

### Actual behavior

N/A

**Comment by daxian-dbw** [comment] 2022-11-17 20:10
Close as a duplicate of #2658

**Closed as completed by daxian-dbw** 2022-11-17 20:10 UTC
Labels: Resolution-Duplicate
