### ISSUE TITLE
Exception on PowerShell startup

### ISSUE THREAD

**Issue by cyp0633** [PowerShell/PSReadLine#2506] opened 2021-05-29 07:55 UTC
### Environment
PSReadLine: 2.2.0-beta1
PowerShell: 7.2.0-preview.6
OS: Microsoft Windows 10.0.19043
BufferWidth: 121
BufferHeight: 30

Last 0 Keys
```

```

### Exception
```
System.TypeLoadException: Could not load type 'System.Management.Automation.Subsystem.PredictionResult' from assembly 'Microsoft.PowerShell.PSReadLine.Polyfiller, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionViewBase.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionInlineView.Reset() in Microsoft.PowerShell.PSReadLine2.dll:token 0x60004a6+0x0
   at Microsoft.PowerShell.PSConsoleReadLine.Prediction.Reset() in Microsoft.PowerShell.PSReadLine2.dll:token 0x6000478+0x7
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics) in Microsoft.PowerShell.PSReadLine2.dll:token 0x60000f2+0x118
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken) in Microsoft.PowerShell.PSReadLine2.dll:token 0x60000eb+0x60
```

### Steps to reproduce

Just updated PowerShell Preview to 7.2.0-preview.6 via Microsoft Store, and launched Windows Terminal. I did nothing else and then it went wrong.
Later I launched VS Code and the same information appeared in the Terminal window, except BufferWidth (216) and BufferHeight (10).

## Expected behavior

I'm just expecting PowerShell to launch properly.

## Actual behavior

The information above appeared and nothing else happened.

**Comment by daxian-dbw** [comment] 2021-06-01 22:06
Thanks for reporting and using the preview version of PowerShell!
This is a duplicate of #2495. The powershell-7.2.0-preview.6 contains a [release note](https://github.com/PowerShell/PowerShell/releases/tag/v7.2.0-preview.6) for this:

> PSReadLine 2.2.0-beta1 and 2.2.0-beta2 do not work with this preview of PowerShell due to breaking changes in the prediction interface. The upcoming PSReadLine 2.2.0-beta3 release will resolve this. Use PSReadLine 2.1.0 as the temporary workaround.

This was addressed by #2524. We will release 2.2.0-beta3 with this fix today or tomorrow.

**Closed as completed by daxian-dbw** 2021-06-01 22:06 UTC
