### ISSUE TITLE
readline threw exception

### ISSUE THREAD

**Issue by ericsciple** [PowerShell/PSReadLine#563] opened 2017-10-17 04:44 UTC
Environment data
----------------

PS version: 5.1.15063.674
PSReadline version: 1.2
os: 10.0.15063.0 (WinBuild.160101.0800)
PS file version: 10.0.15063.0 (WinBuild.160101.0800)

Steps to reproduce or exception report
--------------------------------------

I was trying to hit enter and accidentally hit the up arrow and page up

Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 LeftArrow LeftArrow LeftArrow LeftArrow Backspace Backspace Backspace a c k a g e M e t a d a t a Enter
 l s Enter
 g i t Spacebar s s Backspace t a t u s Enter
 o p e n Enter
 l s Spacebar . . / . . / . . / t f s Tab / b u i Backspace Backspace Backspace Backspace s e r Tab b Tab Tab s e r Tab Tab Tab Tab Tab Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Tab Tab Tab Tab Backspace Backspace Backspace Backspace Backspace Backspace Backspace Enter
 UpArrow e x t e n s i o n s Tab Enter
 UpArrow * y a m l * Tab | g c Enter
 l s Spacebar . . / . . / C l i e n t G e n e r a t o r C o n f i g s \ g e n c l i e n t . j s o n Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow C l i e n t / Enter
 UpArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow W e b A p i / Enter
 UpArrow PageUp

Exception:
System.IO.IOException: The parameter is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ScrollDisplayUp(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by lzybkr** [comment] 2017-10-17 05:38
Duplicate of #292 .

**Closed as completed by lzybkr** 2017-10-17 05:38 UTC
Labels: Resolution-Duplicate
