### ISSUE TITLE
Vim bindings break terminal after `c2t<char>` sequence sometimes

### ISSUE THREAD

**Issue by ghost** [PowerShell/PSReadLine#1796] opened 2020-09-09 09:00 UTC
I am using the vim bindings, the error occured when I wanted to replace. I assume this is the only relevant part of my profile file, I also change prompt and define some functions, env vars and aliases, but I assume that shouldn't play a role. I am using Windows Terminal if that comes into play in any way.

This happened to me in both scenarios when the desired substitution was possible (i.e. there were the two characters after it) and when it wasn't possible. In both scenarios it worked a few times and then broke down.

```
Set-PSReadLineOption -EditMode Vi
Set-PSReadLineKeyHandler -Key Tab -Function Complete
```

### Environment
PSReadLine: 2.0.0
PowerShell: 7.0.1
OS: Microsoft Windows 10.0.18363
Last 24 Keys
```
 a b c a b c a b c Escape B c 2 t b Escape c 2 t b c 2 t b
```

### Exception
```
System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Microsoft.PowerShell.PSConsoleReadLine.StartEditGroup()
   at Microsoft.PowerShell.PSConsoleReadLine.GroupUndoHelper.StartGroup(Action`2 instigator, Object instigatorArg)
   at Microsoft.PowerShell.PSConsoleReadLine.ViReplaceToBeforeChar(Char keyChar, Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ViReplaceToBeforeChar(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ViChord(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```
Underneath the `digit-argument: 2` now appears whenever I start typing and is either rewritten with the prompt or the output of a command.

PS C:\...\InputGenerator> az account set -s <redacted>
PS C:\...\InputGenerator>
PS C:\...\InputGenerator>
digit-argument: 2
```
```
PS C:\...\InputGenerator>
PS C:\...\InputGenerator> echo foobar
foobarargument: 2
```

**Comment by springcomp** [comment] 2020-12-03 12:03
This is a duplicate of #1281.

**Comment by daxian-dbw** [comment] 2020-12-14 20:00
Close as a duplicate.

**Closed as completed by daxian-dbw** 2020-12-14 20:00 UTC
Labels: Resolution-Duplicate, VI-Mode
