### ISSUE TITLE
History per working directory or per git repo?

### ISSUE THREAD

**Issue by aardappel** [PowerShell/PSReadLine#1745] opened 2020-08-13 20:51 UTC
## Description of the new feature/enhancement

A command history that is tracked per working directory (or per git repo).

I can't be the only programmer where I have many PS open (inside Terminal), one per git repo, and the history of commands I might want to re-use is mostly unique per such repo, and I pretty much never change directory inside each PS. It is not very useful that when I return to a project I haven't touched for a while I first have to scroll thru commands of other projects before getting to the command-lines I wish to reuse (or with CTRL+R, get hits from other projects I don't want).

## Proposed technical implementation details (optional)

It could be as simple as one history file per directory. PS would internally have to switch to read/write to a different history file on each `cd`.

More advanced would be to recognize git directories, and switch history only for such directories. Any `cd` inside a repo would not change history file.

**Comment by lzybkr** [comment] 2020-08-24 19:33
The idea in general sounds potentially useful but I think would require quite a bit of design work. I am a little concerned it might require too many configuration options to be generally useful.

I'd suggest experimenting using PSReadLine extensibility first. Judicious use of `PSConsoleReadLine.ClearHistory`, `PSConsoleReadLine.AddToHistory`, and `Set-PSReadLineOption -HistorySavePath` in your prompt function should be enough to get started.

**Comment by StevenBucher98** [comment] 2023-10-30 17:09
Closing as duplicate of #3472

**Comment by aardappel** [comment] 2023-10-30 17:48
@StevenBucher98 that does not seem like a duplicate to me. That one is about history prediction (presumably completion) which says nothing of what happens when you simply browse the history with up/down keys.. is it going to skip past history items of other directories, as I requested?

**Comment by StevenBucher98** [comment] 2023-10-30 21:17
History predictions are using the same history as what you get from up and down keys. If we want history per working directory we would need to incorporate a more detailed database of history inputs to save what entry and where it was run.

**Closed as completed** 2023-10-31 16:36 UTC
Labels: Resolution-Duplicate, Issue-Enhancement, Not-Planned, Area-HistoryImprovements
