### ISSUE TITLE
bck-i-search (Ctrl-R) quits accepting input when it finds a very long command

### ISSUE THREAD

**Issue by Narvey** [PowerShell/PSReadLine#1083] opened 2019-10-03 18:21 UTC
When I press Ctrl-R, I keep having this gigantic line I once pasted in pop up in the history and clobber the bck-i-search. All the keyboard input then goes at the end of the giant command and so I can't finish typing into bck-i-search the rest of what I wanted to search for. Worse still, Ctrl-C does not get me out, and Ctrl-D just puts ^D on the end of the command. Up arrow does get me out, but causes the below exception. 

Environment data
----------------

PS version: 5.1.18362.145
PSReadline version: 2.0.0-beta2
os: 10.0.18362.1 (WinBuild.160101.0800)
PS file version: 10.0.18362.1 (WinBuild.160101.0800)
BufferWidth: 120
BufferHeight: 3000

Steps to reproduce or exception report
-----------------------------------------------------------------------
Last 4 Keys:
 Ctrl+r b a UpArrow

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -4965.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.HistoryRecall(Int32 direction)
   at Microsoft.PowerShell.PSConsoleReadLine.PreviousHistory(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

-----------------------------------------------------------------------

**Comment by msftrncs** [comment] 2019-10-04 02:07
@Narvey, you should give PSReadline 2.0.0-beta5 a try, from PowerShellGallery.  I cannot say that it will help or entirely eliminate the issue, but a better error report may be possible, knowing how the latest version handles.

**Comment by daxian-dbw** [comment] 2019-10-04 05:49
The `ArgumentOutOfRangeException` exception should be fixed in `2.0.0-beta5`, but I'm curious about the `clobber the bck-i-search` part. Like @msftrncs suggested, can you please try `2.0.0-beta5` and if that doesn't work too, please provide a repro.

**Comment by daxian-dbw** [comment] 2019-10-07 18:53
@Narvey I will close this issue. If you run into the same issue with `2.0.0-beta5`, please re-open the issue and provide a repro. Thanks.

**Comment by msftrncs** [comment] 2019-10-25 22:19
@daxian-dbw, I just had this issue occur on me, when using the CTRL-R search in a 7.0.0-preview5 session in VS Code's terminal, when the resulting found history item was longer than the terminal buffer (which is only a few lines (19).   Then things became really goofy, because the search prompt remained on the screen, but keypresses edited the command that was pulled up, even after pressing escape I could not close the search using escape.  instead I had to press CTRL-R or CTRL-S to get the input going back to the right place, without any exceptions occurring, and then press escape.

Edit: It was a PowerShell Integrated Console, incase that becomes important.

**Comment by daxian-dbw** [comment] 2019-10-25 22:23
Thanks @msftrncs. Re-open this issue.

**Comment by msftrncs** [comment] 2019-10-26 01:58
To produce a good reproduction of this issue

```
PS version: 7.0.0-preview.5
PSReadline version: 2.0.0-beta5
os: 10.0.19008.1 (WinBuild.160101.0800)
PS file version: 7.0.0.0
HostName: Visual Studio Code Host
BufferWidth: 174
BufferHeight: 10
```

Reference code  (you will probably not be able to paste this in to VS Code's terminal)
```PowerShell
(
$ZQZV # because its unique
# 2
# 3
# 4
# 5
# 6
# 7
# 8
# 9
# 10
)
```
After entering the above as a command and posting it to history, press CTRL-R and type `ZQ`, the searched for text will scroll off the top of the buffer and an exception will occur.

### Exception
```
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Actual value was -2.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Render()
   at Microsoft.PowerShell.PSConsoleReadLine.UpdateFromHistory(HistoryMoveCursor moveCursor)
   at Microsoft.PowerShell.PSConsoleReadLine.UpdateHistoryDuringInteractiveSearch(String toMatch, Int32 direction, Int32& searchFromPoint)
   at Microsoft.PowerShell.PSConsoleReadLine.InteractiveHistorySearchLoop(Int32 direction)
   at Microsoft.PowerShell.PSConsoleReadLine.InteractiveHistorySearch(Int32 direction)
   at Microsoft.PowerShell.PSConsoleReadLine.ReverseSearchHistory(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```
Any less than the `# 10` line wouldn't do it...  the text that gets selected has to be more than one line off the screen, probably because the exception occurs when the `bck-i-search: z_` appears.  However, with a 1 line shorter version, ~the~ an exception happens when you try to move off this particular item, ~probably because the selection, which was on the screen initially when it was highlighted, is no longer when it goes to clear it~.

**Comment by msftrncs** [comment] 2019-10-26 02:15
Its purposely trying to put the cursor where the text was found, but that location has scrolled off the screen.

**Comment by msftrncs** [comment] 2019-10-26 02:21
The exception when the search is cleared (when it hadn't first asserted an exception) is different:

### Exception
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Text.StringBuilder.get_Chars(Int32 index)
   at Microsoft.PowerShell.PSConsoleReadLine.ConvertOffsetToPoint(Int32 offset)
   at Microsoft.PowerShell.PSConsoleReadLine.RecomputeInitialCoords()
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Render()
   at Microsoft.PowerShell.PSConsoleReadLine.ClearStatusMessage(Boolean render)
   at Microsoft.PowerShell.PSConsoleReadLine.InteractiveHistorySearch(Int32 direction)
   at Microsoft.PowerShell.PSConsoleReadLine.ReverseSearchHistory(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

**Comment by msftrncs** [comment] 2019-10-26 02:43
In the case of this second exception, the `point.Y` value is -1, and its under neither of the two cases in the comment at

https://github.com/PowerShell/PSReadLine/blob/664b168be26eff7d28af6e71f1c42aa287bd9a8f/PSReadLine/Render.cs#L796-L810

So the `_current` value gets set to some ridiculous point way past the end of the command buffer.  In this case, the entire command is shorter than the `bufferWidth`.

**Comment by msftrncs** [comment] 2019-10-28 06:08
Experimenting with a solution for this, seems the code causing the exception when right-click pasting in Windows Terminal might be closely related.

**Comment by adityapatwardhan** [comment] 2019-12-17 22:45
I am also reproing this on RC1

**Closed as completed** 2019-12-21 07:00 UTC
