### ISSUE TITLE
psreadline vi mode setting ctrl+[ to normalmode doesn't work, instead gets takes ctrl+esc rather than ctrl+[

### ISSUE THREAD

**Issue by mgpinf** [PowerShell/PSReadLine#3116] opened 2021-12-18 13:09 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
N/A
```

### Screenshot

N/A

### Environment data

```console
PS Version: 7.2.1
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.1.0
PSReadLine EditMode: Vi
OS: 10.0.22000.1 (WinBuild.160101.0800)
BufferWidth: 170
BufferHeight: 44
```

### Steps to reproduce

Set-PSReadLineKeyHandler -Key "ctrl+[" -Function ViCommandMode

### Expected behavior

Ctrl+[ should map to esc

### Actual behavior

Ctrl+[ doesn't get mapped to anything. Rather "ctrl+esc" gets mapped to esc

**Comment by daxian-dbw** [comment] 2021-12-20 00:33
Duplicate of #906

**Closed as completed by daxian-dbw** 2021-12-20 00:33 UTC
