### ISSUE TITLE
handle is invalid

### ISSUE THREAD

**Issue by nap** [PowerShell/PSReadLine#357] opened 2016-03-16 20:36 UTC
```
rp-yul-l1344:~/devel/slack_integration $ ssh administrator@192.168.56.102 -v
OpenSSH_6.9p1, LibreSSL 2.1.8
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug1: Connecting to 192.168.56.102 [192.168.56.102] port 22.
debug1: Connection established.
debug1: identity file /Users/jeanr/.ssh/id_rsa type 1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/jeanr/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/jeanr/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/jeanr/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/jeanr/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/jeanr/.ssh/id_ecdsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/jeanr/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/jeanr/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.9
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.1p1 Microsoft_Win32_port_with_VS
debug1: match: OpenSSH_7.1p1 Microsoft_Win32_port_with_VS pat OpenSSH* compat 0x04000000
debug1: Authenticating to 192.168.56.102:22 as 'administrator'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: server->client chacha20-poly1305@openssh.com <implicit> none
debug1: kex: client->server chacha20-poly1305@openssh.com <implicit> none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:YoOFTGkYfjICqCFVioDyk+CpCBkm1fg/nBmvqOsDNQI
debug1: Host '192.168.56.102' is known and matches the ECDSA host key.
debug1: Found key in /Users/jeanr/.ssh/known_hosts:11
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: Roaming not allowed by server
debug1: SSH2_MSG_SERVICE_REQUEST sent
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey,password,keyboard-interactive
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /Users/jeanr/.ssh/id_rsa
debug1: Server accepts key: pkalg ssh-rsa blen 279
debug1: Authentications that can continue: publickey,password,keyboard-interactive
debug1: Trying private key: /Users/jeanr/.ssh/id_dsa
debug1: Trying private key: /Users/jeanr/.ssh/id_ecdsa
debug1: Trying private key: /Users/jeanr/.ssh/id_ed25519
debug1: Next authentication method: keyboard-interactive
debug1: Authentications that can continue: publickey,password,keyboard-interactive
debug1: Next authentication method: password
administrator@192.168.56.102's password: 
debug1: Authentication succeeded (password).
Authenticated to 192.168.56.102 ([192.168.56.102]:22).
debug1: channel 0: new [client-session]
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
debug1: Sending environment.
debug1: Sending env LANG = en_CA.UTF-8

Microsoft Windows [Version 10.0.10586]
(c) 2016 Microsoft Corporation. All rights reserved.

 Volume in drive C has no label.\Users\Administrator>dir
 Volume Serial Number is 30C9-DC3B

 Directory of C:\Users\Administrator

03/16/2016  01:17 PM    <DIR>          .
03/16/2016  01:17 PM    <DIR>          ..
03/16/2016  03:32 PM    <DIR>          Contacts
03/16/2016  03:32 PM    <DIR>          Desktop
03/16/2016  03:32 PM    <DIR>          Documents
03/16/2016  03:44 PM    <DIR>          Downloads
03/16/2016  03:32 PM    <DIR>          Favorites
03/16/2016  03:32 PM    <DIR>          Links
03/16/2016  03:32 PM    <DIR>          Music
03/16/2016  03:32 PM    <DIR>          Pictures
03/16/2016  03:32 PM    <DIR>          Saved Games
03/16/2016  03:32 PM    <DIR>          Searches
03/16/2016  03:32 PM    <DIR>          Videos
03/16/2016  01:17 PM             4,080 _viminfo
               1 File(s)          4,080 bytes
              13 Dir(s)  30,016,204,800 bytes free

Windows PowerShell 27AV36HC2B C:\Users\Administrator>powershell
Copyright (C) 2015 Microsoft Corporation. All rights reserved.


Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 0 Keys:


Exception:
System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

**Comment by lzybkr** [comment] 2017-01-12 19:53
Most likely a dupe of #158, reopen with additional information if you disagree.

**Closed as completed by lzybkr** 2017-01-12 19:53 UTC
Labels: Resolution-Duplicate
