### ISSUE TITLE
Tried to start a powershell from a docker-compose.yml on Windows Server 2016 [TP4] 10575, but got `Exception: System.IO.IOException: The handle is invalid.`

### ISSUE THREAD

**Issue by powersplay** [PowerShell/PSReadLine#303] opened 2015-11-11 21:48 UTC
Used this `docker-compose.yml`: 

```
Wocker:
   image: wsimage:latest
   net: none
   command: ["powershell"]
```

Expecting to get a powershell after the container starts.
Output: 

> PS C:\Users\Administrator\compose> ..\docker-compose-Windows-x86_64.exe up
> Creating compose_Wocker_1
> Attaching to compose_Wocker_1
> Wocker_1 | Windows PowerShell
> Wocker_1 | Copyright (C) 2015 Microsoft Corporation. All rights reserved.
> Wocker_1 |
> Wocker_1 |
> Wocker_1 | Oops, something went wrong.  Please report this bug with the details below.
> Wocker_1 | Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
> Wocker_1 | -----------------------------------------------------------------------
> Wocker_1 | Last 0 Keys:
> Wocker_1 |
> Wocker_1 |
> Wocker_1 | Exception:
> Wocker_1 | System.IO.IOException: The handle is invalid.
> Wocker_1 |
> Wocker_1 |    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
> Wocker_1 |    at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
> Wocker_1 |    at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics
> Wocker_1 |    at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
> Wocker_1 | -----------------------------------------------------------------------

**Comment by lzybkr** [comment] 2015-12-02 21:01
I believe this is a duplicate of #158.

**Closed as completed by lzybkr** 2015-12-02 21:01 UTC
Labels: Issue-Bug, Resolution-Duplicate
