### ISSUE TITLE
Bug after while resizing window

### ISSUE THREAD

**Issue by javijupra** [PowerShell/PSReadLine#1434] opened 2020-03-30 04:49 UTC
-----------------------------------------------------------------------
Last 56 Keys:
 c d Space s p Tab Backspace Backspace Backspace Space s o Tab r e Tab a s Tab Enter
 l s Enter
 l Space s Backspace s Space Backspace Backspace Backspace Backspace Backspace c d Space N e Tab Enter
 Ctrl+l l s Enter
 c d Space S t r Tab Enter
 Ctrl+l d o

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_Cu
rsorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(
RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()

**Comment by iSazonov** [comment] 2020-03-30 05:03
See #1306

**Comment by daxian-dbw** [comment] 2020-03-30 17:13
From the bug report template:
```
The maintainer may close your issue without further explanation or engagement if:
- You delete this entire template and go your own path;
```
So, please follow the bug report template to provide **environment data** and **repro step** the next time.

As for this issue, it's very likely a duplicate of #1306 and was fixed in the latest version. Please check out #1306 for more information.

**Closed as completed by daxian-dbw** 2020-03-30 17:13 UTC
Labels: Resolution-Duplicate
