### ISSUE TITLE
Bash style completion and directories

### ISSUE THREAD

**Issue by idealist1508** [PowerShell/PSReadLine#313] opened 2015-12-07 12:51 UTC
I have following folders on c:
`Program Files`        `Program Files (x86)`  `ProgramData`          `Programme`
if I type `cd c:\pr[tab]` it completes as:  `cd C:\Program`,
but if I type `c:\pr[tab]` it doesn't completes. It shows only all possible variants:
`Program Files       Program Files (x86)        ProgramData          Programme`

**Comment by lzybkr** [comment] 2015-12-07 16:45
This drove me nuts for a long time but I never got around to fixing it.  I now use Ctrl+Space after I hit this situation and it's a reasonable workaround, but I agree this should be fixed.  At any rate, this is a dupe of #72.

**Closed as completed by lzybkr** 2015-12-07 16:45 UTC
Labels: Issue-Bug, Resolution-Duplicate

**Comment by idealist1508** [comment] 2015-12-08 20:38
Indeed the reason for this strange behavior is a space. But I don't think that this is a dupe.

Case 1 (`cd c:\pr[tab]` -> `cd C:\Program`) is a dupe, but IMHO not a issue. It works as expected. I can type now `m[tab]`. and it completes as `cd c:\Programme\`. Or I can type `' [tab]` and it completes as `cd 'C:\Program Files` . Both are correct.

Case 2 (`c:\pr[tab]` -> doesn't completes) is a (new) issue.
