### ISSUE TITLE
Came across this exception when using powershell. Using windows 10 pro, 64 bit

### ISSUE THREAD

**Issue by eltommo** [PowerShell/PSReadLine#281] opened 2015-09-02 08:29 UTC
```
PS C:\Users\XXXXXXXX> powershell -noexit -command "Read-Host" | write-output
hello
hello
PS C:\Users\XXXXXXXX>
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 1 Keys:
 UpArrow

Exception:
System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.PlaceCursor(Int32 x, Int32& y)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender()
   at Microsoft.PowerShell.PSConsoleReadLine.HistoryRecall(Int32 direction)
   at Microsoft.PowerShell.PSConsoleReadLine.PreviousHistory(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

**Comment by lzybkr** [comment] 2017-01-12 20:43
Most likely a dupe of #158, reopen with additional information if you disagree.

**Closed as completed by lzybkr** 2017-01-12 20:43 UTC
Labels: Resolution-Duplicate
