### ISSUE TITLE
System.IO.IOException: The system cannot open the device or file specified. : 'PSReadLineHistoryFile_2544786955'

### ISSUE THREAD

**Issue by deanml** [PowerShell/PSReadLine#1579] opened 2020-06-02 22:17 UTC
I am getting this on Mac OS Catalina, I've tried several ways of installing and reinstalling powershell.  All to no avail.  I've also use the Get-PSReadlineOption to check the location of HistorySavePath and completely deleted this folder off the system to no avail.  

### Environment
PSReadLine: 2.0.1
PowerShell: 7.1.0-preview.3
OS: Darwin 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64
Last 0 Keys
```

```

### Exception
```
System.IO.IOException: The system cannot open the device or file specified. : 'PSReadLineHistoryFile_2544786955'
   at System.Threading.Mutex.CreateMutexCore(Boolean initiallyOwned, String name, Boolean& createdNew)
   at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name)
   at Microsoft.PowerShell.PSConsoleReadLine.DelayedOneTimeInitialize()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

**Comment by daxian-dbw** [comment] 2020-06-04 17:55
This is a duplicate of #1464. It's likely the `/tmp` directory on you mac doesn't have the permission for the dotnet runtime to write to it. See https://github.com/PowerShell/PSReadLine/issues/1464#issuecomment-631941511

**Closed as completed by daxian-dbw** 2020-06-04 17:55 UTC
Labels: Resolution-Duplicate

**Comment by HitanshuGupta** [comment] 2022-01-17 15:33
i also getting same problem in linux
and in asus laptop
