### ISSUE TITLE
PSReadLine 2.0.0 in PowerShell Core 6.1 and Windows PowerShell RS5

### ISSUE THREAD

**Issue by damrichard** [PowerShell/PSReadLine#769] opened 2018-09-29 09:08 UTC
Environment data
----------------
PSVersion                      6.1.0 or 5.1.17763.1
PSReadLine                   2.0.0

Steps to reproduce or exception report
--------------------------------------
Get-PSReadLineOption
Get-PSReadLineOption : The type initializer for 'Microsoft.PowerShell.PSConsoleReadLine' threw an exception.
At line:1 char:1
+ Get-PSReadLineOption
+ ~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Get-PSReadLineOption], TypeInitializationException
+ FullyQualifiedErrorId : System.TypeInitializationException,Microsoft.PowerShell.GetPSReadLineOption

The module doesn't work. Any command are available.

**Comment by lzybkr** [comment] 2018-09-29 15:33
Duplicate of #614, fixed in #768 (just merged, not in any release yet).
The workaround for now is to used another keyboard layout, build from the latest, or grab a build out of appveyor.

**Closed as completed by lzybkr** 2018-09-29 15:33 UTC
Labels: Resolution-Duplicate
