### ISSUE TITLE
Allow tabs at the start of lines

### ISSUE THREAD

**Issue by pavelbraginskiy** [PowerShell/PSReadLine#715] opened 2018-06-21 23:29 UTC
Currently, the tab key only does autocompletion, and can't insert actual tabs. 

However, a lot of the time, I have a large amount of text, such as code, in a here-string `@''@`, where I want to put indentation. 

Adding indentation is most useful at the start of lines, where autocomplete can't happen anyway, so it would be useful to have tab insert an actual tab at the start of a line.

Alternatively, since here-strings don't allow autocompletion anyway, make tab always insert a tab character while in the middle of a here-string.

**Comment by lzybkr** [comment] 2018-06-21 23:57
If this is simply an ask to support *pasting* tabs, then it's a duplicate of #77 and is really part of a bigger issue captured in #579.

If you really want to insert explicit tabs, then we could follow how it's done in Emacs mode where you would type <kbd>Ctrl+q</kbd> first - that basically says insert the next character, whatever it might be, instead of invoking what it's bound to.

This function is not yet implemented in `PSReadLine`, but it would be the natural way to do this in Emacs mode, and I suppose it would be fine in Windows mode too.

**Comment by pavelbraginskiy** [comment] 2018-06-22 00:10
I often write short code snippets in here-strings, so it's not just pasting. The c-q solution isn't ideal but it's better than nothing.

**Comment by pavelbraginskiy** [comment] 2018-06-22 00:12
Though this includes pasting as well, since I rely on my terminal's built-in paste (ctrl-shift-v), which sends the copied text as keystrokes.

**Closed as completed** 2023-11-07 00:41 UTC
Labels: Resolution-Duplicate
