### ISSUE TITLE
vscode debug HANG when psreadline=2.2.0 beta3

### ISSUE THREAD

**Issue by kasini3000** [PowerShell/PSReadLine#2643] opened 2021-07-04 09:10 UTC
## Environment

psreadline=2.2.0 beta3
powershell=7.2 preview7
vscode=1.56.2
powershell ext for vscode=2021.6.2

## Steps to reproduce
```
$a = 1
$a
$b = 2  #breakprint
$b
```
then F5

## Expected behavior

debug toolbar work 

## Actual behavior
powershell integrated console Flashing...
vscode HANG
debug toolbar not work 

# Q:how to fix the problem?
A: 
1 exit vscode .
2 delete psreadline 2.2.0 beta3 from module folder 【c:\Users\myusername\Documents\PowerShell\Modules\PSReadLine\2.2.0】
3 restart vscode,then debug ps1file . 
4 Failure can be reproduced, if return psreadline 2.2.0 beta3 folder.

**Comment by daxian-dbw** [comment] 2021-07-07 05:11
Close as a duplicate of #2616

**Closed as completed by daxian-dbw** 2021-07-07 05:11 UTC
