### ISSUE TITLE
Exit debug mode ends with 'length is too big' exception

### ISSUE THREAD

**Issue by amnich** [PowerShell/PSReadLine#550] opened 2017-08-05 05:13 UTC
Environment data
----------------

```powershell
PS version: 5.1.15063.483
PSReadline version: 1.2
os: 10.0.15063.0 (WinBuild.160101.0800)
PS file version: 10.0.15063.0 (WinBuild.160101.0800)
```

Exception report
--------------------------------------
```powershell
-----------------------------------------------------------------------
Last 15 Keys:
 g e t - c h i l d Tab e x i t Enter


Exception:
System.ArgumentException: length is too big
Nazwa parametru: length
   w Microsoft.PowerShell.PSConsoleReadLine.Replace(Int32 start, Int32 length, String replacement, Action`2 instigator,
Object instigatorArg)
   w Microsoft.PowerShell.PSConsoleReadLine.DoReplacementForCompletion(CompletionResult completionResult, CommandComplet
ion completions)
   w Microsoft.PowerShell.PSConsoleReadLine.Complete(Boolean forward)
   w Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignore
IfNoAction, Object arg)
   w Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   w Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

Steps to reproduce
--------------------------------------

1. Enter debug mode with Ctrl + Break
2. Type partial cmdlet name -> Get-Child
3. Hit TAB
4. In debug mode type -> exit
5. Hit Enter

**Comment by lzybkr** [comment] 2017-10-16 23:45
Odd, I can't reproduce this error. Can you, or did you see it just once?

**Comment by lzybkr** [comment] 2017-11-03 05:21
Closing as no repro - though this looks a lot like #534 which I just fixed.

**Closed as completed by lzybkr** 2017-11-03 05:21 UTC
