### ISSUE TITLE
PSReadline crashes on startup running from the new Win32 SSH server

### ISSUE THREAD

**Issue by ghost** [PowerShell/PSReadLine#327] opened 2016-01-01 23:45 UTC
```
Exception:
System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------


Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 0 Keys:

```

Steps to reproduce: 
- Install OpenSSH from https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH
- Connect to your windows box from somewhere else / localhost via SSH
- Run Powershell (with a profile that loads PSReadLine)

**Comment by lzybkr** [comment] 2016-01-02 21:07
This is a duplicate of #158.

**Closed as completed by lzybkr** 2016-01-02 21:07 UTC
Labels: Issue-Bug, Resolution-Duplicate
