### ISSUE TITLE
IOException on Ctrl+L

### ISSUE THREAD

**Issue by abaddon82** [PowerShell/PSReadLine#248] opened 2015-06-18 07:32 UTC
I'm getting an exception when trying to Ctrl+L to clear the screen. Running on Windows 10 Insider Preview Build 10130. `Clear-Host` works fine.

Output:

```
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 Backspace Backspace Backspace Enter
 g e t - h e l p Spacebar n e w - p s d r i v e Enter
 UpArrow Spacebar e Backspace - e x a m p l e s Enter
 UpArrow | m o r e Enter
 UpArrow Enter
 Ctrl+l l s Enter
 n e w - p s Tab Spacebar - Tab Spacebar " <Redacted> " Shift+Spacebar - p w e Backspace Backspace e r s Tab Spacebar - P S P Tab Spacebar Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Enter
 Ctrl+l n e w - i t e m Tab Spacebar - Tab Tab Spacebar " <Redacted> " Spacebar - Tab Tab Tab Shift+Tab Spacebar Tab Tab Enter
 UpArrow Spacebar - c r e Tab Spacebar ( G e t - C r e d Tab ) Enter
 m k d i r Spacebar " <Redacted> " Enter
 Ctrl+l l s Enter
 c d Spacebar T o m Tab Enter
 Ctrl+l l s Enter
 Ctrl+l Ctrl+l

Exception:
System.IO.IOException: The parameter is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ClearScreen(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, Object reserved)
-----------------------------------------------------------------------
```

$PSVersionTable:

```
Name                           Value
----                           -----
PSVersion                      5.0.10130.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   10.0.10130.0
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
```

**Comment by lzybkr** [comment] 2015-06-18 16:08
Assuming this happens in full screen mode, it's a dupe of #232.

**Closed as completed by lzybkr** 2015-06-18 16:08 UTC
Labels: Resolution-Duplicate
