### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Hirugao** [PowerShell/PSReadLine#547] opened 2017-07-23 11:06 UTC
Environment data
----------------

powershell
PS version:
 Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      14393  1480

PSReadline version:
Major  Minor  Build  Revision
-----  -----  -----  --------
1      2      -1     -1

os:  10.0.14393.0 (rs1_release.160715-1616)

PS file version: 10.0.14393.0 (rs1_release.160715-1616)

Steps to reproduce or exception report
--------------------------------------
-----------------------------------------------------------------------
直前 50 個のキー:
 h e l p Spacebar I n v Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 VolumeMute I

例外:
System.IO.IOException: パラメーターが間違っています。

   場所 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   場所 System.Console.SetWindowPosition(Int32 left, Int32 top)
   場所 Microsoft.PowerShell.Internal.ConhostConsole.set_WindowTop(Int32 value)
   場所 Microsoft.PowerShell.PSConsoleReadLine.ReallyRender()
   場所 Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   場所 Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   場所 Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   場所 Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   場所 Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by lzybkr** [comment] 2017-10-17 01:50
Duplicate of #292.

**Closed as completed by lzybkr** 2017-10-17 01:50 UTC
Labels: Resolution-Duplicate
