### ISSUE TITLE
Bug Found when an Emoji is typed in the commit message for a file

### ISSUE THREAD

**Issue by vinaykulk621** [PowerShell/PSReadLine#3566] opened 2023-02-03 18:32 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
### Exception

System.Text.EncoderFallbackException: Unable to translate Unicode character \uD83E at index 40 to specified code page.
   at System.Text.EncoderExceptionFallbackBuffer.Fallback(Char charUnknown, Int32 index)
   at System.Text.EncoderFallbackBuffer.InternalFallback(Char ch, Char*& chars)
   at System.Text.UTF8Encoding.GetBytes(Char* chars, Int32 charCount, Byte* bytes, Int32 byteCount, EncoderNLS baseEncoder)
   at System.Text.EncoderNLS.GetBytes(Char[] chars, Int32 charIndex, Int32 charCount, Byte[] bytes, Int32 byteIndex, Boolean flush)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at Microsoft.PowerShell.PSConsoleReadLine.<>c__DisplayClass83_0.<WriteHistoryRange>b__0()
   at Microsoft.PowerShell.PSConsoleReadLine.WithHistoryFileMutexDo(Int32 timeout, Action action)
   at Microsoft.PowerShell.PSConsoleReadLine.MaybeAddToHistory(String result, List`1 edits, Int32 undoEditIndex, Boolean fromDifferentSession, Boolean fromInitialRead)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

### Screenshot

![image](https://user-images.githubusercontent.com/94120295/216679766-404759d6-2a4e-4bc1-b20d-72ab310ffcd6.png)

### Environment data

```console
PS Version: 5.1.22621.963
PS HostName: ConsoleHost
PSReadLine Version: 2.0.0
PSReadLine EditMode: Windows
OS: 10.0.22621.1 (WinBuild.160101.0800)
BufferWidth: 228
BufferHeight: 37
```

### Steps to reproduce

1-->Add Files to commit (git add .)
2-->commit (git commit -m "<Content/>{Emojis}"
3-->Error

### Expected behavior

Normal Commit should happen with emojis in the commit messeage

### Actual behavior

Getting some long error about not able to traslate unicode charecter

**Comment by daxian-dbw** [comment] 2023-02-06 18:35
Close as a duplicate of #1329

**Closed as completed by daxian-dbw** 2023-02-06 18:35 UTC
Labels: Resolution-Duplicate, Issue-Emoji
