### ISSUE TITLE
Paste in PowerShell drops certain characters like "【】｜"

### ISSUE THREAD

**Issue by czphoenix** [PowerShell/PSReadLine#2249] opened 2021-02-25 13:50 UTC
## Environment

```none
PS version: 7.1.2
PSReadline version: 2.2.0-beta2
os: 10.0.19041.860 (WinBuild.160101.0800)
PS file version: 7.1.2.0
HostName: ConsoleHost (Windows Terminal)
BufferWidth: 120
BufferHeight: 30

Windows Terminal version 1.5.10411.0
```

## Steps to reproduce

1. Open a tab of PowerShell 7.1.2 or Windows PowerShell
2. Copy any line of the following text
```none
【1】【2】【3】[4][5][6]
【】【】【】
【【【【【【
】】】】】】
｜｜｜｜｜｜
1｜2｜3｜4|5|6|
```
3. Paste it

## Expected behavior

Pasted text should be the same as copied

## Actual behavior

Ended up with the following
```none
【123[4][5][6]
【
【
】
｜
1234|5|6|
```

affects Chinese punctuation marks
```none
！￥…………（）————【】；：‘“，。《》？、·
```

#https://github.com/microsoft/terminal/issues/9263

**Comment by daxian-dbw** [comment] 2021-03-05 19:13
@czphoenix Thanks for the report. I believe you did the pasting with right click, and this is a duplicate of #579.
You can try using `ctrl+v` and it will work as expected:

![demo1](https://user-images.githubusercontent.com/127450/110162622-d57fdd00-7da3-11eb-8ebc-d0934e3a439c.gif)

**Closed as completed by daxian-dbw** 2021-03-05 19:13 UTC

**Comment by czphoenix** [comment] 2021-03-06 03:27
In my case ctrl+v results the same as right click.
However, this only occur in Terminal
![image](https://user-images.githubusercontent.com/2180490/110193438-d893cf80-7e6e-11eb-9cca-60bff0facba7.png)
![image](https://user-images.githubusercontent.com/2180490/110193448-e0ec0a80-7e6e-11eb-8be9-f26ef819b7bc.png)

Standalone PowerShell Core 7.1.2 and PowerShell works fine
![image](https://user-images.githubusercontent.com/2180490/110193422-bf8b1e80-7e6e-11eb-9170-c2763084bbbe.png)
![image](https://user-images.githubusercontent.com/2180490/110193432-cf0a6780-7e6e-11eb-8f59-d6073d7f2e02.png)

Cmder works fine
![image](https://user-images.githubusercontent.com/2180490/110193393-8c488f80-7e6e-11eb-925e-3178dfd2f2ce.png)
![image](https://user-images.githubusercontent.com/2180490/110193407-a4b8aa00-7e6e-11eb-8f81-0466d329b127.png)
