### ISSUE TITLE
Exception while pasting a command from clipboard using a right click and then Ctrl+V

### ISSUE THREAD

**Issue by aughun** [PowerShell/PSReadLine#392] opened 2016-05-29 08:27 UTC
Exception:
System.Runtime.InteropServices.ExternalException (0x800401D0): Requested Clipboard operation did not succeed.
   at System.Windows.Forms.Clipboard.ThrowIfFailed(Int32 hr)
   at System.Windows.Forms.Clipboard.GetDataObject(Int32 retryTimes, Int32 retryDelay)
   at System.Windows.Forms.Clipboard.GetDataObject()
   at System.Windows.Forms.Clipboard.ContainsText(TextDataFormat format)
   at Microsoft.PowerShell.PSConsoleReadLine.<>c__DisplayClass146_0.<Paste>b__0()
   at Microsoft.PowerShell.PSConsoleReadLine.Paste(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by lzybkr** [comment] 2017-02-09 15:36
Duplicate of #265.

**Closed as completed by lzybkr** 2017-02-09 15:36 UTC
Labels: Resolution-Duplicate
