### ISSUE TITLE
Font flashes to default then back when typing a non-existent command

### ISSUE THREAD

**Issue by MonkeTGG** [PowerShell/PSReadLine#4257] opened 2024-11-07 09:03 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
N/A
```

### Screenshot

Uploading 2024-11-07 19-59-17.mp4…

### Environment data

```console
don't think its needed ngl, and i cant, pressing enter just makes a new like, and Ctrl + C, just doesn't run it
```

### Steps to reproduce

Apply a custom font (i think)
run a non-existent command
Done

### Expected behavior

No flashing between fonts

### Actual behavior

Flashes between 2 fonts when non-existent command ran

**Comment by daxian-dbw** [comment] 2024-11-07 18:05
I cannot reproduce with the given repro steps. I will close this issue as it doesn't provide any other information about the issue that would help investigation.

**Closed as completed by daxian-dbw** 2024-11-07 18:05 UTC
