### ISSUE TITLE
Error when starting Powershell for Mac

### ISSUE THREAD

**Issue by lmontalvillo** [PowerShell/PSReadLine#3955] opened 2024-02-24 09:23 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
### Environment
PSReadLine: 2.2.6
PowerShell: 7.3.6
OS: Darwin 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:54:10 PST 2023; root:xnu-10002.61.3~2/RELEASE_X86_64
BufferWidth: 204
BufferHeight: 40

Last 0 Keys:



### Exception

System.IO.IOException: The system cannot open the device or file specified. : 'PSReadLineHistoryFile_2626316539'
   at System.Threading.Mutex.CreateMutexCore(Boolean initiallyOwned, String name, Boolean& createdNew)
   at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name)
   at Microsoft.PowerShell.PSConsoleReadLine.DelayedOneTimeInitialize()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken, Nullable`1 lastRunStatus)
```

### Screenshot

<img width="1324" alt="image" src="https://github.com/PowerShell/PSReadLine/assets/37110322/2223931e-1d1c-4991-9363-ab9e44e12539">

### Environment data

```console
PS Version: 7.3.6
PS HostName: ConsoleHost
PSReadLine Version: 2.2.6
PSReadLine EditMode: Emacs
OS: Darwin MacBook-Pro-de-Luis.local 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:54:10 PST 2023; root:xnu-10002.61.3~2/RELEASE_X86_64 x86_64
BufferWidth: 204
BufferHeight: 40
```

### Steps to reproduce

Just Starting the app in Mac OSX Sonoma 14.3

### Expected behavior

Normal starting

### Actual behavior

Ocassionaly

**Comment by daxian-dbw** [comment] 2024-02-26 17:58
@lmontalvillo Please see if https://github.com/PowerShell/PSReadLine/issues/1464#issuecomment-631656531 solves your problem. If your permissions on `/private/tmp` are fine, then it's a duplicate of #2658, which is caused by the .NET issue https://github.com/dotnet/runtime/issues/79375

**Closed as completed by daxian-dbw** 2024-02-26 17:58 UTC
Labels: Resolution-Duplicate
