### ISSUE TITLE
Hyphen before parameter gets stripped on paste

### ISSUE THREAD

**Issue by rockerinthelocker** [PowerShell/PSReadLine#2374] opened 2021-04-19 07:38 UTC
First opened here: https://github.com/PowerShell/PowerShell/issues/15268

Thanks, @iSazonov! Indeed, the bug seems to be introduced in PSReadline 2.1! Still not resolved in 2.2.0 beta2.

## Steps to reproduce
Copy and paste the following line into a Powershell Core console.
```
Optimize-Volume -DriveLetter C -Analyze –Verbose
```
## Expected behavior
The hyphen before the Verbose parameter should be preserved.
```
Optimize-Volume -DriveLetter C -Analyze –Verbose
```
## Actual behavior
The hyphen before the Verbose parameter has been stripped.
```
Optimize-Volume -DriveLetter C -Analyze Verbose
```
## Environment data

Note: The bug affects PSReadline 2.1.0-2.2.0 beta 2.

```
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by daxian-dbw** [comment] 2021-04-29 22:05
Close as a duplicate of #1603

@rockerinthelocker Note that the pasting works fine with `Ctrl+v` in PSReadLine. It only doesn't work when you paste with right click.

**Closed as completed by daxian-dbw** 2021-04-29 22:05 UTC
