### ISSUE TITLE
Error in SQL Server 2014 Agent Job Step

### ISSUE THREAD

**Issue by Daddio6** [PowerShell/PSReadLine#239] opened 2015-05-20 21:19 UTC
The CmdExec statement is (literal between the braces): 
powershell.exe -noexit "&  ""c:\temp\getPerfCounters.ps1"""

-----------------------------------------------------------------------  Last 0 Keys:      Exception:  System.IO.IOException: The handle is invalid.       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)     at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)     at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)     at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, Object reserved)  -----------------------------------------------------------------------.  Process Exit Code 2.  The step failed.

**Comment by lzybkr** [comment] 2017-01-12 20:35
Most likely a dupe of #158, reopen with additional information if you disagree.

**Closed as completed by lzybkr** 2017-01-12 20:35 UTC
Labels: Resolution-Duplicate
