### ISSUE TITLE
Got an exception trying to page up in Powershell prompt

### ISSUE THREAD

**Issue by RobertBernstein** [PowerShell/PSReadLine#244] opened 2015-06-13 00:46 UTC
Here is the dump of the error I received.

Last 200 Keys:
 Backspace Tab Tab d Tab Tab Tab i p Tab Enter
 d i r Enter
 c d Spacebar Tab Enter
 d i r Enter
 d i r Spacebar - h Tab Enter
 g i t Spacebar s Backspace l o g Enter
 g i t Spacebar b r a n c h Enter
 g i t Spacebar l o g Spacebar c 6 c 3 8 3 c c Enter
 g i t Spacebar h e l p Spacebar l o g Enter
 d i r Enter
 c d Spacebar i p Tab Tab Tab Enter
 d i r Enter
 c d Spacebar b i n Enter
 d i r Enter
 c d Spacebar d Tab Enter
 d i r Enter
 c d Spacebar . . Enter
 c d Spacebar r e l Tab Enter
 d i r Enter
 c d . Backspace Spacebar . . Enter
 d i r Enter
 d i r Enter
 c d Spacebar d Tab Enter
 d i r Enter
 d u m p b i n Spacebar \* e x e Tab Enter
 UpArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+RightArrow LeftArrow LeftArrow / h e a d e r s Spacebar Enter
 PageUp Ctrl+PageUp Ctrl+PageUp Ctrl+PageUp

Exception:
System.IO.IOException: The parameter is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ScrollDisplayUpLine(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()

**Comment by lzybkr** [comment] 2015-06-17 23:19
I assume this was on Win10 in full screen mode.  Assuming so, it's a dupe of #232.

**Closed as completed by lzybkr** 2015-06-17 23:19 UTC
Labels: Resolution-Duplicate
