### ISSUE TITLE
PSReadLine crashes on Ctrl+PageUp or Ctrl+PageDown

### ISSUE THREAD

**Issue by MiToZZG** [PowerShell/PSReadLine#321] opened 2015-12-17 16:27 UTC
PS C:>
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
## Or email: jason@truewheels.net

Last 9 Keys:
 e f d s Shift+Home Escape Delete Shift+PageUp Ctrl+PageUp

Exception:
System.IO.IOException: The parameter is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.SetWindowPosition(Int32 left, Int32 top)
   at PSConsoleUtilities.PSConsoleReadLine.ScrollDisplayUpLine(Nullable`1 key, Object arg)
   at PSConsoleUtilities.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreI
fNoAction, Object arg)
   at PSConsoleUtilities.PSConsoleReadLine.InputLoop()
##    at PSConsoleUtilities.PSConsoleReadLine.ReadLine(Runspace remoteRunspace, EngineIntrinsics engineIntrinsics)

PS C:>

PS C:>
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
## Or email: jason@truewheels.net

Last 1 Keys:
 Ctrl+PageDown

Exception:
System.IO.IOException: The parameter is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.SetWindowPosition(Int32 left, Int32 top)
   at PSConsoleUtilities.PSConsoleReadLine.ScrollDisplayDownLine(Nullable`1 key, Object arg)
   at PSConsoleUtilities.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreI
fNoAction, Object arg)
   at PSConsoleUtilities.PSConsoleReadLine.InputLoop()
##    at PSConsoleUtilities.PSConsoleReadLine.ReadLine(Runspace remoteRunspace, EngineIntrinsics engineIntrinsics)

PS C:>

**Comment by lzybkr** [comment] 2015-12-17 19:51
I assume this happens in full screen mode on Win10.
If so, it's a dupe of #232, which I thought was fixed in the Nov update to Win10 - and seems fixed in later builds.

**Comment by lzybkr** [comment] 2015-12-31 05:44
I'm closing this as I haven't received any additional information and I believe the problem is addressed by a fix in the Win10 November update.  Please re-open with more details if the problem exists without full screen mode or still happens for you using the latest Win10 builds.

**Closed as completed by lzybkr** 2015-12-31 05:44 UTC
