### ISSUE TITLE
Powershell returning an error whenever I use an emoji in the terminal

### ISSUE THREAD

**Issue by Keith-Web3** [PowerShell/PSReadLine#3915] opened 2024-01-08 13:39 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
System.Text.EncoderFallbackException: Unable to translate Unicode character \\uD83D at index 0 to specified code page.    
   at System.Text.EncoderExceptionFallbackBuffer.Fallback(Char charUnknown, Int32 index)
   at System.Text.Encoding.GetBytesWithFallback(ReadOnlySpan`1 chars, Int32 originalCharsLength, Span`1 bytes, Int32 originalBytesLength, EncoderNLS encoder)
   at System.Text.Encoding.GetBytesWithFallback(Char* pOriginalChars, Int32 originalCharCount, Byte* pOriginalBytes, Int32 originalByteCount, Int32 charsConsumedSoFar, Int32 bytesWrittenSoFar, EncoderNLS encoder)
   at System.Text.EncoderNLS.GetBytes(Char* chars, Int32 charCount, Byte* bytes, Int32 byteCount, Boolean flush)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at Microsoft.PowerShell.PSConsoleReadLine.<>c__DisplayClass99_0.<WriteHistoryRange>b__0()
   at Microsoft.PowerShell.PSConsoleReadLine.WithHistoryFileMutexDo(Int32 timeout, Action action)
   at Microsoft.PowerShell.PSConsoleReadLine.WriteHistoryRange(Int32 start, Int32 end, Boolean overwritten)
   at Microsoft.PowerShell.PSConsoleReadLine.MaybeAddToHistory(String result, List`1 edits, Int32 undoEditIndex, Boolean fromDifferentSession, Boolean fromInitialRead)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken, Nullable`1 lastRunStatus)
```

### Screenshot

![Screenshot (362)](https://github.com/PowerShell/PSReadLine/assets/96974022/fefba190-0402-4d7f-9f2e-1af7a9fb3851)

### Environment data

```console
PS Version: 7.3.10
PS HostName: ConsoleHost
PSReadLine Version: 2.2.6
PSReadLine EditMode: Windows
OS: 10.0.22000.1 (WinBuild.160101.0800)
BufferWidth: 122
BufferHeight: 18
```

### Steps to reproduce

1) Create a new folder
2) cd into the folder
3) Initialize a git repository in the folder with
    ```
    git init
    ````
 4) Make a change in the folder
 5) Stage and commit the change while adding an emoji in the commit message e.g `Hello world 😂`
 6) Run the commit command

### Expected behavior

Commit the change with the emoji

### Actual behavior

Throws an error saying "something went wrong" without further info on the error.

**Comment by Keith-Web3** [comment] 2024-01-08 13:42
Just realized there's already an open issue referencing the same error.

**Comment by StevenBucher98** [comment] 2024-01-08 17:11
@Keith-Web3 thanks for submitting the issue! Can you link the issue you found that has the same error and we can close this one to track that one?

**Comment by Keith-Web3** [comment] 2024-01-08 17:27
Sure, it's #1329.
Seems there's been no update on the issue for about a year now.

**Comment by StevenBucher98** [comment] 2024-01-08 19:53
Do you mind trying on PSReadLine 2.3.4 just to check that this is still an issue with the latest version of PSReadLine?

**Comment by Keith-Web3** [comment] 2024-01-08 21:32
![Screenshot (363)](https://github.com/PowerShell/PSReadLine/assets/96974022/a3098848-3a71-4b6d-a504-26dea1083a13)
Still the same

**Comment by daxian-dbw** [comment] 2024-01-31 22:23
This is a duplicate of #3832 and is actually an issue with the older version of conpty that ships with Windows -- the � shown in VSCode terminal was because only the high surrogate of the surrogate pair that represents the emoji was pasted into the read-line buffer, due to the older version of conpty not handling it correctly.

See https://github.com/PowerShell/PSReadLine/issues/3832#issuecomment-1766839454 and the replying comment from @Tyriar for details.

**Closed as completed by daxian-dbw** 2024-01-31 22:23 UTC
Labels: Resolution-Duplicate
