### ISSUE TITLE
un problème s'est produit

### ISSUE THREAD

**Issue by p4cm4n972** [PowerShell/PSReadLine#2263] opened 2021-03-02 18:25 UTC
Dernières 200 touches :
 Tab Tab Tab Tab Tab Tab Tab Tab Tab Escape r m Space - R Space n o d Tab Tab Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace l s Enter
 n p m Space i Enter
 n p m Space r u n Space s t a r t : d e v Enter
 n p m Space i Space - D Space t y p e s c r i p t Ctrl+Alt+@ 4 . 0 . 5 Backspace 0 Backspace Backspace Backspace 2 . 0 Enter
 UpArrow LeftArrow LeftArrow RightArrow RightArrow Ctrl+u Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace n p m Space i Space - D Space t y p e s c r i p t Ctrl+Alt+@ 4 . 0 . 5 Enter
 UpArrow UpArrow UpArrow Enter
 n p m Space i Enter
 c a t Space p a c Tab Enter
 UpArrow UpArrow UpArrow Enter
 c o d e Space . Enter
 Ctrl+l

Exception :
System.ArgumentOutOfRangeException: La valeur doit être supérieure ou égale à zéro et inférieure à la taille de la mémoire tampon de la console dans cette dimension.
Nom du paramètre : top
La valeur réelle était -24.
   à System.Console.SetCursorPosition(Int32 left, Int32 top)
   à Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   à Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   à Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment] 2021-03-05 18:57
This is a duplicate of #1315. Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.

**Closed as completed by daxian-dbw** 2021-03-05 18:57 UTC
