### ISSUE TITLE
Unable to translate Unicode character \\uD83D at index 5 to specified code page.

### ISSUE THREAD

**Issue by maximousblk** [PowerShell/PSReadLine#2170] opened 2021-01-30 12:23 UTC
### Environment
PSReadLine: 2.1.0
PowerShell: 7.1.1
OS: Microsoft Windows 10.0.19042
BufferWidth: 133
BufferHeight: 31

Last 7 Keys
```
 e c h o Spacebar � Enter

```

### Exception
```
System.Text.EncoderFallbackException: Unable to translate Unicode character \\uD83D at index 5 to specified code page.
   at System.Text.EncoderExceptionFallbackBuffer.Fallback(Char charUnknown, Int32 index)
   at System.Text.EncoderFallbackBuffer.InternalFallback(ReadOnlySpan`1 chars, Int32& charsConsumed)
   at System.Text.Encoding.GetBytesWithFallback(ReadOnlySpan`1 chars, Int32 originalCharsLength, Span`1 bytes, Int32 originalBytesLength, EncoderNLS encoder)
   at System.Text.Encoding.GetBytesWithFallback(Char* pOriginalChars, Int32 originalCharCount, Byte* pOriginalBytes, Int32 originalByteCount, Int32 charsConsumedSoFar, Int32 bytesWrittenSoFar, EncoderNLS encoder)
   at System.Text.Encoding.GetBytes(Char* pChars, Int32 charCount, Byte* pBytes, Int32 byteCount, EncoderNLS encoder)
   at System.Text.EncoderNLS.GetBytes(Char* chars, Int32 charCount, Byte* bytes, Int32 byteCount, Boolean flush)
   at System.Text.EncoderNLS.GetBytes(Char[] chars, Int32 charIndex, Int32 charCount, Byte[] bytes, Int32 byteIndex, Boolean flush)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at Microsoft.PowerShell.PSConsoleReadLine.<>c__DisplayClass83_0.<WriteHistoryRange>b__0()
   at Microsoft.PowerShell.PSConsoleReadLine.WithHistoryFileMutexDo(Int32 timeout, Action action)
   at Microsoft.PowerShell.PSConsoleReadLine.WriteHistoryRange(Int32 start, Int32 end, Boolean overwritten)
   at Microsoft.PowerShell.PSConsoleReadLine.IncrementalHistoryWrite()
   at Microsoft.PowerShell.PSConsoleReadLine.MaybeAddToHistory(String result, List`1 edits, Int32 undoEditIndex, Boolean fromDifferentSession, Boolean fromInitialRead)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

### Note

<sup>I copied this issue as-is from the error and replaced the template with it.</sup>

I was looking at the issue [microsoft/terminal#190](https://github.com/microsoft/terminal/issues/190) and wanted to test for myself what happens if I input emojis on the prompt.

I ran `echo 👻` which rendered as `echo �` on the input. It errored when I hit enter but when I ran it again (using up arrow) it didn't error.

**Comment by theJasonHelmick** [comment] 2021-02-04 19:48
This is a duplicate of #949

**Closed as completed by theJasonHelmick** 2021-02-04 19:48 UTC
