### ISSUE TITLE
can't echo Emoj

### ISSUE THREAD

**Issue by kioyong** [PowerShell/PSReadLine#1572] opened 2020-06-02 08:40 UTC

**Comment by kioyong** [comment] 2020-06-02 08:43
```
echo 😀
```
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new
### Environment
PSReadLine: 2.0.0
PowerShell: 5.1.19635.1
OS: Microsoft Windows 10.0.19635
Last 200 Keys
```
 a d d Spacebar - A Enter
 g i t Spacebar s t a t u s Enter
 g i t Spacebar c o m m i t Spacebar - m Spacebar " a d d Spacebar l a y e r " Enter
 g i t Spacebar p u s h Enter
 g i t Spacebar p u l l Enter
 g i t Spacebar p u s h Enter
 g i t Spacebar s t a t u s Enter
 c l e a r Enter
 � � ☮ � � Enter
 c c l e Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace c e Backspace l e a r Enter
 � � � � � � Home e c h o Spacebar Enter
 c l e a r Enter
 c l e Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace c l e a r Enter
 e c h o s Spacebar Backspace Backspace Spacebar a Enter
 e h Backspace c h o s Backspace Spacebar � Enter

```

### Exception
```
System.Text.EncoderFallbackException: Unable to translate Unicode character \uD83D at index 5 to specified code page.
   at System.Text.EncoderExceptionFallbackBuffer.Fallback(Char charUnknown, Int32 index)
   at System.Text.EncoderFallbackBuffer.InternalFallback(Char ch, Char*& chars)
   at System.Text.UTF8Encoding.GetBytes(Char* chars, Int32 charCount, Byte* bytes, Int32 byteCount, EncoderNLS baseEncoder)
   at System.Text.EncoderNLS.GetBytes(Char[] chars, Int32 charIndex, Int32 charCount, Byte[] bytes, Int32 byteIndex, Boolean flush)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at Microsoft.PowerShell.PSConsoleReadLine.<>c__DisplayClass83_0.<WriteHistoryRange>b__0()
   at Microsoft.PowerShell.PSConsoleReadLine.WithHistoryFileMutexDo(Int32 timeout, Action action)
   at Microsoft.PowerShell.PSConsoleReadLine.MaybeAddToHistory(String result, List`1 edits, Int32 undoEditIndex, Boolean fromDifferentSession, Boolean fromInitialRead)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

#### how to reproduce
in windows Powershell, i type win + "." input a Emoji, when i type enter, will hit this error,   In Ubuntu Shell is ok

**Comment by daxian-dbw** [comment] 2020-06-04 17:58
Thanks for the reporting. This is a duplicate of #949.

**Closed as completed by daxian-dbw** 2020-06-04 17:58 UTC
Labels: Resolution-Duplicate
