### ISSUE TITLE
Error when running powershell over SSH

### ISSUE THREAD

**Issue by giggio** [PowerShell/PSReadLine#336] opened 2016-01-19 02:34 UTC
I just ran the https://github.com/PowerShell/Win32-OpenSSH/releases/tag/12_22_2015 release from OpenSSH, the 64 bit version. I created the sshd server on windows. Then, I ssh'd on a Linux VM on the same machine, then ssh'd back to Windows. It started a `cmd` session.
The log bellow showed when I ran powershell interactive, from the cmd session. Every `<ENTER>` would present the error again.
I hope it helps. If you need more info let me know.

```
-----------------------------------------------------------------------
Last 0 Keys:


Exception:
System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

**Comment by lzybkr** [comment] 2017-01-12 20:55
Most likely a dupe of #158, reopen with additional information if you disagree.

**Closed as completed by lzybkr** 2017-01-12 20:55 UTC
Labels: Resolution-Duplicate
