### ISSUE TITLE
Pushing twice F8 leads to crash in console

### ISSUE THREAD

**Issue by Schwanowski** [PowerShell/PSReadLine#1202] opened 2019-11-22 11:32 UTC
Hi there

i am using Visual Studio Code 1.41 Insider edition with Powerhell V7 latest preview and have a very strange issue.

Everything looks stable but when I try to press twice F8 to debug my scripts my console crashs entirely.

Its not related to code because when i reverse to ps ise and v5 all runs perfectly fine.

Can you please advice?

Environment data
----------------

Steps to reproduce or exception report
--------------------------------------

![grafik](https://user-images.githubusercontent.com/34173158/69422425-ebd76600-0d23-11ea-80d3-b0ba5b16d8f1.png)

[Crash.txt]

[Crash.txt](https://github.com/PowerShell/PSReadLine/files/3879307/Crash.txt)

**Comment by msftrncs** [comment] 2019-11-23 06:35
I am pretty sure this is the same as #1083, and there is no perfect solution for it yet.   It happens because the history item that you are reaching with <kbd>F8</kbd> is too long for the buffer in VS Code, and PSReadLine, when it tries to display it to you, it expects to put the cursor on the first line at the end of the matching text, the same as <kbd>CTRL</kbd>+<kbd>r</kbd> (or + <kbd>s</kbd>), but that position is not accessible from VS Code's console.

**Comment by Schwanowski** [comment] 2019-11-23 06:54
Is there a chance to clear the history?

I think I should be able to reproduce the error at least (and i will be
able to work again).

Carl Morris <notifications@github.com> schrieb am Sa., 23. Nov. 2019, 07:35:

**Comment by Schwanowski** [comment] 2019-11-23 07:22
I could fix it on my machine be uninstalling the powershell plugins and re-install them again.

Unforunately, I was not able to reproduce the issue. It seems be to related to

- a long code in the history ran by f8
- maybe a braket } error in the code

**Comment by msftrncs** [comment] 2019-11-25 02:56
Any history item longer than your VS Code buffer (in lines), should cause the problem, when you use history search commands.  This is different than <kbd>UpArrow</kbd> or <kbd>DownArrow</kbd>, as those always put the cursor on the last line.  The search functions will try to place the cursor after the match, and if that match is off the buffer in VS Code, the exception occurs.

You can also erase your history, note its location is given in `Get-PSReadLineOption'.  You could delete the file or edit the file to remove entries.

**Comment by Schwanowski** [comment] 2019-11-26 19:58
ok thank you I will figure it out

**Comment by daxian-dbw** [comment] 2019-11-27 22:09
Close as a duplicate of #1083

**Closed as completed by daxian-dbw** 2019-11-27 22:09 UTC
Labels: Resolution-Duplicate

**Comment by msftrncs** [comment] 2019-11-28 03:53
@Schwanowski, you might want to look at the `Set-PSReadLineOption` parameter `-HistorySearchCursorMovesToEnd`.   It may be a workaround for this issue, but not sure it will apply to #1083.
