### ISSUE TITLE
Cannot type any characters while capslock is on, and holding shift.

### ISSUE THREAD

**Issue by JamesLear92** [PowerShell/PSReadLine#1114] opened 2019-10-22 13:19 UTC
PS version: 5.1.18362.1
PSReadline version: 2.0.0-beta2
os: 10.0.18362.1 (WinBuild.160101.0800)
PS file version: 10.0.18362.1 (WinBuild.160101.0800)
HostName: ConsoleHost
BufferWidth: 120
BufferHeight: 3000

**Issue Description:**
When capslock is turned on, it is impossible to type a lowercase letter by holding shift; instead no letters are typed.

**Steps to reproduce:**
Turn on capslock
Hold shiftkey
Type letters

**Comment by msftrncs** [comment] 2019-10-22 16:31
I cannot reproduce this using your steps.

Almost always when I see this, its a Windows keyboard driver problem, and is fixed one of two ways, rebooting the computer, or pressing each CTRL/ALT/WIN/FN/MENU key on all attached keyboards once.  It is almost certainly not a problem with PSReadLine.  I would also expect the same issue if you open a CMD window and try typing.

**Comment by MVKozlov** [comment] 2019-10-22 18:49
#798 ?

**Comment by msftrncs** [comment] 2019-10-23 03:33
This does seem to be reproducible with PSReadline 2.0.0-Beta2, but not with 2.0.0-beta5.  It appears it was fixed by #822.

**Comment by daxian-dbw** [comment] 2019-11-11 22:42
As @msftrncs suggested, please try out the 2.0.0-beta5 version of PSReadLine from PowerShellGallery.

**Closed as completed** 2019-11-11 22:41 UTC

**Comment by OZ1** [comment] 2021-11-15 17:41
> I cannot reproduce this using your steps.
> 
> Almost always when I see this, its a Windows keyboard driver problem, and is fixed one of two ways, rebooting the computer, or pressing each CTRL/ALT/WIN/FN/MENU key on all attached keyboards once. It is almost certainly not a problem with PSReadLine. I would also expect the same issue if you open a CMD window and try typing.

CMD works fine when this issue appears in PowerShell
