### ISSUE TITLE
an error occurs when S-End C-x on empty command line

### ISSUE THREAD

**Issue by asterisk9101** [PowerShell/PSReadLine#479] opened 2016-12-03 16:09 UTC
select 0 character(S-Home, S-End, S-LeftArrow, S-RightArrow) and C-x 

```
例外:
System.ArgumentNullException: 値を Null にすることはできません。
パラメーター名:text
   場所 System.Windows.Forms.Clipboard.SetText(String text, TextDataFormat format)
   場所 Microsoft.PowerShell.PSConsoleReadLine.Cut(Nullable`1 key, Object arg)
   場所 Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   場所 Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   場所 Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

**Comment by lzybkr** [comment] 2017-11-06 03:59
Duplicate of #341.

**Closed as completed by lzybkr** 2017-11-06 03:59 UTC
Labels: Resolution-Duplicate
