### ISSUE TITLE
Bug occurred after resizing the PowerShell

### ISSUE THREAD

**Issue by Ch-sriram** [PowerShell/PSReadLine#576] opened 2017-11-09 16:47 UTC
Last 19 Keys:                Print a synopsis of nonstandard options
 Enterlag>                   Pass <flag> directly to the runtime system
 j a v a c Enter             Terminate compilation if warnings occur
 j a v a c Spacebar Backspace Backspace Backspace Backspace Backspace Backspace
PS C:\Users\sriram.ch1995\Desktop\RAM Stuff\Distributed Systems Lab Programs>
Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was 78.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender()
   at Microsoft.PowerShell.PSConsoleReadLine.BackwardDeleteChar(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by lzybkr** [comment] 2017-11-10 06:31
Dupe of #503.

**Closed as completed by lzybkr** 2017-11-10 06:31 UTC
Labels: Resolution-Duplicate
