### ISSUE TITLE
PowerShell.exe -ExecutionPolicy AllSigned

### ISSUE THREAD

**Issue by Rasmusjohnsen** [PowerShell/PSReadLine#352] opened 2016-03-08 12:01 UTC
PS Microsoft.PowerShell.Core\FileSystem::\totalwind.dk\NETLOGON> PowerShell.exe -ExecutionPolicy AllSigned
Windows PowerShell 
Copyright (C) 2015 Microsoft Corporation. All rights reserved.

Oops, something went wrong.  Please report this bug with the details below.
## Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new

Last 0 Keys:

Exception:
System.IO.IOException: Handlen er ikke gyldig.

   ved System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   ved System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   ved Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by lzybkr** [comment] 2017-01-12 20:52
Most likely a dupe of #158, reopen with additional information if you disagree.

**Comment by lzybkr** [comment] 2017-01-12 20:53
Most likely a dupe of #292, reopen with additional information if you disagree.

**Closed as completed by lzybkr** 2017-01-12 20:52 UTC
Labels: Resolution-Duplicate
