### ISSUE TITLE
System.IO.IOException

### ISSUE THREAD

**Issue by Layer8Err** [PowerShell/PSReadLine#511] opened 2017-03-01 21:56 UTC
Running PowerShell version 5.1.14393.693 in console (non-admin)
Hang after nestat -ano
----------------------------------------------------------------------------
Last 17 Keys:
 n e t s t a t Spacebar - a n o Enter
 Ctrl+v Enter
 c Ctrl+c

Exception:
System.IO.IOException: The parameter is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.ConhostConsole.set_WindowTop(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender()
   at Microsoft.PowerShell.PSConsoleReadLine.CancelLine(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.CopyOrCancelLine(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsicsengineIntrinsics)
-----------------------------------------------------------------------

**Comment by lzybkr** [comment] 2017-04-11 19:10
Most likely a dupe of #292, reopen with additional information if you disagree.

**Closed as completed by lzybkr** 2017-04-11 19:10 UTC
Labels: Resolution-Duplicate
