### ISSUE TITLE
Baby Hammering on Keyboard Produced an Exception 

### ISSUE THREAD

**Issue by b4ux1t3** [PowerShell/PSReadLine#2910] opened 2021-10-08 18:10 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
PSReadLine: 2.1.0
PowerShell: 7.1.4
OS: Microsoft Windows 10.0.19043
BufferWidth: 274
BufferHeight: 54

Last 200 Keys

 [ [ [ [ [ [ [ [ [ [ o o o O O Ctrl+, Ctrl+ю Ctrl+ю Ctrl+ю Ctrl+ю Ctrl+ю Ctrl+ю Ctrl+ю Ctrl+ю Ctrl+ю Ctrl+ю Ctrl+ю Ctrl+ю Ctrl+ю Ctrl+ю Ctrl+ю Ctrl+ю Ctrl+ю Ctrl+ю Ctrl+ю Ctrl+ю Ctrl+ю Ctrl+ю Ctrl+ю Ctrl+ю Ctrl+ю Ctrl+ю Ctrl+ю Ctrl+ю Ctrl+ю Ctrl+ю Ctrl+ю Ctrl+ю Ctrl+ю Ctrl+ю Ctrl+ю Ctrl+ю Ctrl+ю Ctrl+ю Ctrl+ю Ctrl+ю Ctrl+ю Ctrl+ю Ctrl+ю Ctrl+ю Ctrl+ю Ctrl+ю Ctrl+ю Ctrl+ю Ctrl+ю Ctrl+ю Ctrl+ю Ctrl+ю Ctrl+ю Ctrl+Ю Ctrl+Ю Ctrl+Ю Ctrl+Ю Ctrl+Ю Ctrl+Ю Ctrl+Ю Ctrl+Ю Ctrl+Ю Ctrl+Ю Ctrl+Ю Ctrl+Ю D D D D D D D D Spacebar . Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar MediaPlay Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar D D D D D D D D D D D D D D D D D D D D D D D D D D D D D Shift+Enter Escape


System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Actual value was 54.
   at System.ConsolePal.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.RevertLine(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

### Screenshot

![image](https://user-images.githubusercontent.com/5150833/136602444-2db61edd-ab33-40f4-841e-1a68d1216621.png)

### Environment data

```console
PS Version: 7.1.4
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.1.0
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 274
BufferHeight: 54
```

### Steps to reproduce

It is important to note that I have the Russian language enabled on my computer, and that part of the "baby typing" situation often involves him un(?)intentionally switching languages.

This is the 'command' that was in the process of being written at the time:

```


  xr.,,,,,,,mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm.'d=ooc[fc vv=f0o[t[[[[[[[[[[[[[[[[[[tt[t[[[[[[[[[[oooOO,юююююююююююююююююююююююююююююююююююююююююююююююююююююЮЮЮЮЮЮЮЮЮЮЮЮDDDDDDDD .                                                                             DDDDDDDDDDDDDDDDDDDDDDDDDDDDD
```

I don't know if the whitespace is important.

### Expected behavior

I'd expect to just get an error if I hit enter. I can't think of a reason a bunch of typed nonsense would make a shell throw an unhandled exception.

### Actual behavior

In this case, Enter wasn't even hit, it threw the exception in the middle of the line.

Side note: Yes, I am aware that this is _completely ridiculous_, but I could also see that this might indicate some subtle problem with PSReadLine.

**Comment by daxian-dbw** [comment] 2021-10-10 00:32
Thanks for reporting the issue. Can you consistently reproduce with that 'command' text? I cannot reproduce the issue locally ...
Can you please share your prompt function? I wonder if that can help me reproduce the issue locally.

**Comment by b4ux1t3** [comment] 2021-10-10 01:20
Oh, I hadn't thought about that!

I'm using [oh-my-posh](https://github.com/jandedobbeleer/oh-my-posh) with the `honukai` theme. I _think_ the themes are just data files that configure the prompt function, so the prompt is probably [this script](https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/src/init/omp.ps1) from their repo.

I haven't been able to reproduce it. There was a significant amount of "keyboard mashing" leading up to it. 

Let me know if the prompt function and the specific exception thrown give you any clues, I'm happy to sit the little one in front of the keyboard again (just kidding, I'll try it myself to make it more "controlled" 😉) to try to reproduce if we can narrow down some of the conditions.

I'll also dig through the prompt function to see what's going on. If you think it's a problem with how the prompt is written, I'll go file a bug over on their repo.

**Comment by daxian-dbw** [comment] 2021-11-05 06:58
@b4ux1t3 Thanks for the additional information! However, I still cannot reproduce the issue locally, and thus cannot determine what could be the root cause. Given that no further investigation can be done at this moment, I will close this issue for now. If you ran into similar issue in future, please open a new issue with as much details as possible. Thank you!

**Closed as completed by daxian-dbw** 2021-11-05 06:58 UTC
