### ISSUE TITLE
PSReadline does not handle alias removal

### ISSUE THREAD

**Issue by chrisbrownie** [PowerShell/PSReadLine#453] opened 2016-10-17 00:40 UTC
I presume this is going to fall into the "not worth fixing" basket, but here's what I'm seeing:

PowerShell starts, PSReadLine is imported. My profile removes the alias for `wget`. PSReadline still thinks `wget` is an alias of `Invoke-WebRequest` so `-o` autocompletes to `-outFile`.

After removing and reimporting the PSReadLine module, the behaviour returns to what is expected. Should PSReadLine somehow be aware of aliases being removed?

**Comment by lzybkr** [comment] 2016-10-20 01:44
Odd. I don't think this has anything to do with PSReadline. I just use an api in PowerShell to get possible completions.

I've tried a quick experiment and see some surprising behavior, not quite what you see, but similar enough. I honestly have no idea how that could happen, but the issue is most likely in PowerShell, not PSReadline.

I'd like to better understand exactly what's going on before closing, because something is definitely not quite right.

**Comment by lzybkr** [comment] 2017-11-03 06:19
I have an explanation - most of the predefined aliases in PowerShell are defined as `AllScope`. This means that the alias is **copied** into each scope that gets created.

When you removed the alias, you removed it from global scope, but not from PSReadLine's module scope.

When PSReadLine is active, it's module scope is also active, so command completion finds results in that module.

If I add the following to the top of `PSReadLine.psm1`, then it looks like the problem is fixed:

```powershell
Get-Alias -Scope 0 | ForEach-Object { Remove-Item alias:$_ -Force }
```

I could make this change to PSReadLine, but I'm not sure it's worth it - it adds about 100ms of time to startup.

Another reason I think this might not be worth it - we just removed `AllScope` from these aliases in PowerShell Core recently, see https://github.com/PowerShell/PowerShell/pull/5268. With that change, this issue should go away (though the issue will still be present in Windows PowerShell.)

As a workaround, I can offer this:

```powershell
& (gmo PSReadLine) Remove-Item alias:wget
```

Add this to your profile, or wherever you remove the `wget` alias and this will remove the alias in PSReadLine's scope, so tab completion won't find the alias anymore.

**Closed as completed by lzybkr** 2017-11-03 06:19 UTC
