### ISSUE TITLE
Exception when switching PS window to full size

### ISSUE THREAD

**Issue by SetTrend** [PowerShell/PSReadLine#393] opened 2016-05-31 22:29 UTC
Using PowerShell with elevated privileges, I clicked the Maximize button at the upper right top of the PowerShell window.

Doing this, the window width changed to the width of the desktop (1920*1200), but the height of the window was only three text lines.

So I clicked the Maximize/Restore button several times. Switching between maximized and restored mode, the window shrunk/expanded correctly, but neither a cursor nor the previously entered text was displayed. Only a blue background showed without scroll bars. After restoring the window for the second time, the scroll bars reappeard. But the vertical scrollbar showed a position of approx. line 900 of 1000 lines, although only 100 lines had been actually displayed before (it was the `icacls` help text I previously invoked).

Here's the exception that was shown to me:

```
PS C:\Windows\system32>

Leider ist ein Fehler aufgetreten. Geben Sie mit diesem Fehler folgende Details an.
Bericht auf GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Letzte 17 Tasten:
 a c a c l s Enter
 i c a c l s Enter
 k Enter
 Enter


Ausnahme:
System.IO.IOException: Falscher Parameter.

   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.Console.SetCursorPosition(Int32 left, Int32 top)
   bei Microsoft.PowerShell.PSConsoleReadLine.PlaceCursor(Int32 x, Int32& y)
   bei Microsoft.PowerShell.PSConsoleReadLine.AcceptLineImpl(Boolean validate)
   bei Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   bei Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   bei Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

It's in German, but you get the point, I guess. The exception message above reads: "System.IO.IOException: Wrong Parameter."

**Comment by lzybkr** [comment] 2017-01-12 19:50
Most likely a dupe of #292, reopen with additional information if you disagree.

**Closed as completed by lzybkr** 2017-01-12 19:50 UTC
Labels: Resolution-Duplicate
