### ISSUE TITLE
ArgumentOutOfRangeException when navigating to folder

### ISSUE THREAD

**Issue by asaff1** [PowerShell/PSReadLine#2251] opened 2021-02-25 15:18 UTC
Type 
```
cd 'C:\Program Files\ 
<Press TAB>
```
You'll get the following exception:

![image](https://user-images.githubusercontent.com/18662769/109174555-9e9b3d00-778d-11eb-8f05-485ec4438883.png)

**Comment by daxian-dbw** [comment] 2021-03-05 19:08
This is a duplicate of #1306 (`DrawMenu` issue), and was fixed. Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.

**Closed as completed by daxian-dbw** 2021-03-05 19:08 UTC
