### ISSUE TITLE
Publish Microsoft_Application gives an error when upgrading On-Premises BC16 to BC18

### ISSUE THREAD

**Issue by tmajvdlaan** [PowerShell/PSReadLine#2942] opened 2021-11-01 20:24 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
### Environment
PSReadLine: 2.1.0
PowerShell: 2021.10.2
OS: Microsoft Windows 10.0.19042
BufferWidth: 168
Parameter name: top
Actual value was 24.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.UpdateFromHistory(HistoryMoveCursor moveCursor)
   at Microsoft.PowerShell.PSConsoleReadLine.HistoryRecall(Int32 direction)
   at Microsoft.PowerShell.PSConsoleReadLine.NextHistory(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

### Screenshot

N/A

### Environment data

```console
PS Version: 5.1.19041.1237
PS HostName: Visual Studio Code Host
PSReadLine Version: 2.1.0
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 154
BufferHeight: 24
```

### Steps to reproduce

Publish-NAVApp -ServerInstance $ServerInstance -Path $PathToMicrosoft_Application

### Expected behavior

Publishing the Microsoft_Application to the new BC18-services

### Actual behavior

The publishing resulted in the above described errors.

**Comment by daxian-dbw** [comment] 2021-11-01 20:28
Duplicate of #2298

**Closed as completed by daxian-dbw** 2021-11-01 20:28 UTC
