### ISSUE TITLE
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new

### ISSUE THREAD

**Issue by petritbahtiri123** [PowerShell/PSReadLine#954] opened 2019-07-01 21:50 UTC
[Bug.txt](https://github.com/PowerShell/PSReadLine/files/3347437/Bug.txt)

Environment data
----------------

Steps to reproduce or exception report
--------------------------------------

**Comment by petritbahtiri123** [comment] 2019-07-01 21:52
[Bug.txt](https://github.com/PowerShell/PSReadLine/files/3347443/Bug.txt)

**Comment by daxian-dbw** [comment] 2019-07-15 23:40
I assume this is a duplicate of #953.

**Closed as completed by daxian-dbw** 2019-07-15 23:40 UTC
Labels: Resolution-Duplicate, OutOfRange
