### ISSUE TITLE
System.DivideByZeroException within pwsh on linux

### ISSUE THREAD

**Issue by lestephane** [PowerShell/PSReadLine#618] opened 2018-01-12 18:23 UTC
Environment data
----------------
```
# pwsh -c '
& {
    "PS version: $($PSVersionTable.PSVersion)"
    "PSReadline version: $((Get-Module PSReadline).Version)"
    if ($IsLinux -or $IsOSX) {
        "os: $(uname -a)"
    } else {
        "os: $((dir $env:SystemRoot\System32\cmd.exe).VersionInfo.FileVersion)"
    }
    "PS file version: $((dir $pshome\powershell.exe).VersionInfo.FileVersion)"
}'
PS version: 6.0.0-rc.2
PSReadline version: 
os: Linux 18227f8f3aba 4.4.108-boot2docker #1 SMP Wed Dec 27 23:32:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
dir : Cannot find path '/opt/microsoft/powershell/6.0.0-rc.2/powershell.exe' because it does not exist.
At line:10 char:26
+     "PS file version: $((dir $pshome\powershell.exe).VersionInfo.File ...
+                          ~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (/opt/microsoft/.../powershell.exe:String) [Get-ChildItem], ItemNotFoundException
+ FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand
```
Steps to reproduce or exception report
--------------------------------------
- docker run -it microsoft/vsts-agent
- in separate shell
  - docker exec -it `<id of the container just started>` /bin/bash
  - pwsh
```
PowerShell v6.0.0-rc.2
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/pscore6-docs
Type 'help' to get help.

PS /vsts> 
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 0 Keys:


Exception:
System.DivideByZeroException: Attempted to divide by zero.
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

```

**Comment by lzybkr** [comment] 2018-01-16 18:43
I didn't see any obvious places where this division could take place. If it's easy for you to debug and find the exact line, that would expedite a fix.

**Comment by lestephane** [comment] 2018-01-18 12:05
My hands are a bit full at the moment, and this is not blocking me, but i see older closed issues with the same exception type in PSReadline. I'm not a dotnet guy, so i'm not sure how to debug this... Any pointers welcome.

**Comment by camalot** [comment] 2018-01-26 04:51
Also running into this with Debian 9

```
PowerShell v6.0.1
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/pscore6-docs
Type 'help' to get help.

PS /home/jenkins>
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 0 Keys:


Exception:
System.DivideByZeroException: Attempted to divide by zero.
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

```
PS version: 6.0.1
PSReadline version: 1.2
os: Linux 12d4c04b1f0f 4.10.0-42-generic #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017 x86_64 GNU/Linux
```
Debian 9 Stretch
Also, there isn't `powershell.exe` in linux version, it is called `pwsh`


I am not sure if it is the situation, but in [Completion.cs](https://github.com/lzybkr/PSReadLine/blob/master/PSReadLine/Completion.cs#L644), there is `Rows = (matches.Count + columns - 1) / columns` which could result in `0` if `columns = 1`. And then [later on](https://github.com/lzybkr/PSReadLine/blob/master/PSReadLine/Completion.cs#L592) is `ColumnWidth * (selectedItem / Rows)`, which would result in a `division by 0`.

I did not see anything specific in `PSConsoleReadLine`.

I will add, this does seem promising, because completion of arguments is not working.


----

More information.

It only happens if I launch directly in to `pwsh`. if I launch `/bin/bash` then `pwsh`, i do not get the error.

**Comment by joachimaumann** [comment] 2018-03-16 09:52
Have the same issue with the vsts container as described by @lestephane .
Container I use getting the issue: https://github.com/microsoft/vsts-agent-docker/blob/3a81525044b23e87b75d3f6b4c7e4feb2d0dca3e/ubuntu/16.04/tfs/2017-u1/standard/Dockerfile

Its blocking us because we could not use azure powershell sdk https://docs.microsoft.com/de-de/powershell/azure/install-azurermps-maclinux?view=azurermps-5.5.0

could you please look into this

**Comment by daxian-dbw** [comment] 2018-03-16 19:42
I tried on a Debian 9 container, and couldn't reproduce the crash. Never tried on VSTS container though.
```
root@1ed6879ac3d8:/# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@1ed6879ac3d8:/# 
root@1ed6879ac3d8:/# pwsh
PowerShell v6.0.2
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/pscore6-docs
Type 'help' to get help.

PS /> gmo

ModuleType Version    Name                                ExportedCommands                         
---------- -------    ----                                ----------------                         
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable,...
Script     2.0.0      PSReadLine                          {Get-PSReadLineKeyHandler, Get-PSReadL...
```
One thing to point out, the crash posted by @camalot at https://github.com/lzybkr/PSReadLine/issues/618#issuecomment-360683929 is with PSReadline 1.2.

**Comment by joachimaumann** [comment] 2018-03-19 07:31
@daxian-dbw  I added the container link which I can reproduce the issue

**Comment by daxian-dbw** [comment] 2018-03-31 05:30
@joachimaumann I cannot reproduce the crash with the docker image `microsoft/vsts-agent`.
Could this be related to the host OS? Can you please provide detailed repro steps?
Please see the screenshot below:

![image](https://user-images.githubusercontent.com/127450/38159984-b0d1b5d6-3469-11e8-9869-0fcd7ae172fe.png)

**Comment by lestephane** [comment] 2018-04-01 15:43
I'm not longer able to reproduce with the latest image
```
REPOSITORY                             TAG                 IMAGE ID            CREATED             SIZE
microsoft/vsts-agent                   latest              3b66c4a0d020        5 days ago          5.72GB
```

**Comment by lzybkr** [comment] 2018-04-01 18:35
So OK to close?

**Comment by lestephane** [comment] 2018-04-02 08:38
As far as I'm concerned, yes.

**Comment by lzybkr** [comment] 2018-04-03 04:39
OK, closing.

**Closed as completed by lzybkr** 2018-04-03 04:39 UTC
