### ISSUE TITLE
Set ViModeIndicator with different values has same result

### ISSUE THREAD

**Issue by roachsinai** [PowerShell/PSReadLine#3159] opened 2022-01-14 15:41 UTC
### Prerequisites

- [X] Write a descriptive title.

### Issue summary

I can define a right prompt of vi-mode of zsh in my WSL like below:

![image](https://user-images.githubusercontent.com/9500049/149541976-b64d41f7-0a89-4449-ac13-70c81b59c3ea.png)

I found a vi mode releated option in PSReadLine is `ViModeIndicator ` but set it to cursor, prompt I get same result with None. All only has a block blink on last char:

![image](https://user-images.githubusercontent.com/9500049/149542382-d1f2a8f0-f198-4a47-a99d-4fe6d5e7d381.png)

Is there a way to get same result like zsh in WSL?

---

By the way, in vi mode of PSReadLine, after press `ESC` and trigger `v` I can edit command in Vim. But After trigger `:wq` in vim I just exit Vim and still in powershell vi mode.

Is there a way to exit vi mode to after exit Vim, then I can directly press `Enter` to run current command. For now I have to switch to insert mode to run command.

Thanks in advance!

**Comment by gwojan** [comment] 2022-01-14 22:08
@roachsinai are you using the Windows Terminal for PowerShell/PSReadLine customization? In my experience the cursor customization ability with shells running atop `conhost.exe` is less than stellar.

I currently have in my `profile.ps1`

```PowerShell
$OnViModeChange = [scriptblock]{
    if ($args[0] -eq 'Command') {
        # Set the cursor to a blinking block.
        Write-Host -NoNewLine "`e[1 q"
    }
    else {
        # Set the cursor to a blinking line.
        Write-Host -NoNewLine "`e[5 q"
    }
}

Set-PsReadLineOption -EditMode Vi
Set-PSReadLineOption -ViModeIndicator Script -ViModeChangeHandler $OnViModeChange
```

This displays a blinking line while in `insert mode` and a block cursor while in `normal mode`.

Is that the behavior you're looking for?

With respect to your question about editing command lines inside `vim` it works just as you describe for me. I rely on that capability every day.

My `profile.ps1` defines

```PowerShell
$env:EDITOR = $env:VISUAL = 'nvim'
```

The behavior I see is:

* edit a command or recall command from history
* press `Esc` to enter vi normal mode
* press `v` and the command line is loaded into `vim/neovim`
* make changes
* press `wq` and return the edited command to the current PowerShell command line
* press `Enter` to execute the command

The only difference I see in the PowerShell/PSReadLine behavior and the same functionality under a Linux distro is in PowerShell I'm required to press `Enter` to execute the edited command line where under Linux pressing `wq` returns the command and executes it immediately.

Is there something I'm missing?

**Comment by roachsinai** [comment] 2022-01-17 01:20
@gwojan thanks for your help! I'm using Windows Terminal, but

```
$OnViModeChange = [scriptblock]{
    if ($args[0] -eq 'Command') {
        # Set the cursor to a blinking block.
        Write-Host -NoNewLine "`e[1 q"
    }
    else {
        # Set the cursor to a blinking line.
        Write-Host -NoNewLine "`e[5 q"
    }
}

Set-PsReadLineOption -EditMode Vi
Set-PSReadLineOption -ViModeIndicator Script -ViModeChangeHandler $OnViModeChange
```

seems not work well for me.

![image](https://user-images.githubusercontent.com/9500049/149686509-883a0835-a1fb-4d50-af07-ffb5b82f0385.png)

As above image shows after I pres `Esc`， Windows Terminal only return characters: `e[1 q`.

**Comment by roachsinai** [comment] 2022-01-17 02:19
Maybe https://github.com/PowerShell/PSReadLine/issues/1596#issuecomment-641679337 could be some help.

**Comment by Drllap** [comment] 2022-01-18 01:01
I'm having the same issue as @roachsinai showes in
![](https://user-images.githubusercontent.com/9500049/149686509-883a0835-a1fb-4d50-af07-ffb5b82f0385.png)

The `e[1 q` is just printed instead of the cursor changes.

I just updated the PSReadLine module to the newest prerealease, 2.2.0 beta something. I'm pretty sure this used to work before that.

**Comment by roachsinai** [comment] 2022-01-18 01:23
@Drllap Yeah, I'm using 2.2.0, too.

**Comment by gwojan** [comment] 2022-01-18 01:51
I'm sorry @roachsinai. I guess I should have mentioned I'm using the latest beta of `PSReadLine` AND PowerShell 7+.

If you're using Windows PowerShell 5.1 it doesn't support the "`e" VT character constant. I have to do something like

```
$ESC = "$([char]0x1b)"
$OnViModeChange = [scriptblock] {
    if ($args[0] -eq 'Command') {
        # Set the cursor to a blinking block.
        Write-Host -NoNewLine "${ESC}[1 q"
    }
    else {
        # Set the cursor to a blinking line.
        Write-Host -NoNewLine "${ESC}[5 q"
    }
}
```
Unfortunately, I just realized the change from `bar` to `block` cursor doesn't appear to be working under Windows PowerShell 5.1. I apologize for the confusion.

**Comment by roachsinai** [comment] 2022-01-18 01:59
@gwojan Thanks you so much for this clarification!

It will be great if PS 5.1 support right prompt which work combine with your method (maybe it support, but I didn't find the docs).

**Comment by Drllap** [comment] 2022-01-18 20:50
@gwojan ![](https://media.makeameme.org/created/you-are-a-5c9ab2.jpg)

**Comment by daxian-dbw** [comment] 2022-01-18 21:40
Close this issue as a duplicate of https://github.com/PowerShell/PSReadLine/issues/1233

**Closed as completed by daxian-dbw** 2022-01-18 21:40 UTC
