### ISSUE TITLE
PowerShell Exception: System.IO.IOException

### ISSUE THREAD

**Issue by sedwardstx** [PowerShell/PSReadLine#449] opened 2016-10-03 19:40 UTC
Oops, something went wrong.  Please report this bug with the details below.
## Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new

Last 6 Keys:
 Ctrl+v Enter
 UpArrow Enter
 Enter
 LeftArrow

Exception:
System.IO.IOException: The parameter is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.SetCursorPosition(Int32 cursor)
   at Microsoft.PowerShell.PSConsoleReadLine.BackwardChar(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()

**Comment by lzybkr** [comment] 2017-01-12 19:55
Most likely a dupe of #292, reopen with additional information if you disagree.

**Closed as completed by lzybkr** 2017-01-12 19:55 UTC
Labels: Resolution-Duplicate
