### ISSUE TITLE
System.PlatformNotSupportedException: when trying to ssh into ubuntu

### ISSUE THREAD

**Issue by mcorning** [PowerShell/PSReadLine#856] opened 2019-02-12 20:18 UTC
At the end of the Azure Quickstart for Ubuntu, i fail when attempting to ssh.

PS Azure:\> ssh azureuser@10.111.12.123
ssh: connect to host 10.111.12.123 port 22: Connection timed out
Azure:/
PS Azure:\>
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
```
 s o u r c e G r o u p N a m e Space " m y R e s o u r c e G r o u p " Space | SpaceS e l e c t Space " I p A d d r e s s " Enter
 s s h Space a z u r e u s e r @ 1 0 . 1 1 1 . 1 2 . 1 2 3 Enter
 s u d o Space a p t - g e t Space - y Space u p d a t e Enter
 s u d o Space a p t - g e t Space - y Space i n s t a l l Space n g i n x BackspaceBackspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace BackspaceBackspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace BackspaceBackspace s s h Space a z u r e u s e r @ 1 0 . 1 1 1 . 1 2 . 1 2 3 Enter
 PageUp
```

Exception:
```
System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.ConsolePal.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ScrollDisplayUp(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```
-----------------------------------------------------------------------
Azure:/
PS Azure:\>

**Comment by SteveL-MSFT** [comment] 2019-06-18 22:07
Based on the keys and the error message, this appears to be a dupe of https://github.com/powershell/psreadline/issues/700

**Closed as completed by SteveL-MSFT** 2019-06-18 22:07 UTC
Labels: Resolution-Duplicate
