### ISSUE TITLE
Exception: System.IO.IOException: The handle is invalid.

### ISSUE THREAD

**Issue by hsluoyz** [PowerShell/PSReadLine#435] opened 2016-08-31 12:04 UTC
I run `start-process powershell -ArgumentList '-NoExit -noprofile -file J:\npcap\installer\DiagReport.ps1 -verb RunAs' -RedirectStandardOutput J:\npcap\installer\1234.txt`

Then the content of `1234.txt` is:

```
Windows PowerShell 
Copyright (C) 2015 Microsoft Corporation. All rights reserved.


Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 1 Keys:
 Enter


Exception:
System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.PlaceCursor(Int32 x, Int32& y)
   at Microsoft.PowerShell.PSConsoleReadLine.AcceptLineImpl(Boolean validate)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

My OS:

```
*************************************************
OS Info:
*************************************************
Caption:             Microsoft Windows 10 Pro
BuildNumber:             10586
Locale:              0409
MUILanguages:            en-US
OSArchitecture:          64-bit
ServicePackMajorVersion:     0
ServicePackMinorVersion:     0
SystemDirectory:         C:\Windows\system32
Version:             10.0.10586
```

My script `DiagReport.ps1`:

``` powershell
$report_file_name = $MyInvocation.MyCommand.Definition.Replace(".ps1", ".txt")

# $ErrorActionPreference="SilentlyContinue"
# Stop-Transcript | Out-Null
# $ErrorActionPreference = "Continue"
# Start-Transcript -IncludeInvocationHeader -Path $report_file_name

function write_report($text)
{
    Write-Host $text
    Write-Output $text
    $text >> STDOUT
    # Write-Output $text | Out-File -Append -FilePath $report_file_name
}

function get_script_bit()
{
    if ([IntPtr]::Size -eq 8)
    {
        '64-bit'
    }
    else
    {
        '32-bit'
    }
}

function get_os_bit()
{
    return (Get-WmiObject Win32_OperatingSystem).OSArchitecture
}

function get_winpcap_mode()
{
    return (Get-Item HKLM:\SYSTEM\CurrentControlSet\Services\npcap).GetValue("WinPcapCompatible")
}

$os_bit = get_os_bit
$winpcap_mode = get_winpcap_mode


write_report ("*************************************************")
write_report "DiagReport for Npcap ( http://npcap.org )"
write_report ("*************************************************")
write_report "Script Architecture:`t`t", (get_script_bit)
write_report "Current Time:`t`t`t", (Get-Date)
write_report "Npcap Version:`t`t`t", ([System.Diagnostics.FileVersionInfo]::GetVersionInfo("C:\Program Files\Npcap\NPFInstall.exe").FileVersion)

#########################################################
write_report ("`n")
write_report ("*************************************************")
write_report ("OS Info:")
write_report ("*************************************************")
write_report "Caption:`t`t`t", (Get-WmiObject Win32_OperatingSystem).Caption
write_report "BuildNumber:`t`t`t", (Get-WmiObject Win32_OperatingSystem).BuildNumber
#write_report "BuildType:`t`t`t`t`, (Get-WmiObject Win32_OperatingSystem).BuildType
write_report "Locale:`t`t`t`t", (Get-WmiObject Win32_OperatingSystem).Locale
write_report "MUILanguages:`t`t`t", (Get-WmiObject Win32_OperatingSystem).MUILanguages
write_report "OSArchitecture:`t`t`t", (Get-WmiObject Win32_OperatingSystem).OSArchitecture
write_report "ServicePackMajorVersion:`t", (Get-WmiObject Win32_OperatingSystem).ServicePackMajorVersion
write_report "ServicePackMinorVersion:`t", (Get-WmiObject Win32_OperatingSystem).ServicePackMinorVersion
write_report "SystemDirectory:`t`t", (Get-WmiObject Win32_OperatingSystem).SystemDirectory
write_report "Version:`t`t`t", (Get-WmiObject Win32_OperatingSystem).Version

#########################################################
write_report ("`n")
"*************************************************"
write_report ("File Info:")
write_report ("*************************************************")

dir "C:\Program Files\Npcap\"

dir "C:\Windows\System32\" NpcapHelper.exe
dir "C:\Windows\System32\" Packet.dll
dir "C:\Windows\System32\" WlanHelper.exe
dir "C:\Windows\System32\" wpcap.dll
dir "C:\Windows\System32\Npcap\"

dir "C:\Windows\SysWOW64\" NpcapHelper.exe
dir "C:\Windows\SysWOW64\" Packet.dll
dir "C:\Windows\SysWOW64\" WlanHelper.exe
dir "C:\Windows\SysWOW64\" wpcap.dll
dir "C:\Windows\SysWOW64\Npcap\"

#########################################################
write_report ("`n")
write_report ("*************************************************")
write_report ("Registry Info:")
write_report ("*************************************************")

if ($os_bit -eq "32-bit")
{
    write_report ("HKLM:\SOFTWARE\Npcap:")
    (Get-ItemProperty HKLM:\SOFTWARE\Npcap | out-string -stream | ? { $_ -NOTMATCH '^ps.+' })
}
else
{
    write_report ("HKLM:\SOFTWARE\WOW6432Node\Npcap:")
    (Get-ItemProperty HKLM:\SOFTWARE\WOW6432Node\Npcap | out-string -stream | ? { $_ -NOTMATCH '^ps.+' })
}

write_report ("HKLM:\SYSTEM\CurrentControlSet\Services\npcap:")
(Get-ItemProperty HKLM:\SYSTEM\CurrentControlSet\Services\npcap | out-string -stream | ? { $_ -NOTMATCH '^ps.+' })
write_report ("HKLM:\SYSTEM\CurrentControlSet\Services\npcap_wifi:")
(Get-ItemProperty HKLM:\SYSTEM\CurrentControlSet\Services\npcap_wifi | out-string -stream | ? { $_ -NOTMATCH '^ps.+' })

if ($winpcap_mode -eq 1)
{
    write_report ("HKLM:\SYSTEM\CurrentControlSet\Services\npf:")
    (Get-ItemProperty HKLM:\SYSTEM\CurrentControlSet\Services\npf | out-string -stream | ? { $_ -NOTMATCH '^ps.+' })
    write_report ("HKLM:\SYSTEM\CurrentControlSet\Services\npf_wifi:")
    (Get-ItemProperty HKLM:\SYSTEM\CurrentControlSet\Services\npf_wifi | out-string -stream | ? { $_ -NOTMATCH '^ps.+' })
}

#########################################################
write_report ("`n")
write_report ("*************************************************")
write_report ("Service Info:")
write_report ("*************************************************")

Get-Service npcap

if ($winpcap_mode)
{
    Get-Service npf
}

#########################################################
write_report ("`n")
write_report ("*************************************************")
write_report ("Install Info:")
write_report ("*************************************************")

write_report ("Please refer to: C:\Program Files\Npcap\install.log")

# Stop-Transcript
```

**Comment by lzybkr** [comment] 2017-01-12 19:56
Most likely a dupe of #158, reopen with additional information if you disagree.

**Closed as completed by lzybkr** 2017-01-12 19:56 UTC
Labels: Resolution-Duplicate
