### ISSUE TITLE
Command line text is displayed at the bottom of the console instead of where the prompt is displayed

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PSReadLine#1682] opened 2020-07-22 18:09 UTC
## Environment

```none
PS version: 7.1.0-preview.5
PSReadline version: 2.1.0-beta2
os: 10.0.19041.1 (WinBuild.160101.0800)
PS file version: 7.1.0.0
HostName: ConsoleHost (Windows Terminal)
BufferWidth: 120
BufferHeight: 50
```
I'm also on `Windows Terminal Preview Version: 1.2.2022.0` and was using `Windows Package Manager v0.1.41821 Preview`

## Exception report

N/A

## Steps to reproduce

I have not figured out the repro steps yet. When this happened, this was my complete history right before I started typing `gsv`:
```
   1        0.002 cd .\Git\KLM\
   2        1.949 Get-ComputerInfo OSVersion,WindowsUBR
   3        0.040 dir
   4        3.492 winget search mumblemumble
   5        0.599 winget search instruments
   6        0.623 winget search keysight
   7        0.603 winget search mumblemumble
   8        0.612 winget search mumblemumble
   9        0.602 winget search mumblemumble
  10        0.620 winget search license
  11        0.609 winget search manager
  12        0.606 winget search Conan
  13        0.606 winget search JFrog
```
FWIW, I've seen this before but not this bad.  When it happened previously the text was only a few (2-4) lines below the prompt.

## Expected behavior

The command I type should always be on the line that displays the prompt.

## Actual behavior

![image](https://user-images.githubusercontent.com/5177512/88211465-fc254500-cc12-11ea-8b6b-98bd0aa759cd.png)

**Comment by daxian-dbw** [comment] 2020-07-25 23:36
@rkeithhill Was there a resizing before this happened?

**Comment by rkeithhill** [comment] 2020-07-26 00:12
I don't think so.  I mean I don't normally resize my window but I might have been experimenting with full-screen mode in Windows Terminal at the time.  That said, I can't repro this right now going in and out of full-screen mode.

**Comment by daxian-dbw** [comment] 2020-11-30 23:00
Close as a duplicate of #1456

**Closed as completed by daxian-dbw** 2020-11-30 23:00 UTC
Labels: Needs-Repro
