### ISSUE TITLE
git pager doesn't render escape codes with latest release of PSReadLine

### ISSUE THREAD

**Issue by gwojan** [PowerShell/PSReadLine#602] opened 2017-12-04 18:57 UTC
I ran across this by pure chance. If ```$env:LESS``` is defined git will automatically use it's internal version of ```less``` with operations like ```git log -1```.

Environment data
----------------
PS version: 6.1.0-preview.503
PSReadline version: 2.0
os: 10.0.15063.0 (WinBuild.160101.0800)
PS file version: 6.1.0

Steps to reproduce or exception report
--------------------------------------
```git log -1```

results:
![image](https://user-images.githubusercontent.com/6855215/33570306-6211f84a-d8fa-11e7-8fb9-e1bf20a9a7bc.png)

```git --no-pager log -1```

results:
![image](https://user-images.githubusercontent.com/6855215/33570444-dbbfc5e6-d8fa-11e7-983b-c484b81ce436.png)

**Comment by bgshacklett** [comment] 2017-12-05 02:57
I'm unable to reproduce this as well. ~I'll see if I can get my hands on an older release of Windows to test on.~

edit: I had my versions mixed up.  I appear to be on the same version of Windows. Can you give us any further details about your setup? Are you running mintty or anything else? Can you reproduce this if you hit `Win+R` and launch `powershell.exe` or `pwsh.exe`?

**Comment by gwojan** [comment] 2017-12-05 14:42
@bgshacklett Do you have ```$env:LESS``` set in your environment? If not, try: ``` $env:LESS = '-i'```

**Comment by lzybkr** [comment] 2017-12-05 15:40
Closing - I can repro this from cmd - no PowerShell involved, so this seems like a git or Cygwin problem.

**Closed as completed by lzybkr** 2017-12-05 15:40 UTC

**Comment by gwojan** [comment] 2017-12-05 17:26
@lzybkr Le sigh... I keep forgetting there is another shell I can test with. 😉 

The reason I never hit the problem with cmd.exe is the LESS variable is defined in my PowerShell profile. Thanks for setting me straight!

**Comment by bgshacklett** [comment] 2017-12-05 18:33
> @bgshacklett Do you have `$env:LESS` set in your environment? If not, try: `$env:LESS = '-i'`

@gwojan For future reference, it would have been helpful in the "steps to reproduce"  section.

**Comment by lzybkr** [comment] 2017-12-05 20:05
I figured it out, but didn't know that the env var was to set default options.

I tried `$env:LESS = 'less.exe' first and saw a weird error, then the repro. So it was sufficient, but an exact repro would have been even more helpful.

**Comment by gwojan** [comment] 2017-12-13 17:53
@lzybkr, @bgshacklett Okay, so I figured out how to make the git pager behave under conhost.exe... It seems there is an option to output raw control characters ```-r```.

Setting ```$env:LESS='-ir'``` is the magic incantation...
