### ISSUE TITLE
ArgumentOutOfRangeException while pressing Ctrl+v

### ISSUE THREAD

**Issue by scegg** [PowerShell/PSReadLine#834] opened 2018-12-16 05:18 UTC
PS version: 5.1.17763.134
PSReadline version: 2.0.0-beta2
os: 10.0.17763.1 (WinBuild.160101.0800)
PS file version: 10.0.17763.1 (WinBuild.160101.0800)

I start my PS instance, press Ctrl+v to paste 4 lines command. Then I got this before text pasted.

```PS D:\Downloaded\ImageStore>
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 1 Keys:
 Ctrl+v

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Paste(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

**Comment by Vogel612** [comment] 2019-01-02 23:37
Can repro, seems highly related to #663, which is the same issue for non-windows OSes it seems

**Comment by daxian-dbw** [comment] 2019-07-18 23:43
Close as a duplicate of #663

**Closed as completed by daxian-dbw** 2019-07-18 23:43 UTC
Labels: Resolution-Duplicate, OutOfRange
