### ISSUE TITLE
💡 Failed to parse Unicode of emoticons 💡

### ISSUE THREAD

**Issue by AbhijithGanesh** [PowerShell/PSReadLine#4048] opened 2024-06-22 13:44 UTC
### Exception report
PS fails to parse emoticons

Heyy devs, I was using PS and I tried to add "💡" as a part of my git commits and I thought git broke but I realized PS broke and asked me to create an issue. I'd like to fix this if it is not very hard.

### Screenshot

![image](https://github.com/PowerShell/PSReadLine/assets/67182544/72059a06-45b5-492c-b616-b01bdc96ade2)

### Environment data

```console
### Environment
PSReadLine: 2.0.0
PowerShell: 5.1.22621.3672
OS: Microsoft Windows 10.0.22631
Last 200 Keys
```

### Steps to reproduce

```sh
mkdir sample
cd sample
touch input.txt
git add input.txt
git commit -m "Initial commit💡"
```

### Expected behavior

Should allow me to commit/should understand that I am trying to input unicode emoticons

### Actual behavior

Breaks due to this exception:

```
System.Text.EncoderFallbackException: Unable to translate Unicode character \uD83D at index 1 to specified code page.
   at System.Text.EncoderExceptionFallbackBuffer.Fallback(Char charUnknown, Int32 index)
   at System.Text.EncoderFallbackBuffer.InternalFallback(Char ch, Char*& chars)
   at System.Text.UTF8Encoding.GetBytes(Char* chars, Int32 charCount, Byte* bytes, Int32 byteCount, EncoderNLS baseEncoder)
   at System.Text.EncoderNLS.GetBytes(Char[] chars, Int32 charIndex, Int32 charCount, Byte[] bytes, Int32 byteIndex, Boolean flush)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at Microsoft.PowerShell.PSConsoleReadLine.<>c__DisplayClass83_0.<WriteHistoryRange>b__0()
   at Microsoft.PowerShell.PSConsoleReadLine.WithHistoryFileMutexDo(Int32 timeout, Action action)
   at Microsoft.PowerShell.PSConsoleReadLine.MaybeAddToHistory(String result, List`1 edits, Int32 undoEditIndex, Boolean fromDifferentSession, Boolean fromInitialRead)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

**Comment by AbhijithGanesh** [comment] 2024-06-22 13:45
I'd like to work on this issue and fix it myself, I am already a party to the Microsoft CLA and I am a previous contributor to [Data API Builder](https://github.com/azure/data-api-builder)

**Comment by daxian-dbw** [comment] 2024-06-24 21:26
This is an issue with the VSCode terminal -- only the high surrogate of the surrogate pair representing that emoji gets pasted into the read-line buffer of PSReadLine. This could be because you are on an old version of Windows. See the following 2 comments for more information
- https://github.com/PowerShell/PSReadLine/issues/3832#issuecomment-1766839454
- https://github.com/PowerShell/PSReadLine/issues/3832#issuecomment-1781770311

Will close as a duplicate of #3832

**Closed as completed by daxian-dbw** 2024-06-24 21:26 UTC
