### ISSUE TITLE
Invoking powershell.exe from 32 Bit process caues this Bug on Windows 10

### ISSUE THREAD

**Issue by jaimin76** [PowerShell/PSReadLine#295] opened 2015-10-19 23:26 UTC
Last 0 Keys:

Exception:

System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)

   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)

   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

---

**Comment by lzybkr** [comment] 2015-12-02 21:08
This looks like a dupe of #158. If you think otherwise, I need more repro details.

**Closed as completed by lzybkr** 2015-12-02 21:08 UTC
Labels: Issue-Bug, Resolution-Duplicate
