### ISSUE TITLE
PowerShell 7 default terminal blank screen after Win+Left (window snap)

### ISSUE THREAD

**Issue by dyota257** [PowerShell/PSReadLine#2827] opened 2021-09-07 16:00 UTC
### Environment
PSReadLine: 2.1.0
PowerShell: 7.1.4
OS: Microsoft Windows 10.0.19043
BufferWidth: 117
BufferHeight: 9001

Last 84 Keys
```
 z Spacebar b o a r d m Backspace - m e e t i n g s Enter
 Spacebar Backspace z Spacebar Backspace Backspace Backspace z Spacebar Backspace Backspace Backspace z Spacebar o n e d r i v e Tab \ Backspace Backspace \ w r e Tab Backspace Backspace Backspace d y o t a Tab w r e s Tab b o a r Tab Enter
 a s d f s d f Shift+Home Backspace LeftWindows UpArrow LeftWindows c UpArrow
```

### Exception
```
System.IO.IOException: The parameter is incorrect.
   at System.ConsolePal.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.CalculateWhereAndWhatToRender(Boolean cursorMovedToInitialPos, RenderData renderData, LineInfoForRendering& lineInfoForRendering)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.UpdateFromHistory(HistoryMoveCursor moveCursor)
   at Microsoft.PowerShell.PSConsoleReadLine.HistoryRecall(Int32 direction)
   at Microsoft.PowerShell.PSConsoleReadLine.PreviousHistory(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)

-->

## Exception report

<!-- Copy and paste the keys and the exception stack trace printed by PSReadLine, if there is any -->

## Steps to reproduce

Pressed Win+Left to snap the window to the left side of the screen. 

## Expected behavior

Expect the text to remain in the window and for PSReadLine to not throw an error. 

## Actual behavior

PS window went all black. Text reappeared wehn returned to Maximised condition.

**Comment by daxian-dbw** [comment] 2021-09-09 23:45
I cannot reproduce the issue. Can you please provide repro steps?

**Comment by daxian-dbw** [comment] 2021-09-16 17:41
@dyota257 I believe you went from "maximized" to "window-on-the-right" using <kbd>win+right</kbd> (well, both <kbd>win+left</kbd> and <kbd>win+right</kbd> show as the `LeftWindows` keystroke), right? This looks like a duplicate of #2044

This is a problem of the console host. `CMD.exe` shows the same behavior in the console host -- it went black screen when snapping the windows from max-size to window-on-the-right. Windows terminal works fine though, so please give Windows Terminal a try -- you will get way better experience with it.

**Closed as completed by daxian-dbw** 2021-09-16 17:41 UTC
Labels: Resolution-Duplicate
