### ISSUE TITLE
`Cannot process argument because the value of argument "name" is not valid` after using namespace wrongly

### ISSUE THREAD

**Issue by ALiwoto** [PowerShell/PSReadLine#3674] opened 2023-05-07 06:34 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.yaml
Thank you!

### Environment
PSReadLine: 2.2.6
PowerShell: 7.3.2
OS: Microsoft Windows 10.0.19042
BufferWidth: 120
BufferHeight: 9001

Last 45 Keys:

 c a s Backspace Backspace Backspace o k Enter
 Ctrl+v Enter
 Enter
 o k Enter
 a Enter
 ; UpArrow Backspace Backspace ; Enter
 a Enter
 h e l p Enter
 UpArrow UpArrow UpArrow UpArrow Enter
 Ctrl+v u s i n g Spacebar RightArrow Enter
 Ctrl+v

### Exception

System.Management.Automation.PSArgumentException: Cannot process argument because the value of argument "name" is not valid. Change the value of the "name" argument and run the operation again.
   at System.Management.Automation.Language.TypeName..ctor(IScriptExtent extent, String name)
   at System.Management.Automation.Language.TypeResolver.ResolveTypeNameWithContext(TypeName typeName, Exception& exception, Assembly[] assemblies, TypeResolutionState typeResolutionState)
   at System.Management.Automation.Language.SymbolResolver.VisitTypeName(TypeName typeName, Int32 genericArgumentCount, Boolean isAttribute)
   at System.Management.Automation.Language.SymbolResolver.VisitTypeConstraint(TypeConstraintAst typeConstraintAst)
   at System.Management.Automation.Language.TypeConstraintAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.ConvertExpressionAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.CommandExpressionAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.PipelineAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.ParenExpressionAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.InvokeMemberExpressionAst.InternalVisitChildren(AstVisitor visitor)
   at System.Management.Automation.Language.InvokeMemberExpressionAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.CommandExpressionAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.PipelineAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.StatementBlockAst.InternalVisit(AstVisitor visitor, ReadOnlyCollection`1 traps, ReadOnlyCollection`1 statements, AstVisitAction action)
   at System.Management.Automation.Language.NamedBlockAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.ScriptBlockAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.SymbolResolver.ResolveSymbols(Parser parser, ScriptBlockAst scriptBlockAst)
   at System.Management.Automation.Language.ScriptBlockAst.PerformPostParseChecks(Parser parser)
   at System.Management.Automation.Language.Parser.ParseTask(String fileName, String input, List`1 tokenList, Boolean recursed, ParseMode parseMode)
   at System.Management.Automation.Language.Parser.Parse(String fileName, String input, List`1 tokenList, ParseError[]& errors, ParseMode parseMode)
   at System.Management.Automation.Language.Parser.ParseInput(String input, String fileName, Token[]& tokens, ParseError[]& errors)
```

### Screenshot

N/A

### Environment data

```console
Actually, I couldn't paste this into the powershell session where I ran into the problem, because pasting code will no longer work! (if I paste any other code inside of powershell besides this, I will get the exact output as this; but here is the output anyway):


Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.yaml
Thank you!

### Environment
PSReadLine: 2.2.6
PowerShell: 7.3.2
OS: Microsoft Windows 10.0.19042
BufferWidth: 120
BufferHeight: 9001

Last 36 Keys:

 c a s Backspace Backspace Backspace o k Enter
 Ctrl+v Enter
 Enter
 o k Enter
 a Enter
 ; UpArrow Backspace Backspace ; Enter
 a Enter
 h e l p Enter
 UpArrow UpArrow UpArrow UpArrow Enter
 Ctrl+v

### Exception

System.Management.Automation.PSArgumentException: Cannot process argument because the value of argument "name" is not valid. Change the value of the "name" argument and run the operation again.
   at System.Management.Automation.Language.TypeName..ctor(IScriptExtent extent, String name)
   at System.Management.Automation.Language.TypeResolver.ResolveTypeNameWithContext(TypeName typeName, Exception& exception, Assembly[] assemblies, TypeResolutionState typeResolutionState)
   at System.Management.Automation.Language.SymbolResolver.VisitTypeName(TypeName typeName, Int32 genericArgumentCount, Boolean isAttribute)
   at System.Management.Automation.Language.SymbolResolver.VisitTypeExpression(TypeExpressionAst typeExpressionAst)
   at System.Management.Automation.Language.TypeExpressionAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.MemberExpressionAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.CommandExpressionAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.PipelineAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.StatementBlockAst.InternalVisit(AstVisitor visitor, ReadOnlyCollection`1 traps, ReadOnlyCollection`1 statements, AstVisitAction action)
   at System.Management.Automation.Language.StatementBlockAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.SubExpressionAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.ExpandableStringExpressionAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.CommandAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.PipelineAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.StatementBlockAst.InternalVisit(AstVisitor visitor, ReadOnlyCollection`1 traps, ReadOnlyCollection`1 statements, AstVisitAction action)
   at System.Management.Automation.Language.NamedBlockAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.ScriptBlockAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.ScriptBlockExpressionAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.CommandAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.PipelineAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.StatementBlockAst.InternalVisit(AstVisitor visitor, ReadOnlyCollection`1 traps, ReadOnlyCollection`1 statements, AstVisitAction action)
   at System.Management.Automation.Language.NamedBlockAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.ScriptBlockAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.SymbolResolver.ResolveSymbols(Parser parser, ScriptBlockAst scriptBlockAst)
   at System.Management.Automation.Language.ScriptBlockAst.PerformPostParseChecks(Parser parser)
   at System.Management.Automation.Language.Parser.ParseTask(String fileName, String input, List`1 tokenList, Boolean recursed, ParseMode parseMode)
   at System.Management.Automation.Language.Parser.Parse(String fileName, String input, List`1 tokenList, ParseError[]& errors, ParseMode parseMode)
   at System.Management.Automation.Language.Parser.ParseInput(String input, String fileName, Token[]& tokens, ParseError[]& errors)
```

### Steps to reproduce

1. Open a new powershell session and write the following: `using namespace [Security.Principal]`
2. Now paste a piece of code, for example this one:
```ps1
([WindowsPrincipal][WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] "Administrator"))
```
You will see this exception appearing:
`System.Management.Automation.PSArgumentException: Cannot process argument because the value of argument "name" is not valid. Change the value of the "name" argument and run the operation again.`

### Expected behavior

After doing all the steps in the "Steps to reproduce section", try writing a command that does not exist, for example: `ok`; what we expect to get is 
`ok: The term 'ok' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.`

### Actual behavior

But we will get from that moment on is: 
```ps1
PS > ok
Cannot process argument because the value of argument "name" is not valid. Change the value of the "name" argument and run the operation again.
```

**Comment by daxian-dbw** [comment] 2023-05-08 16:14
@ALiwoto Thanks for reporting this error. This is actually a parsing bug in PowerShell engine, `using namespace [Security.Principal]` should raise a parsing error because it's supposed to be `using namespace System.Security.Principal`. The brackets `[]` should trigger a parsing error.

**Comment by daxian-dbw** [comment] 2023-05-08 16:16
Closed as a duplicate of https://github.com/PowerShell/PowerShell/issues/17113

**Closed as completed by daxian-dbw** 2023-05-08 16:16 UTC
Labels: Resolution-Duplicate
