### ISSUE TITLE
Cannot set key handler for "ctrl+["

### ISSUE THREAD

**Issue by akbyrd** [PowerShell/PSReadLine#3554] opened 2023-01-28 23:49 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
N/A
```

### Screenshot

![image](https://user-images.githubusercontent.com/484784/215296306-08c9f458-8ba3-4538-9c3c-c9edd0021edc.png)

### Environment data

```console
PS Version: 7.3.2
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.2.6
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 140
BufferHeight: 30
```

### Steps to reproduce

* Assign a a readline handler to `ctrl+[`
* Press `ctrl+[`
* Notice `^[` is input and the key handler is not executed

### Expected behavior

It is possible to assign a readline handler to `ctrl+[`

### Actual behavior

It is not possible to assign a readline handler to `ctrl+[`

**Comment by daxian-dbw** [comment] 2023-01-30 17:41
Close as a duplicate of #906

**Closed as completed by daxian-dbw** 2023-01-30 17:41 UTC
Labels: Resolution-Duplicate

**Comment by akbyrd** [comment] 2023-01-30 17:52
That issue is specific to vi mode. I'm not using vi mode. If this is the same issue should the vi one be renamed to make it clear it's not specific to vi mode?

**Comment by daxian-dbw** [comment] 2023-01-30 17:56
It's not specific to VI, but the same key-binding issue. The issue was renamed to make that clear.
