### ISSUE TITLE
Exception on input after window resize

### ISSUE THREAD

**Issue by ins0mniaque** [PowerShell/PSReadLine#308] opened 2015-11-25 03:13 UTC
Steps to reproduce:
1. Set console to wrap text output on resize (Properties > Layout > Screen Buffer Size)
2. Have a prompt bigger than minimum window width (14 characters for me)
3. Resize console width until prompt is wrapped
4. Type anything

---

```
Last 1 Keys:
 a

Exception:
System.ArgumentException: Destination array was not long enough. Check destIndex and length, and the array's lower bounds.
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Array destinationArray, Int32 length)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

---

**Comment by lzybkr** [comment] 2015-12-02 20:59
The exception is a little different, but this is effectively of dupe of #292.

**Closed as completed by lzybkr** 2015-12-02 20:59 UTC
Labels: Resolution-Duplicate
