### ISSUE TITLE
PredictionViewStyle ListView allow escape out of selection in emacs mode

### ISSUE THREAD

**Issue by bgelens** [PowerShell/PSReadLine#1932] opened 2020-11-05 18:39 UTC
## Description of the new feature/enhancement

The new ListView for predictions is awesome! One thing I've found a little bit impacting my flow, is the lack of ability to escape out of the list and just return to what I had typed. I've tried a couple of keybindings but none seem to work.

![image](https://user-images.githubusercontent.com/10071039/98282251-3c2fee00-1f9e-11eb-8f49-90a17438e93e.png)

The only option is to arrow up until I'm out of the list view. This will return my original input

![image](https://user-images.githubusercontent.com/10071039/98282321-5b2e8000-1f9e-11eb-9d7b-c89f841d95c0.png)

## Proposed technical implementation details (optional)

Allow Escape to directly return back to what was typed and return the cursor position

cc @SteveL-MSFT

**Comment by daxian-dbw** [comment] 2020-11-05 19:04
Hello @bgelens, thanks for trying out this feature!
Which `EditMode` were you in? The prediction `ListView` has been mainly tested and enhanced in the `Windows` edit mode.
Testing in the `Emacs` and `VI` edit modes is very minimum as of today, but we will spend more time improving its user experience in these 2 edit modes (Issue to track: #1934).

You can check your edit mode by `Get-PSReadLineOption | % EditMode`, and switching to `Windows` by `Set-PSReadLineOption -EditMode Windows`.

**Comment by daxian-dbw** [comment] 2020-11-05 19:11
If you are using the `Windows` edit mode, you will find <kbd>Escape</kbd> works as expected -- pressing it will escape out of the list and return to what I had typed. <kbd>Ctrl+z</kbd> (undo) will also be handy for you to escape out of a selection. Please see the "**Handling of Commonly Used Keys**" section in the PR description of #1909 to learn more about the details.

Also, we will have a blog posted next week about this feature, so please stay tuned.

**Comment by bgelens** [comment] 2020-11-05 19:17
Hey @daxian-dbw. Thanks for the info.

I'm using emacs (running on Mac where this is more natural fit). I did not think about using ctrl+z. I can confirm it has the desired effect for me! I'll use this as a workaround for now (esc will be more natural and getting from your reply it is mend to work)

**Comment by daxian-dbw** [comment] 2020-11-05 19:20
Yes, <kbd>Escape</kbd> in `Emacs` edit mode should work the same as in the `Windows` edit mode, and we will make that improvement for the next beta release.

**Comment by bgelens** [comment] 2020-11-05 19:29
Should I close this issue considering the tracking issue you created? If so please feel free to close yourself :)

**Comment by daxian-dbw** [comment] 2020-11-05 19:37
I will close this one as a duplicate of #1934. Thanks @bgelens!

**Closed as completed by daxian-dbw** 2020-11-05 19:37 UTC
Labels: Issue-Enhancement

**Comment by daxian-dbw** [comment] 2022-01-11 02:33
It turns out <kbd>Escape</kbd> in `Emacs` edit mode is already bound to `ChordFirstKey` and that means it's a special key indicating a chord of keys (e.g <kbd>Escape,f</kbd>, <kbd>Escape,d</kbd>, or even <kbd>Escape,Ctrl+y</kbd>). So we cannot make <kbd>Escape</kbd> to work the same as in the `Windows` edit mode.

A workaround would be to map <kbd>Escape, Escape</kbd> to `RevertLine`, so you can press `ESC` twice to get the same behavior as in `Windows` edit mode.
```pwsh
Set-PSReadLineKeyHandler -Key 'Escape, Escape' -Function RevertLine
```
