### ISSUE TITLE
Crash in Cloudshell (Powershell)

### ISSUE THREAD

**Issue by johlae** [PowerShell/PSReadLine#770] opened 2018-10-02 11:41 UTC
PS Azure:\> $cred=Get-Credential -UserName Student

PowerShell credential request
Enter your credentials.
Password for user Student: ************

Azure:/
PS Azure:\> Enter-AzVM -Name
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 127 Keys:
```
 e n t e r - a z v m Space Backspace Tab Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace g e t - c r e d e n t i a l Tab Space - u s r Backspace e r n q a Backspace Backspace Tab Space S t u d e n t Enter
 $ c r e d = g e t - c r e Tab Space - u s e r Tab Space S t u d e n t Enter
 e n t e r - a z v m Tab Space - v m Tab Backspace Backspace N a m Tab Space DownArrow Insert PageDown
```

Exception:
```
System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.ConsolePal.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ScrollDisplayDown(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```
-----------------------------------------------------------------------
Azure:/
PS Azure:\> Enter-AzVM -Name
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 128 Keys:
```
 e n t e r - a z v m Space Backspace Tab Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace g e t - c r e d e n t i a l Tab Space - u s r Backspace e r n q a Backspace Backspace Tab Space S t u d e n t Enter
 $ c r e d = g e t - c r e Tab Space - u s e r Tab Space S t u d e n t Enter
 e n t e r - a z v m Tab Space - v m Tab Backspace Backspace N a m Tab Space DownArrow Insert PageDown PageDown
```

Exception:
```
System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.ConsolePal.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ScrollDisplayDown(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```
-----------------------------------------------------------------------

**Comment by johlae** [comment] 2018-10-02 11:43
Just reporting I have no idea what happened. I guess I was typing a VM name (with the beginning of the name being numbers) without numlock on and ended up sending down-arrow and PG down istead of numbers.

**Comment by lzybkr** [comment] 2018-10-19 04:42
Closing as a duplicate of #700.

**Closed as completed by lzybkr** 2018-10-19 04:42 UTC
