### ISSUE TITLE
When switched to "half screen mode" with Win+Left arrow shortcut on PS, it did not show anything except black screen

### ISSUE THREAD

**Issue by mturczyn** [PowerShell/PSReadLine#2344] opened 2021-04-06 12:13 UTC
```
Last 200 Keys:
 Tab Enter
 UpArrow UpArrow Enter
 i i Enter
 c d Space . . Enter
 c d Space . . Enter
 d i r Enter
 c d Space ' f s Space g Tab Enter
 d i r Enter
 c d Space Tab Enter
 i i Backspace Space * Backspace Backspace i Space * S Tab l n Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace * s l n Tab Enter
 ` Insert c d Space \ f s Tab \ Tab Tab Tab Enter
 c d Space * c a m Tab Enter
 i i Space * s l n Tab Enter
 c d Space . . Backspace Backspace \ Tab t Tab Escape c d Space u Tab Backspace \ u Tab t Tab s o Tab Enter
 d i r Enter
 c d Space t Tab Enter
 d i r Enter
 c d Space c o n s Tab Enter
 i i Space * s l n Tab Enter
 ` UpArrow d d d d d Escape Escape Escape Escape Escape Escape c d . . Enter
 Enter
 c l e a r Enter
 c l e a r Enter
 ` c l e a r Enter
```

Exception:
System.IO.IOException: The parameter is incorrect.
```
   w System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   w System.Console.SetCursorPosition(Int32 left, Int32 top)
   w Microsoft.PowerShell.PSConsoleReadLine.AcceptLineImpl(Boolean validate)
   w Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   w Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   w Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

**Comment by daxian-dbw** [comment] 2021-04-08 21:20
> When switched to "half screen mode" with Win+Left arrow shortcut on PS, it did not show anything except black screen

This seems to be a problem of the console host. CMD.exe shows the same behavior in the console host. Windows terminal works fine though. This is a duplicate of #2037.

**Closed as completed by daxian-dbw** 2021-04-08 21:20 UTC
