### ISSUE TITLE
Exception ``` System.IO.IOException: The system cannot open the device or file specified.

### ISSUE THREAD

**Issue by tacpham** [PowerShell/PSReadLine#2554] opened 2021-06-08 07:03 UTC
## Environment

```none
[run the script below and paste the output here]
```

### Environment
PSReadLine: 2.1.0
PowerShell: 7.1.3
OS: Linux 4.18.0-305.3.1.el8.x86_64 #1 SMP Tue Jun 1 16:14:33 UTC 2021
BufferWidth: 100
BufferHeight: 35

Last 0 Keys
## Exception report

```

### Exception
```
System.IO.IOException: The system cannot open the device or file specified. : 'PSReadLineHistoryFile_3120419687'
   at System.Threading.Mutex.CreateMutexCore(Boolean initiallyOwned, String name, Boolean& createdNew)
   at Microsoft.PowerShell.PSConsoleReadLine.DelayedOneTimeInitialize()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

## Steps to reproduce
Every time try to using Powershell bash with pwsh command I get that error
<!-- A description of how to trigger this bug. -->

## Expected behavior
It's just work fine before. Now I try to reinstall it again. Hope it work.
<!-- A description of what you're expecting, possibly containing screenshots or reference material. -->

## Actual behavior

<!-- What's actually happening? -->

**Comment by daxian-dbw** [comment] 2021-07-01 19:07
@tacpham Thanks for reporting the issue. This looks like a duplicate of #1464. It's likely a permission issue to `/tmp`. Please take a look at https://github.com/PowerShell/PSReadLine/issues/1464#issuecomment-631941511 to see if that helps with your problem too.

**Closed as completed by daxian-dbw** 2021-07-01 19:07 UTC
Labels: Resolution-Duplicate

**Comment by tacpham** [comment] 2021-07-01 23:59
Just a small question, why it working before, with the same environment and then boom, show error. I'm doing nothing with /tmp, never touch it.
