### ISSUE TITLE
Trying to Run commands in Powershell through Docker. 

### ISSUE THREAD

**Issue by clandestine8** [PowerShell/PSReadLine#283] opened 2015-09-11 19:43 UTC
C:\Users\Administrator>docker run 9aaec35b61af
Windows PowerShell
Copyright (C) 2015 Microsoft Corporation. All rights reserved.

Oops, something went wrong.  Please report this bug with the details below.
## Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new

Last 0 Keys:

Exception:
System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by lzybkr** [comment] 2017-01-12 20:42
Most likely a dupe of #158, reopen with additional information if you disagree.

**Closed as completed by lzybkr** 2017-01-12 20:42 UTC
Labels: Resolution-Duplicate
