### ISSUE TITLE
MenuComplete tab completion does not render properly

### ISSUE THREAD

**Issue by mikemaccana** [PowerShell/PSReadLine#716] opened 2018-06-22 11:10 UTC
I'm sure I've seen and fixed this before, but it's happening again in the current PSReadLine 2 alpha/

Environment data
----------------

```powershell
PS version: 6.1.0-preview.2
PSReadline version: 2.0.0-alpha1
os: 10.0.17692.1000 (WinBuild.160101.0800)
PS file version: 6.1.0
```

Steps to reproduce or exception report
--------------------------------------

     Set-PSReadlineKeyHandler -Chord Tab -Function MenuComplete

Use tab to menu complete. Notice the cursor doesn't unselect the previous entry, so everything gets selected.

![image](https://user-images.githubusercontent.com/172594/41773496-24ce3784-7614-11e8-854f-e3450ef08912.png)

**Comment by lzybkr** [comment] 2018-06-22 16:47
Something must be wrong with your environment - the problem is definitely fixed in `PSReadLine 2.0.0` - any build.

I'm guessing that you still have the version that is released with `PowerShell 6`. Check `[Microsoft.PowerShell.PSConsoleReadLine].Assembly.Location` to check, if the filename is `Microsoft.PowerShell.PSReadLine2.dll`, then I have no clue what's going on.

**Comment by mikemaccana** [comment] 2018-06-22 20:30
Thanks for your help. Killing all powershell processes, opening a new one (Pwsh 6 preview 2), and running my profile (which as `Import-Module PSReadLine`), then running:

    ~\Documents $ [Microsoft.PowerShell.PSConsoleReadLine].Assembly.Location
    C:\Program Files\PowerShell\6-preview\Microsoft.PowerShell.PSReadLine.dll

But:

    ~\Documents $ Get-Module psreadline

    ModuleType Version    Name                                ExportedCommands
    ---------- -------    ----                                ----------------
    Script     2.0.0      PSReadLine                          {Get-PSReadlineKeyHandler, Get-PSReadlineOption, Remove-PSR...

So it's using an old .dll, but get-mdoule shows version 2? I'm not sure what to do here - I've only been using Powershell for a year.

**Comment by lzybkr** [comment] 2018-06-22 20:43
Based on that info, I'm guessing you don't have an official release of PSReadLine. To check, run:

```
sls NestedModules -Path ((gmo PSReadLine).Path -replace 'psm1','psd1')
```

If the path to the psd1 has `2.0.0` and does not specify `Microsoft.PowerShell.PSReadLine2.dll`, then that would explain the problem.

Builds of PowerShell before `6.1.0-preview3` have `Microsoft.PowerShell.PSReadLine.dll` as a trusted assembly that cannot be replaced - if you try to load an assembly with that name, it will load the one installed with PowerShell instead, and that version does have this bug.

Do you know how you installed PSReadLine?

One fix is to upgrade to 6.1.0 preview3 and remove the version of PSReadLine that you installed.

**Comment by mikemaccana** [comment] 2018-06-22 20:59
`C:\Program Files\PowerShell\Modules\PSReadLine\2.0.0\PSReadLine.psd1:3:NestedModules =
@("Microsoft.PowerShell.PSReadLine.dll")`

I installed psreadline via `Install-Module -Name PSReadLine -RequiredVersion 2.0.0 -AllowPrerelease`

I didnt' realise preview 3 was out (I wish powershell would tell me). Installing it now.

**Comment by mikemaccana** [comment] 2018-06-22 21:02
Where is preview 3?

https://github.com/PowerShell/PowerShell only has `6.0.2` which I assume is preview 2. (I assume because powershell has weird ass naming and the file shoudl be called `6.0 preview 2` if it wanted to make sense.)

**Comment by lzybkr** [comment] 2018-06-22 21:19
I see - that is pulling a hidden release which never should have been published. If you remove the `-RequiredVersion` parameter, it would install `2.0.0 -beta2` which is what you want (but it's included in preview 3, so that's good too.)

I'm closing as I believe there is no further investigation needed on my part.

**Closed as completed by lzybkr** 2018-06-22 21:19 UTC

**Comment by mikemaccana** [comment] 2018-06-22 21:43
All good on preview 3. Thanks @lzybkr ! ✨👍🙌
