### ISSUE TITLE
gem install sinatra error,

### ISSUE THREAD

**Issue by Lylesanders** [PowerShell/PSReadLine#487] opened 2017-01-03 15:40 UTC
4 gems installed
PS C:\> c
Oops, something went wrong.  Please report this bug with the details below
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 . . / . . Enter
 g e m Spacebar i n s t a l l Spacebar - - Spacebar l o c a l Spacebar c
 l s Enter
 g e m Spacebar i n s t a l l Spacebar = = Backspace Backspace - - l o c
 u p d a t e Spacebar Backspace _ r u b y g e m s Spacebar - - n o - r i
 g e m s Spacebar - v Enter
 g e m s Spacebar - v e r s i o n Enter
 g e m Spacebar l i s t Enter
 g e m Spacebar i n s t a l l Spacebar s i n a t r a Enter
 c

Exception:
System.IO.IOException: The parameter is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.ConhostConsole.set_WindowTop(Int32 va
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, O
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace,
-----------------------------------------------------------------------

**Comment by lzybkr** [comment] 2017-01-12 20:27
Most likely a dupe of #292, reopen with additional information if you disagree.

**Closed as completed by lzybkr** 2017-01-12 20:27 UTC
Labels: Resolution-Duplicate
