### ISSUE TITLE
MenuComplete with filtering

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PSReadLine#2598] opened 2021-06-18 19:08 UTC
## Description of the new feature/enhancement

There are many cases where tab completion can result in a large list (not just files which is a common case, but think of resources in Azure). It would be useful to have either a new mode for MenuComplete or an alternate where you have a filter line that will dynamically filter results showing matches to the typed filter.  In the file case, I should be able to type `*.jpg` which will filter out to just files with that extension.  If I type `jpg` then any result that contains that string would be shown.

One question is whether the cmdlet participates as an optimization rather than filtering on the client.

**Comment by SteveL-MSFT** [comment] 2021-06-19 14:06
I think for this feature to work, https://github.com/PowerShell/PSReadLine/issues/2306 needs to be implemented.  Then, if the user types `ctrl+f`, for example, they have a new input line to type a filter that gets applied dynamically and they can tab into the menu complete

**Comment by iSazonov** [comment] 2021-06-21 05:11
Does PowerShell Pager already support ctrl+f and return a selection or we need request these features?

**Comment by daxian-dbw** [comment] 2021-09-22 20:01
Close as a duplicate of #1235

**Closed as completed by daxian-dbw** 2021-09-22 20:01 UTC
Labels: Issue-Enhancement
