### ISSUE TITLE
Garbage characters displayed in prompt on Ubuntu 14.04

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PSReadLine#454] opened 2016-10-18 23:00 UTC
I have the PS Core alpha 11 installed.  When PowerShell starts, my prompt looks like this:
![image](https://cloud.githubusercontent.com/assets/5177512/19499476/ef005f9e-9553-11e6-87bb-26ac8b3135bd.png)
As soon as I type a single character `l` in this case, the prompt changes to:
![image](https://cloud.githubusercontent.com/assets/5177512/19499489/fd87ee9c-9553-11e6-865a-e07a53a65b90.png)
The erroneous `1` displayed has nothing to do with the history id I display in my prompt.  For instance, if my history was at `2`, as soon as I type the `1` reappears.  

After I execute the command the prompt is displayed correctly again until I start typing a new command.

**Comment by lzybkr** [comment] 2016-10-20 09:17
Is this related to the prompt function getting invoked twice?

**Comment by rkeithhill** [comment] 2016-10-21 03:16
I don't know. I'll experiment with this some tomorrow when I'm back on this VM.  It is interesting that the garbage glyph appears to be `001B` which is the hex value of the \e char.  It's still too bad `<backtick>e` didn't get added to PowerShell along with `<backtick>uXXXX` e.g. `u001b.

**Comment by rkeithhill** [comment] 2016-10-22 01:52
Yup, the prompt is getting invoked twice.  Not sure if that is what is causing the garbage char.  

Here is my prompt func (using a hacked version of posh-git that runs on PS Core and returns an ANSI seq string instead of writing to host):
![image](https://cloud.githubusercontent.com/assets/5177512/19616058/517cc494-97c7-11e6-8226-6b28a8cd78d7.png)

**Comment by lzybkr** [comment] 2017-01-12 21:02
Most likely a dupe of #468, reopen with additional information if you disagree.

**Closed as completed by lzybkr** 2017-01-12 21:02 UTC
Labels: Resolution-Duplicate
