### ISSUE TITLE
Autocomplete Error

### ISSUE THREAD

**Issue by DissectMalware** [PowerShell/PSReadLine#2255] opened 2021-02-26 20:13 UTC
```
Last 3 Keys:
 w Ctrl+Space y

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -8.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.Menu.DrawMenu(Menu previousMenu)
   at Microsoft.PowerShell.PSConsoleReadLine.PossibleCompletionsImpl(CommandCompletion completions, Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.CompleteImpl(Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

![image](https://user-images.githubusercontent.com/9646319/109350103-f779dc80-7844-11eb-9918-a9efae7493a9.png)

![image](https://user-images.githubusercontent.com/9646319/109350230-298b3e80-7845-11eb-86fb-6413329211fb.png)

**Comment by daxian-dbw** [comment] 2021-03-05 19:00
This is a duplicate of #1306, and was fixed. Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.

**Closed as completed by daxian-dbw** 2021-03-05 19:00 UTC
