### ISSUE TITLE
Windows powershell can not echo 😁

### ISSUE THREAD

**Issue by Anduin2017** [PowerShell/PSReadLine#1582] opened 2020-06-03 11:59 UTC
![image](https://user-images.githubusercontent.com/19531547/83634114-9504f000-a5d4-11ea-8601-74232e34d050.png)

I tried to execute the following command:

```powershell
PS C:\Users\andui> echo ��
```
And it just crashed.

```log
### Exception
```
System.Text.EncoderFallbackException: Unable to translate Unicode character \\uD83D at index 5� to specified code page.
   at System.Text.EncoderExceptionFallbackBuffer.Fallback(Char charUnknown, Int32 index)
   at System.Text.EncoderFallbackBuffer.InternalFallback(ReadOnlySpan`1 chars, Int32& charsConsumed)
   at System.Text.Encoding.GetBytesWit�hFallback(ReadOnlySpan`1 chars, Int32 originalCharsLength, Span`1 bytes, Int32 originalBytesLength, EncoderNLS encoder)
   at System.Text.Encoding.GetBytesWithFallback(Char* pOriginalChars, Int32 originalCharCount, Byte* pOriginalBytes, Int32 originalByte�Count, Int32 charsConsumedSoFar, Int32 bytesWrittenSoFar, EncoderNLS encoder)
   at System.Text.Encoding.GetBytes(Char* pChars, Int32 charCount, Byte* pBytes, Int32 byteCount, EncoderNLS encoder)
   at System.Text.EncoderNLS.GetBytes(Char* chars, Int32 c�harCount, Byte* bytes, Int32 byteCount, Boolean flush)
   at System.Text.EncoderNLS.GetBytes(Char[] chars, Int32 charIndex, Int32 charCount, Byte[] bytes, Int32 byteIndex, Boolean flush)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flu�shEncoder)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at Microsoft.PowerShell.PSConsoleReadLine.<>c__DisplayClass83_0.<WriteHistoryRange>b__0()
   at Microsoft.PowerShell.PSConsoleReadLine.WithHistor�yFileMutexDo(Int32 timeout, Action action)
   at Microsoft.PowerShell.PSConsoleReadLine.WriteHistoryRange(Int32 start, Int32 end, Func`2 fileOpener)
   at Microsoft.PowerShell.PSConsoleReadLine.IncrementalHistoryWrite()
   at Microsoft.PowerShell.PSCons�oleReadLine.MaybeAddToHistory(String result, List`1 edits, Int32 undoEditIndex, Boolean fromDifferentSession, Boolean fromInitialRead)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace� runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
````

**Comment by iSazonov** [comment] 2020-06-03 12:02
Please report the issue to PSReadline repository. (Perhaps such issue already was reported.)

**Comment by vexx32** [comment] 2020-06-03 13:54
I believe we have an open issue tracking emoji etc problems: #949 

If you have any information not already covered by that issue, please add a comment to the existing issue instead. 🙂

**Comment by daxian-dbw** [comment] 2020-06-04 17:27
Thanks for the reporting. This is a duplicate of #949.

**Closed as completed by daxian-dbw** 2020-06-04 17:27 UTC
Labels: Resolution-Duplicate
