### ISSUE TITLE
Something wrong with powershell; here's what it said

### ISSUE THREAD

**Issue by sethbfrank** [PowerShell/PSReadLine#1427] opened 2020-03-26 16:25 UTC
Last 200 Keys:
 n \ j a v a . e x e ' Space ' - - e n a b l e - p r e v i e w ' Space ' - D f 
i l e . e n c o d i n g = U T F - 8 ' Space ' - c p ' Space ' C : \ U s e r s \ s e t h b \ A p p D a t a \ R o a m i n g \ C o d e \ U s e r \ w o r k s p a 
c e S t o r a g e \ e 7 7 7 3 3 6 a 2 8 2 f 1 d d 3 f a c 2 3 d 0 b 5 6 d 2 5 f 7 6 \ r e d h a t . j a v a \ j d t _ w s \ u n i t 7 _ 6 c 5 b e 4 e e \ b i 
n ' Space ' T e s t ' Space Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to 
zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object 
arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, 
Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment] 2020-03-30 17:20
From the bug report template:
```
The maintainer may close your issue without further explanation or engagement if:
- You delete this entire template and go your own path;
```
So, please follow the bug report template to provide **environment data** and **repro step** the next time.

As for this issue, it's a duplicate of #1306 and was fixed in the latest version. Please check out #1306 for more information.

**Closed as completed by daxian-dbw** 2020-03-30 17:20 UTC
Labels: Resolution-Duplicate
