### ISSUE TITLE
version 1.2 Delete key bug

### ISSUE THREAD

**Issue by MVKozlov** [PowerShell/PSReadLine#486] opened 2016-12-30 09:59 UTC
latest version have bug with delete key:

if cursor **at** the last character and 'delete' pressed it remove last symbol and move to left, at previous character but should stay **after** that character.

ver. 1.0.0.14 doesn't have this bug and Server 2016's version doesn't have it

**Comment by MVKozlov** [comment] 2016-12-30 10:03
```
EditMode                               : Windows
ContinuationPrompt                     : >>
HistoryNoDuplicates                    : True
MaximumHistoryCount                    : 4096
MaximumKillRingCount                   : 10
HistorySearchCursorMovesToEnd          : False
ShowToolTips                           : True
HistorySearchCaseSensitive             : False
ViModeIndicator                        : None
```

**Comment by Dessix** [comment] 2017-01-09 05:21
Seeing it here too.
```
EditMode                               : Windows
ContinuationPrompt                     : >>
HistoryNoDuplicates                    : True
MaximumHistoryCount                    : 4096
MaximumKillRingCount                   : 10
HistorySearchCursorMovesToEnd          : False
ShowToolTips                           : True
HistorySearchCaseSensitive             : False
ViModeIndicator                        : None
```

**Comment by lzybkr** [comment] 2017-01-12 19:32
This is a duplicate of #380 - fixed in the latest but I need to create a new release.

**Closed as completed by lzybkr** 2017-01-12 19:32 UTC
Labels: Resolution-Duplicate
