### ISSUE TITLE
Cannot paste three byte characters

### ISSUE THREAD

**Issue by 89z** [PowerShell/PSReadLine#2171] opened 2021-01-30 20:02 UTC
If I have this string:

~~~
μ‐Ziq
~~~

With these codepoints:

~~~
μ       U+03BC
‐       U+2010
Z       U+005A
i       U+0069
q       U+0071
~~~

and I paste (with either right click or Ctrl + V), I get this:

~~~
μZiq
~~~

So the character is stripped out.

~~~
PS C:\> Get-InstalledModule
Version              Name                                Repository     
-------              ----                                ----------        
2.1.0                PSReadLine                          PSGallery      
~~~

**Comment by msftrncs** [comment] 2021-01-31 01:09
What version of PowerShell and what terminal are you running it in?   It is working fine for me here with PowerShell 7.1.1 running in either VS Code's terminal or the standard ConHost from Windows (though I am running Windows build 21296).

**Comment by msftrncs** [comment] 2021-01-31 01:16
Of course as soon as I said that, I realized I was only trying <kbd>CTRL</kbd>-<kbd>V</kbd>.   Right clicking in VS Code and ConHost does strip the character, but <kbd>CTRL</kbd>-<kbd>V</kbd> does not.

This is kind of an old issue, it was mostly remedied by trapping <kbd>CTRL</kbd>-<kbd>V</kbd> directly in PSReadLine/PowerShell, giving access to the clipboard without interference by the terminal.   Some terminals don't allow that though.

I think the issue is really deep in the .Net IO layer, and it has yet to be resolved.

**Comment by 89z** [comment] 2021-01-31 01:17
> VS Code

This issue has nothing to do with Visual Studio...

**Comment by daxian-dbw** [comment] 2021-02-04 20:19
I can reproduce your issue with right click, but NOT `Ctrl+v` in Windows Terminal or Conhost, see the screenshot:
Windows Terminal (PS 7.1.0):
![demo1](https://user-images.githubusercontent.com/127450/106949947-8aaa7100-66e2-11eb-9ca2-cee052458aec.gif)

Conhost (PS 7.1.0 and CMD)
![demo1](https://user-images.githubusercontent.com/127450/106950041-add52080-66e2-11eb-8771-bd97b5702d3f.gif)
![demo1](https://user-images.githubusercontent.com/127450/106950101-c04f5a00-66e2-11eb-98da-0b6f4b79337e.gif)

The `right-click` paste issue is old, see #579.

**Comment by 89z** [comment] 2021-02-04 20:45
ok using `Ctrl + V`, it works as expected with Conhost, but not Windows Terminal. Can you clarify what version you are using? I am using `v1.0`, but I also tried with `v1.1`, `v1.2`, `v1.3`, `v1.4` and `v1.5` with same problem.

Also are you using `WindowsTerminal.exe` or `wt.exe`, I dont understand the difference between the two.

**Comment by daxian-dbw** [comment] 2021-02-09 18:47
The version of Windows Terminal that I'm using is 1.6.10272.0

**Comment by 89z** [comment] 2021-02-09 21:10
I tried again with `Ctrl + V` and Windows Terminal `1.6.10272.0`, but the character is still getting stripped. Not sure what Im doing wrong. What PSReadline are you using?

**Comment by daxian-dbw** [comment] 2021-02-10 17:46
I'm using the 2.1.0 version of PSReadLine.

![demo1](https://user-images.githubusercontent.com/127450/107549500-c16e0480-6b84-11eb-955c-feebec038fb6.gif)

**Comment by 89z** [comment] 2021-02-10 18:31
ok I just tried again with these:

- Ctrl + V
- PowerShell 7.1
- Readline 2.1
- Windows Terminal 1.6

and the character is still getting stripped out. Not sure what I am doing wrong. I have this in my profile:

~~~
[Console]::OutputEncoding = [System.Text.UTF8Encoding]::new()
~~~

but taking that out didnt change anything. Also I havent messed with the Registry, these should be default:

~~~
Windows Registry Editor Version 5.00
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Nls\CodePage]
"ACP"="1252"
"OEMCP"="437"
"MACCP"="10000"
~~~

maybe my Windows is old? I am using Windows 10 1909 (18363). What version are you using?

**Comment by daxian-dbw** [comment] 2021-02-11 07:05
Mine is 20H2 (19042.804), but I doubt is because of the OS ...
```
PS:86> Get-ChildItem HKLM:\SYSTEM\CurrentControlSet\Control\Nls\CodePage

    Hive: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Nls\CodePage

Name                           Property
----                           --------
EUDCCodeRange                  932 : F040-F9FC
                               936 : AAA1-AFFE,F8A1-FEFE,A140-A7A0
                               949 : C9A1-C9FE,FEA1-FEFE
                               950 : FA40-FEFE,8E40-A0FE,8140-8DFE,C6A1-C8FE
```

**Comment by 89z** [comment] 2021-02-11 14:33
thats the wrong command:


~~~
PS C:\> Get-ItemProperty HKLM:\SYSTEM\CurrentControlSet\Control\Nls\CodePage
ACP               : 1252
OEMCP             : 437
MACCP             : 10000
~~~

**Comment by daxian-dbw** [comment] 2021-02-24 17:55
Ah, sorry, here it goes:
```
AllowDeprecatedCP : 1111573537
OEMHAL            : vgaoem.fon
ACP               : 1252
OEMCP             : 437
MACCP             : 10000
```

**Comment by jbolton-corvalgroup** [comment] 2021-07-13 01:41
I've had this exact bug, there are several factors

1. `ctrl+v` may be being capture by 1] `windowsterminal` or 2] `vs code`, sending the wrong bytes
2. older versions of PSReadLine had a bug
2. There's 3 variables for encoding, not having `InputEncoding` as utf8

# You'll probably be fixed if you try

1.  Update `WindowsTerminal`. I'm using `1.9 Preview` (which is really stable)
2. Set the 3 encodings
3. Maybe update PSReadLine. Your version might be good enough. 

I'm using

| App | Version |
| - | - |
| WindowsTerminal Preview | 1.9 |
| PSReadLine | 2.2.0 beta2 (to use the new features, might not be required) |

Then start your profile with

```ps1
$global:OutputEncoding = [console]::InputEncoding = [console]::OutputEncoding = [System.Text.UTF8Encoding]::new()
```

It even fixed the: can't paste from `WindowKey + .` emojis issue

![image](https://user-images.githubusercontent.com/25640518/125376531-d24bbd80-e350-11eb-8c28-347e04cec981.png)


>     * Windows Terminal 1.6
> 
> and the character is still getting stripped out. Not sure what I am doing wrong. I have this in my profile:
> 
> ```
> [Console]::OutputEncoding = [System.Text.UTF8Encoding]::new()

You want to use the snippet above, otherwise non-utf8 encoding issues will pop up

> ok I just tried again with these:
>     * Ctrl + V

Check the default keybindings, I think older versions used `ctrl+v` as the paste action, meaning it consumes it **before** PSReadLine, so the wrong bytes are sent.

This is also the cause of the slow 'it-pastes-one-character-at-a-time' issue

You don't want 
```json
    { "command": "paste", "keys": "ctrl+v" },
```
You  want PSReadLine to catch it. Verify:

```json
🐒> Get-PSReadLineKeyHandler -Bound | ? Function -Match paste

Basic editing functions
=======================

Key          Function Description
---          -------- -----------
Ctrl+v       Paste    Paste text from the system clipboard
```

>  [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Nls\CodePage]
> but taking that out didnt change anything. Also I havent messed with the Registry

You will not need to edit the registry.

> maybe my Windows is old? I am using Windows 10 1909 (18363). What version are you using?

That should be fine.

**Comment by daxian-dbw** [comment] 2022-10-10 18:29
Given that I cannot reproduce the reported issue with `Ctrl+v`, I will close this issue. The right-click issue is tracked by #579

**Closed by daxian-dbw** 2022-10-10 18:29 UTC
Labels: Resolution-Not Repro

**Comment by 89z** [comment] 2022-10-10 22:01
Looks like I was previously using Windows Terminal 1.6 [1], currently I am using Windows Terminal 1.10 and the problem seems to have been fixed.


1. https://github.com/PowerShell/PSReadLine/issues/2171#issuecomment-776919659
