### ISSUE TITLE
Oops, something went wrong

### ISSUE THREAD

**Issue by jedgar02** [PowerShell/PSReadLine#447] opened 2016-09-29 23:43 UTC
```
Oops, something went wrong. Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys: Spacebar Spacebar Spacebar Spacebar ' D e s k t o p O r I O T ' , $ O S T Y P E , $ e n v : P R O C E S S O R _ A R C H I T E C T U R E Spacebar - j o i n Spacebar ' - ' Enter Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar } Enter Enter Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar D e f a u l t Enter Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar { Enter Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar ' D e s k t o p - W i n d o w s ' , $ e n v : P R O C E S S O R _ A R C H I T E C T U R E Spacebar - j o i n Spacebar ' - ' Enter Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar } Enter Spacebar Spacebar Spacebar Spacebar } Enter Enter Spacebar Spacebar Spacebar Spacebar Enter } Enter } Enter Enter Enter UpArrow UpArrow
Exception: System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. Parameter name: top Actual value was -73.
at System.Console.SetCursorPosition(Int32 left, Int32 top)
at Microsoft.PowerShell.Internal.TTYConsole.SetCursorPosition(Int32 left, Int32 top)
at Microsoft.PowerShell.PSConsoleReadLine.PlaceCursor(Int32 x, Int32& y)
at Microsoft.PowerShell.PSConsoleReadLine.PlaceCursor()
at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender()
at Microsoft.PowerShell.PSConsoleReadLine.Render()
at Microsoft.PowerShell.PSConsoleReadLine.UpdateFromHistory(Boolean moveCursor)
at Microsoft.PowerShell.PSConsoleReadLine.HistoryRecall(Int32 direction)
at Microsoft.PowerShell.PSConsoleReadLine.PreviousHistory(Nullable1 key, Object arg)
at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

**Comment by lzybkr** [comment] 2017-01-12 21:02
Most likely a dupe of #292, reopen with additional information if you disagree.

**Closed as completed by lzybkr** 2017-01-12 21:02 UTC
Labels: Resolution-Duplicate
