### ISSUE TITLE
Error changing Powershell version from 5 to 3

### ISSUE THREAD

**Issue by fortram64** [PowerShell/PSReadLine#276] opened 2015-08-30 11:24 UTC
Oops, something went wrong.  Please report this bug with the details below.
## Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new

Last 0 Keys:

Exception:
System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntri
nsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrins

**Comment by lzybkr** [comment] 2015-09-02 04:29
Can you provide some more context, there's not enough information here to repro.

**Comment by lzybkr** [comment] 2016-01-17 17:07
Closing due to no more info, possibly a dupe of #158.

**Closed as completed by lzybkr** 2016-01-17 17:07 UTC
