### ISSUE TITLE
FR: Tab completion items appearance

### ISSUE THREAD

**Issue by Crypt32** [PowerShell/PSReadLine#305] opened 2015-11-22 17:27 UTC
I have used PowerTab for years and I like the way how tab completion items appeared there: 
![PowerTab appearance](http://download-codeplex.sec.s-msft.com/Download?ProjectName=powertab&DownloadId=136419)

what is (in my opinion) wrong with current PSReadLine behavior:
- PSReadLine shows tab completion items in multiple columns: it is hard to search over them.

There really should be only one column, because eyes work better in vertical direction and you can't predict in which column your desired item is listed. You have to check first items of each column and spend another seconds to determine the target column.
- when tab completion contains a lot of items (when completing directory content, or .NET namespaces/classes/members), CTRL+Space just throws the list of tab completion items to console.

the tab completion list should be scrollable and do not permanently throw items to console.
- when attempting to launch tab-completion, the list is shown and the first element is selected as default. Only then you can navigate over columns to select the right item. No filtering is allowed.

I think, that PSReadLine should not select first item as a default value. Instead, it should allow further typing to reduce the amount of items to show (by limiting them to values that match typed text).

Assuming that PowerTab is dead (and has side issues in PSv4+), you should take the best of it and implement in PSReadLine.

**Comment by lzybkr** [comment] 2015-12-02 20:56
There are multiple issues reported here.  I'm resolving it as a dupe of #122 for the UI.
If you want one completion per line, try:

```
Set-PSReadlineOption -ShowToolTips
```

The UI is the same, but you'll get tool tips and each completion shown on one line.

**Closed as completed by lzybkr** 2015-12-02 20:56 UTC
Labels: Resolution-Duplicate
