### ISSUE TITLE
PSReadine doesnt clear multiline text when Escape pressed

### ISSUE THREAD

**Issue by MVKozlov** [PowerShell/PSReadLine#607] opened 2017-12-08 12:26 UTC
Environment data
----------------
```powershell
PS version: 5.1.14409.1012
PSReadline version: 2.0.0
os: 6.1.7601.17514 (win7sp1_rtm.101119-1850)
PS file version: 10.0.14409.1005 (rs1_srvoob.161208-1155)
```
Steps to reproduce or exception report
--------------------------------------
1. Write any long text into cmdline (it mush be longer than one line)
2. Press Escape key
3. PSReadline should clear all command text but clear only first line

**Comment by lzybkr** [comment] 2017-12-08 13:51
Strange, I've been self hosting for months and should have noticed this. It will be a few days before I can take a look.

**Comment by MVKozlov** [comment] 2017-12-09 15:46
Tested on another WIn7, same effect
on Win10 all ok

**Comment by MVKozlov** [comment] 2017-12-11 08:37
I addition: Powershell shutdown/unload time on 2.0 up to 6-7 sec :(

**Comment by lzybkr** [comment] 2017-12-17 07:40
I have reproduced the problem on Win7 as well as Win10 in legacy mode.

There is a difference in how `conhost` handles `Console.WriteLine()` when at the end of the line. I'll think more about a fix - and hopefully this difference doesn't come up elsewhere - I think it came up in menu completion (which is fixed now) but I don't think the same fix will work here.

**Comment by MVKozlov** [comment] 2018-11-06 08:59
Back to old problem :)
this diff fixes rendering on win7 and  I do not see any difference of WinSrv2016. It doesn't break anything (I try to check it on Win10 later)

Do not try any Linuxes, may be it need to tune up
``` diff
--- Render~orig.cs      Tue Nov 06 11:49:37 2018
+++ Render.cs   Tue Nov 06 11:48:58 2018
@@ -486,7 +486,7 @@

             while (previousPhysicalLine > physicalLine)
             {
-                _console.Write("\n");
+                //_console.Write("\n");
                 physicalLine += 1;
                 var lenToClear = physicalLine == previousPhysicalLine ? lenPrevLastLine : bufferWidth;
                 if (lenToClear > 0)
```

May be I don't uderstand something but it just works :O

**Comment by lzybkr** [comment] 2018-11-06 16:36
Feel free to submit a PR.

**Comment by MVKozlov** [comment] 2018-11-07 06:11
I'll wait until I'm at least understand what this code should do and test it on win10/linuxes :)

**Comment by s-shamesmuhametov-parc** [comment] 2019-03-04 08:13
It also reproduced on my Windows 8.1. When I navigate through my history containing multi-line commands
Commenting line _console.Write("\n");  helps. Thanks @MVKozlov 
It would be good to fix it PR

**Comment by daxian-dbw** [comment] 2023-04-28 02:05
I cannot reproduce this anymore on Windows Server 2012R2 (legacy mode), so it should have been fixed.

**Closed as completed by daxian-dbw** 2023-04-28 02:05 UTC
