### ISSUE TITLE
Running the initialization Policheck script causes the error

### ISSUE THREAD

**Issue by Ptomaine** [PowerShell/PSReadLine#369] opened 2016-04-07 23:30 UTC
Running the initialization Policheck script causes the error

---

![powershell](https://cloud.githubusercontent.com/assets/2706546/14369948/0a8b5aca-fcde-11e5-98b5-af7382a4e7c9.png)

Here is the output goes in text format:

PS C:\windows\system32> cd C:\PSClient

PS C:\PSClient> .\AweShell.ps1
Configuring AWE environment...

Oops, something went wrong.  Please report this bug with the details below.
## Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new

Last 0 Keys:

Exception:
System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by lzybkr** [comment] 2017-01-12 20:52
Most likely a dupe of #158, reopen with additional information if you disagree.

**Closed as completed by lzybkr** 2017-01-12 20:52 UTC
Labels: Resolution-Duplicate
