### ISSUE TITLE
ArgumentOutOfRangeException when attempting to git commit

### ISSUE THREAD

**Issue by zprobinson** [PowerShell/PSReadLine#3766] opened 2023-08-01 00:50 UTC
### Prerequisites

- [X] Write a descriptive title.
- [ ] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.yaml
Thank you!

### Environment
PSReadLine: 2.2.6
PowerShell: 7.3.6
OS: Microsoft Windows 10.0.19045
BufferWidth: 144
BufferHeight: 27

Last 200 Keys:

 m m i t Spacebar - m Spacebar " Ctrl+Backspace Ctrl+Backspace Ctrl+Backspace Ctrl+Backspace g i t Spacebar a d d Spacebar Ctrl+Backspace d i f f Spacebar * R e q u e s t D e t a i l V i e w M o d e l * Enter DownArrow g i t Spacebar a d d Spacebar * R e q u e s t D e t a i l V i e w M o d e l * Enter g i t Spacebar s t a t u s Enter g i t Spacebar c o m m i t Spacebar - m Spacebar " A d d Spacebar t h e Spacebar R e q u e s t e d F o r T N u m b e r Spacebar t o Spacebar t h e Spacebar C # Spacebar c l a s s e s . " Enter g i t Spacebar s t s Backspace a t u s Enter g i t Spacebar a d d Spacebar . Enter g i t Spacebar c o m m i t Spacebar - a m Spacebar " Ctrl+Backspace

### Exception

System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Actual value was 27.
   at System.ConsolePal.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Render()
   at Microsoft.PowerShell.PSConsoleReadLine.Kill(Int32 start, Int32 length, Boolean prepend)
   at Microsoft.PowerShell.PSConsoleReadLine.BackwardKillWord(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken, Nullable`1 lastRunStatus)
```

### Screenshot

I cleared the terminal after pasting the environment/exception information before running the script to get environment data... It was a foolhardy mistake.

I was doing simple `git add .` and `git commit -am "My Message here"`. I don't think there was anything special outside of my beautiful and new OhMyPosh setup.

### Environment data

```console
PS Version: 7.3.6
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.2.6
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 156
BufferHeight: 30
```

### Steps to reproduce

I'm not sure, I haven't been able to reproduce. I'm largely posting the bug report because the error message asked me politely.

### Expected behavior

No exception, I suppose.

### Actual behavior

The `git add .` command was successful, the `git commit -am "<message>"` command was unsuccessful. And then the error message popped up.

**Comment by daxian-dbw** [comment] 2023-08-01 06:03
We recently got several similar issue reports that seem to point to OhMyPosh module, see #3750 and #3722.
I suspect this one was also due to OhMyPosh. I will resolve this one as a duplicate of #3750.

**Closed as completed by daxian-dbw** 2023-08-01 06:03 UTC
Labels: Resolution-Duplicate

**Comment by zprobinson** [comment] 2023-08-01 13:56
> We recently got several similar issue reports that seem to point to OhMyPosh module, see #3750 and #3722. I suspect this one was also due to OhMyPosh. I will resolve this one as a duplicate of #3750.

Sounds good, thanks daxian!
