### ISSUE TITLE
No support for Emojis

### ISSUE THREAD

**Issue by viktorvoltz** [PowerShell/PSReadLine#3235] opened 2022-03-14 12:29 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.md
Thank you!

### Environment
PSReadLine: 2.1.0
PowerShell: 7.2.1
OS: Microsoft Windows 10.0.19042
BufferWidth: 122
BufferHeight: 10

Last 108 Keys

 g i t Spacebar s t a t u s Enter
 g i t Spacebar a d d Spacebar . Enter
 g i t Spacebar c o m m i t Spacebar - m Spacebar " r e m o v i n g Spacebar f r o m Spacebar l e g a c y Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace u p r o o t i n g Spacebar Backspace Backspace Backspace Backspace e d Spacebar f r o m Spacebar l e g a c y Spacebar � " Enter

```

### Exception
```
System.Text.EncoderFallbackException: Unable to translate Unicode character \\uD83E at index 36 to specified code page.   
   at System.Text.EncoderExceptionFallbackBuffer.Fallback(Char charUnknown, Int32 index)
   at System.Text.EncoderFallbackBuffer.InternalFallback(ReadOnlySpan`1 chars, Int32& charsConsumed)
   at System.Text.Encoding.GetBytesWithFallback(ReadOnlySpan`1 chars, Int32 originalCharsLength, Span`1 bytes, Int32 originalBytesLength, EncoderNLS encoder)
   at System.Text.Encoding.GetBytesWithFallback(Char* pOriginalChars, Int32 originalCharCount, Byte* pOriginalBytes, Int32 originalByteCount, Int32 charsConsumedSoFar, Int32 bytesWrittenSoFar, EncoderNLS encoder)
   at System.Text.Encoding.GetBytes(Char* pChars, Int32 charCount, Byte* pBytes, Int32 byteCount, EncoderNLS encoder)     
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at Microsoft.PowerShell.PSConsoleReadLine.<>c__DisplayClass83_0.<WriteHistoryRange>b__0()
   at Microsoft.PowerShell.PSConsoleReadLine.WithHistoryFileMutexDo(Int32 timeout, Action action)
   at Microsoft.PowerShell.PSConsoleReadLine.IncrementalHistoryWrite()
   at Microsoft.PowerShell.PSConsoleReadLine.MaybeAddToHistory(String result, List`1 edits, Int32 undoEditIndex, Boolean fromDifferentSession, Boolean fromInitialRead)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```
```


### Screenshot

![uproot](https://user-images.githubusercontent.com/45709308/158171072-617920a0-30b7-4498-a50c-81fc9ff9cbf2.png)
![uproot1](https://user-images.githubusercontent.com/45709308/158171093-b4ff672d-f7f0-4c4a-b672-c3b2920e017d.png)


### Environment data

```console
PowerShell 7.2.1
Visual Studio Code -version 1.64.2
Windows 10.0.19042
```

### Steps to reproduce

Try to commit with an emoji.
Example: `git commit -m "initial commit 👽"`

### Expected behavior

[master ######] initial commit 👽
...
...
...
...

### Environment
PSReadLine: 2.1.0
PowerShell: 7.2.1
OS: Microsoft Windows 10.0.19042
BufferWidth: 122
BufferHeight: 10

Last 108 Keys
```
 g i t Spacebar s t a t u s Enter
 g i t Spacebar a d d Spacebar . Enter
 g i t Spacebar c o m m i t Spacebar - m Spacebar " r e m o v i n g Spacebar f r o m Spacebar l e g a c y Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace u p r o o t i n g Spacebar Backspace Backspace Backspace Backspace e d Spacebar f r o m Spacebar l e g a c y Spacebar � " Enter

```

### Exception
```
System.Text.EncoderFallbackException: Unable to translate Unicode character \\uD83E at index 36 to specified code page.   
   at System.Text.EncoderExceptionFallbackBuffer.Fallback(Char charUnknown, Int32 index)
   at System.Text.EncoderFallbackBuffer.InternalFallback(ReadOnlySpan`1 chars, Int32& charsConsumed)
   at System.Text.Encoding.GetBytesWithFallback(ReadOnlySpan`1 chars, Int32 originalCharsLength, Span`1 bytes, Int32 originalBytesLength, EncoderNLS encoder)
   at System.Text.Encoding.GetBytesWithFallback(Char* pOriginalChars, Int32 originalCharCount, Byte* pOriginalBytes, Int32 originalByteCount, Int32 charsConsumedSoFar, Int32 bytesWrittenSoFar, EncoderNLS encoder)
   at System.Text.Encoding.GetBytes(Char* pChars, Int32 charCount, Byte* pBytes, Int32 byteCount, EncoderNLS encoder)     
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at Microsoft.PowerShell.PSConsoleReadLine.<>c__DisplayClass83_0.<WriteHistoryRange>b__0()
   at Microsoft.PowerShell.PSConsoleReadLine.WithHistoryFileMutexDo(Int32 timeout, Action action)
   at Microsoft.PowerShell.PSConsoleReadLine.IncrementalHistoryWrite()
   at Microsoft.PowerShell.PSConsoleReadLine.MaybeAddToHistory(String result, List`1 edits, Int32 undoEditIndex, Boolean fromDifferentSession, Boolean fromInitialRead)
at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

**Comment by daxian-dbw** [comment] 2022-03-14 19:16
Close as a duplicate of #949

**Closed as completed by daxian-dbw** 2022-03-14 19:16 UTC
