### ISSUE TITLE
System.Threading.WaitHandleCannotBeOpenedException: A WaitHandle with system-wide name 'PSReadLineHistoryFile_1117427230' cannot be created.

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PSReadLine#2410] opened 2021-04-29 17:15 UTC
```
> Start-DevPowerShell
WARNING: Start-DevPowerShell -NoNewWindow is currently implied in PowerShellCore edition https://github.com/PowerShell/PowerShell/issues/1543
PS /Users/rjmholt/Documents/Dev/Microsoft/PowerShell>
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.md
Thank you!
```

### Environment
PSReadLine: 2.1.0
PowerShell: 7.2.0-preview.5
OS: Darwin 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101
BufferWidth: 134
BufferHeight: 63

Last 0 Keys
```

```

### Exception
```
System.Threading.WaitHandleCannotBeOpenedException: A WaitHandle with system-wide name 'PSReadLineHistoryFile_1117427230' cannot be created. A WaitHandle of a different type might have the same name.
   at System.Threading.Mutex.CreateMutexCore(Boolean initiallyOwned, String name, Boolean& createdNew)
   at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name)
   at Microsoft.PowerShell.PSConsoleReadLine.DelayedOneTimeInitialize()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

## Steps to reproduce

1. `Start-DevPowerShell`
2. Await prompt

## Expected behavior

Get prompt

## Actual behavior

Throws in PSRL due to wait handle issue and falls back to default readline.

**Comment by iSazonov** [comment] 2021-04-29 17:23
I guess it can not create a temp file for the mutex.

**Comment by rjmholt** [comment] 2021-04-29 17:27
```
Exception             :
    Type           : System.Management.Automation.MethodInvocationException
    ErrorRecord    :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Exception calling "ReadLine" with "2" argument(s): "A WaitHandle with system-wide name
'PSReadLineHistoryFile_1117427230' cannot be created. A WaitHandle of a different type might have the same name."
            HResult : -2146233087
        CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : WaitHandleCannotBeOpenedException
        InvocationInfo        :
            ScriptLineNumber : 4
            OffsetInLine     : 5
            HistoryId        : -1
            ScriptName       : /Users/rjmholt/Documents/Dev/Microsoft/PowerShell/src/powershell-unix/bin/Debug/net6.0/osx-arm64/p
ublish/Modules/PSReadLine/PSReadLine.psm1
            Line             : [Microsoft.PowerShell.PSConsoleReadLine]::ReadLine($host.Runspace, $ExecutionContext)

            PositionMessage  : At /Users/rjmholt/Documents/Dev/Microsoft/PowerShell/src/powershell-unix/bin/Debug/net6.0/osx-arm64/pu
blish/Modules/PSReadLine/PSReadLine.psm1:4 char:5
                               +     [Microsoft.PowerShell.PSConsoleReadLine]::ReadLine($host.Runspace …
                               +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            PSScriptRoot     :
/Users/rjmholt/Documents/Dev/Microsoft/PowerShell/src/powershell-unix/bin/Debug/net6.0/osx-arm64/publish/Modules/PSReadLine
            PSCommandPath    : /Users/rjmholt/Documents/Dev/Microsoft/PowerShell/src/powershell-unix/bin/Debug/net6.0/osx-arm64/p
ublish/Modules/PSReadLine/PSReadLine.psm1
            CommandOrigin    : Internal
        ScriptStackTrace      : at PSConsoleHostReadLine, /Users/rjmholt/Documents/Dev/Microsoft/PowerShell/src/powershell-unix/bin/D
ebug/net6.0/osx-arm64/publish/Modules/PSReadLine/PSReadLine.psm1: line 4
    TargetSite     :
        Name          : ConvertToMethodInvocationException
        DeclaringType : System.Management.Automation.ExceptionHandlingOps, System.Management.Automation, Version=7.2.0.0,
Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    StackTrace     :
   at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Exception exception, Type typeToThrow,
String methodName, Int32 numArgs, MemberInfo memberInfo) in
/Users/rjmholt/Documents/Dev/Microsoft/PowerShell/src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs:line 2067
   at CallSite.Target(Closure , CallSite , Type , Object , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at System.Management.Automation.Interpreter.DynamicInstruction`4.Run(InterpretedFrame frame) in /Users/rjmholt/Documents/Dev/Micro
soft/PowerShell/src/System.Management.Automation/engine/interpreter/DynamicInstructions.Generated.cs:line 192
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame) in /Users/rjmholt/Document
s/Dev/Microsoft/PowerShell/src/System.Management.Automation/engine/interpreter/ControlFlowInstructions.cs:line 358
    Message        : Exception calling "ReadLine" with "2" argument(s): "A WaitHandle with system-wide name
'PSReadLineHistoryFile_1117427230' cannot be created. A WaitHandle of a different type might have the same name."
    Data           : System.Collections.ListDictionaryInternal
    InnerException :
        Type       : System.Threading.WaitHandleCannotBeOpenedException
        TargetSite :
            Name          : CreateMutexCore
            DeclaringType : System.Threading.Mutex
            MemberType    : Method
            Module        : System.Private.CoreLib.dll
        StackTrace :
   at System.Threading.Mutex.CreateMutexCore(Boolean initiallyOwned, String name, Boolean& createdNew)
   at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name)
   at Microsoft.PowerShell.PSConsoleReadLine.DelayedOneTimeInitialize()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken
cancellationToken)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at CallSite.Target(Closure , CallSite , Type , Object , Object )
        Message    : A WaitHandle with system-wide name 'PSReadLineHistoryFile_1117427230' cannot be created. A WaitHandle of a
different type might have the same name.
        Source     : System.Private.CoreLib
        HResult    : -2146233044
    Source         : System.Management.Automation
    HResult        : -2146233087
CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : WaitHandleCannotBeOpenedException
InvocationInfo        :
    ScriptLineNumber : 4
    OffsetInLine     : 5
    HistoryId        : -1
    ScriptName       : /Users/rjmholt/Documents/Dev/Microsoft/PowerShell/src/powershell-unix/bin/Debug/net6.0/osx-arm64/publish/M
odules/PSReadLine/PSReadLine.psm1
    Line             : [Microsoft.PowerShell.PSConsoleReadLine]::ReadLine($host.Runspace, $ExecutionContext)

    PositionMessage  : At /Users/rjmholt/Documents/Dev/Microsoft/PowerShell/src/powershell-unix/bin/Debug/net6.0/osx-arm64/publish/Mo
dules/PSReadLine/PSReadLine.psm1:4 char:5
                       +     [Microsoft.PowerShell.PSConsoleReadLine]::ReadLine($host.Runspace …
                       +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    PSScriptRoot     :
/Users/rjmholt/Documents/Dev/Microsoft/PowerShell/src/powershell-unix/bin/Debug/net6.0/osx-arm64/publish/Modules/PSReadLine
    PSCommandPath    : /Users/rjmholt/Documents/Dev/Microsoft/PowerShell/src/powershell-unix/bin/Debug/net6.0/osx-arm64/publish/M
odules/PSReadLine/PSReadLine.psm1
    CommandOrigin    : Internal
ScriptStackTrace      : at PSConsoleHostReadLine, /Users/rjmholt/Documents/Dev/Microsoft/PowerShell/src/powershell-unix/bin/Debug/net
6.0/osx-arm64/publish/Modules/PSReadLine/PSReadLine.psm1: line 4
```

**Comment by iSazonov** [comment] 2021-04-29 17:43
Is it really on MacOS?
I wonder if so https://github.com/dotnet/runtime/blob/6a5bc5315a6416de33655e127b5fbc5cb97a16a7/src/libraries/System.Private.CoreLib/src/System/Threading/Mutex.Unix.cs#L18

**Comment by daxian-dbw** [comment] 2021-04-29 18:07
This is a duplicate of #1464. It's likely a permission issue to `/private/tmp`. @rjmholt, please take a look at https://github.com/PowerShell/PSReadLine/issues/1464#issuecomment-631941511 to see if that fix your problem too.

**Comment by rjmholt** [comment] 2021-04-29 23:12
`/private/tmp` seems to have full permissions according to `stat` but not sure about `pwsh`:

![image](https://user-images.githubusercontent.com/7009879/116629294-b9ad3900-a905-11eb-9e38-4e57959253b4.png)

![image](https://user-images.githubusercontent.com/7009879/116629324-cc277280-a905-11eb-925a-79f52a64eaad.png)

**Comment by rjmholt** [comment] 2021-04-29 23:14
Also, I've been running PSRL without issue in PS 7.1.3. It's in dev builds where it fails.

**Comment by daxian-dbw** [comment] 2021-04-29 23:35
Wait a minute. The error message you had is different from the `/private/tmp` permission-issue one.
> A WaitHandle with system-wide name 'PSReadLineHistoryFile_1117427230' cannot be created. A WaitHandle of a different type might have the same name.

The permission-issue ones:
> The system cannot open the device or file specified.

I never saw this failure before. Can you collect some diagnostic information by following the instructions described in https://github.com/PowerShell/PSReadLine/issues/1464#issuecomment-631015069?

Can you also try opening the 7.1.3 `pwsh` within your PS 7.1.3 session?

**Comment by rjmholt** [comment] 2021-04-30 16:35
Location of the `/tmp` link:
```
PS /Users/rjmholt/Documents/Dev/Microsoft/PowerShell> readlink /tmp
private/tmp
```

Permissions on mutex dir:
```
rjmholt@Roberts-Mac-mini ~ % stat -f '%A' /tmp/.dotnet
777
rjmholt@Roberts-Mac-mini ~ % stat -f '%A' /tmp/.dotnet/shm
777
```

Results of mutex creation:
```
> ./src/powershell-unix/bin/Debug/net6.0/osx-arm64/publish/pwsh -noprofile -noninteractive                                            PowerShell 7.2.0-preview.5-20-g8f8ddc3fb76a03dad93f5664314c2795dd69f390                                                               Copyright (c) Microsoft Corporation.                                                                                                                                                                                                                                        https://aka.ms/powershell                                                                                                             Type 'help' to get help.                                                                                                                                                                                                                                                    PS /Users/rjmholt/Documents/Dev/Microsoft/PowerShell> $mutex = [system.threading.mutex]::new($false, "MyM")                           PS /Users/rjmholt/Documents/Dev/Microsoft/PowerShell> dir /tmp/.dotnet/shm -recurse                                                                                                                                                                                             Directory: /tmp/.dotnet/shm
UnixMode   User             Group                 LastWriteTime           Size Name
--------   ----             -----                 -------------           ---- ----
drwxrwxrwx rjmholt          wheel               4/30/2021 07:13             96 session778
drwxrwxrwx rjmholt          wheel               4/30/2021 09:33            128 session779

    Directory: /tmp/.dotnet/shm/session778

UnixMode   User             Group                 LastWriteTime           Size Name
--------   ----             -----                 -------------           ---- ----
-rw-rw-rw- rjmholt          wheel               4/30/2021 07:13           4096 PSReadLineHistoryFile_1117427230

    Directory: /tmp/.dotnet/shm/session779

UnixMode   User             Group                 LastWriteTime           Size Name
--------   ----             -----                 -------------           ---- ----
-rw-rw-rw- rjmholt          wheel               4/30/2021 09:33          16384 MyM
-rw-rw-rw- rjmholt          wheel               4/30/2021 09:31           4096 PSReadLineHistoryFile_1117427230

PS /Users/rjmholt/Documents/Dev/Microsoft/PowerShell> $mutex.Dispose()
```

The second mutex creation succeeds.

Opening `pwsh` within `pwsh` also works fine.

**Comment by rjmholt** [comment] 2021-04-30 20:08
Just to follow up, when I rebuilt PS to target `osx-x64` this went away. It was only running `osx-arm64` that this was an issue.

**Comment by daxian-dbw** [comment] 2021-05-01 00:05
That is really strange ... may be a mutex issue in .NET

**Comment by daxian-dbw** [comment] 2021-06-03 17:05
PowerShell doesn't support (release) the arm64 package for macOS today, even though our build script allows `osx-arm64` as the runtime value. Given that, I don't think there will be investigation to this issue until we're considering supporting arm64 for macOS. So I will close this issue for now.

**Closed as completed by daxian-dbw** 2021-06-03 17:05 UTC
Labels: Needs-More Investigation, Issue-Triaged
