### ISSUE TITLE
The parameter is incorrect

### ISSUE THREAD

**Issue by sakthiyuvaraj** [PowerShell/PSReadLine#355] opened 2016-03-15 23:52 UTC
---

Last 200 Keys:
 d Enter g i t Spacebar s t Enter g i t Spacebar d i f f Enter Spacebar g i t Spacebar a d d Spacebar . Enter g i t Spacebar l o g Spacebar - 2 Enter q i g t Ctrl+a Ctrl+k g i t Spacebar r e s e t Spacebar H E A D ~ 1 Enter g i t Spacebar s t Enter g i t Spacebar a d d Spacebar . Enter g i t Spacebar c Ctrl+a Ctrl+k Ctrl+l . . Ctrl+a Ctrl+k Ctrl+l . . Enter g i t Spacebar s t Enter g i t Spacebar a d d Spacebar . . Backspace Enter g i t Spacebar s t Enter g i t Spacebar d i f f Spacebar Alt+b Alt+d d t Spacebar - - c a c h e d Enter g i t Spacebar a d d Spacebar . Enter g i t Spacebar c i a Enter c l s Enter Enter d i r Enter k Enter Ctrl+a Ctrl+k Ctrl+l d Backspace Backspace d Backspace c l s Enter d i r Enter c l s Enter c l s Ctrl+a Ctrl+k Ctrl+l

Exception:
System.IO.IOException: The parameter is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.SetWindowPosition(Int32 left, Int32 top)
   at PSConsoleUtilities.PSConsoleReadLine.ClearScreen(Nullable`1 key, Object arg)
   at PSConsoleUtilities.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at PSConsoleUtilities.PSConsoleReadLine.InputLoop()
   at PSConsoleUtilities.PSConsoleReadLine.ReadLine(Runspace remoteRunspace, EngineIntrinsics engineIntrinsics)

**Comment by lzybkr** [comment] 2017-01-12 20:52
Most likely a dupe of #292, reopen with additional information if you disagree.

**Closed as completed by lzybkr** 2017-01-12 20:52 UTC
Labels: Resolution-Duplicate
