### ISSUE TITLE
Exception System.IndexOutOfRangeException was thrown

### ISSUE THREAD

**Issue by jmickey8080** [PowerShell/PSReadLine#508] opened 2017-02-23 20:06 UTC
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow m a t c h i n g RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow LeftArrow Spacebar t a b l e . RightArrow Enter
 g i t Spacebar a d d Spacebar - A Enter
 UpArrow UpArrow Enter
 g i t Spacebar [ Backspace Backspace Backspace Backspace Backspace Backspace r e p o Spacebar r e v i e w Spacebar - - t i t l e Spacebar " " LeftArrow [ O O B ] Spacebar A d d Spacebar W a t m Spacebar p r e f i x Spacebar t o Spacebar t a b l e Spacebar n a m e Spacebar f o r Spacebar A I M S Spacebar r u l e s Spacebar m a t c h i n g Spacebar W a t m D n s E v e n t L o g Spacebar t a b l e . RightArrow Spacebar - c Spacebar o u t g o i n g Spacebar - r Spacebar a l e k Backspace Backspace Backspace l g

Exception:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by lzybkr** [comment] 2017-02-24 02:50
Did you resize after last having pressed `Enter`?  If so, I think this is another symptom of a known issue.

**Comment by jmickey8080** [comment] 2017-03-09 06:12
Yes, I believe so. It have not been able to repro it since. This was in Cmder if that makes a difference.

**Comment by lzybkr** [comment] 2017-04-11 19:12
Different symptom, but most likely a dupe of #292, reopen with additional information if you disagree.

**Closed as completed by lzybkr** 2017-04-11 19:12 UTC
Labels: Resolution-Duplicate
