### ISSUE TITLE
Allow PredictionListView suggestion count to auto-adjust based on the height of the console

### ISSUE THREAD

**Issue by ChristopherHaws** [PowerShell/PSReadLine#3557] opened 2023-01-31 20:28 UTC
### Prerequisites

- [X] Write a descriptive title.

### Description of the new feature/enhancement

I love the `Set-PSReadLineOption -PredictionViewStyle ListView` option of PSReadLine nad rely on it everyday. One issue I run into a lot is when I am in a code editor (VS Code, Visual Studio, Rider, etc) and I have my terminal open, usually the terminal is at the bottom of my screen and shrunk down to only a few lines visible which results in this warning:

```
WARNING: The prediction 'ListView' is temporarily disabled because the current window size of the console is too small. To use the 'ListView', please make sure the 'WindowWidth' is not less than '54' and the 'WindowHeight' is not less than '15'.
```

![image](https://user-images.githubusercontent.com/5934505/215873598-56239bc9-255b-4e70-a34a-c34741dbdb28.png)

While it is true that the window does not have very many lines visible, I still feel like there is enough room there to show at least a few items in the list view.

Instead of having a hard cap of 10 suggestions, I think the suggestion count should auto-adjust based on the size of the window.

### Proposed technical implementation details (optional)

Currently there is a `MinWindowHeight` of 15 lines. Anything less than this and the `PredictionListView` simply stops running.

Instead of having a hard cap of 15 lines visible, I think the suggestion count should simply decrease for smaller windows. There is currently a hard upper limit (`ListMaxCount`) of 10 suggestions. I could see there being a minimum suggestion count (`ListMinCount`) of maybe 3 suggestions to prevent there from being any weird behavior.

**Comment by ChristopherHaws** [comment] 2023-01-31 22:08
I created a branch that has this logic working in it. I haven't made a PR because I didn't add any tests. Before I do, I would like to know if this is something that would potentially get merged or not.

https://github.com/ChristopherHaws/PSReadLine/tree/chaws/adaptive-prediction-list

**Comment by iSazonov** [comment] 2023-02-01 03:36
@ChristopherHaws It is better to pull draft PR.

**Comment by ChristopherHaws** [comment] 2023-02-01 03:51
@iSazonov Sure. Created :)

**Comment by daxian-dbw** [comment] 2023-02-06 17:57
Thanks @ChristopherHaws. Close this one as a duplicate of #3563

**Closed as completed by daxian-dbw** 2023-02-06 17:57 UTC
Labels: Resolution-Duplicate, Issue-Enhancement

**Comment by daxian-dbw** [comment] 2023-02-06 18:20
@ChristopherHaws please see https://github.com/PowerShell/PSReadLine/issues/3563#issuecomment-1419544968 for a demo of the work so far.

**Comment by ChristopherHaws** [comment] 2023-02-06 19:48
Sure, even though my issue was created first ;)

Thanks for the update and awesome work! :)
