### ISSUE TITLE
Unable to translate Unicode character \\uD83D

### ISSUE THREAD

**Issue by 1oneand1** [PowerShell/PSReadLine#3847] opened 2023-10-24 17:06 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong.
### Environment
PSReadLine: 2.2.6
PowerShell: 7.3.8
OS: Microsoft Windows 10.0.22621
BufferWidth: 120
BufferHeight: 9001

Last 69 Keys:

 c d Spacebar ~ Enter
 d i r Enter
 c d Spacebar P y Tab Enter
 c d Spacebar P Tab Enter
 d i r Enter
 . / b l a Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace p y t h o n Spacebar b l a s t _ o f f . p y Enter
 � � � Backspace Backspace Backspace Backspace � Enter


### Exception

System.Text.EncoderFallbackException: Unable to translate Unicode character \\uD83D at index 0 to specified code page.
   at System.Text.EncoderExceptionFallbackBuffer.Fallback(Char charUnknown, Int32 index)
   at System.Text.Encoding.GetBytesWithFallback(ReadOnlySpan`1 chars, Int32 originalCharsLength, Span`1 bytes, Int32 originalBytesLength, EncoderNLS encoder)
   at System.Text.Encoding.GetBytesWithFallback(Char* pOriginalChars, Int32 originalCharCount, Byte* pOriginalBytes, Int32 originalByteCount, Int32 charsConsumedSoFar, Int32 bytesWrittenSoFar, EncoderNLS encoder)
   at System.Text.EncoderNLS.GetBytes(Char* chars, Int32 charCount, Byte* bytes, Int32 byteCount, Boolean flush)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at Microsoft.PowerShell.PSConsoleReadLine.<>c__DisplayClass99_0.<WriteHistoryRange>b__0()
   at Microsoft.PowerShell.PSConsoleReadLine.WithHistoryFileMutexDo(Int32 timeout, Action action)
   at Microsoft.PowerShell.PSConsoleReadLine.WriteHistoryRange(Int32 start, Int32 end, Boolean overwritten)
   at Microsoft.PowerShell.PSConsoleReadLine.IncrementalHistoryWrite()
   at Microsoft.PowerShell.PSConsoleReadLine.MaybeAddToHistory(String result, List`1 edits, Int32 undoEditIndex, Boolean fromDifferentSession, Boolean fromInitialRead)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken, Nullable`1 lastRunStatus)
```

### Screenshot

![image](https://github.com/PowerShell/PSReadLine/assets/123364703/aa9c204c-e4c2-4b73-aad6-3fa6c624de9d)

### Environment data

```console
PS Version: 7.3.8
PS HostName: ConsoleHost
PSReadLine Version: 2.2.6
PSReadLine EditMode: Windows
OS: 10.0.22621.2338 (WinBuild.160101.0800)
BufferWidth: 120
BufferHeight: 9001
```

### Steps to reproduce

🚀 This unicode character doesn't appear in the terminal input but can be displayed as a output in a Python code print function.

### Expected behavior

To be able to be  taken as a terminal input like it is showed as an output.

### Actual behavior

It can't be displayed as an input.

**Comment by daxian-dbw** [comment] 2023-10-24 17:13
@1oneand1 How did you type the character🚀 to the command line? Did you right click the mouse to trigger the Paste operation?
Can you try <kbd>ctrl+v</kbd> to paste the emoji character and see if that works?

**Comment by 1oneand1** [comment] 2023-10-24 17:20
> @1oneand1 How did you type the character🚀 to the command line? Did you right click the mouse to trigger the Paste operation? Can you try ctrl+v to paste the emoji character and see if that works?

I typed it buy Copying it and Paste it. I tryed again and with ctrl+v worked this time. :)

**Comment by daxian-dbw** [comment] 2023-10-24 17:34
Thanks for trying `ctrl+v` and confirming it works.
Right-click pasting has various known issues including omitting part of a Unicode character. In your case, the low surrogate of the emoji surrogate pair got lost by the right-click pasting. It's always recommended to use `ctrl+v` for pasting in PowerShell.

I will resolve this issue as a duplicate of https://github.com/PowerShell/PSReadLine/issues/579

**Closed as completed by daxian-dbw** 2023-10-24 17:34 UTC
