### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by kai-low256** [PowerShell/PSReadLine#2258] opened 2021-02-28 07:52 UTC
![image](https://user-images.githubusercontent.com/68333641/109411415-05229400-79f6-11eb-8ea6-12aa1a3a30bb.png)

an error that I get once in a while

**Comment by daxian-dbw** [comment] 2021-03-05 18:59
This is a duplicate of #1306, and was fixed. Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.

**Closed as completed by daxian-dbw** 2021-03-05 18:59 UTC
