### ISSUE TITLE
System.MissingMethodException: Method not found

### ISSUE THREAD

**Issue by tomgron** [PowerShell/PSReadLine#2291] opened 2021-03-10 11:25 UTC
### Environment
PSReadLine: 2.2.0-beta1
PowerShell: 7.2.0-preview.3
OS: Microsoft Windows 10.0.19042
BufferWidth: 120
BufferHeight: 30

Last 8 Keys
```
 . $ p r o f Tab Enter

```

### Exception
```
System.MissingMethodException: Method not found: 'Void System.Management.Automation.Subsystem.CommandPrediction.OnCommandLineAccepted(System.Collections.Generic.IReadOnlyList`1<System.String>)'.
   at Microsoft.PowerShell.PSConsoleReadLine.Microsoft.PowerShell.Internal.IPSConsoleReadLineMockableMethods.OnCommandLineAccepted(IReadOnlyList`1 history)
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionViewBase.OnCommandLineAccepted(String commandLine)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

**Comment by daxian-dbw** [comment] 2021-03-10 19:52
This is a duplicate of #2221. Please upgrade to use the 2.2.0-beta2 version of PSReadLine with `7.2.0-preview.3`.

**Closed as completed by daxian-dbw** 2021-03-10 19:52 UTC
