### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Marjedad** [PowerShell/PSReadLine#2569] opened 2021-06-12 04:10 UTC
Please be promptly justified this bug... Thank You

**Comment by Marjedad** [comment] 2021-06-12 04:11
Last 124 Keys:
 & Space C : / U s e r s / M a r j e d a d / A p p D a t a / L o c a l / P r o g r a m s / P y t h o n / P y t h o n 3 9 / p y t h o n . e x e Space " d : / E d i t i n g / B e l a j a r Space P y t h o n / B u k u / 0 0 1 Space K e r a n g k a Space F i l e . p y " Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the 
console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)       
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor) 
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment] 2021-07-01 18:44
No environment data is provided to help the investigation. The issue looks like a duplicate of #1306. Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.

**Closed as completed by daxian-dbw** 2021-07-01 18:44 UTC

**Comment by Marjedad** [comment] 2021-07-01 23:02
Ia this serious ?

Pada tanggal Jum, 2 Jul 2021 01.44, Dongbo Wang ***@***.***>
menulis:
