### ISSUE TITLE
Crash on 'echo 😃'

### ISSUE THREAD

**Issue by mikemaccana** [PowerShell/PSReadLine#952] opened 2019-06-28 14:32 UTC
PSReadline as shipped in Powershell 6.2.1.

(Markdown hates the triple-backtick below so I removed them)

```
$ echo �

Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 7 Keys:
(Triple backtick removed by Mike)
e c h o Space � Enter

(Triple backtick removed by Mike)

Exception:
(Triple backtick removed by Mike)

System.Text.EncoderFallbackException: Unable to translate Unicode character \\uD83D at index 5 to specified code page.
  at System.Text.EncoderExceptionFallbackBuffer.Fallback(Char charUnknown, Int32 index)                                   at System.Text.EncoderFallbackBuffer.InternalFallback(Char ch, Char*& chars)                                            at System.Text.UTF8Encoding.GetBytes(Char* chars, Int32 charCount, Byte* bytes, Int32 byteCount, EncoderNLS baseEncoder)                                                                                                                        at System.Text.EncoderNLS.GetBytes(Char[] chars, Int32 charIndex, Int32 charCount, Byte[] bytes, Int32 byteIndex, Boolean flush)                                                                                                                at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)                                              at System.IO.StreamWriter.Dispose(Boolean disposing)                                                                    at System.IO.TextWriter.Dispose()
  at Microsoft.PowerShell.PSConsoleReadLine.<>c__DisplayClass81_0.<WriteHistoryRange>b__0()
  at Microsoft.PowerShell.PSConsoleReadLine.WithHistoryFileMutexDo(Int32 timeout, Action action)
  at Microsoft.PowerShell.PSConsoleReadLine.WriteHistoryRange(Int32 start, Int32 end, Func`2 fileOpener)
```

**Comment by mkontani** [comment] 2019-07-03 16:34
maybe this issue is dup of https://github.com/PowerShell/PSReadLine/issues/949 ?

**Comment by daxian-dbw** [comment] 2019-07-16 18:08
Close as a duplicate of #949

**Closed as completed by daxian-dbw** 2019-07-16 18:08 UTC
Labels: Resolution-Duplicate
