### ISSUE TITLE
System.ArgumentException: Destination array was not long enough. Check destIndex and length, and the array's lower bounds.

### ISSUE THREAD

**Issue by karol-tarasiuk** [PowerShell/PSReadLine#491] opened 2017-01-12 07:38 UTC
Last 1 Keys:
 p

Exception:
System.ArgumentException: Destination array was not long enough. Check destIndex and length, and the array's lower bounds.
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Array destinationArray, Int32 length)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by lzybkr** [comment] 2017-01-12 19:08
Dupe of #292.

**Closed as completed by lzybkr** 2017-01-12 19:08 UTC
Labels: Resolution-Duplicate
