### ISSUE TITLE
Help with VC Code

### ISSUE THREAD

**Issue by hyj5016** [PowerShell/PSReadLine#1663] opened 2020-07-15 00:02 UTC
Hello, 

I'm having this error come up in my terminal. Not sure what is going on. Any suggestions?

Regards,
Helyne 

Last 200 Keys:
 r a m s \ P y t h o n \ P y t h o n 3 8 - 3 2 \ p y t
h o n . e x e ' Space ' c : \ U s e r s \ h j o s e p h \ . v s c o d e \ e x t e n s i o n s \ m s - p y t h
o n . p y t h o n - 2 0 2 0 . 6 . 9 1 3 5 0 \ p y t h o n F i l e s \ l i b \ p y t h o n \ d e b u g p y \ l
a u n c h e r ' Space ' 5 5 2 2 8 ' Space ' - - ' Space ' y : \ u s e r s \ h j o s e p h \ A l l Space P y t
h o n Space P r a c t i c e . p y ' Space Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)(Nullable`1 key, Object arg)                           Key(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boo)lean ignoreIfNoAction, Object arg)                     unspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop(----------------)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by daxian-dbw** [comment] 2020-07-16 18:46
What version of PSReadLine are you using? It's likely a duplicate of #1306, which was fixed.  Please upgrade to the 2.0.2 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions.

Please let me know if you already on the latest PSReadLine version and ran into this issue.

**Closed as completed by daxian-dbw** 2020-07-16 18:46 UTC
Labels: Resolution-Duplicate
