### ISSUE TITLE
Oops, something went wrong.  Please report this bug with the details below.

### ISSUE THREAD

**Issue by halter73** [PowerShell/PSReadLine#250] opened 2015-06-19 19:02 UTC
```
Last 200 Keys:
 Backspace s t Tab R e Tab Tab Tab Tab Enter g i t Spacebar f e t c h Enter g i t Spacebar d i f f Enter . Backspace . / b u Tab Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace l s Spacebar ~ / . d Tab r Tab Enter . / b u Tab Backspace . s Tab Enter . \ b Tab Tab Tab Enter d n v m Spacebar l i s t Enter UpArrow UpArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace c d Spacebar s s Backspace Tab Tab Tab M i Tab Enter d n u Spacebar b u i l d Backspace Backspace Backspace Backspace Backspace l i s t Enter UpArrow Spacebar - A Enter UpArrow Backspace a Enter d n - Backspace u Spacebar - - h e l p Enter d n v m Spacebar u p g r e a Backspace Backspace a d e Spacebar - r Spacebar C l r Enter UpArrow LeftArrow LeftArrow LeftArrow LeftArrow Spacebar - u Enter UpArrow PageUp

Exception:
System.IO.IOException: The parameter is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ScrollDisplayUp(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, Object reserved)
-----------------------------------------------------------------------
```

**Comment by lzybkr** [comment] 2015-06-19 19:07
Dupe of #232, assuming this is in full screen mode.

**Closed as completed by lzybkr** 2015-06-19 19:07 UTC
Labels: Resolution-Duplicate
