### ISSUE TITLE
System.IO.IOException: The handle is invalid.

### ISSUE THREAD

**Issue by rs38** [PowerShell/PSReadLine#277] opened 2015-09-01 15:48 UTC
within 2106 TP3 
docker run "microsoft/iis"

ops, something went wrong.  Please report this bug with the details below.
## Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new

Last 0 Keys:
Last 0 Keys:

Exception:
System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by lzybkr** [comment] 2016-01-02 21:08
Duplicate of #158.

**Closed as completed by lzybkr** 2016-01-02 21:08 UTC
Labels: Issue-Bug, Resolution-Duplicate
