### ISSUE TITLE
PSReadLine Issues over ssh using the backspace key PowerShell Core.

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PSReadLine#678] opened 2018-04-28 01:48 UTC
The issue when working over ssh from Windows to Linux.  Other than that, is working Ok in both Linux and Windows.

Environment data
----------------
Linux OS:
```
maxt@mars:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 17.10"
VERSION_ID="17.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=artful
UBUNTU_CODENAME=artful
```

Steps to reproduce or exception report
--------------------------------------
Just start type a cmd and then use the backspace key.

![ssh_psreadline_01_2018-04-27_21-40-16](https://user-images.githubusercontent.com/19892435/39390561-49b1779a-4a64-11e8-96e8-cf89c92ca74d.jpg)

**Comment by lzybkr** [comment] 2018-05-03 22:51
I believe this was fixed by #661, if you wanted to verify, you could grab a build out of appveyor.

**Comment by daxian-dbw** [comment] 2020-01-31 20:14
I verified with the `2.0.0-rc2` version of PSReadLine, and cannot reproduce the issue.

**Closed as completed by daxian-dbw** 2020-01-31 20:14 UTC

**Comment by MaximoTrinidad** [comment] 2020-02-01 20:13
It's working!
Thanks
