### ISSUE TITLE
Invalid Characters causing System.Text.EncoderFallbackException

### ISSUE THREAD

**Issue by void-en** [PowerShell/PSReadLine#1704] opened 2020-07-26 17:10 UTC
### Steps
1. Open a new PowerShell window
2. Press [Windows+.] to open emoji menu
3. Type [P][r][e][t][z][e][l][Enter] to insert a pretzel
4. Press [Esc] to leave the emoji menu
5. Press [Backspace] to remove 1 character from the Emoji
6. Press [Enter]

If you wish to repeat the exception, enter a full pretzel again first, then enter half a pretzel.

### Bonus
7. After the crash, when back on a normal prompt, [Ctrl+A] will select all text in the shell, instead of just the command.

### Characters
A pretzel, should you need it: 🥨
The first half of the pretzel: �

**Comment by daxian-dbw** [comment] 2020-07-26 17:38
@voidbiscuit Thanks for reporting the issue. This is a duplicate of #949

**Closed as completed by daxian-dbw** 2020-07-26 17:38 UTC
Labels: Resolution-Duplicate
