### ISSUE TITLE
🐞 Bugged using windows emoji

### ISSUE THREAD

**Issue by MrAyush** [PowerShell/PSReadLine#1794] opened 2020-09-08 18:45 UTC
### Environment
PSReadLine: 2.0.4
PowerShell: 5.1.19041.1
OS: Microsoft Windows 10.0.19041
BufferWidth: 149
BufferHeight: 12

Last 200 Keys
```
 e r Spacebar Backspace Backspace Backspace Backspace m b e r LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow Backspace Backspace Backspace Backspace Backspace Backspace N o w Spacebar RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow LeftArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace L a s t Spacebar P a t h Spacebar i s Spacebar Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace S a v i n Spacebar g Backspace Backspace Spacebar Backspace g Spacebar t h e Spacebar L o a s Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace P a t h Spacebar S a v e d 
LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow Spacebar i n Spacebar J S N O Backspace Backspace O N LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow Spacebar LeftArrow � End LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow RightArrow 
LeftArrow LeftArrow RightArrow LeftArrow LeftArrow RightArrow RightArrow RightArrow End Enter

```

### Exception
```
System.Text.EncoderFallbackException: Unable to translate Unicode character \uD83D at index 15 to specified code page.
   at System.Text.EncoderExceptionFallbackBuffer.Fallback(Char charUnknown, Int32 index)
   at System.Text.EncoderFallbackBuffer.InternalFallback(Char ch, Char*& chars)
   at System.Text.UTF8Encoding.GetBytes(Char* chars, Int32 charCount, Byte* bytes, Int32 byteCount, EncoderNLS baseEncoder)
   at System.Text.EncoderNLS.GetBytes(Char[] chars, Int32 charIndex, Int32 charCount, Byte[] bytes, Int32 byteIndex, Boolean flush)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at Microsoft.PowerShell.PSConsoleReadLine.<>c__DisplayClass83_0.<WriteHistoryRange>b__0()
   at Microsoft.PowerShell.PSConsoleReadLine.WithHistoryFileMutexDo(Int32 timeout, Action action)
   at Microsoft.PowerShell.PSConsoleReadLine.MaybeAddToHistory(String result, List`1 edits, Int32 undoEditIndex, Boolean fromDifferentSession, Boolean fromInitialRead)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)     
```

**Comment by daxian-dbw** [comment] 2020-09-10 18:55
Close as a duplicate of #949

**Closed as completed by daxian-dbw** 2020-09-10 18:55 UTC
Labels: Resolution-Duplicate
