### ISSUE TITLE
"<"

### ISSUE THREAD

**Issue by Traiyi** [PowerShell/PSReadLine#893] opened 2019-04-14 11:28 UTC
Environment data
----------------

Steps to reproduce or exception report
--------------------------------------
-----------------------------------------------------------------------
上 89 个密钥:
 UpArrow UpArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow Backspace Backspace < Enter
 UpArrow UpArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 s q l Tab Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace i Tab Space . d u Tab m Tab p Tab Backspace Backspace Backspace Backspace Backspace Backspace Backspace e Space m y d a Backspace Backspace Backspace Backspace d a t a b a s e . d b Space <

异常:
System.ArgumentOutOfRangeException: 该值必须大于或等于零，且必须小于控制台缓冲区在该维度的大小。
参数名: left
实际值是 -1。
   在 System.Console.SetCursorPosition(Int32 left, Int32 top)
   在 Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   在 Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   在 Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   在 Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   在 Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   在 Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   在 Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   在 Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment] 2019-07-16 22:36
Close as a duplicate of #875

**Closed as completed by daxian-dbw** 2019-07-16 22:36 UTC
Labels: Resolution-Duplicate, OutOfRange
