### ISSUE TITLE
Cannot bulk change file names in Windows 10

### ISSUE THREAD

**Issue by ljbnomad** [PowerShell/PSReadLine#1425] opened 2020-03-26 04:15 UTC
PS D:\AA_LISA\resources\games\SIMS\MODS\ZZ_New\furnish0323\replace>
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 2 Keys:
 Backspace Ctrl+v

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Paste(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS D:\AA_LISA\resources\games\SIMS\MODS\ZZ_New\furnish0323\replace> get-childitem *.package | foreach {rename-item $_ $_.name.replace("[","")}

**Comment by daxian-dbw** [comment] 2020-03-26 06:42
From the bug report template:
```
The maintainer may close your issue without further explanation or engagement if:
- You delete this entire template and go your own path;
```
So, please follow the bug report template to provide **environment data** and **repro step** the next time.

As for this issue, it's a duplicate of #1306 and was fixed in the latest version. Please check out #1306 for more information.

**Closed as completed by daxian-dbw** 2020-03-26 06:42 UTC
Labels: Resolution-Duplicate
