### ISSUE TITLE
Bug: Oops, something went wrong. After Enter a partial 2-Char Unicode

### ISSUE THREAD

**Issue by bugfrei** [PowerShell/PSReadLine#3756] opened 2023-07-26 01:29 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Exception by enter a incomplete 2-Char Unicode (Paste an Unicode, delete the 2th Char, then enter).
```

### Screenshot

<img width="508" alt="SCR-20230726-dvvg" src="https://github.com/PowerShell/PSReadLine/assets/71234951/6c962d4d-4c20-4151-9a38-960a7efa4118">
<br />
<img width="107" alt="SCR-20230726-dvmd" src="https://github.com/PowerShell/PSReadLine/assets/71234951/7e3df66f-e7a3-4f50-a502-292fdca2d2e6">

And then press Enter

### Environment data

```console
PS Version: 7.3.4
PS HostName: ConsoleHost
PSReadLine Version: 2.2.6
PSReadLine EditMode: Vi
OS: Darwin MBP-von-Carsten.fritz.box 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000 arm64
BufferWidth: 120
BufferHeight: 32
```

### Steps to reproduce

You can reach the exception with these steps:

- Copy an 2-Char Unicode like 👆
- Paste it into the PowerShell
- Delete 1 Character (press Backspace 1 times)
  --> it must displayed 1 <?> Symbol (or two, but left was light, right was dark for autocomplete with cursor right)
- Press Enter

### Expected behavior

No exception, and

�:: The term '�:' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

### Actual behavior

Exception and then press Enter the "�:: The term '�:' is not recognized..." error comes.

**Comment by daxian-dbw** [comment] 2023-07-26 05:35
Please share the exception stack trace you got when running into this issue.
I believe this is a duplicate of #2358, but would love to have your stack trace to confirm.

**Comment by daxian-dbw** [comment] 2023-07-27 16:29
In this particular case, deletion in PSReadLine doesn't handle surrogate pair, and thus deletes half of the emoji. It should delete the whole emoji in this case with one "delete" operation.

**Comment by daxian-dbw** [comment] 2023-07-27 16:30
Close as a duplicate of #1587

**Closed as completed by daxian-dbw** 2023-07-27 16:30 UTC
Labels: Issue-Emoji
