### ISSUE TITLE
Error during start-process powershell

### ISSUE THREAD

**Issue by peter-lang** [PowerShell/PSReadLine#548] opened 2017-07-25 17:12 UTC
Reproduce:
---------------
I tried to set up a windows environment, using gitlab-ci-multi-runner to drive my test automation. While trying, I set my gitlab-ci-multi-runner service to log-on as a specific user, and executed the command:
start-process powershell "noexit" -credential $cred
where $cred is the specific users credential.

Environment data
----------------
PS version: 5.0.10586.1007
PSReadline version: 1.1
os: 10.0.10586.0 (th2_release.151029-1700)
PS file version: 10.0.10586.0 (th2_release.151029-1700)

Steps to reproduce or exception report
--------------------------------------
Exception:
System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by Rick-2CA** [comment] 2017-08-16 15:55
I'm getting the same behavior on PS 5.1.14409.1012 on Windows 8.1 with PSReadline v1.2.

Doing a 'Run as different user' manually does not reproduce the behavior.  

Edit/Update:
Typing in the respective consoles is somehow connected.  When I type into the original window no text comes up.  When I then type into the new window (different user) the command I typed into the original will type out with each corresponding keystroke in the new window.  This works in reverse too where something typed in the new window won't show until you type into the old.

**Comment by lzybkr** [comment] 2017-08-16 17:48
I believe this is fixed, but I haven't produced a release in a long time and the fix is not in the Windows code base.

If you build the latest from this repo, the error should go away, but PSReadline won't work, it is just throwing and exception so that the console host falls back to reading from StandardInput.

**Comment by lzybkr** [comment] 2017-10-17 01:56
Duplicate of #158.

**Closed as completed by lzybkr** 2017-10-17 01:56 UTC
Labels: Resolution-Duplicate
