### ISSUE TITLE
System.Text.EncoderFallbackException returned when string parameter contains emoji "🌿"

### ISSUE THREAD

**Issue by mateusz-dobrowolny** [PowerShell/PSReadLine#4133] opened 2024-08-21 16:21 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
### Environment
PSReadLine: 2.3.5+2cc85806c561a9395751a96a818e8ff1592d19f7
PowerShell: 7.4.4
OS: Microsoft Windows 10.0.19045
BufferWidth: 237
BufferHeight: 9001

Last 200 Keys:
[Does not matter - I pasted string into PS console]

### Exception

System.Text.EncoderFallbackException: Unable to translate Unicode character \\uD83C at index 7 to specified code page.
   at System.Text.EncoderExceptionFallbackBuffer.Fallback(Char charUnknown, Int32 index)
   at System.Text.Encoding.GetBytesWithFallback(ReadOnlySpan`1 chars, Int32 originalCharsLength, Span`1 bytes, Int32 originalBytesLength, EncoderNLS encoder, Boolean throwForDestinationOverflow)
   at System.Text.Encoding.GetBytesWithFallback(Char* pOriginalChars, Int32 originalCharCount, Byte* pOriginalBytes, Int32 originalByteCount, Int32 charsConsumedSoFar, Int32 bytesWrittenSoFar, EncoderNLS encoder)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at Microsoft.PowerShell.PSConsoleReadLine.<>c__DisplayClass103_0.<WriteHistoryRange>b__0()
   at Microsoft.PowerShell.PSConsoleReadLine.WithHistoryFileMutexDo(Int32 timeout, Action action)
   at Microsoft.PowerShell.PSConsoleReadLine.WriteHistoryRange(Int32 start, Int32 end, Boolean overwritten)
   at Microsoft.PowerShell.PSConsoleReadLine.IncrementalHistoryWrite()
   at Microsoft.PowerShell.PSConsoleReadLine.MaybeAddToHistory(String result, List`1 edits, Int32 undoEditIndex, Boolean fromDifferentSession, Boolean fromInitialRead)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken, Nullable`1 lastRunStatus)
```

### Screenshot

N/A

### Environment data

```console
PS Version: 7.4.4
PS HostName: ConsoleHost
PSReadLine Version: 2.3.5
PSReadLine EditMode: Windows
OS: 10.0.19041.320 (WinBuild.160101.0800)
BufferWidth: 237
BufferHeight: 9001
```

### Steps to reproduce

I have a script called "s.ps1" which accepts one parameter of type string
My string parameter was:
xxxx/� - which was a result of copy text printed in console.

Original UTF character used is: 🌿

### Expected behavior

This is valid unicode character, I'd expect error handling if this is something PS cannot parse.
I can parse this when not sending as parameter to ps1 script.

### Actual behavior

The exception above is printed in PS console

**Comment by daxian-dbw** [comment] 2024-08-21 21:23
Duplicate of #1329

**Closed as completed by daxian-dbw** 2024-08-21 21:23 UTC
Labels: Resolution-Duplicate

**Comment by mateusz-dobrowolny** [comment] 2024-08-22 07:13
@daxian-dbw  Ooooooooops, I haven't found that issue. Thanks.
