### ISSUE TITLE
Error in Visual Code

### ISSUE THREAD

**Issue by Viraj-Rana008** [PowerShell/PSReadLine#1445] opened 2020-04-01 11:56 UTC
Last 200 Keys:
 . b a t ' Space ' C : \ P r o g r a m Space F i l e s \ J a v a \ j d k - 1 3 . 0 . 2 \ b i n \ j a v a . e x e ' Space ' - - e n a b l e - p r e v i e w ' Space ' - D f i l e . e n c o d i n g = U T F - 8 ' Space ' - c p ' Space ' C : \ U s e r s \ t o d f t \ A p p D a t a \ L o c a l \ T e m p \ v s c o d e s w s _ 4 2 f 2 4 \ j d t _ w s \ j d t . l s - j a v a - p r o j e c t \ b i n ' Space ' H e a p _ i m p l i ' Space Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or 
equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -2.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object 
arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by iSazonov** [comment] 2020-04-01 14:02
See #1306

**Comment by daxian-dbw** [comment] 2020-04-01 21:01
This is a duplicate of  #1306

**Closed as completed by daxian-dbw** 2020-04-01 21:01 UTC

**Comment by Viraj-Rana008** [comment] 2020-04-02 15:36
ok.
