### ISSUE TITLE
Using no EN localization, no history and no colors

### ISSUE THREAD

**Issue by FXEGIT** [PowerShell/PSReadLine#813] opened 2018-11-13 15:06 UTC
On a Windows 10 fr/FR, since latest fall update (the bad 1809 update), there is no more history in PowerShell and no colors while typing.

Environment data
----------------

**PS version: 5.1.17763.1**
```
Split-Path : Impossible de lier l'argument au paramètre « Path », car il a la valeur Null.
Au caractère Ligne:5 : 44
+ ... et-Content "$(Split-Path -Parent (Get-Module PSReadLine).Path)\PSRead ...
+                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData : (:) [Split-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.SplitPathCommand
 
Get-Content : Impossible de trouver le chemin d'accès « C:\PSReadLine.psd1 », car il n'existe pas.
Au caractère Ligne:5 : 10
+     $m = Get-Content "$(Split-Path -Parent (Get-Module PSReadLine).Pa ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\PSReadLine.psd1:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand
```
 
**PSReadline version: 
os: 10.0.17763.107 (WinBuild.160101.0800)
PS file version: 10.0.17763.107 (WinBuild.160101.0800)**

Steps to reproduce or exception report
--------------------------------------
Use PowerShell !

**Comment by lzybkr** [comment] 2018-11-13 17:26
Duplicate of #614, fixed in the latest builds (available in AppVeyor) but not yet published to the PowerShell Gallery.

**Closed as completed by lzybkr** 2018-11-13 17:26 UTC
