### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by YUANYI6868** [PowerShell/PSReadLine#1404] opened 2020-03-15 19:15 UTC
上 200 个密钥:
 n / T e s t _ p y t h o n / t e s t _ s y n t a x 
. p y Enter
 & Space C : / A n a c o n d a 3 / p y t h o n . e 
x e Space c : / D _ P a n / T e s t _ p y t h o n / P r o j e c t 2 / m n i s t / p a r t 2 - n n / n 
e u r a l _ n e t s . p y Enter
 & Space C : / A n a c o n d a 3 / p y t h o n . e 
x e Space c : / D _ P a n / T e s t _ p y t h o n / t e s t _ s y n t a x . p y Enter
 c d Space P r Tab Backspace Backspace 2 Tab Tab p 
Tab Backspace Backspace 2 - ; Backspace m Tab Enter &

异常:
System.ArgumentOutOfRangeException: 该值必须大于或 
等于零，且必须小于控制台缓冲区在该维度的大小。     
参数名: left
实际值是 -1。
   在 System.Console.SetCursorPosition(Int32 left, 
Int32 top)
   在 Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   在 Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor) 
   在 Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   在 Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   在 Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   在 Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   在 Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   在 Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by iSazonov** [comment] 2020-03-16 04:38
See https://github.com/PowerShell/PSReadLine/issues/1306

**Comment by daxian-dbw** [comment] 2020-03-19 00:09
From the bug report template:
```
The maintainer may close your issue without further explanation or engagement if:
- You delete this entire template and go your own path;
```
So, please follow the bug report template to provide **environment data** and **repro steps** the next time.

As for the issue, it's a duplicate of the pinned issue #1306. See that issue for details.

**Closed as completed by daxian-dbw** 2020-03-19 00:09 UTC
Labels: Resolution-Duplicate
