### ISSUE TITLE
Error when opening Cmder (with profile script)

### ISSUE THREAD

**Issue by mikejwhat** [PowerShell/PSReadLine#629] opened 2018-02-02 17:34 UTC
Environment data
----------------

**PS version: 5.1.16299.98
PSReadline version: 1.2
os: 10.0.16299.15 (WinBuild.160101.0800)
PS file version: 10.0.16299.15 (WinBuild.160101.0800)**

Steps to reproduce or exception report
--------------------------------------

**Open Cmder (configured to start PowerShell as Admin). I think my profile script was running at the time (I can provide this via PM if required).**

**Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 1 Keys:
 c

Exception:
System.ArgumentException: Destination array was not long enough. Check destIndex and length, and the array's lower bounds.
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Array destinationArray, Int32 length)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
--------------------------------------------------------------**

**Comment by lzybkr** [comment] 2018-02-02 18:12
Duplicate of #292, try 2.0.0-beta1 for the fix.

**Closed as completed by lzybkr** 2018-02-02 18:12 UTC
Labels: Resolution-Duplicate
