### ISSUE TITLE
While using Ctrl+L in the terminal, showing the bug and letting me report here.

### ISSUE THREAD

**Issue by timeneverdie** [PowerShell/PSReadLine#1398] opened 2020-03-12 13:23 UTC
哎呀，出现问题。请在报告此 Bug 时添加以下详细信息。
在 GitHub 上报告: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
上 200 个密钥:
 DownArrow DownArrow DownArrow DownArrow DownArrow UpArrow UpArrow DownArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow Enter
 UpArrow End Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 4 Space 5 Space 6 Space Backspace Enter
 UpArrow UpArrow Enter
 4 Space 0 Space 4 Enter
 UpArrow UpArrow Enter
 UpArrow Enter
 4 Space 4 Backspace 1 Space 3 Space 3 Space Backspace UpArrow Enter
 3 Space 0 Space Backspace Backspace Backspace Backspace 4 Space 0 Space 4 4 Backspace Space 3 Enter
 UpArrow UpArrow UpArrow Enter
 Ctrl+l UpArrow UpArrow UpArrow UpArrow UpArrow Enter
 UpArrow UpArrow UpArrow UpArrow Enter
 UpArrow Enter
 Ctrl+l UpArrow UpArrow DownArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow UpArrow DownArrow DownArrow DownArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow DownArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Ctrl+l UpArrow UpArrow Enter  
 UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 Ctrl+l

异常:
System.ArgumentOutOfRangeException: 该值必须大于或等于零，且必须小于控制台缓冲区在该维度的大小。
参数名: top
实际值是 -3。
   在 System.Console.SetCursorPosition(Int32 left, Int32 top)
   在 Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   在 Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   在 Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by daxian-dbw** [comment] 2020-03-19 00:02
Thanks for reporting. From the bug report template:
```
The maintainer may close your issue without further explanation or engagement if:
- You delete this entire template and go your own path;
```
So, please follow the bug report template to provide **environment data** and **repro steps** the next time.

As for the issue, it's a duplicate of the pinned issue #1315 and has been fixed in the 2.0.0 GA version of PSReadLine. Please try it out from the PowerShell Gallery.

**Closed as completed by daxian-dbw** 2020-03-19 00:02 UTC
