### ISSUE TITLE
System IO exception In Windows 2016 

### ISSUE THREAD

**Issue by Acidguy** [PowerShell/PSReadLine#400] opened 2016-06-15 07:26 UTC
![image](https://cloud.githubusercontent.com/assets/19946397/16071361/89f3c716-32f8-11e6-933d-ea90c4213300.png)

**Comment by lzybkr** [comment] 2017-11-04 18:10
Closing as a dupe of #551.

**Closed as completed by lzybkr** 2017-11-04 18:10 UTC
Labels: Resolution-Duplicate
