### ISSUE TITLE
New W10 console Ctrl-key shortcuts not supported

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PSReadLine#434] opened 2016-08-29 16:06 UTC
The new console host that ships with Windows 10 introduced ^-based (Ctrl-key-based) shortcuts for access to functionality that (mostly) operates on the entire _screen buffer_:

![image](https://cloud.githubusercontent.com/assets/588825/18057166/d8960d92-6ddc-11e6-8a93-6264e2e40104.png)

PSReadLine currently doesn't support these keyboard shortcuts (the only way to access the functionality is via the console window's system menu):

PSReadline handles `^V` itself with the same functionality, so there's no problem.

`^A` is also handled by PSReadline itself, but only _partly_ has the same functionality:
- PSReadline selects the entire input line _without_ the prompt string (which is actually more sensible)
- However, pressing `^A` _again_ has no effect; by contrast, the console's functionality would select the _entire screen buffer_ in that event.

Furthermore, `^M` (Mark (select) arbitrary parts of the screen buffer) and `^F` (Find text anywhere in the screen buffer) do not work at all (only accessible via the window's system menu) - with the default configuration, PSReadline simply prints _literal_ `^M` and `^F` when these shortcut keys are pressed.

Supporting keyboard shortcuts `^M` and `^F` and `^A` (to select the _entire screen buffer_ on _second_ invocation of `^A`) would be great (I don't know whether technical restrictions prevent that).

**Comment by lzybkr** [comment] 2016-08-30 05:02
This is a duplicate of #280.

**Closed as completed by lzybkr** 2016-08-30 05:02 UTC
Labels: Resolution-Duplicate

**Comment by mklement0** [comment] 2018-11-24 02:45
For workarounds, see https://github.com/lzybkr/PSReadLine/issues/280#issuecomment-441338880
