### ISSUE TITLE
console window entry point jumps up (into existing text) and down (over a large gap of empty space) when window has text near the right edge of the window and is horizontally resized (with 150% dpi) or dragged between monitors with different DPI.

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PSReadLine#418] opened 2016-08-12 19:51 UTC
console window entry point jumps up (into existing text) and down (over a large gap of empty space) when window has text near the right edge of the window and is horizontally resized (with 150% dpi) or dragged between monitors with different DPI.

**Comment by lzybkr** [comment] 2017-11-06 06:29
I'm closing the issue because it's mostly fixed.

I do see a small problem after resizing where the cursor jumps to a different line, but everything stays in the correct column, so it's not as bad as it used to be.

I have difficulty reproducing this, so if you see the problem again and have a solid repro, go ahead and reopen.

**Closed as completed by lzybkr** 2017-11-06 06:29 UTC
