### ISSUE TITLE
System.IO.IOException: The parameter is incorrect.

### ISSUE THREAD

**Issue by AnthonyMastrean** [PowerShell/PSReadLine#526] opened 2017-04-07 17:57 UTC
```
PS>
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 87 Keys:
 LeftWindows c d Spacebar ~ / p r o j Backspace Backspace Backspace Backspace s d Tab Backspace Backspace p r o j Tab s d Tab p a r s e r Tab Enter
 Ctrl+l s u b l Spacebar . Enter
 p u s h d Spacebar ~ / p r o j Tab c o d Tab v a Tab c o m Backspace Backspace Backspace c o m Tab c o r Tab Enter
 s u b l Spacebar . Enter
 Ctrl+r Ctrl+l

Exception:
System.IO.IOException: The parameter is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()

```

**Comment by lzybkr** [comment] 2017-04-11 19:09
Most likely a dupe of #292, reopen with additional information if you disagree.

**Closed as completed by lzybkr** 2017-04-11 19:09 UTC
Labels: Resolution-Duplicate
