### ISSUE TITLE
OutOfRangeException

### ISSUE THREAD

**Issue by MCRusher** [PowerShell/PSReadLine#786] opened 2018-10-25 15:35 UTC
PS C:\Users\XXX\Desktop\BC\implementation>

Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 2 Keys:
 d Backspace

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was 45.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender()
   at Microsoft.PowerShell.PSConsoleReadLine.BackwardDeleteChar(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\Users\XXX\Desktop\BC\implementation>

So, what I did was I resized the window into a square so that the blinking '_' was the only thing that could fit on that line, and then I typed d, then hit backspace, may have multitapped it on accident, then thing lagged out and crashed.
This did happen shortly after resizing, but has a different error.

Hope this helps.

Below is a screenshot of what my powershell window was like exactly:

![pwrshll](https://user-images.githubusercontent.com/16050377/47512202-a65b1780-d849-11e8-97e8-39e32a160495.jpg)

**Comment by lzybkr** [comment] 2018-10-25 16:35
Which version of PSReadLine? If it's 1.2, we can close as it's probably fixed in 2.0.

**Comment by jocgir** [comment] 2018-10-29 10:53
I have this problem with version 2.0 on OSX.

The problem appeared when I updated my powershell to v6.1. 

I noticed that the problem is also there within the docker image microsoft/powershell.

The problem only occurs when the cursor it at the first line.

**Closed as completed** 2019-09-13 00:04 UTC
Labels: OutOfRange
