### ISSUE TITLE
 Ctrl+l docker Space ps Enter

### ISSUE THREAD

**Issue by muei** [PowerShell/PSReadLine#2578] opened 2021-06-15 06:30 UTC
-----------------------------------------------------------------------
Last 12 Keys:
 Ctrl+l d o c k e r Space p s Enter
 Ctrl+l

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -2.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment] 2021-07-01 18:17
No environment data is provided for us to investigate the issue. This looks like a duplicate of #1315, so please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.

**Closed as completed by daxian-dbw** 2021-07-01 18:17 UTC
