### ISSUE TITLE
Module error?

### ISSUE THREAD

**Issue by EquipoZorrillo** [PowerShell/PSReadLine#1000] opened 2019-08-20 13:42 UTC
Not sure where this came from.  Was not doing anything at the time.  Powershell was up but I was engaged in other tasks.  Went to powershell and this had come up.

Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 82 Keys:
 g e t - m y Tab Enter
 c o n n e c t - c o m Tab Enter
 UpArrow Enter
 UpArrow UpArrow Enter
 g e t - p s s Tab Enter
 c o n n e c t - c o m o n Tab Enter
 s e t - c o m a d a Tab Enter
 g e t - m y Tab Enter
 s e t - c o m a d a Tab Enter

Exception:
System.IO.IOException: No more data is available.

   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.GetValueNames()
   at System.Management.Automation.Utils.GetGroupPolicySetting(String groupPolicyBase, String settingName, RegistryKey[] preferenceOrder)
   at System.Management.Automation.ScriptBlock.ShouldLogScriptBlockActivity(String activity)
   at System.Management.Automation.ScriptBlock.LogScriptBlockStart(ScriptBlock scriptBlock, Guid runspaceId)
   at System.Management.Automation.DlrScriptCommandProcessor.DoBegin()
   at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
   at System.Management.Automation.Runspaces.LocalPipeline.StartPipelineExecution()
   at System.Management.Automation.Runspaces.PipelineBase.CoreInvoke(IEnumerable input, Boolean syncCall)
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadKey()
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by daxian-dbw** [comment] 2019-09-11 22:30
This is an exception thrown from PowerShell, not from PSReadLine ...

**Comment by daxian-dbw** [comment] 2019-09-26 19:01
Based on the call stack, the exception happens in PowerShell code (registry value retrieval) when PSReadLine tries to pump the pulse pipeline (by calling `PowerShell.AddScript(0); PowerShell.Invoke()`).
I cannot reproduce this issue ... Will close it as `need repro` for now.

**Closed as completed by daxian-dbw** 2019-09-26 19:01 UTC
Labels: Needs-Repro
