### ISSUE TITLE
Get-Process | sort @{<Press Tap Key Here>

### ISSUE THREAD

**Issue by ebrahimkali** [PowerShell/PSReadLine#739] opened 2018-08-04 17:20 UTC
PS version: 5.1.16299.522
PS file version: 10.0.16299.15 (WinBuild.160101.0800)

```
PS C:\> Get-Process | sort @{
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 t e m 3 2 \ c m d . e x e ) . V e r s i o n I n f o . F i l e V e r s i o n ) " Enter
 Spacebar Spacebar Spacebar Spacebar } Enter
 Spacebar Spacebar Spacebar Spacebar " P S Spacebar f i l e Spacebar v e r s i o n : Spacebar $ ( ( d i r Spacebar $ p s h o m e \ p * [ h l ] . e x e ) . V e r s i o n I n f o . F i l e V e r s i o n ) " Enter
 g e t - Tab Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace g e t - p Tab Backspace Backspace Backspace Backspace Backspace Backspace r Tab Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace o Tab Spacebar | Spacebar s o r Tab Spacebar @ { Tab

Exception:
System.ArgumentException: 'start' cannot be less than zero or greater than the length of the buffer
Parameter name: start
   at Microsoft.PowerShell.PSConsoleReadLine.Replace(Int32 start, Int32 length, String replacement, Action`2 instigator, Object instigatorArg)
   at Microsoft.PowerShell.PSConsoleReadLine.DoReplacementForCompletion(CompletionResult completionResult, CommandCompletion completions)
   at Microsoft.PowerShell.PSConsoleReadLine.Complete(Boolean forward)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

**Comment by lzybkr** [comment] 2018-08-07 17:57
Dupe of #534, fixed in [2.0.0-beta2](https://www.powershellgallery.com/packages/PSReadLine/2.0.0-beta2).

**Closed as completed by lzybkr** 2018-08-07 17:57 UTC
