### ISSUE TITLE
Update-Help does not get the correct file name for version 2.0.0

### ISSUE THREAD

**Issue by adityapatwardhan** [PowerShell/PSReadLine#819] opened 2018-11-29 01:16 UTC
Environment data
----------------

Steps to reproduce or exception report
--------------------------------------
PS> get-module PSReadLine

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.0.0      PSReadLine                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PSReadLineKeyHandler, Set-PSReadLineKeyHandler...}

**Comment by daxian-dbw** [comment] 2019-08-01 21:58
@adityapatwardhan Can you please add the repro steps? Thanks.

**Comment by daxian-dbw** [comment] 2021-03-10 22:39
@adityapatwardhan It's not clear what the problem is. Given this is 2-year old, I will close this one. Feel free to open a new issue if it's needed.

**Closed as completed by daxian-dbw** 2021-03-10 22:39 UTC
Labels: Needs-Repro
