### ISSUE TITLE
Cannot run docker images on Powershell

### ISSUE THREAD

**Issue by iempairote** [PowerShell/PSReadLine#474] opened 2016-11-24 07:54 UTC
PS C:\WINDOWS\system32> docker run --net host -it buuweben/powershell:nginx

PowerShell 
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new

Last 0 Keys:

Exception:
System.DivideByZeroException: Attempted to divide by zero.
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrins
ics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsic
s engineIntrinsics)
-----------------------------------------------------------------------

**Comment by lzybkr** [comment] 2017-01-12 20:28
Most likely a dupe of #158, reopen with additional information if you disagree.

**Closed as completed by lzybkr** 2017-01-12 20:28 UTC
Labels: Resolution-Duplicate
