### ISSUE TITLE
vscode 1.54

### ISSUE THREAD

**Issue by Peripheral72** [PowerShell/PSReadLine#2297] opened 2021-03-11 16:56 UTC
## Environment

PSReadLine: 2.2.0-beta2
PowerShell: 2021.2.2
OS: Microsoft Windows 10.0.18363
BufferWidth: 244
BufferHeight: 25

Last 200 Keys
```
 UpArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow g e t - p s f c o n f i g Spacebar Enter
 UpArrow . v l a u e Backspace Backspace Backspace Backspace a l u e Enter
 UpArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow ) LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow ( Enter
 DownArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow Enter
 DownArrow H e l p Spacebar a b o u t _ p s f _ m e s s a g e Enter
 DownArrow Ctrl+s DownArrow UpArrow DownArrow Enter
 DownArrow Ctrl+z DownArrow LeftArrow LeftArrow UpArrow DownArrow
```

-->

## Exception report
```
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was 26.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.CalculateWhereAndWhatToRender(Boolean cursorMovedToInitialPos, RenderData renderData, LineInfoForRendering& lineInfoForRendering)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadKey()
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

**Comment by daxian-dbw** [comment] 2021-03-11 17:19
@Peripheral72 We really want to fix this issue, and a local repro is needed for us to investigate. Can you please provide us the repro steps?

**Comment by Peripheral72** [comment] 2021-03-11 19:20
I'd like to, but this was spontaneous. There wasn't anything special going on.
FWIW, I only updated locally to 1.54 yesterday and didn't do a reboot, just the installers. I do have a lot of editors open, but the file I was working on was the first that I opened under the new codebase. There was only 12 lines written. It happened during an F5.
If I can help more, lemme know.

Regards,
Henry Schlarb

________________________________

**Comment by iSazonov** [comment] 2021-03-12 03:10
Maybe dup #2214

**Comment by daxian-dbw** [comment] 2021-03-12 07:05
@Peripheral72 Thanks for the additional information. I will close this one as a duplicate of #2298

**Closed as completed by daxian-dbw** 2021-03-12 07:05 UTC
Labels: Issue-Bug, Needs-Repro, Needs-Attention :wave:
