### ISSUE TITLE
ctrl + l twice makes an error

### ISSUE THREAD

**Issue by ingenika** [PowerShell/PSReadLine#723] opened 2018-07-09 02:54 UTC
Environment data
----------------

Steps to reproduce or exception report
--------------------------------------
Ctrl+l s u d o Space a [ t = Backspace Backspace Backspace p t - g e t Space u p d a t e Enter
 UpArrow Backspace Backspace Backspace Backspace g r a d e Enter
 Ctrl+l UpArrow UpArrow UpArrow UpArrow Enter
 c d Space ~ Enter
 c d Space ~ Enter
 c d Space ` Backspace ~ Backspace Backspace Backspace Backspace Backspace c d Space . Enter
 c d Space . . Enter
 c d Space . . Enter
 c d Space . . Enter
 l s Enter
 c d Space ~ Enter
 l s Enter
 Ctrl+l UpArrow UpArrow UpArrow UpArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace s u d o Space a p t - g e t Space u p d a t e Enter
 UpArrow Backspace Backspace Backspace Backspace g r a d e Enter
 Ctrl+l d o c k e r Enter
 Ctrl+l Ctrl+l Ctrl+l Ctrl+l Ctrl+l Ctrl+l Ctrl+l Ctrl+l Ctrl+l Ctrl+l Ctrl+l Ctrl+l Ctrl+l Ctrl+l Ctrl+l Ctrl+l

Exception:
System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.ConsolePal.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

--
Ubuntu 18.04

**Comment by davividal** [comment] 2018-10-12 10:06
I got the same error on Mac:

    Oops, something went wrong.  Please report this bug with the details below.
    Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
    -----------------------------------------------------------------------
    Last 8 Keys:
    ```
     p w d Enter
     Ctrl+l Ctrl+l Ctrl+l Ctrl+l
    ```
    
    Exception:
    ```
    System.PlatformNotSupportedException: Operation is not supported on this platform.
       at System.ConsolePal.SetWindowPosition(Int32 left, Int32 top)
       at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
       at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
       at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
    ```
    -----------------------------------------------------------------------

**Comment by lzybkr** [comment] 2018-10-19 04:43
Closing as a duplicate of #654.

**Closed as completed by lzybkr** 2018-10-19 04:43 UTC
