### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by NipunSyn** [PowerShell/PSReadLine#2572] opened 2021-06-13 09:42 UTC
Last 200 Keys:
 " M I T " Enter
 n p m Space g e t Space d e Backspace Backspace i n i t - a u t h o r - n a m e Enter
 n p m Space c o n f i g Space g e t Space i n i t - a u t h o r - n a m e Enter
 Ctrl+l n p m Space c o n f i Backspace Backspace Backspace Backspace Backspace i n i t Space - y Enter 
 Ctrl+l n p m Space i n s t a l l Space l o a d a s 
h Space - - s a v e Backspace Backspace Backspace a 
v e Enter
 n p m Space u n i n s t a l l Space - - s Backspace Backspace Backspace Backspace Space l o a d a s h Space - - s a v e Enter
 n p m Space i n s t a l l Space l o a d a s h Space Backspace @ 4 . 1 7 . 4 Space - - s a e Backspace v e Enter
 Ctrl+l

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by daxian-dbw** [comment] 2021-07-01 18:17
No environment data is provided for us to investigate the issue. This looks like a duplicate of #1315, so please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.

**Closed as completed by daxian-dbw** 2021-07-01 18:17 UTC
