### ISSUE TITLE
The value must be greater than or equal to zero and less than the console's buffer size in that dimension.

### ISSUE THREAD

**Issue by ericsciple** [PowerShell/PSReadLine#320] opened 2015-12-17 05:33 UTC
# Capture from Console Window

```
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 1 Keys:
 e

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -38.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.PlaceCursor(Int32 x, Int32& y)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\>
```
# Repro Steps

1) Windows 10
2) Launch cmd.exe. Font: 12, Lucida Console ; Layout: Buffer width 175, height 300, wrap text output on resize, window width 175, height ; Let system position window
3) Run cmd:

```
start "" "cmd /c "powershell.exe -noexit -command "$Host.UI.RawUI.WindowSize = New-Object System.Management.Automation.Host.Size($Host.UI.RawUI.WindowSize.Width, 2) ; $Host.UI.RawUI.BufferSize = New-Object System.Management.Automation.Host.Size(16kb, 2)""
```

4) Maximize new window.
5) Type a letter (I was trying to type "exit").
# Additional Comments

I'm not concerned about this scenario working. I was just playing around with buffer size and came across this issue. Just reporting it, per the exception message. Although the repro steps are probably an unrealistic customer scenario, it may indicate a problem for some more realistic conditions.

**Comment by lzybkr** [comment] 2015-12-17 07:02
Thanks for the report, it's a duplicate of #292.

**Closed as completed by lzybkr** 2015-12-17 07:02 UTC
Labels: Issue-Bug, Resolution-Duplicate
