### ISSUE TITLE
PowerShell terminal pops up below error.

### ISSUE THREAD

**Issue by tianliu** [PowerShell/PSReadLine#510] opened 2017-03-01 08:30 UTC
-----------------------------------------------------------------------
Last 200 Keys:
 Tab Tab Tab Tab Tab Shift+Tab Enter
 UpArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Shift+End Shift+Delete Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+RightArrow Backspace Backspace Ba
ckspace - E x Tab Spacebar LeftArrow Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Ctrl+Shift+LeftArrow Backspace E x p Tab Tab Backspace Backspac
e Backspace Backspace Backspace Backspace Backspace Backspace End Backspace Backspace Backspace Backspace Backspace Backspace Backspace Enter
 UpArrow Enter
 UpArrow Ctrl+LeftArrow LeftArrow Tab Enter
 UpArrow Ctrl+LeftArrow LeftArrow Ctrl+Shift+LeftArrow E x p Tab Tab Tab Tab Ctrl+Shift+LeftArrow e x Tab Tab Tab Enter
 UpArrow UpArrow Enter
 UpArrow | W h e r e Tab Tab Spacebar { } LeftArrow _ Backspace $ _ . Backspace Spacebar - l i Tab Spacebar ' ' LeftArrow 1 0 . 1 1 7 Backspace Backspace 1 * En
ter
 UpArrow Ctrl+a Ctrl+c LeftWindows LeftWindows Home Ctrl+RightArrow LeftArrow LeftArrow RightArrow Tab Tab Backspace Tab Backspace Backspace Backspace Backspace
 g e t - w Backspace w m Tab Enter
 UpArrow Ctrl+a Ctrl+c Ctrl+c g e t - p s s Tab Enter
 UpArrow Enter
 Ctrl+v Enter
 $ a u s Tab Enter
 UpArrow Enter
 UpArrow | g m Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow UpArrow UpArrow UpArrow Ctrl+a Ctrl+c

Exception:
System.Runtime.InteropServices.ExternalException (0x800401D0): Requested Clipboard operation did not succeed.
   at System.Windows.Forms.Clipboard.ThrowIfFailed(Int32 hr)
   at System.Windows.Forms.Clipboard.SetDataObject(Object data, Boolean copy, Int32 retryTimes, Int32 retryDelay)
   at System.Windows.Forms.Clipboard.SetText(String text, TextDataFormat format)
   at Microsoft.PowerShell.PSConsoleReadLine.Copy(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.CopyOrCancelLine(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by lzybkr** [comment] 2017-04-11 19:11
Duplicate of #265.

**Closed as completed by lzybkr** 2017-04-11 19:11 UTC
Labels: Resolution-Duplicate
