### ISSUE TITLE
Looks like changing the prompt leads to problems?

### ISSUE THREAD

**Issue by ggrammar** [PowerShell/PSReadLine#444] opened 2016-09-18 22:18 UTC
```
PS>
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 $ P S P a t h Enter
 Enter
 Enter
 e c h o Spacebar $ P A T H Enter
 Enter
 Enter
 $ e n c Backspace v : P Backspace p a t h Enter
 Enter
 Enter
 UpArrow Spacebar | Spacebar 4 _ Backspace Backspace $ _ . c o n t a i n s " Backspace ( " P O Backspace Backspace p o s t o o l s " ) Enter
 Enter
 Enter
 Enter
 Enter
 $ e n v : p a t h Enter
 Enter
 Enter
 $ m y T h i n g Spacebar = Spacebar $ e n v : p a t h Enter
 Enter
 Enter
 $ m y T h i n g Enter
 Enter
 Enter
 UpArrow . c o n Tab " p o s t o o l s " ) Enter
 Enter
 Enter
 Enter
 Enter
 UpArrow UpArrow Ctrl+C Enter
 Enter
 l s Enter
 Enter
 Enter
 UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow Ctrl+C Enter
 Enter
 p w d Enter
 Enter
 Enter
 i p m o Spacebar . / P O S Tab m Tab Backspace Backspace d Tab Spacebar - f o r c e Enter


Exception:
System.Management.Automation.CommandNotFoundException: The term 'prompt' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input) in /PowerShell/src/System.Management.Automation/engine/hostifaces/pipelinebase.cs:line 415
   at System.Management.Automation.Runspaces.Pipeline.Invoke() in /PowerShell/src/System.Management.Automation/engine/hostifaces/Pipeline.cs:line 536
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke) in /PowerShell/src/System.Management.Automation/engine/hostifaces/PowerShell.cs:line 5305
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings) in /PowerShell/src/System.Management.Automation/engine/hostifaces/PowerShell.cs:line 4291
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings) in /PowerShell/src/System.Management.Automation/engine/hostifaces/PowerShell.cs:line 4463
   at System.Management.Automation.PowerShell.CoreInvoke[TOutput](IEnumerable input, PSDataCollection`1 output, PSInvocationSettings settings) in /PowerShell/src/System.Management.Automation/engine/hostifaces/PowerShell.cs:line 4207
   at System.Management.Automation.PowerShell.Invoke[T](IEnumerable input, IList`1 output, PSInvocationSettings settings) in /PowerShell/src/System.Management.Automation/engine/hostifaces/PowerShell.cs:line 2712
   at System.Management.Automation.PowerShell.Invoke[T]() in /PowerShell/src/System.Management.Automation/engine/hostifaces/PowerShell.cs:line 2440
   at Microsoft.PowerShell.PSConsoleReadLine.GetPrompt() in /PowerShell/src/Microsoft.PowerShell.PSReadLine/ReadLine.cs:line 925
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics) in /PowerShell/src/Microsoft.PowerShell.PSReadLine/ReadLine.cs:line 562
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics) in /PowerShell/src/Microsoft.PowerShell.PSReadLine/ReadLine.cs:line 276
-----------------------------------------------------------------------

```

**Comment by lzybkr** [comment] 2017-01-12 20:34
Dupe of #468 - `PSReadline` shouldn't be calling prompt on initialize.

**Closed as completed by lzybkr** 2017-01-12 20:34 UTC
Labels: Resolution-Duplicate
