### ISSUE TITLE
EncoderFallbackException when mutating failed emoji paste in wt

### ISSUE THREAD

**Issue by dragondave** [PowerShell/PSReadLine#2395] opened 2021-04-26 02:49 UTC
## Environment
```
PS version: 5.1.19041.906
PSReadline version: 2.0.0-beta2
os: 10.0.19041.1 (WinBuild.160101.0800)
PS file version: 10.0.19041.1 (WinBuild.160101.0800)
HostName: ConsoleHost (Windows Terminal)
BufferWidth: 174
BufferHeight: 42
```

## Exception report

```
PS C:\Users\Dragon> ????

Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 t : Space $ ( [ c o n s o l e ] : : B u f f e r H e i g h t ) ` n " Enter
 } Enter
 [ x Space f o r Space x Space i n Space ' ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ' ] Enter
 UpArrow LeftArrow LeftArrow Backspace Backspace Enter
 UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow LeftArrow LeftArrow Backspace Backspace Enter
 UpArrow DownArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow LeftArrow LeftArrow Backspace Backspace Enter
 DownArrow UpArrow UpArrow DownArrow Enter
 Ctrl+c UpArrow Enter
 UpArrow LeftArrow LeftArrow Backspace Backspace Enter
 UpArrow UpArrow UpArrow UpArrow DownArrow Enter
 UpArrow LeftArrow LeftArrow Backspace Backspace Enter
 Enter
 ? ? ? ? ? ? Enter
 UpArrow Backspace Backspace Enter
 Enter
 UpArrow Backspace UpArrow Backspace Backspace Backspace Backspace ? ? ? ? ? ? Backspace Backspace Backspace Enter
 ? ? ? ? ? ? Backspace Backspace Backspace Backspace Backspace Enter
 Backspace ? ? ? ? ? ? Backspace Enter
 ? ? ? ? ? ? Backspace Enter
 ? ? ? ? ? ? Backspace Backspace Enter


Exception:
System.Text.EncoderFallbackException: Unable to translate Unicode character \uD83D at index 3 to specified code page.
   at System.Text.EncoderExceptionFallbackBuffer.Fallback(Char charUnknown, Int32 index)
   at System.Text.EncoderFallbackBuffer.InternalFallback(Char ch, Char*& chars)
   at System.Text.UTF8Encoding.GetBytes(Char* chars, Int32 charCount, Byte* bytes, Int32 byteCount, EncoderNLS baseEncoder)
   at System.Text.EncoderNLS.GetBytes(Char[] chars, Int32 charIndex, Int32 charCount, Byte[] bytes, Int32 byteIndex, Boolean flush)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at Microsoft.PowerShell.PSConsoleReadLine.<>c__DisplayClass81_0.<WriteHistoryRange>b__0()
   at Microsoft.PowerShell.PSConsoleReadLine.WithHistoryFileMutexDo(Int32 timeout, Action action)
   at Microsoft.PowerShell.PSConsoleReadLine.MaybeAddToHistory(String result, List`1 edits, Int32 undoEditIndex, Boolean fromDifferentSession, Boolean fromInitialRead)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

## Steps to reproduce

paste 🕸️🕸️ into Powershell in Windows Terminal.

[specifically, this is:]
U+1F578 : SPIDER WEB
U+FE0F : VARIATION SELECTOR-16 [VS16] {emoji variation selector}
U+1F578 : SPIDER WEB
U+FE0F : VARIATION SELECTOR-16 [VS16] {emoji variation selector}

This will render as a sequence of six question marks in Windows Terminal.

Delete the last two (or five) question marks, and execute the line.

## Expected behavior

Some regular Powershell error not unlike when you don't delete the questionmarks.

## Actual behavior

Exception shown above. Note that pressing enter without changing the command works "fine" (i.e. outputs a regular Powershell error)

**Comment by daxian-dbw** [comment] 2021-04-29 18:17
@dragondave, thanks for reporting the issue. This is a duplicate of #949, and thus I will close this one.

**Closed as completed by daxian-dbw** 2021-04-29 18:17 UTC
Labels: Resolution-Duplicate
