### ISSUE TITLE
System.IO.IOException: The handle is invalid

### ISSUE THREAD

**Issue by desrioux** [PowerShell/PSReadLine#297] opened 2015-10-31 13:04 UTC
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by lzybkr** [comment] 2015-12-02 21:05
This looks like a dupe of #158

**Closed as completed by lzybkr** 2015-12-02 21:05 UTC
Labels: Issue-Bug, Resolution-Duplicate
