### ISSUE TITLE
Buffer exceeds top of window size

### ISSUE THREAD

**Issue by mavaddat** [PowerShell/PSReadLine#3722] opened 2023-06-22 20:31 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
### Environment
PSReadLine: 2.3.1-beta1
PowerShell: 7.3.4
OS: Microsoft Windows 10.0.19044
BufferWidth: 120
BufferHeight: 30

Last 200 Keys:

 RightArrow c o d e Enter
 UpArrow Home Spacebar LeftArrow $ v s c o d e Spacebar = Enter
 $ v s Tab Home & End PageDown Spacebar RightArrow Enter
 UpArrow UpArrow Ctrl+a Ctrl+x UpArrow DownArrow w i n g e t Spacebar s e a r c h Spacebar j Backspace j d k Enter
 Ctrl+r w i n g e t Ctrl+r Ctrl+r Ctrl+r Ctrl+r Ctrl+r Ctrl+r Ctrl+r Ctrl+r Ctrl+r Ctrl+r Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+RightArrow Ctrl+RightArrow Ctrl+RightArrow Ctrl+RightArrow Ctrl+RightArrow Ctrl+RightArrow Ctrl+RightArrow Ctrl+RightArrow Ctrl+RightArrow Ctrl+RightArrow Ctrl+LeftArrow Ctrl+RightArrow Home Shift+Ctrl+RightArrow Shift+Ctrl+RightArrow Shift+RightArrow Shift+RightArrow Shift+RightArrow Shift+RightArrow Shift+RightArrow Ctrl+c Ctrl+RightArrow Ctrl+RightArrow Ctrl+RightArrow Ctrl+RightArrow Ctrl+RightArrow Ctrl+RightArrow Ctrl+RightArrow Ctrl+RightArrow Ctrl+RightArrow Ctrl+RightArrow Ctrl+RightArrow Ctrl+RightArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow UpArrow

### Exception

System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Actual value was 30.
   at System.ConsolePal.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Render()
   at Microsoft.PowerShell.PSConsoleReadLine.UpdateFromHistory(HistoryMoveCursor moveCursor)
   at Microsoft.PowerShell.PSConsoleReadLine.HistoryRecall(Int32 direction)
   at Microsoft.PowerShell.PSConsoleReadLine.PreviousHistory(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken, Nullable`1 lastRunStatus)
```

### Screenshot

Original window size:

![Microsoft Terminal in its original window size](https://github.com/PowerShell/PSReadLine/assets/5055400/899436fa-51ab-4d76-9c8e-8d03152c67c3)

### Environment data

```console
PS Version: 7.3.4
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.3.1-beta1
PSReadLine EditMode: Windows
OS: 10.0.19041.320 (WinBuild.160101.0800)
BufferWidth: 120
BufferHeight: 30
```

### Steps to reproduce

It is possible that I ran `winget list` on a maximized Terminal window, then restored the window size down and executed the reverse search.

### Expected behavior

Navigate the command history using arrow keys.

### Actual behavior

Buffer overrun.

**Comment by daxian-dbw** [comment] 2023-07-24 23:18
I cannot reproduce this issue based on the repro steps.
However, given that the repro steps include maximize and then restore the terminal window, based on our conversation in https://github.com/PowerShell/PSReadLine/issues/3750, I think it's also related to the custom prompts used in your session.
I will close this one as a duplicate of #3750.

**Closed as completed by daxian-dbw** 2023-07-24 23:18 UTC
Labels: Resolution-Duplicate

**Comment by mavaddat** [comment] 2023-07-25 14:10
> [&hellip;] based on our conversation in #3750, I think it's also related to the custom prompts used in your session. I will close this one as a duplicate of #3750.

Yes, I think you are right and I agree: Looks like a duplicate. Thank you for identifying the issue and following up on a solution.
