### ISSUE TITLE
Windows 10 Build 10130 :: "Something went wrong"

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/PSReadLine#258] opened 2015-06-26 15:27 UTC
Got this message, which said to report on GitHub.

![2015-06-26 09_26_46-start](https://cloud.githubusercontent.com/assets/466713/8380868/7d225dca-1be5-11e5-96b1-abb5c77ea1e0.png)

```
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 101 Keys:
$ p s v e r i o n Tab Backspace Backspace Backspace Tab Enter
 g m o Spacebar - l i Tab Spacebar - m o Tab Spacebar Backspace Tab Backspace Backspace Tab Spacebar A z u r e Enter
 1 Spacebar - e q Spacebar $ t r u e Enter
 UpArrow Ctrl+LeftArrow Home [ b o o l ] Enter
 UpArrow Home Delete Delete Delete Delete Delete Delete RightArrow RightArrow RightArrow Delete RightArrow Delete Backsp
ace i s Spacebar Delete Delete Delete Delete Delete Delete [ b o o l ] Enter
 UpArrow Ctrl+a Ctrl+c Ctrl+a Ctrl+x Ctrl+a Ctrl+x

Exception:
System.ArgumentNullException: Value cannot be null.
Parameter name: text
   at Microsoft.PowerShell.PSConsoleReadLine.ExecuteOnSTAThread(Action action)
   at Microsoft.PowerShell.PSConsoleReadLine.Cut(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignor
eIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, Object reser
ved)
-----------------------------------------------------------------------
```

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by lzybkr** [comment] 2015-06-26 15:40
This was caused by moving to winforms, but also fixed.  9c153bd848c9f8f513cb4956a2a8161cdf528743

**Closed as completed by lzybkr** 2015-06-26 15:40 UTC
