### ISSUE TITLE
Exception on module initialization

### ISSUE THREAD

**Issue by FallenGameR** [PowerShell/PSReadLine#264] opened 2015-07-09 22:56 UTC
While windows was opening Powershell window I typed into it and when Powershell finally initialized, PsReadLine that is imported in my profile threw this exception:

```
Windows PowerShell
Copyright (C) 2014 Microsoft Corporation. All rights reserved.

D:\autopilot\gitsd.az_compute\private\Services\Hardware\services\SyslogCollector [ALEXKO-DEV] REDMOND\alexko
»
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
Or email: jason@truewheels.net
-----------------------------------------------------------------------
Last 6 Keys:
 g i t Spacebar Ctrl+End Ctrl+Home

Exception:
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collectio
n.
Parameter name: index
   at PSConsoleUtilities.PSConsoleReadLine.Kill(Int32 start, Int32 length, Boolean prepend)
   at PSConsoleUtilities.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreI
fNoAction, Object arg)
   at PSConsoleUtilities.PSConsoleReadLine.InputLoop()
   at PSConsoleUtilities.PSConsoleReadLine.ReadLine(Runspace remoteRunspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
D:
>
```

**Comment by lzybkr** [comment] 2015-08-20 06:03
Can I get some more information for a repro?
Do you have some custom bindings for any of the 6 keys reported above?

PSConsoleReadLine.Kill is a private helper method that can't be bound directly, but maybe you've bound Ctrl+Home to BackwardKillLine?

**Comment by FallenGameR** [comment] 2015-08-20 18:05
Yes, I do have custom bindings for Ctrl+End and Ctrl+Home:

» ack Kill
Initialize-PsReadLine.ps1
129:Set-PSReadlineKeyHandler -Chord "Alt+q" -Function ShellBackwardKillWord
130:Set-PSReadlineKeyHandler -Chord "Alt+e" -Function ShellKillWord
135:Set-PSReadlineKeyHandler -Chord "Ctrl+Home" -Function BackwardKillLine
136:Set-PSReadlineKeyHandler -Chord "Ctrl+End" -Function KillLine

**Comment by lzybkr** [comment] 2017-11-08 01:09
Closing as a dupe of #462. Even with these additional details, I can't seem to repro, hopefully it was fixed somehow.

**Closed as completed** 2017-11-08 01:56 UTC
