### ISSUE TITLE
Powershell error while copying/pasting

### ISSUE THREAD

**Issue by Dlayknee** [PowerShell/PSReadLine#528] opened 2017-04-11 13:46 UTC
I was trying to copy and paste a command from a Powershell window into ISE and it threw an error:

> Last 200 Keys:
>  c $ Delete RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow Delete Delete Delete Delete Delete Delete Delete Delete r o j a l v o Enter
>  UpArrow UpArrow DownArrow UpArrow DownArrow UpArrow LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow $ p i c s Spacebar Backspace Spacebar = Spacebar Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete g c i LeftWindows Backspace i Ctrl+End DownArrow UpArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace " Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow $ p i c s Spacebar Backspace Spacebar = Spacebar g c i Spacebar End Delete UpArrow DownArrow Escape DownArrow UpArrow Ctrl+a Ctrl+c
> 
> Exception:
> System.Runtime.InteropServices.ExternalException (0x800401D0): Requested Clipboard operation did not succeed.
>    at System.Windows.Forms.Clipboard.ThrowIfFailed(Int32 hr)
>    at System.Windows.Forms.Clipboard.SetDataObject(Object data, Boolean copy, Int32 retryTimes, Int32 retryDelay)
>    at System.Windows.Forms.Clipboard.SetText(String text, TextDataFormat format)
>    at Microsoft.PowerShell.PSConsoleReadLine.Copy(Nullable`1 key, Object arg)
>    at Microsoft.PowerShell.PSConsoleReadLine.CopyOrCancelLine(Nullable`1 key, Object arg)
>    at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
>    at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
>    at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

Everything still works, however.

**Comment by lzybkr** [comment] 2017-04-11 19:07
Duplicate of #265.

**Closed as completed by lzybkr** 2017-04-11 19:07 UTC
Labels: Resolution-Duplicate
