### ISSUE TITLE
Error on pasting multi-line script

### ISSUE THREAD

**Issue by alansingfield** [PowerShell/PSReadLine#3307] opened 2022-05-11 08:35 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
PowerShell 7.2.3
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS C:\Users\SpanWork> using namespace [System.Security.Cryptography]
PS C:\Users\SpanWork>
PS C:\Users\SpanWork> $s = "CN=Fabrikam Encryption Certificate"
PS C:\Users\SpanWork>
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.yaml
Thank you!

### Environment
PSReadLine: 2.2.5
PowerShell: 7.2.3
OS: Microsoft Windows 10.0.19044
BufferWidth: 120
BufferHeight: 30

Last 200 Keys:

 C e r t i f i c a t e s ] : : X 5 0 0 D i s t i n g u i s h e d N a m e ( $ s ) Enter
 $ r e q Spacebar = Spacebar N e w - O b j e c t Spacebar [ X 5 0 9 C e r t i f i c a t e s ] : : C e r t i f i c a t e R e q u e s t ( Enter
 Spacebar Spacebar Spacebar Spacebar $ s u b j e c t , Spacebar ` Enter
 Spacebar Spacebar Spacebar Spacebar $ a l g o r i t h m , Spacebar ` Enter
 Spacebar Spacebar Spacebar Spacebar H a s h A l g o r i t h m N a m e . S H A 2 5 6 , Spacebar ` Enter
 Spacebar Spacebar Spacebar Spacebar R S A S i g n a t u r e P a d d i n g . P k c s 1 ) Enter
 Spacebar Spacebar Spacebar Spacebar

### Exception

System.Management.Automation.PSArgumentException: Cannot process argument because the value of argument "name" is not valid. Change the value of the "name" argument and run the operation again.
   at System.Management.Automation.Language.TypeName..ctor(IScriptExtent extent, String name)
   at System.Management.Automation.Language.TypeResolver.ResolveTypeNameWithContext(TypeName typeName, Exception& exception, Assembly[] assemblies, TypeResolutionState typeResolutionState)
   at System.Management.Automation.Language.SymbolResolver.VisitTypeName(TypeName typeName, Int32 genericArgumentCount, Boolean isAttribute)
   at System.Management.Automation.Language.SymbolResolver.DispatchTypeName(ITypeName type, Int32 genericArgumentCount, Boolean isAttribute)
   at System.Management.Automation.Language.SymbolResolver.VisitTypeExpression(TypeExpressionAst typeExpressionAst)
   at System.Management.Automation.Language.TypeExpressionAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.InvokeMemberExpressionAst.InternalVisitChildren(AstVisitor visitor)
   at System.Management.Automation.Language.InvokeMemberExpressionAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.CommandExpressionAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.AssignmentStatementAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.StatementBlockAst.InternalVisit(AstVisitor visitor, ReadOnlyCollection`1 traps, ReadOnlyCollection`1 statements, AstVisitAction action)
   at System.Management.Automation.Language.NamedBlockAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.ScriptBlockAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.Ast.Visit(AstVisitor astVisitor)
   at System.Management.Automation.Language.SymbolResolver.ResolveSymbols(Parser parser, ScriptBlockAst scriptBlockAst)
   at System.Management.Automation.Language.ScriptBlockAst.PerformPostParseChecks(Parser parser)
   at System.Management.Automation.Language.Parser.ParseTask(String fileName, String input, List`1 tokenList, Boolean recursed, ParseMode parseMode)
   at System.Management.Automation.Language.Parser.Parse(String fileName, String input, List`1 tokenList, ParseError[]& errors, ParseMode parseMode)
   at System.Management.Automation.Language.Parser.ParseInput(String input, String fileName, Token[]& tokens, ParseError[]& errors)


PS C:\Users\SpanWork>
```

### Screenshot

![image](https://user-images.githubusercontent.com/4689924/167804921-9758ffbc-0d44-43e2-a8a9-56a74c1ba9d2.png)

### Environment data

```console
PS Version: 7.2.3
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.2.5
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 120
BufferHeight: 73
```

### Steps to reproduce

Put any multi-line text onto the clipboard.
Then press Ctrl-V.
It shows "Warning - you are about to to paste text that contains multiple lines"
Click "Paste Anyway"

### Expected behavior

Multi-line text is pasted

### Actual behavior

This message is written to the console:

 ### Exception
>> ```
>> System.Management.Automation.PSArgumentException: Cannot process argument because the value of argument "name" is not valid. Change the value of the "name" argument and run the operation again.

**Comment by alansingfield** [comment] 2022-05-11 08:43
The problem seems to be caused by the USING statement.

Type in the following lines manually (not copy-paste), one by one:

using namespace [System.Security.Cryptography]
$s = "CN=Fabrikam Encryption Certificate"
$algorithm = [RSA]::Create(2048)

It will crash when you key the [

**Comment by daxian-dbw** [comment] 2022-05-11 16:03
Thanks for reporting the issue. This is a duplicate of https://github.com/PowerShell/PowerShell/issues/17113.

**Closed as completed by daxian-dbw** 2022-05-11 16:03 UTC
