### ISSUE TITLE
Error using right alt key

### ISSUE THREAD

**Issue by FriedrichWeinmann** [PowerShell/PSReadLine#646] opened 2018-03-12 04:16 UTC
Environment data
----------------

```
PS version: 6.0.1
PSReadline version: 2.0.0-beta1
os: 10.0.16299.15 (WinBuild.160101.0800)
PS file version: 6.0.1
OS Language: German
Keyboard Layout: German
```

Steps to reproduce or exception report
--------------------------------------

PSReadline currently refuses all character input that requires the right `ALT` key.

On a German keyboard, that includes `[`, `]`, `{`, `}`, `|`, ...

**Comment by lzybkr** [comment] 2018-03-12 04:50
This is a dupe of https://github.com/lzybkr/PSReadLine/issues/617 but the fix is not published to the gallery yet, so you'll need to grab a build from appveyor [here](https://ci.appveyor.com/project/lzybkr/PSReadLine/build/artifacts) to try out the fix.

**Closed as completed by lzybkr** 2018-03-12 04:50 UTC
Labels: Resolution-Duplicate
