### ISSUE TITLE
Random error

### ISSUE THREAD

**Issue by Korabi-dev** [PowerShell/PSReadLine#3056] opened 2021-11-21 17:17 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
glitter push Login endpoint now ip grabs people �

Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new
### Environment
PSReadLine: 2.0.0
PowerShell: 5.1.22000.282
OS: Microsoft Windows 10.0.22000
Last 89 Keys

 c l s Enter
 Backspace Backspace n o Backspace p m Spacebar i Spacebar b c r y p t Enter
 c l s Enter
 Backspace Backspace g l i t t e r Spacebar p u s h Spacebar L o g i n Spacebar e n d p o i n t Spacebar n o w Spacebar t o k e n Spacebar Backspace Backspace Backspace Backspace Backspace Backspace i p Spacebar g r a b s Spacebar p e o p l e Spacebar � Enter

```

### Exception
```
System.Text.EncoderFallbackException: Unable to translate Unicode character \uD83D at index 48 to specified code page.
   at System.Text.EncoderExceptionFallbackBuffer.Fallback(Char charUnknown, Int32 index)
   at System.Text.EncoderFallbackBuffer.InternalFallback(Char ch, Char*& chars)
   at System.Text.UTF8Encoding.GetBytes(Char* chars, Int32 charCount, Byte* bytes, Int32 byteCount, EncoderNLS baseEncoder)
   at System.Text.EncoderNLS.GetBytes(Char[] chars, Int32 charIndex, Int32 charCount, Byte[] bytes, Int32 byteIndex, Boolean flush)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at Microsoft.PowerShell.PSConsoleReadLine.<>c__DisplayClass83_0.<WriteHistoryRange>b__0()
   at Microsoft.PowerShell.PSConsoleReadLine.WithHistoryFileMutexDo(Int32 timeout, Action action)
   at Microsoft.PowerShell.PSConsoleReadLine.MaybeAddToHistory(String result, List`1 edits, Int32 undoEditIndex, Boolean fromDifferentSession, Boolean fromInitialRead)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

### Screenshot

![image](https://user-images.githubusercontent.com/69105206/142772204-0f722658-701c-489c-9d52-3eace9d154fd.png)

### Environment data

```console
PS Version: 5.1.22000.282
PS HostName: ConsoleHost
PSReadLine Version: 2.0.0
PSReadLine EditMode: Windows
OS: 10.0.22000.1 (WinBuild.160101.0800)
BufferWidth: 228
BufferHeight: 55
```

### Steps to reproduce

firstly run `Set-ExecutionPolicy RemoteSigned -scope CurrentUser && iwr -useb get.scoop.sh | iex` then run `scoop install glitter` then change the terminal directory to a project that is on github and type `glitter push  Login endpoint now ip grabs people 😂` (my app doesnt actually ip grab people it was a joke just to clear that up).  

### Expected behavior

Glitter should run and push all changes to github

### Actual behavior

You will get an error telling you to report a bug

**Comment by daxian-dbw** [comment] 2021-11-21 22:58
Close as a duplicate of #2358

**Closed as completed by daxian-dbw** 2021-11-21 22:58 UTC
