### ISSUE TITLE
Got "Oops, something went wrong" while doing 

### ISSUE THREAD

**Issue by rmariboe** [PowerShell/PSReadLine#270] opened 2015-08-18 00:40 UTC
Tried to do something in the order of this:

$process = New-Object -TypeName 'System.Diagnostics.Process'
...
$process.BeginOutputReadLine()
$process.BeginErrorReadLine()
...
$process.Close()
$process.CancelOutputRead()
$process.CancelErrorRead()
- And got this:

Oops, something went wrong.  Please report this bug with the details below.
## Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new

Last 0 Keys:

Exception:
System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
##    at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

Exception calling "CancelOutputRead" with "0" argument(s): "No async read operation is in progress on the stream."
At line:123 char:2
-  $process.CancelOutputRead()
-  ~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
  - FullyQualifiedErrorId : InvalidOperationException

Exception calling "CancelErrorRead" with "0" argument(s): "No async read operation is in progress on the stream."
At line:124 char:2
-  $process.CancelErrorRead()
-  ~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
  - FullyQualifiedErrorId : InvalidOperationException

Apparently, PSReadLine is an integral part of PowerShell 5..?

**Comment by lzybkr** [comment] 2015-08-20 05:16
Dupe of #158.
As a workaround, if you don't need input redirection, passing -NonInteractive will suppress loading PSReadline.

**Closed as completed by lzybkr** 2015-08-20 05:16 UTC
Labels: Resolution-Duplicate
