### ISSUE TITLE
invalid ”Set-PSReadlineKeyHandler -Chord Ctrl+[ -Function ViCommandMode” (PowerShell 7.2.2)

### ISSUE THREAD

**Issue by liangjunheng** [PowerShell/PSReadLine#3255] opened 2022-04-02 03:12 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
PowerShell 7.2.2
invalid ”Set-PSReadlineKeyHandler -Chord Ctrl+[ -Function ViCommandMode”
```

### Screenshot
![image](https://user-images.githubusercontent.com/13973175/161363774-50bdb478-ac11-49cf-8982-41d3a5948d26.png)

PowerShell 7.2.2
invalid ”Set-PSReadlineKeyHandler -Chord Ctrl+[ -Function ViCommandMode”

### Environment data

```console
PowerShell 7.2.2
```

### Steps to reproduce

invalid ”Set-PSReadlineKeyHandler -Chord Ctrl+[ -Function ViCommandMode”

### Expected behavior

 ”Ctrl+[” invalid

### Actual behavior

PowerShell 7.2.2

**Comment by daxian-dbw** [comment] 2022-04-04 17:14
Close as a duplicate of #3116

**Closed as completed by daxian-dbw** 2022-04-04 17:14 UTC
