### ISSUE TITLE
Control-l causes crash

### ISSUE THREAD

**Issue by pavelbraginskiy** [PowerShell/PSReadLine#729] opened 2018-07-17 04:45 UTC
Environment data
----------------

```
PS version: 6.1.0-preview.3
PSReadline version: 2.0.0-beta2
os: Linux ThinkPad 4.16.16-300.fc28.x86_64 #1 SMP Sun Jun 17 03:02:42 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
PS file version: 
```

Steps to reproduce or exception report
--------------------------------------
```
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 1 Keys:
 Ctrl+l

Exception:
System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.ConsolePal.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

**Comment by lzybkr** [comment] 2018-10-19 04:43
Closing as a duplicate of #654.

**Closed as completed by lzybkr** 2018-10-19 04:43 UTC
