### ISSUE TITLE
Problem with unicode input (copy-paste) on Windows 10 + Terminal

### ISSUE THREAD

**Issue by RoguePointer80** [PowerShell/PSReadLine#1715] opened 2020-07-30 18:14 UTC
I am using Windows Terminal + Powershell 7.0.3. I noticed that I could not copy-paste some unicode characters into it.
Here is some basic repro steps:
open up your favorite web browser to : https://emojipedia.org/green-heart/
Copy the line at the bottom that contains the character and its code point to the clipboard (ctrl-c)
example : 💚 U+1F49A

Open up Windows Terminal with a Powershell Core tab.
Try to type `Write-Host ''` and paste the clipboard (ctrl-v) between the two ''.
Expected: Write-Host '💚 U+1F49A'
> 💚 U+1F49A

Actual:
![image](https://user-images.githubusercontent.com/30326057/88958420-6fabff80-d26e-11ea-88bc-c7a354a4beb3.png)

Textual version:
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new
### Environment
PSReadLine: 2.0.0-rc2
PowerShell: 7.0.3
OS: Microsoft Windows 10.0.19041
Last 23 Keys
```
 W r i t e - H o s t Spacebar ' � Spacebar U + 1 F 4 9 A ' Enter

```

### Exception
```
System.Text.EncoderFallbackException: Unable to translate Unicode character \\uD83D at index 12 to specified code page.   at System.Text.EncoderExceptionFallbackBuffer.Fallback(Char charUnknown, Int32 index)
   at System.Text.EncoderFallbackBuffer.InternalFallback(ReadOnlySpan`1 chars, Int32& charsConsumed)
   at System.Text.Encoding.GetBytesWithFallback(ReadOnlySpan`1 chars, Int32 originalCharsLength, Span`1 bytes, Int32 originalBytesLength, EncoderNLS encoder)
   at System.Text.Encoding.GetBytesWithFallback(Char* pOriginalChars, Int32 originalCharCount, Byte* pOriginalBytes, Int32 originalByteCount, Int32 charsConsumedSoFar, Int32 bytesWrittenSoFar, EncoderNLS encoder)
   at System.Text.Encoding.GetBytes(Char* pChars, Int32 charCount, Byte* pBytes, Int32 byteCount, EncoderNLS encoder)
   at System.Text.EncoderNLS.GetBytes(Char* chars, Int32 charCount, Byte* bytes, Int32 byteCount, Boolean flush)
   at System.Text.EncoderNLS.GetBytes(Char[] chars, Int32 charIndex, Int32 charCount, Byte[] bytes, Int32 byteIndex, Boolean flush)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at Microsoft.PowerShell.PSConsoleReadLine.<>c__DisplayClass83_0.<WriteHistoryRange>b__0()
   at Microsoft.PowerShell.PSConsoleReadLine.WithHistoryFileMutexDo(Int32 timeout, Action action)
   at Microsoft.PowerShell.PSConsoleReadLine.WriteHistoryRange(Int32 start, Int32 end, Func`2 fileOpener)
   at Microsoft.PowerShell.PSConsoleReadLine.IncrementalHistoryWrite()
   at Microsoft.PowerShell.PSConsoleReadLine.MaybeAddToHistory(String result, List`1 edits, Int32 undoEditIndex, Boolean fromDifferentSession, Boolean fromInitialRead)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

I actually tried to paste the same clipboard into VS Code and it worked perfectly. Also, just for fun, I tried to paste the equivalent into CMD.exe:
![image](https://user-images.githubusercontent.com/30326057/88958681-d3362d00-d26e-11ea-91e2-1052e1aca6b3.png)

to my suprise it nearly worked.
My System Locale is English, but I have activated the beta feature "use UTF-8" that makes the system code page 65001.

**Comment by RoguePointer80** [comment] 2020-07-30 20:16
This seems like a problem with UTF-16 surrogate pairs.

**Comment by syntroniks** [comment] 2020-08-17 16:56
I am able to reproduce this 

### Environment
PSReadLine: 2.1.0-beta2
PowerShell: 5.1.20180.1000
OS: Microsoft Windows 10.0.20180
BufferWidth: 120
BufferHeight: 30
Last 24 Keys
```
 w r i t e - h o s t Spacebar ' ' LeftArrow � Spacebar U + 1 F 4 9 A Enter

```

### Exception
```
System.Text.EncoderFallbackException: Unable to translate Unicode character \uD83D at index 12 to specified code page.
   at System.Text.EncoderExceptionFallbackBuffer.Fallback(Char charUnknown, Int32 index)
   at System.Text.EncoderFallbackBuffer.InternalFallback(Char ch, Char*& chars)
   at System.Text.UTF8Encoding.GetBytes(Char* chars, Int32 charCount, Byte* bytes, Int32 byteCount, EncoderNLS baseEncoder)
   at System.Text.EncoderNLS.GetBytes(Char[] chars, Int32 charIndex, Int32 charCount, Byte[] bytes, Int32 byteIndex, Boolean flush)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at Microsoft.PowerShell.PSConsoleReadLine.<>c__DisplayClass83_0.<WriteHistoryRange>b__0()
   at Microsoft.PowerShell.PSConsoleReadLine.WithHistoryFileMutexDo(Int32 timeout, Action action)
   at Microsoft.PowerShell.PSConsoleReadLine.MaybeAddToHistory(String result, List`1 edits, Int32 undoEditIndex, Boolean fromDifferentSession, Boolean fromInitialRead)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

```
> chcp
Active code page: 437
```

```
cmd->

>echo '💚 U+1F49A'
'💚 U+1F49A'
```

**Comment by syntroniks** [comment] 2020-08-17 17:10
Looks like a duplicate of #949

**Comment by nu8** [comment] 2020-08-24 23:01
As a workaround, I found that NuShell with Windows Terminal works as expected:

>![1715](https://user-images.githubusercontent.com/61808913/91104657-cde0be00-e633-11ea-8064-9b5ca1588d6c.png)

https://github.com/nushell/nushell

**Comment by daxian-dbw** [comment] 2020-08-28 19:25
Closing as a dup of #949

**Closed as completed by daxian-dbw** 2020-08-28 19:25 UTC
Labels: Resolution-Duplicate
