### ISSUE TITLE
exception error after usage sudo command

### ISSUE THREAD

**Issue by mitek-mb** [PowerShell/PSReadLine#3504] opened 2022-12-02 15:16 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.yaml
Thank you!

### Environment
PSReadLine: 2.2.6
PowerShell: 7.3.0
OS: Darwin 21.6.0 Darwin Kernel Version 21.6.0: Thu Sep 29 20:12:57 PDT 2022; root:xnu-8020.240.7~1/RELEASE_X86_64
BufferWidth: 190
BufferHeight: 34

Last 0 Keys:



### Exception

System.IO.IOException: The system cannot open the device or file specified. : 'PSReadLineHistoryFile_91202998'
   at System.Threading.Mutex.CreateMutexCore(Boolean initiallyOwned, String name, Boolean& createdNew)
   at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name)
   at Microsoft.PowerShell.PSConsoleReadLine.DelayedOneTimeInitialize()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken, Nullable`1 lastRunStatus)
```

### Screenshot

![pwsh-error-psreadline](https://user-images.githubusercontent.com/89939041/205322313-e9c8fedd-4a41-477e-8ac8-ab62bc0a1a78.png)

### Environment data

```console
PS Version: 7.3.0
PS HostName: ConsoleHost
PSReadLine Version: 2.2.6
PSReadLine EditMode: Emacs
OS: Darwin MacBookPro 21.6.0 Darwin Kernel Version 21.6.0: Thu Sep 29 20:12:57 PDT 2022; root:xnu-8020.240.7~1/RELEASE_X86_64 x86_64
BufferWidth: 120
BufferHeight: 30
```

### Steps to reproduce

1. start 'sudo pwsh'
2. Install-Module -Name PSWSMan
3. Install-WSMan
4. (it will drop back to bash)
5. start 'pwsh'
6. error is shown. 
7. type 'exit'
8. start 'pwsh'
9. error is shown again

A normal pwsh is only possible again after initiating a new terminal shell 

### Expected behavior

no exception error after restarting pwsh

### Actual behavior

every command shows an exception error as mentioned above

**Comment by daxian-dbw** [comment] 2022-12-02 18:30
Thanks for reporting this issue. It's a duplicate of #2658

**Closed as completed by daxian-dbw** 2022-12-02 18:30 UTC
