### ISSUE TITLE
System.IO.IOException in ConEmu+Windows 10

### ISSUE THREAD

**Issue by DanielRosenwasser** [PowerShell/PSReadLine#274] opened 2015-08-27 20:10 UTC
```
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 p t o j s / t e s t / m o d e - c t r - t e s t s . t s Tab Enter
 s t a r t Spacebar c r y p t o j s / t e s t / t r i p l e d e s - t e s t s . t s Tab Enter
 s t a r t Spacebar c r y p t o j s / t e s t / m o d e - o f b - t e s t s . t s Tab Enter
 s t a r t Spacebar c r y p t o j s / a l l - t e s t s . t s Tab Enter
 g f i t Spacebar Backspace Backspace Backspace Backspace Backspace i t Backspace Backspace g i t Spacebar d i f f Enter
 g i t Spacebar a d d Spacebar c r y p t o j s / t Tab Enter
 g i t Spacebar d i f f Spacebar - - c a c h e d Enter
 PageDown

Exception:
System.IO.IOException: The parameter is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ScrollDisplayDown(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

Was using ConEmu in Windows 10, did not have it in fullscreen mode, so not sure if this is related to #232, or if somehow ConEmu runs in a pseudo-fullscreen mode, but figured a bug report couldn't hurt

**Comment by lzybkr** [comment] 2017-01-12 20:39
Most likely a dupe of #292, reopen with additional information if you disagree.

**Closed as completed by lzybkr** 2017-01-12 20:39 UTC
Labels: Resolution-Duplicate
