### ISSUE TITLE
Remote Runspace Error

### ISSUE THREAD

**Issue by pldmgg** [PowerShell/PSReadLine#312] opened 2015-12-06 09:51 UTC
(This is my first time posting an issue to project on GitHub, so please let me know if I'm not following proper etiquette)

I received the below error while testing https://github.com/PowerShell/Win32-OpenSSH in a lab environment by ssh-ing from one Windows 2012 R2 VM to another.

On the localhost, I simply extracted OpenSSH-Win32.zip to C:\openssh. 

On the remote host  (in an RDP session) I extracted OpenSSH-Win32.zip to C:\openssh, and from an elevated command prompt ran the following:
cd C:\openssh
ssh-keygen.exe -t rsa -f ssh_host_rsa_key
ssh-keygen.exe -t dsa -f ssh_host_dsa_key
ssh-keygen.exe -t ecdsa -f ssh_host_ecdsa_key
ssh-keygen.exe -t ed25519 -f ssh_host_ed25519_key
sshd install
net start sshd

Also on the remote host, my C:\openssh\sshd_config file is attached (the .txt file extension was added so that I could upload to github).

[sshd_config.txt](https://github.com/lzybkr/PSReadLine/files/53115/sshd_config.txt)

Back on the localhost, I launched an elevated command prompt and ran the following:
cd C:\openssh
ssh.exe -l user@domain remotehost

I was able to successfully get to the command prompt on the remote host.  Next, I tried launching PowerShell (version 4.0) using the following command (see: https://github.com/PowerShell/Win32-OpenSSH/wiki/ssh.exe-examples ):
user@remotehost C:\Users\user>powershell -File -

(Note - I do not have a PowerShell profile configured to be loaded.)

I received the following error message:

Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
## Or email: jason@truewheels.net

Last 0 Keys:

Exception:
System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at PSConsoleUtilities.PSConsoleReadLine.Initialize(Runspace remoteRunspace, EngineIntrinsics engineIntrinsics)
##    at PSConsoleUtilities.PSConsoleReadLine.ReadLine(Runspace remoteRunspace, EngineIntrinsics engineIntrinsics)

Also, as an alternate to "powershell -File -", I tried "powershell -NoProfile" with the same results (i.e. the above error message)

Please let me know if you need any additional information or if I can assist in any way.

**Comment by lzybkr** [comment] 2015-12-07 16:47
Thanks for the report, proper etiquette is to provide enough detail to reproduce the bug if possible, which it looks like you have.

I'm pretty sure this is a dupe of #158 and I'll resolve it as such, but if the problem reproduces after fixing the reference bug, feel free to reopen.

**Closed as completed by lzybkr** 2015-12-07 16:47 UTC
Labels: Issue-Bug, Resolution-Duplicate
