### ISSUE TITLE
Container terminal crashes for powershell - System.IndexOutOfRangeException: Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by qinl-li** [PowerShell/PSReadLine#3774] opened 2023-08-08 05:05 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.yaml
Thank you!

### Environment
PSReadLine: 2.2.6
PowerShell: 7.3.6
OS: Linux 5.15.0-1035-azure #42-Ubuntu SMP Tue Feb 28 19:41:23 UTC 2023
BufferWidth: 0
BufferHeight: 0

Last 1 Keys:

 t

### Exception

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Text.StringBuilder.get_Chars(Int32 index)
   at Microsoft.PowerShell.PSConsoleReadLine.ConvertOffsetToPoint(Int32 offset)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Render()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken, Nullable`1 lastRunStatus)
```

### Screenshot

<img width="1462" alt="image" src="https://github.com/PowerShell/PSReadLine/assets/63257243/3e3c7e3f-a905-4241-95e9-6dd40a0ddef0">

### Environment data

```console
PS Version: 7.3.6
PS HostName: ConsoleHost
PSReadLine Version: 2.2.6
PSReadLine EditMode: Emacs
OS: Linux toolbox10 5.15.0-1035-azure #42-Ubuntu SMP Tue Feb 28 19:41:23 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
BufferWidth: 0
BufferHeight: 0
```

### Steps to reproduce

1.  Create a container use the following command: 
k run toolbox10 --image=azuresearchlab.azurecr.io/toolbox:0.0.4-qinl  -- /bin/pwsh -NoLogo -NoExit -Command Start-Sleep -Seconds 9999

2. using @kubernetes/client-node to create interactive session 
3. 
	const kc = new k8s.KubeConfig();
	kc.loadFromDefault();

	const k8sApi = kc.makeApiClient(k8s.CoreV1Api);
	const exec_command2 = [
		'/bin/bash',
		'-c',
		'export TERM=xterm-256color;printenv;pwsh -NoLogo']
	const exec = new k8s.Exec(kc);
		
	socket = await exec.exec(namespace, podName, containerName, exec_command2, stdout, stdout, stdin, true,
		(status: k8s.V1Status) => {
			console.log('Exited with status:');
			console.log(JSON.stringify(status, null, 2));
		})

### Expected behavior

It should create an interactive session and pipe the input to container

### Actual behavior

Terminal crashes when typing in powershell session. However, it works fine  for bash
<img width="1214" alt="image" src="https://github.com/PowerShell/PSReadLine/assets/63257243/ccded7be-44fd-45fa-b484-18bd79330378">

**Comment by daxian-dbw** [comment] 2023-08-08 14:32
@qinl-li Can you please provide repro steps with the docker commands only? The repro steps you provided cannot execute directly. We need simple repros to run locally for investigation.

**Comment by daxian-dbw** [comment] 2023-08-08 18:03
Chatted with @qinl-li offline and this is a duplicate of #2844. See https://github.com/PowerShell/PSReadLine/issues/2844#issuecomment-921047295 for details.

**Closed as completed by daxian-dbw** 2023-08-08 18:03 UTC
Labels: Resolution-Duplicate
