### ISSUE TITLE
Error while clearing console in VS Code

### ISSUE THREAD

**Issue by AgainPsychoX** [PowerShell/PSReadLine#2623] opened 2021-06-27 15:13 UTC
I wanted to clear console with `Ctrl`+`L` while in VS Code. It worked for second time.

```
Last 200 Keys:
 / f i r e b a s e Tab Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace . . / f i r e b a s e Tab DownArrow UpArrow DownArrow UpArrow UpArrow DownArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace i n s t a l l Space f i r e b s a Backspace Backspace a s e Enter
 UpArrow UpArrow UpArrow DownArrow Enter
 c l e a r Enter
 c d Space . . / m o Tab Enter
 t s c Space Backspace Enter
 UpArrow Enter
 UpArrow UpArrow DownArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow UpArrow DownArrow Enter
 c l e a r Enter
 UpArrow UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 c d Space . . Enter
 c d Space f u n Tab Enter
 UpArrow UpArrow UpArrow UpArrow DownArrow UpArrow UpArrow UpArrow DownArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace n p m Space r u n Space b u i l d Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 Tab Ctrl+l

Exception:
System.ArgumentOutOfRangeException: Wartość musi być większa lub równa zero i mniejsza od rozmiaru buforu konsoli w tym wymiarze.
Nazwa parametru: top /// parameter name
Rzeczywista wartość to -3. /// real value is -3
   w System.Console.SetCursorPosition(Int32 left, Int32 top)
   w Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   w Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   w Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

**Comment by daxian-dbw** [comment] 2021-07-01 17:53
@AgainPsychoX No environment data is provided for us to investigate the issue. This looks like a duplicate of #1315, so please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.

**Closed as completed by daxian-dbw** 2021-07-01 17:53 UTC
