### ISSUE TITLE
Git Commit Error

### ISSUE THREAD

**Issue by Mutahhar** [PowerShell/PSReadLine#3421] opened 2022-08-28 08:00 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
### Environment
PSReadLine: 2.1.0
PowerShell: 7.2.6
OS: Microsoft Windows 10.0.22000
BufferWidth: 140
BufferHeight: 6

Last 200 Keys

 Spacebar a p p / C o n s o l e / C o m m a n d s / G e n e r a t e P i t c h T i m e R e s e r v a t i o n s C o m m a n d . p h p Enter
 UpArrow UpArrow Enter
 g i t Spacebar a d d Spacebar a p p / C o n s o l e / K e r n e l . p h p Enter
 g i t Spacebar c o m m i t Spacebar - m Spacebar ' ' LeftArrow � Backspace � Spacebar N E W Spacebar - Spacebar S c h d Backspace e d u l e
 Spacebar p i LeftArrow RightArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace S c h e d u l e Spacebar g e n e r a t e : p i t c h - t i m e - r e s e r v a t i o n s Spacebar c o m m a n d Enter

```

### Exception
```
System.Text.EncoderFallbackException: Unable to translate Unicode character \\uD83D at index 15 to specified code page.
   at System.Text.EncoderExceptionFallbackBuffer.Fallback(Char charUnknown, Int32 index)
   at System.Text.Encoding.GetBytesWithFallback(ReadOnlySpan`1 chars, Int32 originalCharsLength, Span`1 bytes, Int32 originalBytesLength, EncoderNLS encoder)
   at System.Text.Encoding.GetBytesWithFallback(Char* pOriginalChars, Int32 originalCharCount, Byte* pOriginalBytes, Int32 originalByteCount, Int32 charsConsumedSoFar, Int32 bytesWrittenSoFar, EncoderNLS encoder)
   at System.Text.Encoding.GetBytes(Char* pChars, Int32 charCount, Byte* pBytes, Int32 byteCount, EncoderNLS encoder)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at Microsoft.PowerShell.PSConsoleReadLine.<>c__DisplayClass83_0.<WriteHistoryRange>b__0()
   at Microsoft.PowerShell.PSConsoleReadLine.WithHistoryFileMutexDo(Int32 timeout, Action action)
   at Microsoft.PowerShell.PSConsoleReadLine.WriteHistoryRange(Int32 start, Int32 end, Boolean overwritten)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```
```


### Screenshot

![image](https://user-images.githubusercontent.com/11645672/187064032-1e9cb93b-deb4-4f35-8757-5ea23e1b629a.png)


### Environment data

```console
PS Version: 7.2.6
PS HostName: ConsoleHost
PSReadLine Version: 2.1.0
PSReadLine EditMode: Windows
OS: 10.0.22000.1 (WinBuild.160101.0800)
BufferWidth: 140
BufferHeight: 12
```

### Steps to reproduce

I don't know how to reproduce this. I encountered this error the first time.

### Expected behavior

git commit command should work as it was working before

### Actual behavior

I am trying to git commit and this error occurred.

**Comment by Mutahhar** [comment] 2022-08-28 09:01
Note: I tried the same command with `git bash` terminal and it worked

**Comment by daxian-dbw** [comment] 2022-08-29 16:33
This is a duplicate of #2358

**Closed as completed by daxian-dbw** 2022-08-29 16:33 UTC
