### ISSUE TITLE
Azure Powershell asked me to post this issue

### ISSUE THREAD

**Issue by JohannStock** [PowerShell/PSReadLine#960] opened 2019-07-07 21:37 UTC
Azure:/
PS Azure:\>
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 21 Keys:
```
 g c i Enter
 g e t - m o d u l e Enter
 PageUp PageUp PageUp PageDown PageDown PageDown
```

Exception:
```
System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.ConsolePal.SetWindowPosition(Int32 left, Int32 top)
   at System.Console.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ScrollDisplayDown(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```
-----------------------------------------------------------------------
Azure:/
PS Azure:\>

**Comment by daxian-dbw** [comment] 2019-07-16 00:14
> Azure Powershell asked me to post this issue

In what environment did you run into this issue? Were you actually using Cloud Shell?

**Comment by daxian-dbw** [comment] 2019-09-11 21:43
Close as a duplicate of #1016

**Closed as completed** 2019-09-11 21:43 UTC
Labels: Resolution-Duplicate
