### ISSUE TITLE
Exception during Initialize from Console.GetBufferInfo

### ISSUE THREAD

**Issue by Helperbot3** [PowerShell/PSReadLine#424] opened 2016-08-20 00:45 UTC
Last 0 Keys:

Exception:
System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by lzybkr** [comment] 2016-08-20 05:35
Can you provide some more context on how I might reproduce this error?

**Comment by lzybkr** [comment] 2017-01-12 20:21
Most likely a dupe of #158, reopen with additional information if you disagree.

**Closed as completed by lzybkr** 2017-01-12 20:21 UTC
Labels: Resolution-Duplicate
