### ISSUE TITLE
Powershell debug error Last 200 Keys:

### ISSUE THREAD

**Issue by phutares** [PowerShell/PSReadLine#1421] opened 2020-03-24 08:02 UTC
Last 200 Keys:
 8 - 3 2 \ p y t h o n . e x e ' Space ' c 
: \ U s e r s \ P A X \ . v s c o d e \ e x t e n s i o n s \ m s - p y t h o n . p y 
t h o n - 2 0 2 0 . 3 . 6 9 0 1 0 \ p y t h o n F i l e s \ l i b \ p y t h o n \ d e 
b u g p y \ n o _ w h e e l s \ d e b u g p y \ l a u n c h e r ' Space ' C : \ U s e 
r s \ P A X \ P A X \ G i t Space P r o j \ D X D \ W e b S c r a p e / W e b S c r a 
p e / m a i n . p y ' Space Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)       
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)   
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by iSazonov** [comment] 2020-03-24 10:46
#1306

**Comment by daxian-dbw** [comment] 2020-03-24 17:07
From the bug report template:
```
The maintainer may close your issue without further explanation or engagement if:
- You delete this entire template and go your own path;
```
So, please follow the bug report template to provide **environment data** and **repro step** the next time.

As for this issue, it's a duplicate of #1306 and was fixed in the latest version. Please check out #1306 for more information.

**Closed as completed by daxian-dbw** 2020-03-24 17:07 UTC
Labels: Resolution-Duplicate
