### ISSUE TITLE
PSReadline array size error on keypress, soon after resize

### ISSUE THREAD

**Issue by brendanburkhart** [PowerShell/PSReadLine#567] opened 2017-10-30 02:43 UTC
Last 4 Keys:
 LeftWindows LeftWindows LeftWindows g

Exception:
System.ArgumentException: Destination array was not long enough. Check destIndex and length, and the array's lower bounds.
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Array destinationArray, Int32 length)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

Environment data
----------------
PS version: 5.1.15063.674
PSReadline version: 1.2
os: 10.0.15063.0 (WinBuild.160101.0800)
PS file version: 10.0.15063.0 (WinBuild.160101.0800)

**Comment by lzybkr** [comment] 2017-10-30 03:28
Dupe of #292.

**Closed as completed by lzybkr** 2017-10-30 03:28 UTC
Labels: Resolution-Duplicate
