### ISSUE TITLE
PSReadLine intercepts keys meant for the terminal

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PSReadLine#1295] opened 2020-01-13 19:07 UTC
Environment data
----------------

PS version: 5.1.19041.1
PSReadline version: 2.0.0-rc1
os: 10.0.19041.1 (WinBuild.160101.0800)
PS file version: 10.0.19041.1 (WinBuild.160101.0800)
HostName: ConsoleHost
BufferWidth: 120
BufferHeight: 3000

Steps to reproduce or exception report
--------------------------------------

1. Start PowerShell in Windows console 
2. Ensure Ctrl+F isn't bound to a handler
3. Ctrl+F

Expected:

Find dialog to pop up

Actual:

^F is printed to console

Not sure if there's a way for PSReadLine to passthrough the keys so that the terminal can get them.  Removing PSReadLine allows this to work as expected.

**Comment by lzybkr** [comment] 2020-01-13 19:12
Duplicate of #280, also see https://github.com/microsoft/terminal/issues/1226

**Comment by daxian-dbw** [comment] 2020-01-13 19:13
Thanks @lzybkr. I knew there was a duplicate issue and was looking for it.

**Closed as completed by lzybkr** 2020-01-13 19:12 UTC
Labels: Issue-Bug, Resolution-Duplicate
