### ISSUE TITLE
Powershell on SSH session ends up in Exception

### ISSUE THREAD

**Issue by prasannavl** [PowerShell/PSReadLine#348] opened 2016-02-21 16:07 UTC
Powershell on SSH session with Win32-OpenSSH from https://github.com/PowerShell/Win32-OpenSSH/releases ends up with the following, with the session unusable.

```
Last 0 Keys:


Exception:
System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

**Comment by lzybkr** [comment] 2017-01-12 20:54
Most likely a dupe of #158, reopen with additional information if you disagree.

**Closed as completed by lzybkr** 2017-01-12 20:54 UTC
Labels: Resolution-Duplicate
