### ISSUE TITLE
"Enter" key press used to invoke the command is passed to the command as an input

### ISSUE THREAD

**Issue by MOZGIII** [PowerShell/PSReadLine#901] opened 2019-04-20 02:05 UTC
Environment data
----------------

PS version: 5.1.17763.316
PSReadline version: 2.0.0-beta2
os: 10.0.17763.470 (WinBuild.160101.0800)
PS file version: 10.0.17763.470 (WinBuild.160101.0800)

Steps to reproduce or exception report
--------------------------------------

"Enter" key press used to invoke the command is passed to the command as an input.

See https://github.com/TimonPost/crossterm/issues/124

Steps to reproduce:

0. I have an app with terminal UI that triggers some action via "Enter".
1. I type `myapp.exe` in PowerShell.
2. I press "Enter" key.
3. App starts and immediately triggers "Enter" key handler.

**Comment by daxian-dbw** [comment] 2023-02-09 18:14
Close as a duplicate of #959, which contains more investigation information.

**Closed as completed by daxian-dbw** 2023-02-09 18:14 UTC
