### ISSUE TITLE
Just went down

### ISSUE THREAD

**Issue by sukkergris** [PowerShell/PSReadLine#616] opened 2018-01-11 16:59 UTC
Last 62 Keys:
 g i t Spacebar b r a n c h Enter
 g i t Spacebar c h e c k o u t Spacebar w e b p a c
k Enter
 g i t Spacebar c h e c k o u t Spacebar w e Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace

Exception:
System.ArgumentException: Destinationens matrix var ikke lang nok. Kontrollér destIndex og længden samt matrixens nedre grænser.
   ved System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   ved System.Array.Copy(Array sourceArray, Array destinationArray, Int32 length)   ved Microsoft.PowerShell.PSConsoleReadLine.ReallyRender()
   ved Microsoft.PowerShell.PSConsoleReadLine.BackwardDeleteChar(Nullable`1 key, Object arg)   ved Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)   ved Microsoft.PowerShell.PSConsoleReadLine.InputLoop()   ved Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------PSn>

**Comment by lzybkr** [comment] 2018-01-11 17:29
Dupe of #292.

**Closed as completed by lzybkr** 2018-01-11 17:29 UTC
Labels: Resolution-Duplicate
