### ISSUE TITLE
PowerShell -ExecutionPolicy Unrestricted

### ISSUE THREAD

**Issue by alzikan** [PowerShell/PSReadLine#482] opened 2016-12-14 05:44 UTC
Last 0 Keys:

Exception:
System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded
)
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, Engi
neIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, Engine
Intrinsics engineIntrinsics)

**Comment by lzybkr** [comment] 2017-01-12 20:44
Most likely a dupe of #158, reopen with additional information if you disagree.

**Closed as completed by lzybkr** 2017-01-12 20:44 UTC
Labels: Resolution-Duplicate
