### ISSUE TITLE
System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string.

### ISSUE THREAD

**Issue by Twometer** [PowerShell/PSReadLine#726] opened 2018-07-11 09:38 UTC
Environment data
----------------
PS version: 5.1.14393.2312
PSReadline version: 1.2
os: 10.0.14393.0 (rs1_release.160715-1616)
PS file version: 10.0.14393.0 (rs1_release.160715-1616)

Steps to reproduce or exception report
--------------------------------------
```
-----------------------------------------------------------------------
Last 37 Keys:
 c d Spacebar C > Alt+_ Backspace Backspace Backspace Backspace Backspace Backspace c d Spacebar . . Enter
 c . . Backspace Backspace d . . Enter
 c d Spacebar s c Tab Enter
 . Alt+- Backspace

Exception:
System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string.
Parameter name: startIndex
   at System.Text.StringBuilder.ToString(Int32 startIndex, Int32 length)
   at Microsoft.PowerShell.PSConsoleReadLine.BackwardDeleteChar(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignor
eIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.DigitArgument(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignor
eIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

**Comment by lzybkr** [comment] 2018-07-11 21:19
Thanks for the report, this is a dupe of https://github.com/lzybkr/PSReadLine/issues/502 and is fixed in [2.0.0-beta2](https://www.powershellgallery.com/packages/PSReadLine/2.0.0-beta2).

**Closed as completed by lzybkr** 2018-07-11 21:19 UTC
Labels: Resolution-Duplicate
