### ISSUE TITLE
Powershell 6.0.1 throwing DivideByZeroException continuously

### ISSUE THREAD

**Issue by ratheeshkv179** [PowerShell/PSReadLine#731] opened 2018-07-20 04:21 UTC
**root@keystone-3458668121-813t5:/app#** pwsh
PowerShell v6.0.1
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/pscore6-docs
Type 'help' to get help.

Loading personal and system profiles took 1296ms.
PS /app>
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 0 Keys:

Exception:
System.DivideByZeroException: Attempted to divide by zero.
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by ratheeshkv179** [comment] 2018-07-20 04:33
It is with connecting the docker container instance and trying to access the pwsh.
The base OS is ubuntu.

**Comment by hifall** [comment] 2018-08-25 02:17
I am seeing the same issue too.

**Comment by daxian-dbw** [comment] 2020-03-20 05:35
A duplicate of #670

**Closed as completed by daxian-dbw** 2020-03-20 05:35 UTC
Labels: Resolution-Duplicate

**Comment by daxian-dbw** [comment] 2020-03-26 23:17
@ratheeshkv179 I cannot reproduce this with the latest powershell container images, see https://github.com/PowerShell/PSReadLine/issues/670#issuecomment-601483384.
If you are able to to repro, please leave a comment in #670 for the repro steps, thanks!
