### ISSUE TITLE
found an issue in VS code integrated terminal

### ISSUE THREAD

**Issue by c0demark** [PowerShell/PSReadLine#604] opened 2017-12-06 16:20 UTC
PS D:\DevEnv\jsWS\AngularJS_1.x\dtep-browser-client-with-gulp-setup>
lp-setup> ^B
Oops, something went wrong.  Please report this bug with th
e details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issu
es/new
-----------------------------------------------------------
------------
Last 57 Keys:
 g u l p Spacebar i n j e c t Enter
 g u l p Spacebar c l e a n Enter
 g Backspace Backspace UpArrow UpArrow Enter
 UpArrow Enter
 UpArrow UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow UpArrow Enter
 UpArrow UpArrow UpArrow Enter
 Ctrl+b Backspace

Exception:
System.ArgumentException: Destination array was not long en
ough. Check destIndex and length, and the array's lower bou
nds.
   at System.Array.Copy(Array sourceArray, Int32 sourceInde
x, Array destinationArray, Int32 destinationIndex, Int32 le
ngth, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Array destinatio
nArray, Int32 length)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender()

   at Microsoft.PowerShell.PSConsoleReadLine.BackwardDelete
Char(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(
ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ign
oreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrins
ics)
-----------------------------------------------------------------------
PS D:\DevE
PS D:\DevE
PS D:\DevEnv\jsWS\AngularJS_1.x\dtep-browser-client-with-gulp-setup>

**Comment by lzybkr** [comment] 2017-12-06 17:44
Dupe of many like #491.

**Closed as completed by lzybkr** 2017-12-06 17:44 UTC
Labels: Resolution-Duplicate
