### ISSUE TITLE
Pressing Ctrl+F enters ^F instead of opening the find dialog

### ISSUE THREAD

**Issue by jevansaks** [PowerShell/PSReadLine#568] opened 2017-10-30 23:07 UTC
I reported this issue against powershell but I was told the issue is with PSReadline: "PSReadline intercepts the keyboard handlers.  If you want ctrl+F to have same behavior as cmd.exe, you need to remove PSReadline: remove-module psreadline"

But I like the functionality of PSReadline, I just want the Ctrl+F shortcut to do a find.

Environment data
----------------

PS version: 5.1.17030.1000
PSReadline version: 1.2
os: 10.0.17030.1000 (WinBuild.160101.0800)
PS file version: 10.0.17030.1000 (WinBuild.160101.0800)

Steps to reproduce or exception report
--------------------------------------

Run powershell
Press Ctrl+F

Expected: Find dialog pops up
Result: ^F

**Comment by lzybkr** [comment] 2017-10-31 01:55
This is a duplicate of #280 - though I have considered implementing a replacement - it might not use a dialog though.

**Closed as completed by lzybkr** 2017-10-31 01:55 UTC
Labels: Resolution-Duplicate

**Comment by mklement0** [comment] 2018-11-24 02:46
For a workaround, see https://github.com/lzybkr/PSReadLine/issues/280#issuecomment-441338880.
