### ISSUE TITLE
Exception thrown when pasting an emoji

### ISSUE THREAD

**Issue by 1Dragoon** [PowerShell/PSReadLine#1804] opened 2020-09-12 22:21 UTC
I know this is an edge case and most probably won't run into it, I just happened to be toying around with unicode characters in the terminal and found a bug in psreadline that is potentially a larger issue with the way psreadline, or even .net in general, handles unicode.

## Environment

```
PS version: 7.0.3
PSReadline version: 2.0.2
os: 10.0.18362.1 (WinBuild.160101.0800)
PS file version: 7.0.3.0
HostName: ConsoleHost
BufferWidth: 120
BufferHeight: 9001
```

### Exception
```
System.Text.EncoderFallbackException: Unable to translate Unicode character \\uD83D at index 0 to specified code page.
   at System.Text.EncoderEx�ceptionFallbackBuffer.Fallback(Char charUnknown, Int32 index)
   at System.Text.EncoderFallbackBuffer.InternalFallback(ReadOnlySpan`1 chars, Int32& charsConsumed)
   at System.Text.Encoding.GetBytesWithFallback(ReadOnlySpan`1 chars, Int32 originalCharsLe�ngth, Span`1 bytes, Int32 originalBytesLength, EncoderNLS encoder)
   at System.Text.Encoding.GetBytesWithFallback(Char* pOriginalChars, Int32 originalCharCount, Byte* pOriginalBytes, Int32 originalByteCount, Int32 charsConsumedSoFar, Int32 bytesWrittenSo�Far, EncoderNLS encoder)
   at System.Text.Encoding.GetBytes(Char* pChars, Int32 charCount, Byte* pBytes, Int32 byteCount, EncoderNLS encoder)
   at System.Text.EncoderNLS.GetBytes(Char[] chars, Int32 charIndex, Int32 charCount, Byte[] bytes, Int32 byteI�ndex, Boolean flush)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at Microsoft.PowerShell.PSConsoleReadLine.<>c__DisplayCla�ss83_0.<WriteHistoryRange>b__0()
   at Microsoft.PowerShell.PSConsoleReadLine.WithHistoryFileMutexDo(Int32 timeout, Action action)
   at Microsoft.PowerShell.PSConsoleReadLine.WriteHistoryRange(Int32 start, Int32 end, Func`2 fileOpener)
   at Microsoft.�PowerShell.PSConsoleReadLine.IncrementalHistoryWrite()
   at Microsoft.PowerShell.PSConsoleReadLine.MaybeAddToHistory(String result, List`1 edits, Int32 undoEditIndex, Boolean fromDifferentSession, Boolean fromInitialRead)
   at Microsoft.PowerShell.PSCo�nsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

## Steps to reproduce

Paste this symbol: 😂 into a powershell console and press enter

## Expected behavior

Ideally just return the boilerplate "the term X is not recognized as the name of a cmdlet"

## Actual behavior

Exception thrown

**Comment by hcsong213** [comment] 2020-09-26 19:31
I'm getting the same problem as well with the 🎈 emoji. ( Also with the special characters needed to render oh-my-posh components. )

**Comment by daxian-dbw** [comment] 2020-10-05 18:59
Close as a duplicate of #949

**Closed as completed by daxian-dbw** 2020-10-05 18:59 UTC
Labels: Resolution-Duplicate
