### ISSUE TITLE
Maximize PowerShell screen. Then press Windows + Right, and Enter, an error occurs.

### ISSUE THREAD

**Issue by nakamurk** [PowerShell/PSReadLine#3625] opened 2023-03-19 07:25 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
N/A
```

### Screenshot

![image](https://user-images.githubusercontent.com/10633360/226158772-43b45729-927b-4ae9-a012-4dcd5d9261ee.png)
after PSReadLine version up
![image](https://user-images.githubusercontent.com/10633360/226159400-c59195d5-e095-490d-b1e3-9c061916fa75.png)
after press enter
![image](https://user-images.githubusercontent.com/10633360/226159430-f6e8fd6a-809c-41f4-ae08-bd7907677181.png)
return full screen
![image](https://user-images.githubusercontent.com/10633360/226159457-0c20330a-89bb-4e1f-a931-7e279d7d54b6.png)

### Environment data

```console
PS Version: 5.1.19041.2673
PS HostName: ConsoleHost
PSReadLine Version: 2.2.6
PSReadLine EditMode: Windows
OS: 10.0.19041.2604 (WinBuild.160101.0800)
BufferWidth: 190
BufferHeight: 3000
```

### Steps to reproduce

- Maximize PowerShell screen.
- Then press Windows + Right,
- and Enter, an error occurs.

see also
- https://github.com/PowerShell/PSReadLine/issues/2890

- https://github.com/PowerShell/PSReadLine/issues/3624

### Expected behavior

accept any key and work well.

### Actual behavior

acceot any key but screen becomes transparent.

**Comment by StevenBucher98** [comment] 2023-03-20 16:49
Hmm I am unable to reproduce this error, @nakamurk what keys/operations are you doing to maximize your Windows PowerShell screen?

**Comment by daxian-dbw** [comment] 2023-03-20 19:17
@nakamurk I think you already saw the comment https://github.com/PowerShell/PSReadLine/issues/2890#issuecomment-926138162 from the issue you referenced above. The root cause of this issue is the console host -- after maximize and `win+RightArrow`, cursor and prompt disappear (the terminal property in .NET is messed up). You can observe the same issue with `CMD.exe` running in console host, but `CMD.exe`. This doesn't happen with Windows Terminal, so please switch to Windows Terminal and give it a try.

BTW, this issue in console host seems to be fixed in Windows 11. I can reproduce the issue in Windows 10, but not in Windows 11.
Duplicate of https://github.com/PowerShell/PSReadLine/issues/2037

**Closed as completed** 2023-03-21 00:01 UTC
Labels: Resolution-Duplicate
