### ISSUE TITLE
PSReadLine is Crashing in all Linux Distro when using either Page-Up/Page-Down key

### ISSUE THREAD

**Issue by MaximoTrinidad** [PowerShell/PSReadLine#780] opened 2018-10-19 04:05 UTC
Environment data
----------------

```powershell
& {
    "PS version: $($PSVersionTable.PSVersion)"
    $v = (Get-Module PSReadline).Version
    $m = Get-Content "$(Split-Path -Parent (Get-Module PSReadLine).Path)\PSReadLine.psd1" | Select-String "Prerelease = '(.*)'"
    if ($m) {
        $v = "$v-" + $m.Matches[0].Groups[1].Value
    }
    "PSReadline version: $v"
    if ($IsLinux -or $IsMacOS) {
        "os: $(uname -a)"
    } else {
        "os: $((dir $env:SystemRoot\System32\cmd.exe).VersionInfo.FileVersion)"
    }
    "PS file version: $((dir $pshome\p*[hl].exe).VersionInfo.FileVersion)"
}
```
In CentOS:
```
PS version: 6.1.0
PSReadline version: 2.0.0-beta2
os: Linux mercury 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
PS file version: 
PS /home/maxt> 

```
In Ubuntu 18.04:
```
PS version: 6.2.0-preview.1
PSReadline version: 2.0.0-beta3
os: Linux mars 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
PS file version: 
PS /home/maxt> 

```
In WSL - Ubuntu 18.04
```
PS version: 6.1.0
PSReadline version: 2.0.0-beta3
os: Linux sapien01 4.4.0-18252-Microsoft #1000-Microsoft Fri Sep 28 14:10:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
PS file version:
PS /home/maxt>
```
In Cloud Shell:
```
PS version: 6.1.0
PSReadline version: 2.0.0-beta3
os: Linux cc-3720380d-86c5976465-lwpdn 4.15.0-1023-azure #24~16.04.1-Ubuntu SMP Wed Aug 29 12:54:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
PS file version:
```
Steps to reproduce or exception report
--------------------------------------
1. Execute Get-ChildItem until you get multiple pages.
2. Either press PgDn or PgUp key.

You'll get the error:
```
PS /home/maxt> 
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 Space Space Space Space Space " o s : Space $ ( u n a m e Space - a ) " Enter
 Space Space Space Space } Space e l s e Space { Enter
 Space Space Space Space Space Space Space Space " o s : Space $ ( ( d i r Space $ e n v : S y s t e m R o o t \ S y s t e m 3 2 \ c m d . e x e ) . V e r s i o n I n f o . F i l e V e r s i o n ) " Enter
 Space Space Space Space } Enter
 Space Space Space Space " P S Space f i l e Space v e r s i o n : Space $ ( ( d i r Space $ p s h o m e \ p * [ h l ] . e x e ) . V e r s i o n I n f o . F i l e V e r s i o n ) " Enter
 } Enter
 PageDown

Exception:
System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.ConsolePal.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ScrollDisplayDown(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS /home/maxt>  
```
(See image)
![issuepsreadline_linux_2018-10-19_0-00-14](https://user-images.githubusercontent.com/19892435/47197207-a97a7300-d332-11e8-8a30-21f27812647a.jpg)
![issuepsreadline_cloudshell_2018-10-19_0-00-14](https://user-images.githubusercontent.com/19892435/47197213-aed7bd80-d332-11e8-8067-20c44b4970ce.jpg)

cc: @SteveL-MSFT

**Comment by lzybkr** [comment] 2018-10-19 04:42
Closing as a duplicate of #700.

**Closed as completed by lzybkr** 2018-10-19 04:42 UTC
