### ISSUE TITLE
Working with python 3.7.7x64

### ISSUE THREAD

**Issue by Falwaeth** [PowerShell/PSReadLine#1416] opened 2020-03-21 08:05 UTC
The error message that I was asked to report lies below. 
```PS C:\Users\falwaeth\Desktop\workspace>                                    &
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 x e Space c : / U s e r s / f a l w a e t h / D e s k t o p / w o r k s p a c e / S p l a s h . p y Enter
 Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space & Space C : / U s e r s / f a l w a e t h / A p p D a t a / L o c a l / P r o g r a m s / P y t h o

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was 36.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\Users\falwaeth\Desktop\workspace>                                    & C:/Users/falwaeth/AppData/Local/Programs/Python/Python37/python.exe c:/Users/falwaeth/Desktop/workspace/Splash.py
  File "c:/Users/falwaeth/Desktop/workspace/Splash.py", line 7
    tk.Tk.__init__(self):
                        ^
SyntaxError: invalid syntax```

**Comment by Falwaeth** [comment] 2020-03-21 08:09
I was trying to run this code: to override the root functionality of tkinter in python, Is it the fact that alpha's transparency is no longer enabled?

```from tkinter import Frame

import tkinter as tk

class Splash_Root(tk.Tk):
    def __init__(self):
        tk.Tk.__init__(self):
            self.attributes('-alpha', 0.5)

class Splash_Frame(tk.Frame):
    def __init__ (self, master):
        tk.Frame.__init__(self, master)
        self.geometry('300x300+100+100')
        self.tkraise(Splash_Root)

def main():
    root = Splash_Root()
    root.lower()
    frame = Splash_Frame(root)
    frame.mainloop()
    #print(type(Splash_Root))
    #print(help(tk.Tk))
    #print(help(type))

if __name__=='__main__':
    main()``

**Comment by daxian-dbw** [comment] 2020-03-24 17:02
From the bug report template:
```
The maintainer may close your issue without further explanation or engagement if:
- You delete this entire template and go your own path;
```
So, please follow the bug report template to provide **environment data** the next time.

As for this issue, it's a duplicate of #1306 and was fixed in the latest version. Please check out #1306 for more information.

**Closed as completed by daxian-dbw** 2020-03-24 17:02 UTC
Labels: Resolution-Duplicate
