### ISSUE TITLE
System.DivideByZeroException: Attempted to divide by zero. on startup

### ISSUE THREAD

**Issue by andyparkerson** [PowerShell/PSReadLine#705] opened 2018-06-06 20:58 UTC
Environment data
----------------
```
Last 0 Keys:


Exception:
System.DivideByZeroException: Attempted to divide by zero.
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

Steps to reproduce or exception report
--------------------------------------

**Comment by lzybkr** [comment] 2018-06-06 21:33
This looks like a dupe of #670 - but it would help if some details were provided.

**Comment by andyparkerson** [comment] 2018-06-06 21:47
I am running Docker for Windows, in a CentOS container. I installed Powershell via the steps on the [Microsoft Page](https://docs.microsoft.com/en-us/powershell/scripting/setup/installing-powershell-core-on-linux?view=powershell-6).

As soon as I run `pwsh`, I get the error. I can run commands such as `Get-ChildItem`, and see the expected output, but at each line, I get the same DivideByZeroException error.

When I follow the steps in #670 to reproduce the error (on a powershell container) I do not get this error. I even stopped, removed, and restarted the powershell container several times and never got the DivideByZero exception.

**Comment by ltamaster** [comment] 2018-06-20 15:28
I got the same error, I tested on MacOS and Ubuntu 18. Both produce the same error.

**Comment by souvikdc9** [comment] 2018-07-09 17:59
In Docker compose environment, the problem occurs only when using the `exec` subcommand:
```
docker exec -it cli pwsh
# OR
docker exec -it cli bash
pwsh
```

But when using `attach` subcommand, the error does not seems to occur.
```
docker attach cli
pwsh
```

Regards,
Souvik

**Comment by daxian-dbw** [comment] 2020-03-20 00:55
Close as a duplicate of #670

**Closed as completed by daxian-dbw** 2020-03-20 00:55 UTC
Labels: Resolution-Duplicate
