### ISSUE TITLE
Exception after hitting up arrow in second window

### ISSUE THREAD

**Issue by nmd3** [PowerShell/PSReadLine#1418] opened 2020-03-23 21:42 UTC
Steps that occurred to cause exception quoted below:

1. Opened powershell window from context menu in Windows Explorer in a networked drive folder over VPN

1. Initiated search:
`Get-ChildItem -recurse | Select-String -pattern "[redacted]" | group path | select name | Out-File "C:\Users\[redacted]\Desktop\[redacted].txt" `

1. Opened second powershell window in same manner as above in the same networked directory and pressed up arrow to alter search parameters to conduct a similar search. Hitting up arrow showed the error, but I was able to reuse the prior commands.

Errors below as copied and pasted from powershell. Possibly similar to #844. May have also snapped windows if that is relevant.

```
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 2 Keys:
 ` UpArrow

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.HistoryRecall(Int32 direction)
   at Microsoft.PowerShell.PSConsoleReadLine.PreviousHistory(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

**Comment by daxian-dbw** [comment] 2020-03-24 16:58
From the bug report template:
```
The maintainer may close your issue without further explanation or engagement if:
- You delete this entire template and go your own path;
```
So, please follow the bug report template to provide **environment data** the next time.

As for this issue, it's a duplicate of #1306 and was fixed in the latest version. Please check out #1306 for more information.

**Closed as completed by daxian-dbw** 2020-03-24 16:58 UTC
Labels: Resolution-Duplicate
