### ISSUE TITLE
Error starting PowerShell

### ISSUE THREAD

**Issue by ryantrem** [PowerShell/PSReadLine#2380] opened 2021-04-21 19:00 UTC
I had two terminal tabs open and I ran `pwsh` from each of them (one immediately after the other). They were both loading my custom profile at the same time, including my custom prompt. Not sure if these details are relevant. One of the terminals though showed the error below though. I've been using PowerShell on Mac daily for the last 16 months and this is the first time I've seen this. Logging an issue as requested.

### Environment
PSReadLine: 2.0.0
PowerShell: 7.0.0
OS: Darwin 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64
Last 0 Keys
```

```

### Exception
```
System.IO.IOException: The system cannot open the device or file specified. : 'PSReadLineHistoryFile_1578830712'
   at System.Threading.Mutex.CreateMutexCore(Boolean initiallyOwned, String name, Boolean& createdNew)
   at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name)
   at Microsoft.PowerShell.PSConsoleReadLine.DelayedOneTimeInitialize()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

**Comment by daxian-dbw** [comment] 2021-04-29 18:12
@ryantrem Thanks for reporting the issue. This is a duplicate of #1464. It's likely a permission issue to `/private/tmp`. Please take a look at https://github.com/PowerShell/PSReadLine/issues/1464#issuecomment-631941511 to see if that fix your problem too.

**Closed as completed by daxian-dbw** 2021-04-29 18:12 UTC
Labels: Resolution-Duplicate
