### ISSUE TITLE
System.IO.IOException: The parameter is incorrect.

### ISSUE THREAD

**Issue by brnn8r** [PowerShell/PSReadLine#408] opened 2016-07-18 02:23 UTC
I received the following exception:

NB: vdiff is an internal alias I use.

Last 200 Keys:
 Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace h g Spacebar r e v Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace h g Spacebar r e v i e w Spacebar P D M - 3 2 5 Tab Enter
 v s Enter
 h g Spacebar s t Enter
 h g Spacebar c o m Spacebar - m m Spacebar Backspace Backspace Spacebar " R e f a c t o r e d Spacebar c o d e Spacebar b e c a u s e Spacebar s h i t Spacebar i s Spacebar Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace R e f a c t o r e d Spacebar a g a i n . . . . " Enter
 UpArrow UpArrow UpArrow DownArrow DownArrow DownArrow DownArrow h g Spacebar r e v i e w Spacebar P D M - 3 2 5 Tab Enter
 h g Spacebar s t Enter
 h g Spacebar v d i f f Spacebar . PageDown

Exception:
System.IO.IOException: The parameter is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ScrollDisplayDown(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by lzybkr** [comment] 2017-01-12 20:22
Most likely a dupe of #292, reopen with additional information if you disagree.

**Closed as completed by lzybkr** 2017-01-12 20:22 UTC
Labels: Resolution-Duplicate
