### ISSUE TITLE
$Host.UI.RawUI.ReadKey Gets a extra enter key for no reason

### ISSUE THREAD

**Issue by avdaredevil** [PowerShell/PSReadLine#291] opened 2015-10-10 17:55 UTC
A lot of my powershell apps rely on 

``` powershell
$Host.UI.RawUI.ReadKey("IncludeKeyUp,NoEcho");
```

to get input, since I do simultaneous thread/non-thread activities, while the user takes time writing his/her input.

Problem is that with PSReadLine the first Prompt after a script is executed already receives an "enter" thus it treats it as if the user wanted to skip the input. This however does not affect

``` powershell
[Console]::ReadKey()
```

Please advise.

**Comment by lzybkr** [comment] 2015-10-13 14:20
Try using IncludeKeyDown instead of IncludeKeyUp.

PSReadline calls Console.ReadKey, which ignores KeyUp events, and returns when it sees a KeyDown event.  So after you press Enter (KeyDown), Console.ReadKey (and hence PSReadline) does not consume the KeyUp event.

**Comment by avdaredevil** [comment] 2015-10-13 14:38
The problem with that approach is that if the user holds the key for too long, there are redundant keys typed, when I would like only one per key press. The fallback I currently use is adding an extra `$Host.UI.RawUI.ReadKey("IncludeKeyUp,NoEcho");` when I detect PSReadLine. This way the first "ghost-enter" gets consumed, and the apps behave normally.

**Comment by lzybkr** [comment] 2017-11-08 01:59
It seems reasonable for PSReadLine to consume the final KeyUp before returning to the caller.

**Comment by daxian-dbw** [comment] 2019-12-12 19:48
Close as a duplicate of #959

**Closed as completed by daxian-dbw** 2019-12-12 19:48 UTC
Labels: Issue-Bug
