### ISSUE TITLE
Attempting to assign a query to a variable for use in Invoke-SqlCmd

### ISSUE THREAD

**Issue by ghost** [PowerShell/PSReadLine#1399] opened 2020-03-12 14:33 UTC
#   Check Job Status of Sql Servers in Metro DC
Clear-Host

$pQTS01ProdSql01 = "QTS01ProdSql01,1433"
$pQTSSqlRpt = "QTSSqlRpt,1433"
$pQTSDW01 = "QTSDW01,28762"
$pQTSSSRS01 = "QTSSSRS01,1433"
$pQTSSqlReport = "QTSSqlReport,40080"
$pQTSDistributor = "10.2.0.133,1433"
$pAtlSqlTransfer = "10.2.25.185,40185"

$runDate = '20200310';

$myQuery = "
Select  j.name
    ,   h.server
    ,   run_date
    ,   run_duration
    ,   message
    ,   retries_attempted
    ,   Count (*) runtimeAttempts
From    msdb.dbo.sysjobHistory h
    Inner Join  msdb.dbo.sysjobs j ON j.job_id = h.job_id
Where   run_date   = $runDate
    AND step_id    = 0
    AND run_status = 0
Group By    j.name
        ,   h.server
        ,   run_date
        ,   run_duration
        ,   message
        ,   retries_attempted
Order By    j.name;
"

Clear-Host
Invoke-Sqlcmd -ServerInstance $pQTS01ProdSql01 `
              -Query $myQuery | Format-Table -AutoSize

Error msgs
[VS Code Issue - 20200311.txt](https://github.com/PowerShell/PSReadLine/files/4324704/VS.Code.Issue.-.20200311.txt)

**Comment by daxian-dbw** [comment] 2020-03-19 00:03
From the bug report template:
```
The maintainer may close your issue without further explanation or engagement if:
- You delete this entire template and go your own path;
```
So, please follow the bug report template to provide **environment data** and **repro steps** the next time.

As for the issue, it's  a duplicate of the pinned issue #1306, please take a look at that one for details.

**Closed as completed by daxian-dbw** 2020-03-19 00:03 UTC
Labels: Resolution-Duplicate
