### ISSUE TITLE
System.ArgumentOutOfRangeException hitting escape

### ISSUE THREAD

**Issue by ScottMunroMS** [PowerShell/PSReadLine#1565] opened 2020-05-30 04:03 UTC
## Environment

```none
[run the script below and paste the output here]
PS version: 7.0.1
PSReadline version: 2.1.0-beta1
os: 10.0.18362.1 (WinBuild.160101.0800)
PS file version: 7.0.1.0
HostName: ConsoleHost (Windows Terminal)
BufferWidth: 305
BufferHeight: 86
```

### Environment
PSReadLine: 2.1.0-beta1
PowerShell: 7.0.1
OS: Microsoft Windows 10.0.18363
Last 200 Keys
```
 u n e LeftArrow LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow LeftArrow Backspace ~ w o r Tab Backspace Backspace Backspace \ w o r Tab Spacebar LeftArrow Tab RightArrow Backspace x b x . Backspace Backspace o x . b u m b l e l i o n Ctrl+RightArrow Ctrl+RightArrow Ctrl+RightArrow Ctrl+RightArrow Ctrl+RightArrow LeftArrow Backspace Spacebar LeftArrow ~ \ w o Tab x b o Tab RightArrow Backspace Ctrl+RightArrow Ctrl+RightArrow Ctrl+RightArrow Ctrl+RightArrow Ctrl+RightArrow Ctrl+Backspace Enter
 UpArrow Spacebar p r u n e Enter
 g s t Enter
 d i r Enter
 c d Spacebar x Tab 6 Tab Enter
 d i r Enter
 c d Spacebar . . Enter
 Escape g s t Enter
 c d Spacebar . . Enter
 d i r Enter
 c d Spacebar . . Enter
 g s t Enter
 UpArrow Spacebar ? Backspace Escape g s Enter
 g s t Enter
 UpArrow Spacebar > Spacebar ~ \ w o Tab d e l . t x t Backspace Backspace Backspace Backspace e t e d . t x t Enter
 v i m Spacebar ~ \ w Tab d e Tab Enter
 UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow DownArrow UpArrow DownArrow UpArrow DownArrow Escape
```

**Comment by daxian-dbw** [comment] 2020-06-04 18:13
Thanks for reporting the issue. It's a duplicate of #1495, which has been fixed recently in the master branch. The fix will be included in the next beta release.

**Closed as completed by daxian-dbw** 2020-06-04 18:13 UTC
Labels: Resolution-Duplicate
