### ISSUE TITLE
Unable to type 🙂 through Windows Terminal

### ISSUE THREAD

**Issue by paramsiddharth** [PowerShell/PSReadLine#2383] opened 2021-04-22 12:01 UTC
## Observations
- I believed this might be solely a Windows Terminal issue and not PowerShell's, but it worked for `cmd.exe` (with the following catch).
  ![image](https://user-images.githubusercontent.com/30315706/115710933-8d873a80-a390-11eb-85e6-c069636e49f7.png)
- The character got inserted properly when I ran `pwsh.exe` outside Windows Terminal.

## Environment

```none
PS version: 7.1.3
PSReadline version: 2.1.0
os: 10.0.19041.1 (WinBuild.160101.0800)
PS file version: 7.1.3.0
HostName: ConsoleHost (Windows Terminal)
BufferWidth: 120
BufferHeight: 30
```

## Exception report

❯ git commit -m '� Done.'

Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.md
Thank you!

### Environment
PSReadLine: 2.1.0
PowerShell: 7.1.3
OS: Microsoft Windows 10.0.19042
BufferWidth: 120
BufferHeight: 30

Last 92 Keys
```
 g i t Spacebar s t a t u s Enter
 g i t Spacebar s t a t u s Enter
 g i t Spacebar a d d Spacebar . Enter
 g i t Spacebar i n i t Enter
 g i t Spacebar a d d Spacebar . Enter
 g i t Spacebar s t a t u s Enter
 g i t Spacebar c o m m i t Spacebar - m Spacebar ' ' LeftArrow W e l l Ctrl+Backspace � Spacebar D o n e . Enter

```

### Exception
```
System.Text.EncoderFallbackException: Unable to translate Unicode character \\uD83D at index 15 to specified code page.
   at System.Text.EncoderExceptionFallbackBuffer.Fallback(Char charUnknown, Int32 index)
   at System.Text.EncoderFallbackBuffer.InternalFallback(ReadOnlySpan`1 chars, Int32& charsConsumed)
   at System.Text.Encoding.GetBytesWithFallback(ReadOnlySpan`1 chars, Int32 originalCharsLength, Span`1 bytes, Int32 originalBytesLength, EncoderNLS encoder)
   at System.Text.Encoding.GetBytesWithFallback(Char* pOriginalChars, Int32 originalCharCount, Byte* pOriginalBytes, Int32 originalByteCount, Int32 charsConsumedSoFar, Int32 bytesWrittenSoFar, EncoderNLS encoder)
   at System.Text.Encoding.GetBytes(Char* pChars, Int32 charCount, Byte* pBytes, Int32 byteCount, EncoderNLS encoder)
   at System.Text.EncoderNLS.GetBytes(Char[] chars, Int32 charIndex, Int32 charCount, Byte[] bytes, Int32 byteIndex, Boolean flush)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at Microsoft.PowerShell.PSConsoleReadLine.<>c__DisplayClass83_0.<WriteHistoryRange>b__0()
   at Microsoft.PowerShell.PSConsoleReadLine.WithHistoryFileMutexDo(Int32 timeout, Action action)
   at Microsoft.PowerShell.PSConsoleReadLine.WriteHistoryRange(Int32 start, Int32 end, Boolean overwritten)
   at Microsoft.PowerShell.PSConsoleReadLine.IncrementalHistoryWrite()
   at Microsoft.PowerShell.PSConsoleReadLine.MaybeAddToHistory(String result, List`1 edits, Int32 undoEditIndex, Boolean fromDifferentSession, Boolean fromInitialRead)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

## Steps to reproduce

Use the `Win+.` shortcut to insert the 🙂 emoji into PowerShell throught **Windows Terminal**.

## Expected behavior

Type 🙂 correctly, as it does when I directly execute `pwsh.exe` not from within Windows Terminal.

## Actual behavior

The following character appears: `�`
And the error message pops up, asking me to raise an issue for the error.

**Comment by daxian-dbw** [comment] 2021-04-29 21:54
Close as a duplicate of #949

**Closed as completed by daxian-dbw** 2021-04-29 21:54 UTC
