### ISSUE TITLE
Input character buffer exceeded

### ISSUE THREAD

**Issue by Sidneys1** [PowerShell/PSReadLine#501] opened 2017-02-03 13:27 UTC
I'm sure this isn't something that needs fixing, but I thought I'd report it anyways. Looks like my KVM glitched out and sent PowerShell 241 keypresses at once, which PSReadLine did not like very much.

```
Last 135 Keys:
 c d Spacebar m Tab m Tab Enter
 s u Backspace Backspace Backspace Backspace g i t Spacebar f e t c h Enter
 g i t Spacebar c o n i Spacebar 2 3 6 8 Enter
 w e Tab Enter
 UpArrow Enter
 UpArrow Home p o w e r s h e l l Spacebar - f i l e Spacebar Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete v i m Spacebar w e Tab Enter
 w e Tab Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 241 UpArrow

Exception:
System.ArgumentException: Destination array was not long enough. Check destIndex and length, and the array's lower bounds.
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Array destinationArray, Int32 length)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender()
   at Microsoft.PowerShell.PSConsoleReadLine.HistoryRecall(Int32 direction)
   at Microsoft.PowerShell.PSConsoleReadLine.PreviousHistory(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

PowerShell did not crash, and everything kept chugging along as expected.

**Comment by Sidneys1** [comment] 2017-02-03 13:29
Also probably a duplicate of #481, #461, and #382

**Comment by bbkane** [comment] 2017-04-02 03:01
I got something similar, I think:

```
λ                                                                                                                                          
Oops, something went wrong.  Please report this bug with the details below.                                                                
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new                                                                          
-----------------------------------------------------------------------                                                                    
Last 200 Keys:                                                                                                                             
 r r a n c h Backspace Backspace Backspace Backspace Backspace a n c h Enter                                                               
 g o t Backspace Backspace i t Spacebar p u l l Enter                                                                                      
 g i t Spacebar b a n Backspace Backspace r a n c h Enter                                                                                  
 g i t Spacebar e Backspace c h e c k o u t Spacebar o r i g i n / e m b e d _ c s s _ j s Enter                                           
 g Backspace g i Spacebar Backspace t Spacebar c e c h Backspace Backspace Backspace h c Backspace e c k o u t Spacebar m a s t e r Enter  
 Ctrl+p Backspace Backspace Backspace Backspace Backspace Backspace e m p b Backspace Backspace b e d _ c s s _ j s s Backspace Enter      
 g i t Spacebar p u l l Enter                                                                                                              
 l s Enter                                                                                                                                 
 v i m Spacebar R E Tab Enter                                                                                                              
 l s Enter                                                                                                                                 
 c d Backspace o d e Spacebar . Enter                                                                                                      
 l s Enter                                                                                                                                 
 p y t o h n Spacebar Backspace Backspace Backspace Backspace h o n Spacebar t m p . p Tab Enter                                           
 UpArrow Enter                                                                                                                             
 UpArrow Enter                                                                                                                             
 LeftWindows UpArrow                                                                                                                       
                                                                                                                                           
Exception:                                                                                                                                 
System.ArgumentException: Destination array was not long enough. Check destIndex and length, and the array's lower bounds.                 
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliab 
le)                                                                                                                                        
   at System.Array.Copy(Array sourceArray, Array destinationArray, Int32 length)                                                           
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender()                                                                                
   at Microsoft.PowerShell.PSConsoleReadLine.HistoryRecall(Int32 direction)                                                                
   at Microsoft.PowerShell.PSConsoleReadLine.PreviousHistory(Nullable`1 key, Object arg)                                                   
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Objec 
t arg)                                                                                                                                     
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()                                                                                   
C:\Users\Ben\Git\bank_db [embed_css_js ≡]ine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)                                
λ                                                                                                                                          
```

**Comment by lzybkr** [comment] 2017-11-03 05:29
I'm closing - it's probably a dupe of another bug, and the rendering code has been rewritten, the `Array.Copy` call is gone.

**Closed as completed by lzybkr** 2017-11-03 05:29 UTC
