### ISSUE TITLE
Not work search in command history (Ctrl+r)

### ISSUE THREAD

**Issue by Sublihim** [PowerShell/PSReadLine#1442] opened 2020-04-01 07:28 UTC
## Environment

```none
PS version: 7.0.0
PSReadline version: 2.0.0
os: 10.0.18362.718 (WinBuild.160101.0800)
PS file version: 7.0.0.0
HostName: ConsoleHost
BufferWidth: 120
BufferHeight: 9001
```

## Steps to reproduce

```powershell
Press Ctrl+r
```

## Expected behavior
```none
Start searching in command history
```
## Actual behavior

```none

<к> symbol appears (Russian letter к)
this behavior does not depend on the selected keyboard layout

also all the keyboard shortcuts with Ctrl lead to the appearance of Russian characters.

For example, pressing Ctrl + v displays the Russian character <м>. 

And this behavior does not depend on the selected keyboard layout.
```

**Comment by iSazonov** [comment] 2020-04-01 14:07
@Sublihim The issue template contains a script. Please run the script and add the script output to the issue description.

**Comment by Sublihim** [comment] 2020-04-01 18:34
@iSazonov In the _environment_ template?
I started it.
Duplicate the output below:
```
PS version: 7.0.0
PSReadline version: 2.0.0
os: 10.0.18362.718 (WinBuild.160101.0800)
PS file version: 7.0.0.0
HostName: ConsoleHost
BufferWidth: 120
BufferHeight: 9001
```

**Comment by daxian-dbw** [comment] 2020-04-01 21:05
> this behavior does not depend on the selected keyboard layout

@Sublihim What do you mean by this? Aren't you using the Russian keyboard layout? How can I reproduce this?

**Comment by iSazonov** [comment] 2020-04-02 04:28
I can not repo on 10.0.17763.1039 with Russian keyboard layout. We need more info.

**Comment by Sublihim** [comment] 2020-04-02 06:08
The error is reproduced regardless of the layout (Russian or English)
In fact, I realized it looks like this error: https://github.com/PowerShell/PSReadLine/issues/1393


If I run PowerShell at The moment when the system is switched to the English layout, then everything works well.

**Comment by iSazonov** [comment] 2020-04-02 07:01
@Sublihim Please share more info. Is your system installed from Russian or English distributive? If English do you install language pack? What is default for non-unicode programs? What is other region and language options? What is default keyboard layout? Do you use Windows Terminal? 
Can you share screenshots? and maybe an animation with repo?

**Comment by Sublihim** [comment] 2020-04-02 08:09
1. This is reproduced on both the Russian-language distribution and the English-Language distribution with Russian-Language pack installed.
2. For non-unicode programs, the default language is Russian on both systems
3. no other languages installed, no other regional options
4. Russian is set as the default  keyboard layout
5. the problem is relevant both in Windows Terminal and just in the PowerShell window.

**Comment by iSazonov** [comment] 2020-04-02 09:32
> This is reproduced on both the Russian-language distribution and the English-Language distribution with Russian-Language pack installed.

Thanks! Looks like this is a key here.

**Comment by daxian-dbw** [comment] 2020-04-02 16:17
Thanks @Sublihim for the additional information!
Indeed, this looks resulted by the same root cause of #1393. I will resolve this issue as a duplicate of the other one.

**Closed as completed by daxian-dbw** 2020-04-02 16:17 UTC
Labels: Resolution-Duplicate, Issue-KeyboardLayout
