### ISSUE TITLE
Tried to abort partially entered command with a Control-C

### ISSUE THREAD

**Issue by buchs** [PowerShell/PSReadLine#3830] opened 2023-10-11 15:10 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.yaml
Thank you!

### Environment
PSReadLine: 2.2.6
PowerShell: 7.3.8
OS: Microsoft Windows 10.0.19045
BufferWidth: 120
BufferHeight: 52

Last 200 Keys:

 UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow Enter
 p u l u m i Spacebar i m p o r t Spacebar a w s : s e c r e t s m a n a g e r / s e c r e t : S e c r e t Spacebar s e c r e t Spacebar a r n : a w s : s e c r e t s m a n a g e r : u s - e a s t - 1 : <REDACTED> Enter
 p u l u l u Backspace Backspace m i Spacebar s t a c k Spacebar e RightArrow Enter
 UpArrow UpArrow UpArrow Enter
 UpArrow UpArrow UpArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Ctrl+c
```

### Screenshot

```
### Exception

System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Actual value was 52.
   at System.ConsolePal.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.CancelLine(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.CopyOrCancelLine(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken, Nullable`1 lastRunStatus)
```

### Environment data

```console
PS Version: 7.3.8
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.2.6
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 120
BufferHeight: 52
```

### Steps to reproduce

Paste a command, start deleting text at the end and then press Control-C.

### Expected behavior

Cancels command

### Actual behavior

Exception thrown

**Comment by daxian-dbw** [comment] 2023-10-11 16:49
> Paste a command, start deleting text at the end and then press Control-C.

@buchs I cannot reproduce this issue locally. I pasted the same command shown in your "Last 200 Keys":
```
pulumi import aws:secretsmanager/secret:Secret secret arn:aws:secretsmanager:us-east-1:
```
And press `Backspace` 27 times (same as shown in the "Last 200 Keys"), then press `Ctrl+c`, and it works fine.
I did try pasting other random command line strings and could not reproduce the issue too.

Can you please provide repro steps that can consistently reproduce the issue? Also, can you also upgrade to the latest 2.3.4 version of PSReadLine and see if you run into the same issue with it?

**Comment by abatishchev** [comment] 2023-10-11 18:47
+1

```
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 44 Keys:
 c d Space s t a Tab Tab Enter
 Ctrl+r n e w - End Backspace Ctrl+r n e w - End Backspace c l s Enter
 UpArrow UpArrow Escape Ctrl+r n e w Enter
 UpArrow Backspace c l s Enter
 UpArrow UpArrow Backspace

Exception:
System.ArgumentOutOfRangeException: StartIndex cannot be less than zero.
Parameter name: startIndex
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.BackwardDeleteChar(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

Environment:

```
PS Version: 7.3.8
PS HostName: ConsoleHost
PSReadLine Version: 2.2.6
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 120
BufferHeight: 9001
```

Also:

```
Microsoft Terminal Version: 1.17.11461.0
```

and

```
Caption                 : Microsoft Windows 10 Enterprise
Version                 : 10.0.19045
```

**Comment by daxian-dbw** [comment] 2023-10-11 19:28
> Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new

@abatishchev You are on a very old version of PSReadLine. This URL was reported only on versions prior to 2.0.0-beta2. The issue you ran into was very likely resolved in recent releases. Please upgrade to the latest 2.3.4 version and try it again.

**Comment by buchs** [comment] 2023-10-12 11:32
@daxian-dbw Sorry, but I have not seen this problem reproduce, so I cannot provide consistent steps. I was just reporting it, as the software requested I do.

**Comment by daxian-dbw** [comment] 2023-10-12 16:39
@buchs No worries at all and thanks for reporting it!
We consider all reliability issue like this one to be of high importance, so we really want to reproduce the failure and fix it. It would be very helpful if you can provide some more information about the command lines you were editing when this happened.

The `Last 200 Keys` contains this line and by looking those keys, the exception happened when you were editing this line (pressing Backspace and then `Ctrl+c`)
> ``` 
> p u l u m i Spacebar i m p o r t Spacebar a w s : s e c r e t s m a n a g e r / s e c r e t : S e c r e t Spacebar s e c r e t Spacebar a r n : a w s : s e c r e t s m a n a g e r : u s - e a s t - 1 : <REDACTED> Enter
> ```

A few questions:
1. Did you resize the terminal window before the exception happened?
   - The environment section shows "BufferWidth: 120; BufferHeight: 52". I assume that you didn't change the terminal window size, but please let me know if you did.
1. Can you please share the full line the full line of the above typing?
   - By mimicking the keys, the command line seems to be `pulumi import aws:secretsmanager/secret:Secret:Secrete secret arn:aws:secretsmanager:us-east-1:`, but I don't know what `<REDACTED>` maps to, so it would be helpful if you can dig your history and provide the actual string of this command line.

With the additional information, I will try again to reproduce the issue locally, and hopefully it will work.

**Closed as completed** 2023-10-23 17:14 UTC
Labels: Needs-Author Feedback
