### ISSUE TITLE
Powershell is producing errors when I press up to use its history. I don't know why.

### ISSUE THREAD

**Issue by ArcaneOverride** [PowerShell/PSReadLine#3921] opened 2024-01-15 07:03 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.yaml
Thank you!

### Environment
PSReadLine: 2.3.4
PowerShell: 7.4.1
OS: Microsoft Windows 10.0.22635
BufferWidth: 270
BufferHeight: 72

Last 200 Keys:

 Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow Ctrl+Backspace k Backspace l i s t Enter
 Ctrl+UpArrow UpArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow Ctrl+Backspace t u p l e Enter
 UpArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Delete Enter
 UpArrow UpArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+Delete a t t Backspace Backspace r r a y Enter
 UpArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow Ctrl+Backspace l i s t Enter
 u s i RightArrow Ctrl+Backspace l i s t Enter
 UpArrow Ctrl+Backspace t u p l e Enter
 Ctrl+Backspace UpArrow Ctrl+Backspace - Tab Tab Backspace Ctrl+Backspace Tab Tab Tab Tab Spacebar t u p l e Enter
 Ctrl+c UpArrow ; Enter
 UpArrow LeftArrow Shift+Ctrl+LeftArrow l i s t Enter
 UpArrow LeftArrow ] Ctrl+LeftArrow [ Enter
 UpArrow UpArrow UpArrow LeftArrow [ Ctrl+LeftArrow [ Ctrl+RightArrow LeftArrow Backspace ] Enter
 UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow

### Exception

System.Management.Automation.PSArgumentException: Cannot process argument because the value of argument "name" is not valid. Change the value of the "name" argument and run the operation again.
   at System.Management.Automation.Language.TypeName..ctor(IScriptExtent extent, String name)
   at System.Management.Automation.Language.TypeResolver.ResolveTypeNameWithContext(TypeName typeName, Exception& exception, Assembly[] assemblies, TypeResolutionState typeResolutionState)
   at System.Management.Automation.Language.SymbolResolver.VisitTypeName(TypeName typeName, Int32 genericArgumentCount, Boolean isAttribute)
   at System.Management.Automation.Language.SymbolResolver.VisitGenericTypeName(GenericTypeName genericTypeName)
   at System.Management.Automation.Language.SymbolResolver.VisitTypeConstraint(TypeConstraintAst typeConstraintAst)
   at System.Management.Automation.Language.ConvertExpressionAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.NamedBlockAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.ScriptBlockAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.Parser.ParseTask(String fileName, String input, List`1 tokenList, Boolean recursed, ParseMode parseMode)
   at System.Management.Automation.Language.Parser.Parse(String fileName, String input, List`1 tokenList, ParseError[]& errors, ParseMode parseMode)
   at System.Management.Automation.Language.Parser.ParseInput(String input, String fileName, Token[]& tokens, ParseError[]& errors)
```

### Screenshot

![image](https://github.com/PowerShell/PSReadLine/assets/11003434/2da30c1d-6c51-4381-abc4-747903598620)

### Environment data

```console
PS C:\Users\Vanessa> & {
>>     $hostName = $Host.Name
>>     if ($hostName -eq "ConsoleHost" -and (Get-Command Get-CimInstance -ErrorAction SilentlyContinue)) {
>>         $id = $PID; $inWindowsTerminal = $false
>>         while ($true) {
>>             $p = Get-CimInstance -ClassName Win32_Process -Filter "ProcessId Like $id"
>>             if (!$p -or !$p.Name) { break }
>>             if ($p.Name -eq "WindowsTerminal.exe") { $inWindowsTerminal = $true; break }
>>             $id = $p.ParentProcessId
>>         }
>>         if ($inWindowsTerminal) { $hostName += " (Windows Terminal)" }
>>     }
>>
>>     $m = Get-Module PSReadline
>>     $v = $m.Version; $pre = $m.PrivateData.PSData.Prerelease
>>     if ($pre) { $v = "$v-$pre" }
>>     $os = if ($IsLinux -or $IsMacOS) { uname -a } else { (dir $env:SystemRoot\System32\cmd.exe).VersionInfo.FileVersion }
>>
>>     Write-Host ''
>>     Write-Host "PS Version: $($PSVersionTable.PSVersion)"
>>     Write-Host "PS HostName: $hostName"
>>     Write-Host "PSReadLine Version: $v"
>>     Write-Host "PSReadLine EditMode: $((Get-PSReadLineOption).EditMode)"
>>     Write-Host "OS: $os"
>>
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.yaml
Thank you!

### Environment
PSReadLine: 2.3.4
PowerShell: 7.4.1
OS: Microsoft Windows 10.0.22635
BufferWidth: 316
BufferHeight: 87

Last 200 Keys:

 M o d e : Spacebar $ ( ( G e t - P S R e a d L i n e O p t i o n ) . E d i t M o d e ) " Enter
 Spacebar Spacebar Spacebar Spacebar W r i t e - H o s t Spacebar " O S : Spacebar $ o s " Enter
 Spacebar Spacebar Spacebar Spacebar W r i t e - H o s t Spacebar " B u f f e r W i d t h : Spacebar $ ( [ c o n s o l e ] : : B u f f e r W i d t h ) " Enter
 Spacebar Spacebar Spacebar Spacebar W r i t e - H o s t Spacebar " B u f f e r H e i g h t : Spacebar $ ( [ c o n s o l e ] : : B u f f e r H e i g h t ) " Enter
 Spacebar Spacebar Spacebar Spacebar W r i t e - H o s t Spacebar ' ' Enter
 }

### Exception

System.Management.Automation.PSArgumentException: Cannot process argument because the value of argument "name" is not valid. Change the value of the "name" argument and run the operation again.
   at System.Management.Automation.Language.TypeName..ctor(IScriptExtent extent, String name)
   at System.Management.Automation.Language.TypeResolver.ResolveTypeNameWithContext(TypeName typeName, Exception& exception, Assembly[] assemblies, TypeResolutionState typeResolutionState)
   at System.Management.Automation.Language.SymbolResolver.VisitTypeName(TypeName typeName, Int32 genericArgumentCount, Boolean isAttribute)
   at System.Management.Automation.Language.SymbolResolver.VisitTypeExpression(TypeExpressionAst typeExpressionAst)
   at System.Management.Automation.Language.TypeExpressionAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.MemberExpressionAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.ExpandableStringExpressionAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.CommandAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.NamedBlockAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.ScriptBlockAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.Parser.ParseTask(String fileName, String input, List`1 tokenList, Boolean recursed, ParseMode parseMode)
   at System.Management.Automation.Language.Parser.Parse(String fileName, String input, List`1 tokenList, ParseError[]& errors, ParseMode parseMode)
   at System.Management.Automation.Language.Parser.ParseInput(String input, String fileName, Token[]& tokens, ParseError[]& errors)


PS C:\Users\Vanessa>
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.yaml
Thank you!

### Environment
PSReadLine: 2.3.4
PowerShell: 7.4.1
OS: Microsoft Windows 10.0.22635
BufferWidth: 316
BufferHeight: 87

Last 200 Keys:

 M o d e : Spacebar $ ( ( G e t - P S R e a d L i n e O p t i o n ) . E d i t M o d e ) " Enter
 Spacebar Spacebar Spacebar Spacebar W r i t e - H o s t Spacebar " O S : Spacebar $ o s " Enter
 Spacebar Spacebar Spacebar Spacebar W r i t e - H o s t Spacebar " B u f f e r W i d t h : Spacebar $ ( [ c o n s o l e ] : : B u f f e r W i d t h ) " Enter
 Spacebar Spacebar Spacebar Spacebar W r i t e - H o s t Spacebar " B u f f e r H e i g h t : Spacebar $ ( [ c o n s o l e ] : : B u f f e r H e i g h t ) " Enter
 Spacebar Spacebar Spacebar Spacebar W r i t e - H o s t Spacebar ' ' Enter
 }

### Exception

System.Management.Automation.PSArgumentException: Cannot process argument because the value of argument "name" is not valid. Change the value of the "name" argument and run the operation again.
   at System.Management.Automation.Language.TypeName..ctor(IScriptExtent extent, String name)
   at System.Management.Automation.Language.TypeResolver.ResolveTypeNameWithContext(TypeName typeName, Exception& exception, Assembly[] assemblies, TypeResolutionState typeResolutionState)
   at System.Management.Automation.Language.SymbolResolver.VisitTypeName(TypeName typeName, Int32 genericArgumentCount, Boolean isAttribute)
   at System.Management.Automation.Language.SymbolResolver.VisitTypeExpression(TypeExpressionAst typeExpressionAst)
   at System.Management.Automation.Language.TypeExpressionAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.MemberExpressionAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.ExpandableStringExpressionAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.CommandAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.NamedBlockAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.ScriptBlockAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.Parser.ParseTask(String fileName, String input, List`1 tokenList, Boolean recursed, ParseMode parseMode)
   at System.Management.Automation.Language.Parser.Parse(String fileName, String input, List`1 tokenList, ParseError[]& errors, ParseMode parseMode)
   at System.Management.Automation.Language.Parser.ParseInput(String input, String fileName, Token[]& tokens, ParseError[]& errors)


PS C:\Users\Vanessa>
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.yaml
Thank you!

### Environment
PSReadLine: 2.3.4
PowerShell: 7.4.1
OS: Microsoft Windows 10.0.22635
BufferWidth: 316
BufferHeight: 87

Last 200 Keys:

 M o d e : Spacebar $ ( ( G e t - P S R e a d L i n e O p t i o n ) . E d i t M o d e ) " Enter
 Spacebar Spacebar Spacebar Spacebar W r i t e - H o s t Spacebar " O S : Spacebar $ o s " Enter
 Spacebar Spacebar Spacebar Spacebar W r i t e - H o s t Spacebar " B u f f e r W i d t h : Spacebar $ ( [ c o n s o l e ] : : B u f f e r W i d t h ) " Enter
 Spacebar Spacebar Spacebar Spacebar W r i t e - H o s t Spacebar " B u f f e r H e i g h t : Spacebar $ ( [ c o n s o l e ] : : B u f f e r H e i g h t ) " Enter
 Spacebar Spacebar Spacebar Spacebar W r i t e - H o s t Spacebar ' ' Enter
 }

### Exception

System.Management.Automation.PSArgumentException: Cannot process argument because the value of argument "name" is not valid. Change the value of the "name" argument and run the operation again.
   at System.Management.Automation.Language.TypeName..ctor(IScriptExtent extent, String name)
   at System.Management.Automation.Language.TypeResolver.ResolveTypeNameWithContext(TypeName typeName, Exception& exception, Assembly[] assemblies, TypeResolutionState typeResolutionState)
   at System.Management.Automation.Language.SymbolResolver.VisitTypeName(TypeName typeName, Int32 genericArgumentCount, Boolean isAttribute)
   at System.Management.Automation.Language.SymbolResolver.VisitTypeExpression(TypeExpressionAst typeExpressionAst)
   at System.Management.Automation.Language.TypeExpressionAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.MemberExpressionAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.ExpandableStringExpressionAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.CommandAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.NamedBlockAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.ScriptBlockAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.Parser.ParseTask(String fileName, String input, List`1 tokenList, Boolean recursed, ParseMode parseMode)
   at System.Management.Automation.Language.Parser.Parse(String fileName, String input, List`1 tokenList, ParseError[]& errors, ParseMode parseMode)
   at System.Management.Automation.Language.Parser.ParseInput(String input, String fileName, Token[]& tokens, ParseError[]& errors)


PS C:\Users\Vanessa>
```

### Steps to reproduce

No idea how to get into this state but right now all I need to do is press up a few times

### Expected behavior

Pressing up shows the previous item in the history

### Actual behavior

pressing up give that error

**Comment by StevenBucher98** [comment] 2024-01-22 17:38
Thanks for the issue @ArcaneOverride does is this issue consistently reproducible for you? I am unable to reproduce it

**Comment by ArcaneOverride** [comment] 2024-01-23 20:48
> Thanks for the issue @ArcaneOverride does is this issue consistently reproducible for you? I am unable to reproduce it

I only got into that bad state once. While in that state it was happening consistently, but restarting the terminal fixed it so it didn't happen anymore.

**Comment by daxian-dbw** [comment] 2024-01-30 19:40
@ArcaneOverride This is because you ran something like "using namespace [tuple]" in that session. The value `[tuple]` contains invalid characters `[` and `]` for a namespace name, so later on, when you were trying to resolve any type names in that session, you will run into this parsing error.

This is a bug in PowerShell -- it should report error when the specified value for `using namespace` contains invalid characters.
Close this issue as a duplicate of https://github.com/PowerShell/PowerShell/issues/17113

**Closed as completed by daxian-dbw** 2024-01-30 19:40 UTC
