### ISSUE TITLE
ArgumentOutOfRangeException after windown resize

### ISSUE THREAD

**Issue by arberg** [PowerShell/PSReadLine#2044] opened 2020-12-16 13:04 UTC
### Environment
PSReadLine: 2.1.0
PowerShell: 7.1.0
OS: Microsoft Windows 10.0.19041
BufferWidth: 135
BufferHeight: 300

Last 25 Keys
```
 c d b Tab Enter
 c d Spacebar d o c Tab Enter
 g i t Spacebar f e t c h Enter
 LeftWindows PageUp
```

### Exception
```
System.ArgumentOutOfRangeException: The window position must be set such that the current window size fits within the console's buffer, and the numbers must not be negative. (Parameter 'left')
Actual value was 0.
   at System.ConsolePal.SetWindowPosition(Int32 left, Int32 top)
   at System.Console.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ScrollDisplayUp(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

## Steps to reproduce

I cannot reproduce it. But this is what I did: 
* open fresh new powershell 7 window 
* 2x cd where I wanted to go
* `git fetch`
* before or after `git fetch` i did `win-right` shortcut, moving window on the right. After move the terminal was weird, like I couldn't see content. Maybe it was just scroll issue, but I think I couldn't see content before resizing again.

**Comment by arberg** [comment] 2020-12-16 13:06
Related: https://github.com/PowerShell/PSReadLine/issues/1306

**Comment by daxian-dbw** [comment] 2021-01-05 20:35
> After move the terminal was weird, like I couldn't see content.

@arberg I guess you went from "maximized" to "window-on-the-right" using `win+right`, right? This looks like a duplicate of #2037
This is a problem of the console host. CMD.exe shows the same behavior in the console host. Windows terminal works fine though.

**Closed as completed by daxian-dbw** 2021-01-05 20:35 UTC
Labels: Resolution-External
