### ISSUE TITLE
Icons throw exceptions when running in windows terminal

### ISSUE THREAD

**Issue by asaff1** [PowerShell/PSReadLine#2370] opened 2021-04-16 10:48 UTC
## Environment

```none
[run the script below and paste the output here]
```
PS version: 5.1.19041.906
PSReadline version: 2.2.0-beta2
os: 10.0.19041.1 (WinBuild.160101.0800)
PS file version: 10.0.19041.1 (WinBuild.160101.0800)
HostName: ConsoleHost (Windows Terminal)
BufferWidth: 120
BufferHeight: 30

### Environment
PSReadLine: 2.2.0-beta2
PowerShell: 5.1.19041.906
OS: Microsoft Windows 10.0.19041
BufferWidth: 120
BufferHeight: 30

Last 13 Keys
```
 � Enter
 Enter
 Enter
 c l s Enter
 UpArrow UpArrow UpArrow DownArrow Enter

```

### Exception
```
System.Text.EncoderFallbackException: Unable to translate Unicode character \uD83D at index 0 to specified code page.
   at System.Text.EncoderExceptionFallbackBuffer.Fallback(Char charUnknown, Int32 index)
   at System.Text.EncoderFallbackBuffer.InternalFallback(Char ch, Char*& chars)
   at System.Text.UTF8Encoding.GetBytes(Char* chars, Int32 charCount, Byte* bytes, Int32 byteCount, EncoderNLS baseEncoder)
   at System.Text.EncoderNLS.GetBytes(Char[] chars, Int32 charIndex, Int32 charCount, Byte[] bytes, Int32 byteIndex, Boolean flush)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at Microsoft.PowerShell.PSConsoleReadLine.<>c__DisplayClass98_0.<WriteHistoryRange>b__0()
   at Microsoft.PowerShell.PSConsoleReadLine.WithHistoryFileMutexDo(Int32 timeout, Action action)
   at Microsoft.PowerShell.PSConsoleReadLine.MaybeAddToHistory(String result, List`1 edits, Int32 undoEditIndex, Boolean fromDifferentSession, Boolean fromInitialRead)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

## Steps to reproduce
- Press WinKey + . (dot)
- select icon and press enter

**Comment by daxian-dbw** [comment] 2021-04-29 22:05
Close as duplicate of #949

**Closed as completed by daxian-dbw** 2021-04-29 22:05 UTC
