### ISSUE TITLE
PSReadLine exception when pasting emojis into PowerShell using Windows Terminal

### ISSUE THREAD

**Issue by Neptune650** [PowerShell/PSReadLine#2414] opened 2021-05-01 01:14 UTC
## Environment

```none
PSReadLine: 2.1.0
PowerShell: 7.1.3
OS: Microsoft Windows 10.0.19042
BufferWidth: 120
BufferHeight: 30
```

## Exception report

```
 Backspace , . Tab . Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace e Tab . c Tab Enter
 v Spacebar m a k e f i Tab Enter
 m a k e Spacebar c l e a n Enter
 UpArrow Backspace Backspace Backspace Backspace Backspace r e l i n Backspace Backspace d e b i n f o Enter
 k s Enter
 l s Enter
 q e m u F8 Enter
 UpArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Enter
 UpArrow UpArrow UpArrow DownArrow UpArrow UpArrow UpArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace d e b u g Enter
 UpArrow Backspace Backspace Backspace Backspace Backspace c l e a n Spacebar d b Backspace Backspace d e b u g Enter
 q e m u F8 Enter
 UpArrow UpArrow LeftArrow RightArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace c l e a n Spacebar k Backspace Backspace Enter
 m a k e Enter
 q e m u F8 Enter
 c k Backspace k e a r Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace c l e a r Enter
 l s Enter
 � LeftArrow RightArrow Enter

```

### Exception
```
System.Text.EncoderFallbackException: Unable to translate Unicode character \\uD83D at index 0 to specified code page.
   at System.Text.EncoderExceptionFallbackBuffer.Fallback(Char charUnknown, Int32 index)
   at System.Text.EncoderFallbackBuffer.InternalFallback(ReadOnlySpan`1 chars, Int32& charsConsumed)
   at System.Text.Encoding.GetBytesWithFallback(ReadOnlySpan`1 chars, Int32 originalCharsLength, Span`1 bytes, Int32 originalBytesLength, EncoderNLS encoder)
   at System.Text.Encoding.GetBytesWithFallback(Char* pOriginalChars, Int32 originalCharCount, Byte* pOriginalBytes, Int32 originalByteCount, Int32 charsConsumedSoFar, Int32 bytesWrittenSoFar, EncoderNLS encoder)
   at System.Text.Encoding.GetBytes(Char* pChars, Int32 charCount, Byte* pBytes, Int32 byteCount, EncoderNLS encoder)
   at System.Text.EncoderNLS.GetBytes(Char[] chars, Int32 charIndex, Int32 charCount, Byte[] bytes, Int32 byteIndex, Boolean flush)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at Microsoft.PowerShell.PSConsoleReadLine.<>c__DisplayClass83_0.<WriteHistoryRange>b__0()
   at Microsoft.PowerShell.PSConsoleReadLine.WithHistoryFileMutexDo(Int32 timeout, Action action)
   at Microsoft.PowerShell.PSConsoleReadLine.WriteHistoryRange(Int32 start, Int32 end, Boolean overwritten)
   at Microsoft.PowerShell.PSConsoleReadLine.MaybeAddToHistory(String result, List`1 edits, Int32 undoEditIndex, Boolean fromDifferentSession, Boolean fromInitialRead)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

## Steps to reproduce

- Paste "🙂" into PowerShell using Windows Terminal
- Press enter like if were a command.
- Have good luck and it will happen.
- (I recently discovered that it may happen when pasting the emoji then using arrow keys and pressing enter)

## Expected behavior

- Error about unrecognized term.

## Actual behavior

- PSReadLine exception.

***This issue is different than https://github.com/PowerShell/PSReadLine/issues/2358 because this one happens when pasting emojis.***

**Comment by bdennir** [comment] 2021-05-04 22:04
This is just to repeat, the method of 'pasting' emoji in my case was directly in terminal (wt.exe hosting pwsh.exe) using keyboard into a command : notepad filename_with_emoji entered with "Win+., (windows+period)" keys then selecting an emoji (which did not appear correctly in the terminal I thought the font might be issue so when ahead & hit "enter". What followed next:
"
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.md
Thank you!

### Environment
PSReadLine: 2.1.0
PowerShell: 7.1.3
OS: Microsoft Windows 10.0.19042
BufferWidth: 121
BufferHeight: 30

Last 62 Keys
```
 c d Spacebar D o w n Tab M i c r o Tab W i n Tab Backspace Backspace Backspace Backspace Backspace s T Tab Enter
 l s Enter
 n o t e p a d Spacebar " A � b o u t Spacebar 1 - 7 - 1 0 9 1 - 0 . t x t " Enter

```

### Exception
```
System.Text.EncoderFallbackException: Unable to translate Unicode character \\uD83E at index 10 to specified code page.
   at System.Text.EncoderExceptionFallbackBuffer.Fallback(Char charUnknown, Int32 index)
   at System.Text.EncoderFallbackBuffer.InternalFallback(ReadOnlySpan`1 chars, Int32& charsConsumed)
   at System.Text.Encoding.GetBytesWithFallback(ReadOnlySpan`1 chars, Int32 originalCharsLength, Span`1 bytes, Int32 originalBytesLength, EncoderNLS encoder)
   at System.Text.Encoding.GetBytesWithFallback(Char* pOriginalChars, Int32 originalCharCount, Byte* pOriginalBytes, Int32 originalByteCount, Int32 charsConsumedSoFar, Int32 bytesWrittenSoFar, EncoderNLS encoder)
   at System.Text.Encoding.GetBytes(Char* pChars, Int32 charCount, Byte* pBytes, Int32 byteCount, EncoderNLS encoder)
   at System.Text.EncoderNLS.GetBytes(Char[] chars, Int32 charIndex, Int32 charCount, Byte[] bytes, Int32 byteIndex, Boolean flush)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at Microsoft.PowerShell.PSConsoleReadLine.<>c__DisplayClass83_0.<WriteHistoryRange>b__0()
   at Microsoft.PowerShell.PSConsoleReadLine.WithHistoryFileMutexDo(Int32 timeout, Action action)
   at Microsoft.PowerShell.PSConsoleReadLine.WriteHistoryRange(Int32 start, Int32 end, Boolean overwritten)
   at Microsoft.PowerShell.PSConsoleReadLine.IncrementalHistoryWrite()
   at Microsoft.PowerShell.PSConsoleReadLine.MaybeAddToHistory(String result, List`1 edits, Int32 undoEditIndex, Boolean fromDifferentSession, Boolean fromInitialRead)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```
"

**Comment by daxian-dbw** [comment] 2021-06-03 16:39
Thanks for reporting the issue. This is a duplicate of #2358.

**Closed as completed by daxian-dbw** 2021-06-03 16:39 UTC
