### ISSUE TITLE
Error Report (Exception: System.ArgumentOutOfRangeException)

### ISSUE THREAD

**Issue by Almeida-a** [PowerShell/PSReadLine#2570] opened 2021-06-12 16:22 UTC
Details:
-----------------------------------------------------------------------
Last 200 Keys:
 n c h Space - a Enter
 g i t Space c h e c k o u t Space m a i n Enter
 UpArrow UpArrow Enter
 UpArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace c h e c k o u t Space o r i g i n / H E A D Enter
 g i t Space l o g Space - - p r e t t y = f o r m a t : " % h Space % s " Space - - g r a p h Enter      
 Ctrl+l g i t Space r e f l o g Enter
 g i t Space c o m m i t Space - - a m m e n d Enter
 Enter
 Enter
 Enter
 UpArrow LeftArrow LeftArrow LeftArrow Backspace Enter
 UpArrow UpArrow UpArrow Enter
 g i t Space r e s e t Space - - h a r d Space a 5 d a f 2 4 6 Enter
 UpArrow DownArrow DownArrow Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 UpArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Space b a 7 4 d 6 6 5 Enter
 Ctrl+l

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -11.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
   -----------------------------------------------------------------------

**Comment by daxian-dbw** [comment] 2021-07-01 18:17
No environment data is provided for us to investigate the issue. This looks like a duplicate of #1315, so please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.

**Closed as completed by daxian-dbw** 2021-07-01 18:17 UTC
