### ISSUE TITLE
Windows PowerShell turns into blank window when I resize / move it with Windows + Arrow buttons

### ISSUE THREAD

**Issue by yaskovdev** [PowerShell/PSReadLine#2890] opened 2021-09-23 15:30 UTC
Windows PowerShell sometimes turns into blank window (without any text, just filled with the background color) when I resize / move it with Windows + Arrow buttons. When I return it back to the initial size / position, it shows the below error report.

```
Last 200 Keys:
 d e l e t e Space d e p l o y m e n t Space Ctrl+v Enter
 k u b e c t l Space d e l e t e Space d e p l o y m e n t Space Ctrl+v Enter
 k b Backspace u b e c t l Space d e l e t e Space d e p l o y m e n t Space Ctrl+v Enter
 k u b e c t l Space g e t Space s t a t e f u l s e t Enter
 k u b e c t l Space d e l e t e Space s t a t e f u l s e t Space Ctrl+v Enter
 k u b e c t l Space g e t Space p o d Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 k u b e c t l Space l o g s Space Ctrl+v Enter
 k u b e c t l Space d e s c r i b e Space p o Space Ctrl+v Enter
 UpArrow UpArrow UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 ` Enter


Exception:
System.IO.IOException: The parameter is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.AcceptLineImpl(Boolean validate)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

**Comment by daxian-dbw** [comment] 2021-09-23 20:41
This is a problem of the console host. CMD.exe shows the same behavior in the console host. Windows terminal works fine though. Please switch to Windows Terminal and give it a try.

Duplicate of #2037

**Closed as completed by daxian-dbw** 2021-09-23 20:41 UTC
