### ISSUE TITLE
PSConsoleReadLine.ReadLine - ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by Kinjara** [PowerShell/PSReadLine#725] opened 2018-07-10 12:06 UTC
If I try to read the encryption-state of my Azure-VM; I get the error that the key does not exists.
To work-a-round this I want to try-catch that error and start the encryption process.

However I get the error 'something went wrong'

With kind regards,
Sebastian

Try
>> {
>> #Get-AzureRmVmDiskEncryptionStatus -ResourceGroupName $RGName -VMName $VMName
>> }
>> catch
>> {
>> f($_.Exception.Message -like "The Resource 'Microsoft.Compute/virtualMachines/")
>> {
>> Continue;
>> }
>> else
>> {
>> throw $_.Exception
>> }
>> $Result = "Not encrypted"
>> }$Result3;1
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` Escape 1 3 ; 1 R

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -3.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by Kinjara** [comment] 2018-07-10 12:10
if I remove the 'else' it doesn't go into the error.

**Comment by lzybkr** [comment] 2018-07-11 20:46
This looks like a dupe of https://github.com/lzybkr/PSReadLine/issues/663. Is `[Console]::BufferHeight` less than the number of lines of input?

**Comment by daxian-dbw** [comment] 2019-07-19 00:05
Close as a duplicate of #663

**Closed as completed by daxian-dbw** 2019-07-19 00:05 UTC
Labels: Resolution-Duplicate, OutOfRange
