### ISSUE TITLE
Wrong Emoji handling in Windows Terminal

### ISSUE THREAD

**Issue by JosefZd** [PowerShell/PSReadLine#1653] opened 2020-07-12 12:07 UTC
Pasted emoji in apostrophes `'😃'` renders as `'�'`  and following error appears in Windows Terminal (does not in pure PowerShell prompt).
`Get-CharInfo` (alias `chr`) is my private function and used merely to demonstrate that an Emoji renders well…

<pre>
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

Loading personal and system profiles took 782ms.
PS D:\PShell> 0x1F603|Get-CharInfo

Char CodePoint    Category Description
---- ---------    -------- -----------
😃   U+1F603   OtherSymbol ??? 0xd83d,0xde03

PS D:\PShell> '�'

Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new
### Environment
PSReadLine: 2.0.0-beta5
PowerShell: 5.1.19041.1
OS: Microsoft Windows 10.0.19041
Last 32 Keys
```
 0 x 1 F 6 0 3 | c h r Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow g e t - c h a r i n f o Tab Enter
 ' � ' Enter

```

### Exception
```
System.Text.EncoderFallbackException: Unable to translate Unicode character \uD83D at index 1 to specified code page.
   at System.Text.EncoderExceptionFallbackBuffer.Fallback(Char charUnknown, Int32 index)
   at System.Text.EncoderFallbackBuffer.InternalFallback(Char ch, Char*& chars)
   at System.Text.UTF8Encoding.GetBytes(Char* chars, Int32 charCount, Byte* bytes, Int32 byteCount, EncoderNLS baseEncoder)
   at System.Text.EncoderNLS.GetBytes(Char[] chars, Int32 charIndex, Int32 charCount, Byte[] bytes, Int32 byteIndex, Boolean flush)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at Microsoft.PowerShell.PSConsoleReadLine.<>c__DisplayClass80_0.<WriteHistoryRange>b__0()
   at Microsoft.PowerShell.PSConsoleReadLine.WithHistoryFileMutexDo(Int32 timeout, Action action)
   at Microsoft.PowerShell.PSConsoleReadLine.MaybeAddToHistory(String result, List`1 edits, Int32 undoEditIndex, Boolean fromDifferentSession, Boolean fromInitialRead)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

PS D:\PShell>  
</pre>

**Comment by rkeithhill** [comment] 2020-07-12 19:56
Does this still happen after you update to the latest PSReadline - `2.1.0-beta2`?
```
install-module psreadline -AllowPrerelease -Scope CurrentUser -Force
```

**Comment by daxian-dbw** [comment] 2020-07-12 23:22
Thanks for reporting the issue. This is a duplicate of #949

**Closed as completed by daxian-dbw** 2020-07-12 23:22 UTC
Labels: Resolution-Duplicate

**Comment by JosefZd** [comment] 2020-07-13 17:05
Yes, this happens again

### Environment
PSReadLine: 2.1.0-beta2
PowerShell: 5.1.19041.1
OS: Microsoft Windows 10.0.19041
BufferWidth: 103
BufferHeight: 30
Last 18 Keys
```
 0 x 1 F 6 0 3 Spacebar | Spacebar c h r Enter
 ' � ' Enter

```

### Exception
```
System.Text.EncoderFallbackException: Unable to translate Unicode character
\uD83D at index 1 to specified code page.
   at System.Text.EncoderExceptionFallbackBuffer.Fallback(Char charUnknown,
Int32 index)
   at System.Text.EncoderFallbackBuffer.InternalFallback(Char ch, Char*&
chars)
   at System.Text.UTF8Encoding.GetBytes(Char* chars, Int32 charCount, Byte*
bytes, Int32 byteCount, EncoderNLS baseEncoder)
   at System.Text.EncoderNLS.GetBytes(Char[] chars, Int32 charIndex, Int32
charCount, Byte[] bytes, Int32 byteIndex, Boolean flush)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean
flushEncoder)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at
Microsoft.PowerShell.PSConsoleReadLine.<>c__DisplayClass83_0.<WriteHistoryRange>b__0()
   at Microsoft.PowerShell.PSConsoleReadLine.WithHistoryFileMutexDo(Int32
timeout, Action action)
   at Microsoft.PowerShell.PSConsoleReadLine.MaybeAddToHistory(String
result, List`1 edits, Int32 undoEditIndex, Boolean fromDifferentSession,
Boolean fromInitialRead)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace,
EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```


Kind Regards
   Josef Zdráhal
