### ISSUE TITLE
 error when clearing the prompt

### ISSUE THREAD

**Issue by mhscardoso** [PowerShell/PSReadLine#2260] opened 2021-02-28 13:37 UTC
Últimas 200 Chaves:
 c u m e n t s Ctrl+Alt+/ P y t h o n 3 7 Space - Space P r o j s Ctrl+Alt+/ m y _ f r a c t i o n Ctrl+Alt+/ m y _ f r a c t i o n . p y " Enter
 & Space C : Ctrl+Alt+/ U s e r s Ctrl+Alt+/ M a t h e u s _ 2 Ctrl+Alt+/ A p p D a t a Ctrl+Alt+/ L o c a l Ctrl+Alt+/ P r o g r a m s Ctrl+Alt+/ P y t h o n Ctrl+Alt+/ P y t h o n 3 7 Ctrl+Alt+/ p y t h o n . e x e Space " c : Ctrl+Alt+/ U s e r s Ctrl+Alt+/ M a t h e u s _ 2 Ctrl+Alt+/ D o c u m e n t s Ctrl+Alt+/ P y t h o n 3 7 Space - Space P r o j s Ctrl+Alt+/ m y _ f r a c t i o n Ctrl+Alt+/ m y _ f r a c t i o n . p y " Enter
 Ctrl+l

Exceção:
System.ArgumentOutOfRangeException: O valor deve ser maior ou igual a zero e menor que o tamanho do buffer do console nessa dimensão.
Nome do parâmetro: top
Valor real era -3.
   em System.Console.SetCursorPosition(Int32 left, Int32 top)
   em Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   em Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   em Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment] 2021-03-05 18:58
This is a duplicate of #1315, and was fixed. Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.

**Closed as completed by daxian-dbw** 2021-03-05 18:59 UTC
