### ISSUE TITLE
Powershell issue Please Help

### ISSUE THREAD

**Issue by mondex111** [PowerShell/PSReadLine#1059] opened 2019-09-20 03:19 UTC
Last 1 Keys:
 UpArrow

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.HistoryRecall(Int32 direction)
   at Microsoft.PowerShell.PSConsoleReadLine.PreviousHistory(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by msftrncs** [comment] 2019-09-20 04:07
@mondex111, are you using PSReadline 2.0.0-beta5?  (see the repository README.md for some instructions)  This is probably resolved in 2.0.0-beta5.

**Comment by daxian-dbw** [comment] 2019-09-20 21:06
@mondex111 please download the 2.0.0-beta5 from PowerShellGallery. The issue is very possibly fixed in beta5.

**Closed as completed by daxian-dbw** 2019-09-20 21:06 UTC
Labels: OutOfRange
