### ISSUE TITLE
Quote/Brace matching breaks in Windows 10

### ISSUE THREAD

**Issue by bobbytreed** [PowerShell/PSReadLine#272] opened 2015-08-25 13:06 UTC
Last 15 Keys:
 p r o m p t - f o Tab Spacebar - Tab Spacebar "

Exception:
System.Management.Automation.RuntimeException: Unable to find type [PSConsoleUtilities.PSConsoleReadLine].
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke clauseToInvoke, Boolean createLocalScope, Dictionary`2 functionsToDefine, List`1 variablesToDefine, Err
orHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
   at System.Management.Automation.ScriptBlock.<>c__DisplayClassa.<InvokeWithPipe>b__8()
   at System.Management.Automation.Runspaces.RunspaceBase.RunActionIfNoRunningPipelinesWithThreadCheck(Action action)
   at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputP
ipe, InvocationInfo invocationInfo, Boolean propagateAllExceptionsToTop, List`1 variablesToDefine, Dictionary`2 functionsToDefine, Object[] args)
   at System.Management.Automation.ScriptBlock.DoInvoke(Object dollarUnder, Object input, Object[] args)
   at Microsoft.PowerShell.PSConsoleReadLine.<>c__DisplayClass67.<ProcessOneKey>b__65()
   at Microsoft.PowerShell.PSConsoleReadLine.<>c__DisplayClass63.<CalloutUsingDefaultConsoleMode>b__62()
   at Microsoft.PowerShell.PSConsoleReadLine.CalloutUsingDefaultConsoleMode[T](Func`1 func)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
##    at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

 HAL9000@ P:>

**Comment by rkeithhill** [comment] 2015-08-25 15:31
If you have a custom key handler for PSReadLine defined in your profile and you are on PowerShell 5.0 you need to make sure any references to `[PSConsoleUtilities.xxx]` have been replaced with `[Microsoft.PowerShell.xxx]`.

**Comment by nightroman** [comment] 2015-08-25 15:47
@rkeithhill Thank you for the useful info. I am not yet affected by this issue but I will be eventually. Your suggestion is clear. The problem is that on some machines I will use the old PSReadLine and on others the new _with the same portable profile_. Can you recommend the way how to distinguish new and old PSReadLine in the PowerShell profile and use a proper class? Is it the version of Windows or PSReadLine or something else? I cannot experiment now because I do not have Windows 10 yet but I would like to be prepared beforehand. Perhaps I am not alone with such a scenario.

**Comment by rkeithhill** [comment] 2015-08-25 16:05
@nightroman  I would use a variable for the namespace and then set that conditionally based on this:

```
(Get-Command Get-PSReadlineKeyHandler).ImplementingType.FullName -match 'Microsoft.PowerShell'
```

If that is true set `$psrl = [Microsoft.PowerShell.PSConsoleReadLine]` else `$psrl = [PSConsoleUtilities.PSConsoleReadLine]`.

**Comment by nightroman** [comment] 2015-08-25 16:11
@rkeithhill Thank you. If I were the author I would mention this or similar trick somewhere in the manual.

**Comment by lzybkr** [comment] 2015-08-25 17:06
Closing, see also #266.
I like the suggestion from @rkeithhill, but I should just publish a new release so the namespaces match.

**Closed as completed by lzybkr** 2015-08-25 17:06 UTC
Labels: Resolution-Duplicate
