### ISSUE TITLE
Error when typing (with a long current path?)

### ISSUE THREAD

**Issue by CodeRunRepeat** [PowerShell/PSReadLine#1413] opened 2020-03-20 09:07 UTC
Current path was: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer

-----------------------------------------------------------------------
Last 200 Keys:
 \ M i c r o s o f t \ T e a m F o u n d a t i o n \ T e a m Space E x p l o r e r Enter
 UpArrow " Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow " Enter
 w i r Backspace t a Tab Enter
 UpArrow Space l i s t Space w i t d LeftArrow LeftArrow LeftArrow LeftArrow Backspace Enter
 UpArrow Space / c o l l e t Backspace c t i o n : h t t p s : / / d e v . a z u r e . c o m / C o d e R u n R e p e a t Space / p : S h a r i n g S a m p l e Enter
 UpArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+RightArrow Ctrl+RightArrow Ctrl+RightArrow RightArrow RightArrow RightArrow RightArrow Backspace Backspace Backspace Backspace e x p r Backspace o r t Ctrl+RightArrow Ctrl+RightArrow Ctrl+RightArrow Ctrl+RightArrow Ctrl+RightArrow Ctrl+RightArrow Ctrl+RightArrow Ctrl+RightArrow Ctrl+RightArrow Space / n "

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.

**Comment by iSazonov** [comment] 2020-03-20 09:19
Please use issue template (and script there) to report.

**Comment by daxian-dbw** [comment] 2020-03-20 21:12
From the bug report template:
```
The maintainer may close your issue without further explanation or engagement if:
- You delete this entire template and go your own path;
```
So, please follow the bug report template to provide **environment data** and **repro steps** the next time.

You included no stack information, but it's likely a duplicate of #1306

**Closed as completed by daxian-dbw** 2020-03-20 21:12 UTC
Labels: Resolution-Duplicate
