### ISSUE TITLE
AzureConsoleFailsToExecutePSScript

### ISSUE THREAD

**Issue by lexdex** [PowerShell/PSReadLine#1018] opened 2019-09-03 18:27 UTC
When trying to execute script to detach drives from azure i keep getting errors and operation is not completed.
Script
```powershell
$deleteUnattachedVHDs=1 $storageAccounts = Get-AzStorageAccountforeach($storageAccount in $storageAccounts){
    $storageKey = (Get-AzStorageAccountKey -ResourceGroupName $storageAccount.ResourceGroupName -Name $storageAccount.StorageAccountName)[0].Value
    $context = New-AzStorageContext -StorageAccountName $storageAccount.StorageAccountName -StorageAccountKey $storageKey
    $containers = Get-AzStorageContainer -Context $context
    foreach($container in $containers){
        $blobs = Get-AzStorageBlob -Container $container.Name -Context $context
        #Fetch all the Page blobs with extension .vhd as only Page blobs can be attached as disk to Azure VMs
        $blobs | Where-Object {$_.BlobType -eq 'PageBlob' -and $_.Name.EndsWith('.vhd')} | ForEach-Object { 
            #If a Page blob is not attached as disk then LeaseStatus will be unlocked
            if($_.ICloudBlob.Properties.LeaseStatus -eq 'Unlocked'){
                    if($deleteUnattachedVHDs -eq 1){
                        Write-Host "Deleting unattached VHD with Uri: $($_.ICloudBlob.Uri.AbsoluteUri)"
                        $_ | Remove-AzStorageBlob -Force
                        Write-Host "Deleted unattached VHD with Uri: $($_.ICloudBlob.Uri.AbsoluteUri)"
                    }
                    else{
                        $_.ICloudBlob.Uri.AbsoluteUri
                    }
            }
        }
    }
}
```
![Screenshot from 2019-09-02 09-02-40](https://user-images.githubusercontent.com/41371569/64198718-7af58000-ce91-11e9-80ec-f6a8b07073e9.png)
![Screenshot from 2019-09-02 09-02-28](https://user-images.githubusercontent.com/41371569/64198731-8052ca80-ce91-11e9-8f94-25338c73708d.png)
![Screenshot from 2019-09-02 09-02-21](https://user-images.githubusercontent.com/41371569/64198739-821c8e00-ce91-11e9-92b3-d13c3204886c.png)

**Comment by msftrncs** [comment] 2019-09-07 05:31
@lexdex,  I notice the script in your screen shots appears to be missing some line endings in the first line.  Looks like the script should read:

```PowerShell
$deleteUnattachedVHDs = 1 
$storageAccounts = Get-AzStorageAccount
foreach ($storageAccount in $storageAccounts) {
    $storageKey = (Get-AzStorageAccountKey -ResourceGroupName $storageAccount.ResourceGroupName -Name $storageAccount.StorageAccountName)[0].Value
    $context = New-AzStorageContext -StorageAccountName $storageAccount.StorageAccountName -StorageAccountKey $storageKey
    $containers = Get-AzStorageContainer -Context $context
    foreach ($container in $containers) {
        $blobs = Get-AzStorageBlob -Container $container.Name -Context $context
        #Fetch all the Page blobs with extension .vhd as only Page blobs can be attached as disk to Azure VMs
        $blobs | Where-Object { $_.BlobType -eq 'PageBlob' -and $_.Name.EndsWith('.vhd') } | ForEach-Object {
            #If a Page blob is not attached as disk then LeaseStatus will be unlocked
            if ($_.ICloudBlob.Properties.LeaseStatus -eq 'Unlocked') {
                if ($deleteUnattachedVHDs -eq 1) {
                    Write-Host "Deleting unattached VHD with Uri: $($_.ICloudBlob.Uri.AbsoluteUri)"
                    $_ | Remove-AzStorageBlob -Force
                    Write-Host "Deleted unattached VHD with Uri: $($_.ICloudBlob.Uri.AbsoluteUri)"
                } else {
                    $_.ICloudBlob.Uri.AbsoluteUri
                }
            }
        }
    }
}
```
~I also question of all the `$.ICloudBlob` references are not supposed to be `$_.ICloudBlob` instead.~ (confirmed in screen shots)

When you get this error, is the terminal window smaller than the script?   That's usually what does this.  The exception caused when the pasted script scrolls off the top of the window would be fixed in #979.

**Closed as completed** 2019-09-12 23:47 UTC
Labels: OutOfRange
