### ISSUE TITLE
Emojis aren't working in powershell 7 😭

### ISSUE THREAD

**Issue by 0xW1sKy** [PowerShell/PSReadLine#1594] opened 2020-06-07 12:06 UTC
### Environment
```none
PS version: 7.1.0-preview.3
PSReadline version: 2.0.1
os: 10.0.19041.1 (WinBuild.160101.0800)
PS file version: 7.1.0.0
HostName: ConsoleHost
BufferWidth: 215
BufferHeight: 40
```

#### Last 14 Keys
```
 � RightArrow Backspace Delete Delete Backspace Enter
 e c h o Spacebar � Enter

```
#### Exception
```
System.Text.EncoderFallbackEx�ception: Unable to translate Unicode character \\uD83D at index 5 to specified code page.
   at System.Text.EncoderExceptionFallbackBuffer.Fallback(Char charUnknown, Int32 index)
   at System.Text.EncoderFallbackBuffer.InternalFallback(ReadOnlySpan`1 cha�rs, Int32& charsConsumed)
   at System.Text.Encoding.GetBytesWithFallback(ReadOnlySpan`1 chars, Int32 originalCharsLength, Span`1 bytes, Int32 originalBytesLength, EncoderNLS encoder)
   at System.Text.Encoding.GetBytesWithFallback(Char* pOriginalChars, �Int32 originalCharCount, Byte* pOriginalBytes, Int32 originalByteCount, Int32 charsConsumedSoFar, Int32 bytesWrittenSoFar, EncoderNLS encoder)
   at System.Text.Encoding.GetBytes(Char* pChars, Int32 charCount, Byte* pBytes, Int32 byteCount, EncoderNLS enc�oder)
   at System.Text.EncoderNLS.GetBytes(Char[] chars, Int32 charIndex, Int32 charCount, Byte[] bytes, Int32 byteIndex, Boolean flush)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Dispose(�Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at Microsoft.PowerShell.PSConsoleReadLine.<>c__DisplayClass83_0.<WriteHistoryRange>b__0()
   at Microsoft.PowerShell.PSConsoleReadLine.WithHistoryFileMutexDo(Int32 timeout, Action action)
   at� Microsoft.PowerShell.PSConsoleReadLine.WriteHistoryRange(Int32 start, Int32 end, Func`2 fileOpener)
   at Microsoft.PowerShell.PSConsoleReadLine.IncrementalHistoryWrite()
   at Microsoft.PowerShell.PSConsoleReadLine.MaybeAddToHistory(String result, List�`1 edits, Int32 undoEditIndex, Boolean fromDifferentSession, Boolean fromInitialRead)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, Can�cellationToken cancellationToken)
```

## Steps to reproduce
use `[Windows Key] + '.' `  to add an emoji
echo 🔥

## Expected behavior
🔥

## Actual behavior
```
�
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new
```

**Comment by 0xW1sKy** [comment] 2020-06-07 12:22
so i was thinking more about this and realized this doesnt happen on my work computer (where i normally use emoji in my git commits.)

this is info for a working version:
### Environment
```
PS version: 7.0.1
PSReadline version: 2.0.0
os: 10.0.17134.1 (WinBuild.160101.0800)
PS file version: 7.0.1.0
HostName: ConsoleHost
BufferWidth: 306
BufferHeight: 3000
```

**Comment by 0xW1sKy** [comment] 2020-06-07 12:44
maybe my version of windows it the issue.
changed to ps 7.0.1 release version and still have same issue on my personal machine.

```
PS version: 7.0.1
PSReadline version: 2.0.0
os: 10.0.19041.1 (WinBuild.160101.0800)
PS file version: 7.0.1.0
HostName: ConsoleHost
BufferWidth: 215
BufferHeight: 37
```

**Comment by rkeithhill** [comment] 2020-06-07 17:18
The Windows Emoji panel doesn't seem to insert emojis correctly into PS 7.  Not sure where the problem lies.  If you execute the following does it display 🔥 correctly?
```
"`u{1f525}"
```

**Comment by 0xW1sKy** [comment] 2020-06-07 17:27
"`u{1f525}" does properly display for me.

**Comment by rkeithhill** [comment] 2020-06-07 17:36
It seems to be that pasting into PS with emojis doesn't work right.  If you copy to the clipboard the emoji that you just displayed using the Unicode escape string and then try to paste it back into PowerShell - it doesn't work.  BTW, you can remove PSReadLine from this situation by running `pwsh -noninteractive -noprofile` and this issue reproduces. So someone should probably move this issue to the PowerShell repo. Even then, this may be a conhost issue.  Yup, just fired up CMD.exe in it's one console window and this reproduces there.  Looking more like a Windows/conhost.exe issue and not a PSRL/PowerShell issue.  OK, see this issue in the WindowsTerminal repo (also repo for conhost) - https://github.com/microsoft/terminal/issues/1503

**Comment by daxian-dbw** [comment] 2020-06-10 00:16
@rkeithhill Thanks for referencing the WT issue!
@0xW1sKy emojis are not well supported in PSReadLine today. Here are the related issue: https://github.com/PowerShell/PSReadLine/issues/1329, https://github.com/PowerShell/PSReadLine/issues/949
I will close this issue as a duplicate.

**Closed as completed by daxian-dbw** 2020-06-10 00:16 UTC
Labels: Resolution-Duplicate
