### ISSUE TITLE
Custom font work incorrectly on windows 10

### ISSUE THREAD

**Issue by coolxxy** [PowerShell/PSReadLine#1198] opened 2019-05-22 08:13 UTC
# Custom font work incorrectly

I have set font to `Source Code Pro`  and Powershell  displaying with `Source Code Pro`, but every time it refresh output content, the font would changed to default font and immediately changed to `Source Code Pro` again and, even worse, if some output showing in `more` mode, it always  using the default font rather than `Source Code Pro`.

# Environment data

```text
Name                           Value
----                           -----
PSVersion                      6.2.1
PSEdition                      Core
GitCommitId                    6.2.1
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by msftrncs** [comment] 2019-11-21 06:39
Can we confirm what console (regular Windows Console or Windows Terminal) is being used, and how the custom font is getting set?

**Comment by coolxxy** [comment] 2019-12-02 10:50
> Can we confirm what console (regular Windows Console or Windows Terminal) is being used, and how the custom font is getting set?

I am using Windows Console, and set the custom font through its setting menu.

**Comment by daxian-dbw** [comment] 2019-12-07 06:50
> but every time **it refresh output content**, the font would changed to default font

By "it refresh output content", do you mean when PowerShell renders any output?

**Comment by daxian-dbw** [comment] 2019-12-12 18:02
Close as a duplicate of #964

**Closed as completed by daxian-dbw** 2019-12-12 18:02 UTC
Labels: Resolution-Duplicate
