### ISSUE TITLE
PowerShell - Ctrl-L does not clear the screen

### ISSUE THREAD

**Issue by bahadirali** [PowerShell/PSReadLine#1314] opened 2020-01-23 23:08 UTC
## Environment

```none
PS version: 5.1.18362.145
PSReadline version: 2.0.0-beta2
os: 10.0.18362.1 (WinBuild.160101.0800)
PS file version: 10.0.18362.1 (WinBuild.160101.0800)
HostName: ConsoleHost
BufferWidth: 211
BufferHeight: 3000
```

## Exception report

-----------------------------------------------------------------------
Last 200 Keys:
 " Space } Space e l s e Space { Space " p o w e r s h e l l . e x e " Space } ; Space ( d i r Space $ p s h o m e \ $ n a m e ) . V e r s i o n I n f o . F i l e V e r s i o n ) " Enter
 Space Space Space Space " H o s t N a m e : Space $ h o s t N a m e " Enter
 Space Space Space Space " B u f f e r W i d t h : Space $ ( [ c o n s o l e ] : : B u f f e r W i d t h ) " Enter
 Space Space Space Space " B u f f e r H e i g h t : Space $ ( [ c o n s o l e ] : : B u f f e r H e i g h t ) ` n " Enter
 } Enter
 Ctrl+l

Exception:
System.IO.IOException: The parameter is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

## Steps to reproduce

Press Ctrl + L in PowerShell

## Expected behavior

Ctrl + L should clear the screen in PowerShell

## Actual behavior

Throws exception. It does not clear the screen.

**Comment by daxian-dbw** [comment] 2020-01-23 23:23
Duplicate of #709, which has been fixed. Please try out the latest version of PSReadLine from PowerShell Gallery.

**Closed as completed by daxian-dbw** 2020-01-23 23:23 UTC
Labels: Resolution-Duplicate
