### ISSUE TITLE
This happened when I opened a quotation to attach a message to a commit. 

### ISSUE THREAD

**Issue by aelizj** [PowerShell/PSReadLine#1422] opened 2020-03-24 23:23 UTC
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 r Backspace UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 Enter
 UpArrow Enter
 UpArrow Enter
 Enter
 UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 g i t Space a d d Backspace Backspace Backspace s t a t u s Enter
 g i t Space a d d Space r Tab Enter      
 g i t Space c o m m i t Space - m Space " R P S Space B o n u s Space F e a t u r e s " Enter
 g i t Space p u s h Enter
 UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow DownArrow Enter
 UpArrow Enter
 i r c Backspace b Enter
 i r b Enter
 i r b Enter
 UpArrow UpArrow Enter
 Ctrl+s Backspace Ctrl+c g i t Space s t a t u s Enter
 g i t Space a d d Space r Tab Enter      
 g i t Space c o m m i t Space - m Space " g i t Space c o m m i t Space - m Space "
Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero 
and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)     
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg) 
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by iSazonov** [comment] 2020-03-25 03:09
See #1306

**Comment by daxian-dbw** [comment] 2020-03-26 06:36
From the bug report template:
```
The maintainer may close your issue without further explanation or engagement if:
- You delete this entire template and go your own path;
```
So, please follow the bug report template to provide **environment data** and **repro step** the next time.

As for this issue, it's a duplicate of #1306 and was fixed in the latest version. Please check out #1306 for more information.

**Closed as completed by daxian-dbw** 2020-03-26 06:36 UTC
Labels: Resolution-Duplicate
