### ISSUE TITLE
Powershell not processing Unicode correctly

### ISSUE THREAD

**Issue by Gym-Brown** [PowerShell/PSReadLine#1447] opened 2020-04-01 22:07 UTC
PS G:\cmd\PS1m echo "��������������"

Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 l 2 Space = Space ' ' Space * Space 6 6 Enter
 $ h l 3 Space = Space ' ' Space * Space 6 6 Enter
 # $ h l 5 Space = Space ' ' Space * Space 6 6 Enter
 c a t Space t o 1 . p s 1 Enter
 UpArrow LeftArrow LeftArrow LeftArrow LeftArrow Backspace Enter
 $ h l 0 Space = Space ' ' Space * Space 6 6 Enter
 $ h l 1 Space = Space ' ' Space * Space 6 6 Enter
 $ h l 2 Space = Space ' ' Space * Space 6 6 Enter
 $ h l 3 Space = Space ' ' Space * Space 6 6 Enter
 # $ h l 5 Space = Space ' ' Space * Space 6 6 Enter
 UpArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow
LeftArrow LeftArrow LeftArrow Backspace Enter
 w r t i t e Backspace Backspace Backspace Backspace i t e Backspace Backspace Backspace Backspace Backspace e e x Back
space Backspace c h o Space " � � � � � � � � � � � � � � " Enter

Exception:
System.Text.EncoderFallbackException: Unable to translate Unicode character \uD83D at index 6 to specified code page.
   at System.Text.EncoderExceptionFallbackBuffer.Fallback(Char charUnknown, Int32 index)
   at System.Text.EncoderFallbackBuffer.InternalFallback(Char ch, Char*& chars)
   at System.Text.UTF8Encoding.GetBytes(Char* chars, Int32 charCount, Byte* bytes, Int32 byteCount, EncoderNLS baseEnco
der)
   at System.Text.EncoderNLS.GetBytes(Char[] chars, Int32 charIndex, Int32 charCount, Byte[] bytes, Int32 byteIndex, Bo
olean flush)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at Microsoft.PowerShell.PSConsoleReadLine.<>c__DisplayClass81_0.<WriteHistoryRange>b__0()
   at Microsoft.PowerShell.PSConsoleReadLine.WithHistoryFileMutexDo(Int32 timeout, Action action)
   at Microsoft.PowerShell.PSConsoleReadLine.MaybeAddToHistory(String result, List`1 edits, Int32 undoEditIndex, Boolea
n fromDifferentSession, Boolean fromInitialRead)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS G:\cmd\PS1> echo "��������������"

**Comment by daxian-dbw** [comment] 2020-04-02 16:21
This is a duplicate of #949

**Closed as completed by daxian-dbw** 2020-04-02 16:21 UTC
Labels: Resolution-Duplicate
