### ISSUE TITLE
System.Text.EncoderFallbackException: Unable to translate Unicode character \uD83D

### ISSUE THREAD

**Issue by Dantochi** [PowerShell/PSReadLine#3796] opened 2023-09-08 16:42 UTC
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
System.Text.EncoderFallbackException: Unable to translate Unicode character \uD83D at index 171 to specified code page.
   at System.Text.EncoderExceptionFallbackBuffer.Fallback(Char charUnknown, Int32 index)
   at System.Text.EncoderFallbackBuffer.InternalFallback(Char ch, Char*& chars)
   at System.Text.UTF8Encoding.GetBytes(Char* chars, Int32 charCount, Byte* bytes, Int32 byteCount, EncoderNLS baseEncoder)
   at System.Text.EncoderNLS.GetBytes(Char[] chars, Int32 charIndex, Int32 charCount, Byte[] bytes, Int32 byteIndex, Boolean flush)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at Microsoft.PowerShell.PSConsoleReadLine.<>c__DisplayClass83_0.<WriteHistoryRange>b__0()
   at Microsoft.PowerShell.PSConsoleReadLine.WithHistoryFileMutexDo(Int32 timeout, Action action)
   at Microsoft.PowerShell.PSConsoleReadLine.MaybeAddToHistory(String result,
 List`1 edits, Int32 undoEditIndex, Boolean fromDifferentSession, Boolean fromInitialRead)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

### Screenshot

![Git-issue ](https://github.com/PowerShell/PSReadLine/assets/57640426/e23313c0-85e7-4e3b-a5bb-0f07c5316622)

### Environment data

```console
PS Version: 5.1.22621.1778
PS HostName: ConsoleHost
PSReadLine Version: 2.0.0
PSReadLine EditMode: Windows
OS: 10.0.22621.1 (WinBuild.160101.0800)
BufferWidth: 77
BufferHeight: 25
```

### Steps to reproduce

When I was making a commit while writing the message, I used the the Shift key and Capslock key interchangeably to write capital letter. One of the messages it gave was something like this:

```
 Spacebar b i n g e s Spacebar Backspace Backspace d Spacebar q u i t e Space
bar a Spacebar n u m b e r Spacebar o f Spacebar m o d u k e Backspace Backsp
ace l e s Spacebar t h a t Spacebar I Spacebar h a d Spacebar a l r e a d y S
pacebar d o n e Spacebar j u s t Spacebar t o Spacebar r e m i n d Spacebar m
 y s e l f Spacebar a d Spacebar Backspace Backspace n f Spacebar Backspace B
ackspace d Spacebar t o Spacebar g e t Spacebar t h o s e Spacebar r u s t y 
Spacebar f i n g e r s Spacebar o i l e d Spacebar a g i a Backspace Backspac
e a i n . Spacebar LeftArrow t Backspace Spacebar T o d a y Spacebar s Spaceb
ar Backspace Backspace i s Spacebar 9 t h Spacebar S e p t e m b e r , Spaceb
ar 2 9 0 2 Backspace Backspace Backspace 0 2 3 Spacebar � Backspace RightArro
w LeftArrow Backspace DownArrow LeftArrow RightArrow DownArrow RightArrow � RightArrow Enter

```

### Expected behavior

The expected behavior was the commit successfully

### Actual behavior

It gave the exception above but after I ran it again, it ran successfully...

**Comment by daxian-dbw** [comment] 2023-09-08 18:15
Thanks for opening the issue. PSReadLine doesn't deal with surrogate pairs properly.
Close as a duplicate of #1587

**Closed as completed by daxian-dbw** 2023-09-08 18:15 UTC

**Comment by Dantochi** [comment] 2023-09-08 20:10
Ok thanks you 💪
