### ISSUE TITLE
Improve update-help warnings if a module does not exist (404) on server

### ISSUE THREAD

**Issue by bobknowscode** [PowerShell/PSReadLine#3317] opened 2022-05-17 20:51 UTC
### Prerequisites

- [X] Write a descriptive title.

### Description of the new feature/enhancement

This enhancement comes from an issue I logged in the PowerShell repo
https://github.com/PowerShell/PowerShell/issues/17067

When running update-help from powershell the user will see "Failed to update Help for the module(s) for several modules including ConfigDefenderPerformance and PSReadline.

There are 2 issues with the failures:
1. There are in red and as such lead users to think the update-help failed.  
2. The error message indicates that the help content is available and can be installed using Update-Help -UICulture -en-us.

For (1)
Would it be possible to catch such 404 download errors and print a warning instead? I would assume this will be written in the user's WarningForegroundColor : Yellow and/or WarningBackgroundColor : Black
Maybe modify the text to indicate a warning as well...
"Warning - failed to update help for module(s)  ..."

For (2)
Would it be possible to remove the last line where the user is told that the English-US help content is available and can be installed using Update-Help -UICulture en-US  when there is a 404 error.  

Why would the help for such a module disappear from the server to cause a 404 error?

![updateHelpError](https://user-images.githubusercontent.com/92458643/168906352-63b5130d-17b7-4176-a9d2-a15c82307092.png)

### Proposed technical implementation details (optional)

I added some possible enhancements to the issue in the description of the new feature

**Comment by daxian-dbw** [comment] 2022-05-17 21:22
The issue about `Update-Help PSReadLine` is a known issue due to the in-box PSReadLine module folder name, which has been fixed in newer versions of Windows. Please see this blog for workarounds: https://devblogs.microsoft.com/powershell/updating-help-for-the-psreadline-module/  /cc @sdwheeler

**Closed as completed** 2022-05-23 21:57 UTC
Labels: Resolution-Fixed

**Comment by marcinsmialek** [comment] 2023-07-08 18:03
If you've reached this page because of 404 error and you're looking for a working link:  
https://devblogs.microsoft.com/powershell/updating-help-for-the-psreadline-module-in-windows-powershell-5-1/

In case it breaks again, the issue is with the letter casing of PSReadline preinstalled with Windows. Rename folder & restart:  
`cmd /c ren "C:\Program Files\WindowsPowerShell\Modules\PSReadline" PSReadLine`

The general issue of `Update-Help` failing with `404` is tracked here:  
https://github.com/PowerShell/PowerShell/issues/17067
