### ISSUE TITLE
In 6.2.3 and above PSReadLine causes 'backspace' in posh-git + Windows Terminal

### ISSUE THREAD

**Issue by tig** [PowerShell/PSReadLine#1078] opened 2019-09-29 19:18 UTC
Environment data
----------------
- posh-git version/path: 1.0.0 beta3 ~\Documents\PowerShell\Modules\posh-git\1.0.0     
- PowerShell version: 6.2.3                                                                                       
- git version 2.23.0.windows.1                                                                                    
- OS: Microsoft Windows NT 10.0.18362.0            

Steps to reproduce or exception report
--------------------------------------
Please see this posh-git Issue for more details: https://github.com/dahlbyk/posh-git/issues/704

@rkeithhill

**Comment by daxian-dbw** [comment] 2019-09-30 17:17
Quoted from https://github.com/dahlbyk/posh-git/issues/704#issuecomment-536654188
> I also noticed this, and posted about it in the Windows Terminal repository. Someone suggested it was caused by the ≡ character; at least where Cascadia Code is concerned, this is currently an "ambiguous-width" character, so the terminal's understanding of the cursor position becomes inconsistent. I think the older console that you get by launching pwsh.exe just forces everything to one character cell.

**Comment by msftrncs** [comment] 2019-09-30 17:35
Then that makes this related to #1054.  Character width is determined by the font …  I don't know if PSReadLine has anyway it can determine this when its behind a terminal.   Can the current character position be polled through a VT sequence?  Spit out a character, poll the new cursor position, etc...?

**Comment by daxian-dbw** [comment] 2019-09-30 17:56
Might be different. The linked issue description mentioned that it happens on Windows Terminal only:
> EDIT: This does NOT happen in Hosts other than Windows Terminal. E.g. in the VSCode terminal, cmd.exe, and ConEmu it works fine.

**Comment by tig** [comment] 2019-09-30 18:02
> Might be different. The linked issue description mentioned that it happens on Windows Terminal only:
> 
> > EDIT: This does NOT happen in Hosts other than Windows Terminal. E.g. in the VSCode terminal, cmd.exe, and ConEmu it works fine.

Correct. I was unable to reproduce in any host other than Windows Terminal.

Additionally, while the character width issue may be the culprit, my instincts say this is in PSReadline as @rkeithhill and I tested a PS 6.2.3 session in Windows Terminal WITHOUT PSReadLine loaded...and the font appeared correctly without the backspace issue.

**Comment by msftrncs** [comment] 2019-09-30 18:14
If the issue is in fact that sometimes (some fonts) the `≡` is a different width, then this will affect PSReadLine's ability to estimate where the cursor is.  PSReadLine attempts to modify the prompt as you type, so it has to move and move again the cursor while you are typing.

**Comment by msftrncs** [comment] 2019-09-30 18:31
Difference in hosts could simply be the default font, or not demonstrating the issue using the same path and same Posh Git connections.

Also, as you type, PSReadLine may modify the color of previous parts of the command line, more reason that the cursor has to be moved, and why PSReadLine needs an accurate estimate of the cursor position.

**Comment by lzybkr** [comment] 2019-09-30 19:35
See https://github.com/microsoft/terminal/pull/2928 where they are assuming ambiguous width characters are 1 character.

Note that PSReadLine hard codes the characters that are double width [here](https://github.com/PowerShell/PSReadLine/blob/288e3c09ebd9d09e6ba90892aedebefaf7ab4a2d/PSReadLine/Render.cs#L857).

**Comment by vexx32** [comment] 2019-09-30 19:36
Should emoji be / are they part of that list @lzybkr ?

**Comment by lzybkr** [comment] 2019-09-30 19:46
Note in my link above the commented out code for surrogate pairs. Emoji have the same issue I think.

**Comment by DHowett-MSFT** [comment] 2019-09-30 22:58
Specifically microsoft/terminal#2928 will _enforce_ all ambiguous width chars being one cell wide -- this will fix this bug.

**Comment by tig** [comment] 2019-10-01 03:20
> Specifically [microsoft/terminal#2928](https://github.com/microsoft/terminal/pull/2928) will _enforce_ all ambiguous width chars being one cell wide -- this will fix this bug.

Woot. Thanks.

**Comment by daxian-dbw** [comment] 2019-11-27 20:48
https://github.com/microsoft/terminal/pull/2928 was merged, so closing this issue.

**Closed as completed by daxian-dbw** 2019-11-27 20:48 UTC
Labels: Resolution-External, Windows-Terminal
