### ISSUE TITLE
Off annoying beep sound

### ISSUE THREAD

**Issue by munrocket** [PowerShell/PSReadLine#636] opened 2018-02-24 12:28 UTC
When I using the VS Code with "terminal.integrated.shell.windows" set to powershell.exe and deleting characters with backspace there is a high-pitched, old-school sound warning when there are no more characters to delete back. It would be wonderful if there is a setting to disable that sound by default. Because it's very annoying and difficult to off.

You can lisen this [sound](https://dl.dropboxusercontent.com/u/10976481/vscode-sound.wav)

VSCode Version: Code 1.20.1 (f9d0c68, 2017-02-09T00:26:45.394Z)
Shell version: Shell 1.7.9
OS Version: Microsoft Windows [Version 10.0.16299.248]
Under macOS all is perfect in VS code.

My solution after 15 minutes of googling:

run cmd.exe as administrator
echo Set-PSReadlineOption -BellStyle None >> C:\Windows\System32\WindowsPowerShell\v1.0\Microsoft.Powershell_profile.ps1
powershell Set-ExecutionPolicy RemoteSigned

**Comment by lzybkr** [comment] 2018-02-25 02:42
This is a duplicate of #422. You can install [2.0.0-beta1](https://www.powershellgallery.com/packages/PSReadLine/2.0.0-beta1) for the fix.

**Closed as completed by lzybkr** 2018-02-25 02:42 UTC
Labels: Resolution-Duplicate

**Comment by munrocket** [comment] 2018-02-25 10:02
@lzybkr Why we need to install some beta? This must be default option in stable version.

Just check. Most populat text editors like Vs code and Vim use your beeping PSReadline

1. [Best programming text editors](https://www.slant.co/topics/12/~best-programming-text-editors)
2. [What is the best javascript IDEs or editors](https://www.slant.co/topics/1686/~javascript-ides-or-editors)

Here can find issues related to silent behavior and “visual beep”:

1. https://github.com/Microsoft/vscode/issues/21441
2. https://github.com/Microsoft/WSL/issues/715
3. https://github.com/noseglid/atom-build/issues/291
4. https://intellij-support.jetbrains.com/hc/en-us/community/posts/205806309-How-to-disable-completely-audible-beeps-

**Comment by lzybkr** [comment] 2018-02-25 20:26
You don't need to install anything - you've found the configuration option, I just suggested an alternative. Note that the beta is pretty stable, there are a couple bugs that might be blocking some folks, but it doesn't hurt to try it.

I considered a visual beep - in fact it's one of the options you can configure, though unfortunately it's not implemented. I find this a little surprising, but I think you're the first to mention it.
