### ISSUE TITLE
New Issue Found while using youtube-dl

### ISSUE THREAD

**Issue by Minecrafter-Pythoner** [PowerShell/PSReadLine#2224] opened 2021-02-18 03:37 UTC
Last 25 Keys:
 c d Space E : \ V i d e o s Enter
 y o u t u b e - d l Space Ctrl+Space

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -14.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.Menu.EnsureMenuAndInputIsVisible(IConsole console, Int32 tooltipLineCount)
   at Microsoft.PowerShell.PSConsoleReadLine.Menu.DrawMenu(Menu previousMenu)
   at Microsoft.PowerShell.PSConsoleReadLine.PossibleCompletionsImpl(CommandCompletion completions, Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.CompleteImpl(Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS E:\Videos> youtube-dl https://www.bilibili.com/video/BV1s7411V7fJ?p=2

**Comment by daxian-dbw** [comment] 2021-02-18 17:32
Hi @Minecrafter-Pythoner, you didn't provide the environment data (version of PSReadLine, PowerShell, and etc.), but by looking at the call stack, it's likely a duplicate of #1306. Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.

**Closed as completed by daxian-dbw** 2021-02-18 17:32 UTC
