### ISSUE TITLE
Exception thrown, when CPU was fully loaded

### ISSUE THREAD

**Issue by GRustamyan-ST** [PowerShell/PSReadLine#2774] opened 2021-08-24 15:37 UTC
### Environment
PSReadLine: 2.1.0
PowerShell: 7.1.3
OS: Microsoft Windows 10.0.19043
BufferWidth: 120
BufferHeight: 30

Last 110 Keys
```
 g i t Spacebar p u l l Enter
 g i t Spacebar w o r k t r e e Spacebar a d d Spacebar - b Spacebar e m e r g e n c y - f i x Spacebar . . / t e m p Spacebar m a s t e r LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow LeftArrow LeftArrow LeftArrow LeftArrow Backspace Backspace Backspace Backspace Backspace Backspace
```

### Exception
```
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Actual value was 39.
   at System.ConsolePal.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.CalculateWhereAndWhatToRender(Boolean cursorMovedToInitialPos, RenderData renderData, LineInfoForRendering& lineInfoForRendering)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.BackwardDeleteChar(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

Powershell terminal was 
Windows Terminal Preview
Version: 1.10.1933.0

**Comment by daxian-dbw** [comment] 2021-09-15 16:49
Hi @GRustamyan-ST, thanks for reporting this issue. I really would like to reproduce it locally, but couldn't with the given information in the bug description. It would be great if you can share some more information:
1. what was the prompt text when the issue happened? for example, the highlighted `PS ...>` part in the screenshot below is the prompt text. Knowing the length of the prompt text helps us to identify where the cursor was when the issue happened, which would help to reproduce the issue.
    ![image](https://user-images.githubusercontent.com/127450/133474329-fb1a8e2c-abe5-44fb-81f4-4b6386535601.png)
2. Were you using the `history prediction` feature when the issue happened? If so, did it have history prediction text rendered when the issue happened? (If you don't know what that feature is, then you were not using it at that time)
3. Do you run into this issue again recently? If so, please take a screenshot of the windows terminal, including the lines before the exception happens.

**Comment by GRustamyan-ST** [comment] 2021-09-15 17:47
Hi @daxian-dbw,
1. Not 100% accurate, but probably it was something like this
```
  ~\Desktop\ServiceTitan\master   master ≡  ~1 
❯
```
I'm using OhMyPosh, so not sure how to dump exact data 
![image](https://user-images.githubusercontent.com/56830600/133483462-1d4883d9-6173-41c2-9489-147c9747ef19.png)

2. Probably not, since IDK what is it :)
3. No I didn't.

The only clue I have is CPU load, since at that moment I was doing CPU intensive build and my laptop was throttling much due to high temperature. Console was pretty laggy because of that. I typed in some stuff and tried to fix typo (this is part with a bunch of Left Arrows and backspaces)

**Comment by daxian-dbw** [comment] 2021-09-15 18:19
Thanks for the additional feedback!
If you run into this again in future, please take a screenshot of the terminal/console, including the lines before the exception happens. We have been seeing several reports with this exception happening in the 2.1.0 version of PSReadLine, but could not reproduce any of them locally. Having the screenshot would be very helpful to our investigation. Thanks in advance!

**Comment by daxian-dbw** [comment] 2021-09-20 18:13
I don't know if the high CPU load played a role, but it may be suspicious -- could the laggy console report the wrong buffer/cursor size? I don't have an answer :confused:

Given that this particular issue cannot be reproduced, no more action can be taken. I will close it for now. If you run into this issue again, please
1. take a screenshot of the terminal/console, including the lines before the exception happens;
2. describe what you did that led to the exception (the more detailed the better!)

Thank you!

**Closed as completed by daxian-dbw** 2021-09-20 18:13 UTC
Labels: Issue-Bug
