### ISSUE TITLE
PSReadLine: ArgumentOutOfRangeException - startIndex cannot be larger than length of string.

### ISSUE THREAD

**Issue by dennyronngren** [PowerShell/PSReadLine#387] opened 2016-05-12 19:02 UTC
---

Last 7 Keys:
 g c Spacebar c > Alt+- Backspace

Exception:
System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string.
Parameter name: startIndex
   at System.Text.StringBuilder.ToString(Int32 startIndex, Int32 length)
   at Microsoft.PowerShell.PSConsoleReadLine.BackwardDeleteChar(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignor
eIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.DigitArgument(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignor
eIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
##    at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

Let me know if you need something more.

**Comment by lzybkr** [comment] 2017-11-06 19:02
Dupe of #502.

**Closed as completed by lzybkr** 2017-11-06 19:02 UTC
Labels: Resolution-Duplicate
