### ISSUE TITLE
Got an assertion - command line told me to report it here. 

### ISSUE THREAD

**Issue by johnmccrae** [PowerShell/PSReadLine#2214] opened 2021-02-12 18:08 UTC
## Environment

```none
PS version: 7.1.1
PSReadline version: 2.1.0
os: 10.0.19041.1 (WinBuild.160101.0800)
PS file version: 7.1.1.0
HostName: ConsoleHost
BufferWidth: 231
BufferHeight: 32766
```

## Exception report

Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.md
Thank you!

### Environment
PSReadLine: 2.1.0
PowerShell: 2020.6.0
OS: Microsoft Windows 10.0.19042
BufferWidth: 271
BufferHeight: 27

Last 0 Keys
```

```

### Exception
```
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Actual value was 27.
   at System.ConsolePal.SetCursorPosition(Int32 left, Int32 top)
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.CalculateWhereAndWhatToRender(Boolean cursorMovedToInitialPos, RenderData renderData, LineInfoForRendering& lineInfoForRendering)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Render()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadKey()
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

## Steps to reproduce

Running a piece of automation code for Azure. I can't repro it. 

## Expected behavior

Expectation - no random assertions

## Actual behavior

Random assertion

**Comment by Long0x0** [comment] 2021-02-14 12:39
bot should reply:
> This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
> See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.

lol
but seems v2.1.0 doesn't solve the problem. **v2.2.0-beta1** did it for me.

**Comment by daxian-dbw** [comment] 2021-03-11 17:27
@johnmccrae We really want to fix this issue, and a local repro is needed for us to investigate. Can you please provide us the repro steps?

**Comment by iSazonov** [comment] 2021-03-11 18:27
> Random assertion

Looks like a race condition in [CalculateWhereAndWhatToRender()] in 
 line (https://github.com/PowerShell/PSReadLine/blob/fd1265e385cb4b7b860d8f1452da1ceb347e123e/PSReadLine/Render.cs#L584)
In the method we get `bufferHeight` at the beginning of the method but use at the end - there is time for external resizing of the buffer.

For line https://github.com/PowerShell/PSReadLine/blob/fd1265e385cb4b7b860d8f1452da1ceb347e123e/PSReadLine/Render.cs#L610 I don't see how it could raise a random throw.

**Comment by daxian-dbw** [comment] 2021-03-12 07:03
@iSazonov I doubt it was because a resizing happens within the execution of `CalculateWhereAndWhatToRender`.

**Comment by daxian-dbw** [comment] 2021-03-12 07:04
I will close this one as a duplicate of #2298

**Closed as completed by daxian-dbw** 2021-03-12 07:04 UTC
Labels: Needs-Repro, Needs-Author Feedback

**Comment by iSazonov** [comment] 2021-03-12 15:33
In any case it would be more safe to move the lines
https://github.com/PowerShell/PSReadLine/blob/fd1265e385cb4b7b860d8f1452da1ceb347e123e/PSReadLine/Render.cs#L507-L508
closer to the place of use. Maybe we'll be lucky to fix this issue too :-)
