### ISSUE TITLE
Pasted content is reversed

### ISSUE THREAD

**Issue by AnthonyMastrean** [PowerShell/PSReadLine#829] opened 2018-12-10 16:10 UTC
Environment data
----------------

```powershell
PS version: 5.1.17134.407
PSReadline version: 1.2
os: 10.0.17134.1 (WinBuild.160101.0800)
PS file version: 10.0.17134.1 (WinBuild.160101.0800)
```

Steps to reproduce or exception report
--------------------------------------

Heeey, so I don't know what to say here... but, I've notice *twice* recently that I'm getting "reversed" content pasted in my PowerShell console. The text I copied was 

```
(Invoke-RestMethod `
    -Headers @{'Private-Token' = $ENV:GITLAB_NEXTGEN_API_TOKEN} `
    -Uri "https://gitlab.com/api/v4/groups/xxxxxx/projects?per_page=100&simple=true&archived=false")
```

And the pasted content looked like

![reverse-paste](https://user-images.githubusercontent.com/217842/49745033-1263d480-fc6c-11e8-8102-36d4ab9744d2.PNG)

Next time I notice it happening, I'll try to quickly paste into notepad or something to see if it's a problem going _into_ the clipboard or coming out.

**Comment by lzybkr** [comment] 2018-12-10 16:13
Are you pasting with <kbd>Ctrl+v</kbd> or right click? If right click, I suggest using <kbd>Ctrl+v</kbd> as it's faster.

**Comment by AnthonyMastrean** [comment] 2018-12-10 17:22
I don’t know for sure, but I feel like I was using the keyboard. Will pay attention next time!

**Comment by Splaxi** [comment] 2019-03-23 08:48
My testing shows that right click is an issue when running non-default font , size and stuff like that. Even after switching back to default values, it is a problem.

**Comment by yecril71pl** [comment] 2020-08-03 10:13
```powershell
@'
A
B
'@
```
Pasted with right click becomes 
```
@
B
A
@
```

**Comment by daxian-dbw** [comment] 2022-10-10 18:23
Close as a duplicate of #579

**Closed as completed by daxian-dbw** 2022-10-10 18:23 UTC
Labels: Needs-Repro
